-- The planets a thing may be built on, and the places on them where nothing
-- may be. Written by scripts/supabase-seed.mjs from scripts/fixtures/planets.json; do not edit by hand.
-- Upserts, so it can be applied again after the list changes.

insert into public.planets (id, name, type, seed, terrain_version) values ('tatooine', 'Tatooine', 'desert', '8647508281676935542', 1) on conflict (id) do update set name = excluded.name, type = excluded.type, seed = excluded.seed, terrain_version = excluded.terrain_version;
insert into public.planets (id, name, type, seed, terrain_version) values ('hoth', 'Hoth', 'ice', '1223795395', 1) on conflict (id) do update set name = excluded.name, type = excluded.type, seed = excluded.seed, terrain_version = excluded.terrain_version;
insert into public.planets (id, name, type, seed, terrain_version) values ('endor', 'Endor', 'forest', '17936333477305376403', 1) on conflict (id) do update set name = excluded.name, type = excluded.type, seed = excluded.seed, terrain_version = excluded.terrain_version;
insert into public.planets (id, name, type, seed, terrain_version) values ('yavin', 'Yavin 4', 'forest', '1927579065696738100', 1) on conflict (id) do update set name = excluded.name, type = excluded.type, seed = excluded.seed, terrain_version = excluded.terrain_version;
insert into public.planets (id, name, type, seed, terrain_version) values ('bespin', 'Bespin', 'gas', '5485698255689101500', 1) on conflict (id) do update set name = excluded.name, type = excluded.type, seed = excluded.seed, terrain_version = excluded.terrain_version;
insert into public.planets (id, name, type, seed, terrain_version) values ('dagobah', 'Dagobah', 'swamp', '1702958522028571207', 1) on conflict (id) do update set name = excluded.name, type = excluded.type, seed = excluded.seed, terrain_version = excluded.terrain_version;
insert into public.planets (id, name, type, seed, terrain_version) values ('mustafar', 'Mustafar', 'lava', '1127027023069150644', 1) on conflict (id) do update set name = excluded.name, type = excluded.type, seed = excluded.seed, terrain_version = excluded.terrain_version;
insert into public.planets (id, name, type, seed, terrain_version) values ('coruscant', 'Coruscant', 'city', '13422630211582984297', 1) on conflict (id) do update set name = excluded.name, type = excluded.type, seed = excluded.seed, terrain_version = excluded.terrain_version;
insert into public.planets (id, name, type, seed, terrain_version) values ('naboo', 'Naboo', 'temperate', '13265591532015992144', 1) on conflict (id) do update set name = excluded.name, type = excluded.type, seed = excluded.seed, terrain_version = excluded.terrain_version;
insert into public.planets (id, name, type, seed, terrain_version) values ('kashyyyk', 'Kashyyyk', 'forest', '1526000029368774964', 1) on conflict (id) do update set name = excluded.name, type = excluded.type, seed = excluded.seed, terrain_version = excluded.terrain_version;
insert into public.planets (id, name, type, seed, terrain_version) values ('kamino', 'Kamino', 'ocean', '16829253035778520168', 1) on conflict (id) do update set name = excluded.name, type = excluded.type, seed = excluded.seed, terrain_version = excluded.terrain_version;
insert into public.planets (id, name, type, seed, terrain_version) values ('geonosis', 'Geonosis', 'desert', '7091074928947837158', 1) on conflict (id) do update set name = excluded.name, type = excluded.type, seed = excluded.seed, terrain_version = excluded.terrain_version;
insert into public.planets (id, name, type, seed, terrain_version) values ('scarif', 'Scarif', 'ocean', '6853207733044931143', 1) on conflict (id) do update set name = excluded.name, type = excluded.type, seed = excluded.seed, terrain_version = excluded.terrain_version;
insert into public.planets (id, name, type, seed, terrain_version) values ('nevarro', 'Nevarro', 'lava', '13487258476707400418', 1) on conflict (id) do update set name = excluded.name, type = excluded.type, seed = excluded.seed, terrain_version = excluded.terrain_version;
insert into public.planets (id, name, type, seed, terrain_version) values ('mandalore', 'Mandalore', 'desert', '13075852038549019104', 1) on conflict (id) do update set name = excluded.name, type = excluded.type, seed = excluded.seed, terrain_version = excluded.terrain_version;
insert into public.planets (id, name, type, seed, terrain_version) values ('lothal', 'Lothal', 'temperate', '5339334118646393569', 1) on conflict (id) do update set name = excluded.name, type = excluded.type, seed = excluded.seed, terrain_version = excluded.terrain_version;
insert into public.planets (id, name, type, seed, terrain_version) values ('sorgan', 'Sorgan', 'forest', '16486895930758120779', 1) on conflict (id) do update set name = excluded.name, type = excluded.type, seed = excluded.seed, terrain_version = excluded.terrain_version;
insert into public.planets (id, name, type, seed, terrain_version) values ('gazorpazorp', 'Gazorpazorp', 'desert', '2431803148514356742', 1) on conflict (id) do update set name = excluded.name, type = excluded.type, seed = excluded.seed, terrain_version = excluded.terrain_version;
insert into public.planets (id, name, type, seed, terrain_version) values ('squanch', 'Squanch', 'stylised', '9590996167492738644', 1) on conflict (id) do update set name = excluded.name, type = excluded.type, seed = excluded.seed, terrain_version = excluded.terrain_version;
insert into public.planets (id, name, type, seed, terrain_version) values ('birdworld', 'Bird World', 'stylised', '13643440753565578034', 1) on conflict (id) do update set name = excluded.name, type = excluded.type, seed = excluded.seed, terrain_version = excluded.terrain_version;
insert into public.planets (id, name, type, seed, terrain_version) values ('gearworld', 'Gear World', 'stylised', '7139150669210096398', 1) on conflict (id) do update set name = excluded.name, type = excluded.type, seed = excluded.seed, terrain_version = excluded.terrain_version;
insert into public.planets (id, name, type, seed, terrain_version) values ('pluto', 'Pluto', 'ice', '11588391963419968745', 1) on conflict (id) do update set name = excluded.name, type = excluded.type, seed = excluded.seed, terrain_version = excluded.terrain_version;
insert into public.planets (id, name, type, seed, terrain_version) values ('snakeplanet', 'Snake Planet', 'temperate', '9125054182730542529', 1) on conflict (id) do update set name = excluded.name, type = excluded.type, seed = excluded.seed, terrain_version = excluded.terrain_version;
insert into public.planets (id, name, type, seed, terrain_version) values ('nuptia', 'Nuptia 4', 'stylised', '1523212486951103434', 1) on conflict (id) do update set name = excluded.name, type = excluded.type, seed = excluded.seed, terrain_version = excluded.terrain_version;
insert into public.planets (id, name, type, seed, terrain_version) values ('resort', 'Immortality Field Resort', 'stylised', '7590726331716762136', 1) on conflict (id) do update set name = excluded.name, type = excluded.type, seed = excluded.seed, terrain_version = excluded.terrain_version;
insert into public.planets (id, name, type, seed, terrain_version) values ('cronenberg', 'Cronenberg World', 'temperate', '3701917680389589232', 1) on conflict (id) do update set name = excluded.name, type = excluded.type, seed = excluded.seed, terrain_version = excluded.terrain_version;
insert into public.planets (id, name, type, seed, terrain_version) values ('purge', 'Purge Planet', 'temperate', '9565460683774068840', 1) on conflict (id) do update set name = excluded.name, type = excluded.type, seed = excluded.seed, terrain_version = excluded.terrain_version;
insert into public.planets (id, name, type, seed, terrain_version) values ('cybertron', 'Cybertron', 'metal', '16057552536471276517', 1) on conflict (id) do update set name = excluded.name, type = excluded.type, seed = excluded.seed, terrain_version = excluded.terrain_version;
insert into public.planets (id, name, type, seed, terrain_version) values ('middle-earth', 'Middle-earth', 'temperate', '18187206293295419981', 1) on conflict (id) do update set name = excluded.name, type = excluded.type, seed = excluded.seed, terrain_version = excluded.terrain_version;
insert into public.planets (id, name, type, seed, terrain_version) values ('caribbean', 'The Caribbean', 'ocean', '11984462318207453812', 1) on conflict (id) do update set name = excluded.name, type = excluded.type, seed = excluded.seed, terrain_version = excluded.terrain_version;
insert into public.planets (id, name, type, seed, terrain_version) values ('albuquerque', 'Albuquerque', 'desert', '10048810785060841797', 1) on conflict (id) do update set name = excluded.name, type = excluded.type, seed = excluded.seed, terrain_version = excluded.terrain_version;
insert into public.planets (id, name, type, seed, terrain_version) values ('scranton', 'Scranton', 'temperate', '2812984397735158369', 1) on conflict (id) do update set name = excluded.name, type = excluded.type, seed = excluded.seed, terrain_version = excluded.terrain_version;
insert into public.planets (id, name, type, seed, terrain_version) values ('avengers', 'Avengers Compound', 'temperate', '18296028802821282410', 1) on conflict (id) do update set name = excluded.name, type = excluded.type, seed = excluded.seed, terrain_version = excluded.terrain_version;
insert into public.planets (id, name, type, seed, terrain_version) values ('invincible', 'Invincible', 'temperate', '17049026213794180600', 1) on conflict (id) do update set name = excluded.name, type = excluded.type, seed = excluded.seed, terrain_version = excluded.terrain_version;
insert into public.planets (id, name, type, seed, terrain_version) values ('c-137', 'Earth C-137', 'temperate', '16337440380819003650', 1) on conflict (id) do update set name = excluded.name, type = excluded.type, seed = excluded.seed, terrain_version = excluded.terrain_version;
insert into public.planets (id, name, type, seed, terrain_version) values ('earth', 'Earth', 'temperate', '6709468555492038659', 1) on conflict (id) do update set name = excluded.name, type = excluded.type, seed = excluded.seed, terrain_version = excluded.terrain_version;
insert into public.planets (id, name, type, seed, terrain_version) values ('dot-matrix', 'Dot Matrix', 'stylised', '11991176794051770286', 1) on conflict (id) do update set name = excluded.name, type = excluded.type, seed = excluded.seed, terrain_version = excluded.terrain_version;
insert into public.planets (id, name, type, seed, terrain_version) values ('E:1,0:0:0', 'Lithialsur', 'gas', '9214131500749537690', 1) on conflict (id) do update set name = excluded.name, type = excluded.type, seed = excluded.seed, terrain_version = excluded.terrain_version;
insert into public.planets (id, name, type, seed, terrain_version) values ('E:1,0:0:1', 'Selimo', 'forest', '9214132600261165901', 1) on conflict (id) do update set name = excluded.name, type = excluded.type, seed = excluded.seed, terrain_version = excluded.terrain_version;
insert into public.planets (id, name, type, seed, terrain_version) values ('E:1,0:0:2', 'Ramsaex', 'lava', '9214129301726281268', 1) on conflict (id) do update set name = excluded.name, type = excluded.type, seed = excluded.seed, terrain_version = excluded.terrain_version;
insert into public.planets (id, name, type, seed, terrain_version) values ('E:1,0:0:3', 'Taecle', 'ice', '9214130401237909479', 1) on conflict (id) do update set name = excluded.name, type = excluded.type, seed = excluded.seed, terrain_version = excluded.terrain_version;
insert into public.planets (id, name, type, seed, terrain_version) values ('E:1,0:0:4', 'Taedixa', 'rock', '9214127102703024846', 1) on conflict (id) do update set name = excluded.name, type = excluded.type, seed = excluded.seed, terrain_version = excluded.terrain_version;
insert into public.planets (id, name, type, seed, terrain_version) values ('E:1,0:0:5', 'Deapho', 'ice', '9214128202214653057', 1) on conflict (id) do update set name = excluded.name, type = excluded.type, seed = excluded.seed, terrain_version = excluded.terrain_version;
insert into public.planets (id, name, type, seed, terrain_version) values ('E:1,0:0:6', 'Vaemalo', 'desert', '9214124903679768424', 1) on conflict (id) do update set name = excluded.name, type = excluded.type, seed = excluded.seed, terrain_version = excluded.terrain_version;
insert into public.planets (id, name, type, seed, terrain_version) values ('E:1,0:1:0', 'Miace', 'desert', '5034333057882641216', 1) on conflict (id) do update set name = excluded.name, type = excluded.type, seed = excluded.seed, terrain_version = excluded.terrain_version;
insert into public.planets (id, name, type, seed, terrain_version) values ('E:1,0:1:1', 'Seritiai', 'ocean', '5034334157394269427', 1) on conflict (id) do update set name = excluded.name, type = excluded.type, seed = excluded.seed, terrain_version = excluded.terrain_version;
insert into public.planets (id, name, type, seed, terrain_version) values ('E:1,0:1:2', 'Tephaemom', 'rock', '5034335256905897638', 1) on conflict (id) do update set name = excluded.name, type = excluded.type, seed = excluded.seed, terrain_version = excluded.terrain_version;
insert into public.planets (id, name, type, seed, terrain_version) values ('E:1,0:2:0', 'Cunano', 'gas', '9427996514885272807', 1) on conflict (id) do update set name = excluded.name, type = excluded.type, seed = excluded.seed, terrain_version = excluded.terrain_version;
insert into public.planets (id, name, type, seed, terrain_version) values ('E:1,0:2:1', 'Nole', 'ocean', '9427995415373644596', 1) on conflict (id) do update set name = excluded.name, type = excluded.type, seed = excluded.seed, terrain_version = excluded.terrain_version;
insert into public.planets (id, name, type, seed, terrain_version) values ('E:1,0:2:2', 'Niathia', 'rock', '9427998713908529229', 1) on conflict (id) do update set name = excluded.name, type = excluded.type, seed = excluded.seed, terrain_version = excluded.terrain_version;

insert into public.pois (id, planet_id, name, x, z, r) values ('hoth:echo-base', 'hoth', 'Echo Base', 1200, -800, 380) on conflict (id) do update set planet_id = excluded.planet_id, name = excluded.name, x = excluded.x, z = excluded.z, r = excluded.r;
