// Generated by scripts/build-sitar.py: the sitar's notes, a file for every
// fourth semitone, each with a Da and a Ra stroke as [start, length, pitch].
// From two strokes on a real sitar by chinpen (Freesound, CC BY 3.0).
export const SITAR_VARIANTS = [
  { shift: -12, url: '/audio/sitar/m12.mp3', takes: [[0.12, 2.9, 146.2], [3.14, 2.9, 145.95]] },
  { shift: -8, url: '/audio/sitar/m8.mp3', takes: [[0.12, 2.9, 184.2], [3.14, 2.9, 183.89]] },
  { shift: -4, url: '/audio/sitar/m4.mp3', takes: [[0.12, 2.9, 232.08], [3.14, 2.9, 231.68]] },
  { shift: 0, url: '/audio/sitar/p0.mp3', takes: [[0.12, 2.9, 292.4], [3.14, 2.9, 291.9]] },
  { shift: 4, url: '/audio/sitar/p4.mp3', takes: [[0.12, 2.9, 368.4], [3.14, 2.9, 367.77]] },
  { shift: 8, url: '/audio/sitar/p8.mp3', takes: [[0.12, 2.9, 464.16], [3.14, 2.9, 463.36]] },
  { shift: 12, url: '/audio/sitar/p12.mp3', takes: [[0.12, 2.9, 584.8], [3.14, 2.9, 583.8]] },
  { shift: 16, url: '/audio/sitar/p16.mp3', takes: [[0.12, 2.9, 736.8], [3.14, 2.9, 735.54]] },
];
