// Generated by scripts/build-tabla.py: where each stroke starts in
// public/audio/tabla.mp3 and how long it rings, in seconds.
// dio_333's tabla, from Freesound via Sonic Pi's sample library (CC0).
export const TABLA_URL = '/audio/tabla.mp3';
export const TABLA_SLOTS = {
  na: [0.12, 0.69],
  na_s: [0.93, 0.23],
  na_o: [1.28, 1.3],
  tas1: [2.7, 1.0],
  tas2: [3.82, 1.1],
  tas3: [5.04, 1.0],
  tun1: [6.16, 1.7],
  tun2: [7.98, 1.7],
  tun3: [9.8, 1.7],
  te1: [11.62, 0.17],
  te2: [11.91, 0.3],
  te_m: [12.33, 0.28],
  te_ne: [12.73, 0.15],
  re: [13.0, 0.28],
  ke1: [13.4, 0.0434],
  ke2: [13.5634, 0.044],
  ke3: [13.7275, 0.07],
  ghe1: [13.9175, 0.59],
  ghe2: [14.6275, 2.0],
  ghe3: [16.7475, 2.0],
  ghe4: [18.8675, 0.79],
  ghe5: [19.7775, 2.1],
  ghe6: [21.9975, 2.1],
  ghe7: [24.2175, 1.9],
  ghe8: [26.2375, 0.58],
};
