// What the Avengers compound fetches (models, textures, skies, sound): the install's list (scripts/packs.mjs, src/runtime/install.js); scripts/pack-check.mjs fails when its source names an asset this misses.
export const PACK = {
  id: '/avengers',
  pages: ['src/pages/Avengers.jsx'], // page modules: the build adds their JS/CSS chunks
  src: ['src/components/avengers', 'src/pages/Avengers.jsx'], // where its source is (files or folders, repo-relative): pack-check scans these
  urls: [
    '/models/marvel/spiderman.glb',
    '/audio/clips/hulk-smash.mp3',
    '/audio/clips/puny-god.mp3',
    '/audio/clips/avengers-assemble.mp3',
    '/audio/clips/i-am-iron-man.mp3',
    '/audio/clips/i-can-do-this-all-day.mp3',
    '/audio/clips/i-am-groot.mp3',
    '/audio/clips/wakanda-forever.mp3',
    '/audio/clips/we-have-a-hulk.mp3',
    '/audio/clips/hes-adopted.mp3',
    '/audio/clips/mr-stark-i-dont-feel-so-good.mp3',
    '/audio/clips/i-am-inevitable.mp3',
    '/audio/clips/small-price-to-pay-for-salvation.mp3',
    '/audio/clips/fine-ill-do-it-myself.mp3',
    '/audio/clips/hulk-roar.mp3',
    '/audio/clips/snap.mp3',
    '/audio/clips/marvel-opening.mp3',
  ], // single files
  globs: [
    '/models/sketchfab/avengers**',
    '/hq/sky/airfield/*',
    '/hq/sky/dusk/*',
    '/hq/sky/hall/*',
    '/hq/sky/midtown/*',
    '/hq/sky/noon/*',
    '/hq/sky/pines/*',
    '/hq/sky/storm/*',
    '/hq/models/*',
    '/hq/impostors/**',
    '/hq/tex/asphalt/*',
    '/hq/tex/bark/*',
    '/hq/tex/brick/*',
    '/hq/tex/brushed-steel/*',
    '/hq/tex/carbon/*',
    '/hq/tex/concrete-floor/*',
    '/hq/tex/concrete-wall/*',
    '/hq/tex/concrete-worn/*',
    '/hq/tex/corrugated/*',
    '/hq/tex/diamond-plate/*',
    '/hq/tex/forest-floor/*',
    '/hq/tex/grass/*',
    '/hq/tex/hay/*',
    '/hq/tex/leather/*',
    '/hq/tex/painted-metal/*',
    '/hq/tex/planks/*',
    '/hq/tex/plywood/*',
    '/hq/tex/rock/*',
    '/hq/tex/rubber-tiles/*',
    '/hq/tex/sci-panels/*',
    '/hq/tex/sidewalk/*',
    '/hq/tex/steel-plate/*',
  ], // folders: `*` within a folder, `**` any depth
};
