// The core worlds, from the ground: Naboo, Coruscant, Kamino and Geonosis.
// (sites/index.js has what a site is.)

// level ground stepping evenly from a to b (a road up a slope): flats
const ramp = (a, b, h0, h1, n = 12, r = 8) =>
  Array.from({ length: n + 1 }, (_, i) => ({ at: [a[0] + ((b[0] - a[0]) * i) / n, a[1] + ((b[1] - a[1]) * i) / n], r, edge: r, h: h0 + ((h1 - h0) * i) / n }));

// a skybridge from a to b, its ends just inside the platforms there (ra,
// rb: how far from each middle its edge is, along the way)
const span = (a, b, ra, rb, w = 6, style = 'coruscant', y = 0) => {
  const dx = b[0] - a[0];
  const dz = b[1] - a[1];
  const L = Math.hypot(dx, dz);
  const s = ra - 1.2;
  const e = L - (rb - 1.2);
  const mid = (s + e) / 2;
  return { kind: 'skybridge', at: [a[0] + (dx / L) * mid, a[1] + (dz / L) * mid], yaw: Math.atan2(dx, dz), abs: true, y, opts: { len: e - s, w, style } };
};
// a tower of the city, standing on its floor far below
const tower = (at, style, h, w = 26) => ({ kind: 'skyscraper', at, abs: true, y: -330, yaw: (at[0] * 0.013 + at[1] * 0.007) % 3, solid: false, opts: { style, h, w, seed: Math.abs(at[0] + at[1]) } });

export const SITES = {
  naboo: {
    place: 'The Great Grass Plains',
    line: 'Green hills, still lakes, and Theed’s domes over the falls.',
    sky: {
      zenith: '#3f82cf',
      horizon: '#cfe4ef',
      haze: 0.7,
      hazeColor: '#e2eef0',
      suns: [{ az: -2.4, el: 0.62, color: '#fff4dc', size: 0.016, glow: 1.1 }],
      clouds: { cover: 0.34, color: '#ffffff', shade: '#c6d2dc', scale: 0.7, speed: 0.005 },
      bodies: [
        { az: 0.5, el: 0.34, size: 0.03, color: '#dfe6ea', color2: '#c4ccd2', bands: 0 },
        { az: 0.78, el: 0.46, size: 0.012, color: '#e4dccc' },
      ],
    },
    fog: { color: '#d3e3e6', density: 0.00075 },
    light: { sun: 3.0, sky: '#b8d4f0', ground: '#6e8a4a', ambient: 0.75 },
    ground: { detail: 'grass', detailLook: { color: 0.7, normal: 0.6 },
      seed: 21,
      wind: 0.3,
      layers: [
        { type: 'swell', scale: 520, height: 6 },
        { type: 'hills', scale: 240, height: 14 },
        // Theed's plateau, its east edge a cliff over the lake
        { type: 'island', at: [-330, 300], r: 250, height: 30, core: 0.9, ragged: 0.1 },
        // the lake, and Padmé's island in it
        { type: 'island', at: [100, 330], r: 290, height: -38, core: 0.5, ragged: 0.25 },
        { type: 'island', at: [300, 420], r: 56, height: 43, core: 0.55, ragged: 0.3 },
        // the swamp round the Gungans' sacred place
        { type: 'island', at: [-360, -280], r: 70, height: -16, core: 0.4, ragged: 0.4 },
        { type: 'mountains', from: 800, to: 3200, height: 460, scale: 1200 },
      ],
      // the road up to Theed
      flats: ramp([-104, 38], [-196, 148], 15, 39.5, 16, 7),
      palette: {
        low: '#5d8a38',
        high: '#79a447',
        rock: '#8a8270',
        accent: '#93ad4c',
        deep: '#4c7a30',
        hLow: 0,
        hHigh: 30,
        rockAt: 0.3,
        accentCover: 0.3,
        ripple: { strength: 0.03, scale: 1.6, wind: 0.3 },
        grain: 0.7,
        wet: { level: 0.5, band: 2.5, color: '#6a6248' },
      },
    },
    water: { level: 0, color: '#3c7f88', deep: '#1f4a58', kind: 'sea', foam: 0.12 },
    weather: [{ kind: 'motes', count: 260, color: '#fffbe0' }],
    dust: '#a8b878',
    edge: 'Grass and gentle hills, all the way to the mountains. The Gungans’ swamps are that way; Theed’s behind you.',
    lines: {
      out: {
        xwing: [['luke', 'Naboo. I never thought anywhere could be this green.'], ['r2', '(A happy, rising whistle: Artoo’s been here before.)']],
        falcon: [['han', 'Nice place. Too nice. Somebody’s got a blockade parked up there, mark my words.'], ['chewie', '(A contented rumble.)']],
        cruiser: [['morty', 'Wow, Rick. It’s like a screensaver.'], ['rick', 'It’s a monarchy with an elected teenage queen, Morty. Don’t get attached.']],
        rv: [['jesse', 'Yo, this is like the nicest place we’ve ever parked the RV.'], ['walt', 'Don’t get comfortable. Nice places have the worst neighbours.']],
      },
    },
    land: { at: [0, 0], yaw: 2.3 },
    places: [
      {
        id: 'palace',
        name: 'The Royal Palace of Theed',
        at: [-235, 300],
        yaw: 2.2,
        r: 75,
        flat: { r: 66, h: 39.5 },
        about: 'Queen Amidala’s palace, high over the falls: green domes, colonnades and the throne room the Trade Federation took, and the Queen took back.',
        lines: {
          xwing: [['luke', 'The palace. Leia said our mother was a queen here, once.'], ['r2', '(A soft, knowing beep.)']],
          falcon: [['han', 'Fancy. I’ve been thrown out of less fancy places than this.']],
          cruiser: [['rick', 'Classical revival, Morty. A whole planet LARPing the Renaissance.'], ['morty', 'I think it’s pretty, Rick.']],
          rv: [['walt', 'An elected queen. Fourteen years old.'], ['jesse', 'Dude, at fourteen I couldn’t elect what to have for lunch.']],
        },
        things: [
          { kind: 'theedpalace', at: [0, 0] },
          { kind: 'plaza', at: [0, 60], opts: { w: 72, d: 48 } },
          { kind: 'lamp', at: [-14, 40], opts: { h: 5, light: '#ffe2a8' } },
          { kind: 'lamp', at: [14, 40], opts: { h: 5, light: '#ffe2a8' } },
          { kind: 'lamp', at: [-14, 56], opts: { h: 5, light: '#ffe2a8' } },
          { kind: 'lamp', at: [14, 56], opts: { h: 5, light: '#ffe2a8' } },
        ],
      },
      {
        id: 'falls',
        name: 'The falls of Theed',
        at: [-130, 300],
        r: 44,
        flat: { r: 28, h: 38, edge: 5 },
        about: 'Theed is built on the edge of a cliff, and the river falls out from under the city in sheets of white, a hundred metres down into the gorge.',
        lines: {
          xwing: [['luke', 'Look at that, Artoo. Water, just… falling off the edge. On Tatooine they’d have a war over this.'], ['r2', '(An awed whistle.)']],
          falcon: [['chewie', '(A long, happy howl at the falls.)'], ['han', 'Yeah, yeah. It’s not Kashyyyk, pal.']],
          cruiser: [['morty', 'It’s beautiful, Rick.'], ['rick', 'It’s erosion, Morty. With a tourism board.']],
        },
        things: [
          { kind: 'waterfall', at: [23.4, -12.4], yaw: 2.06, opts: { h: 46, w: 10, out: 13 } },
          { kind: 'waterfall', at: [26.5, 0], yaw: Math.PI / 2, opts: { h: 46, w: 14, out: 13 } },
          { kind: 'waterfall', at: [23.4, 12.4], yaw: 1.08, opts: { h: 46, w: 10, out: 13 } },
          { kind: 'theed', at: [-44, 2], yaw: Math.PI / 2, opts: { style: 'rotunda' } },
          { kind: 'lamp', at: [4, -18], opts: { h: 4.5, light: '#ffe2a8' } },
          { kind: 'lamp', at: [4, 20], opts: { h: 4.5, light: '#ffe2a8' } },
        ],
      },
      {
        id: 'hangar',
        name: 'The Theed Royal Hangar',
        at: [-300, 180],
        yaw: 2.4,
        r: 55,
        flat: { r: 48, h: 39.5 },
        about: 'Where the N-1 starfighters of Bravo Squadron wait, yellow and chrome. A boy hid in one of their cockpits, and flew it to the droid control ship.',
        lines: {
          xwing: [['luke', 'N-1s. Look at the lines on those, Artoo. Somebody built these to be beautiful.'], ['r2', '(A smug little trill. Artoo knows these.)']],
          falcon: [['han', 'Pretty. Chrome. Not much armour. I’d still take one for a spin.']],
          cruiser: [['morty', 'A kid flew one of these and blew up a whole space station, Rick.'], ['rick', 'Ugh, don’t tell me that, Morty. I hate it when the kid wins.']],
          rv: [['jesse', 'Yo, these are like the Lamborghinis of spaceships.'], ['walt', 'Hand-built. No two the same. Craftsmanship, Jesse.']],
        },
        things: [
          { kind: 'hangar', at: [0, -6] },
          { kind: 'n1fighter', at: [-14, -8], yaw: 0.1 },
          { kind: 'n1fighter', at: [0, -12], yaw: 0 },
          { kind: 'n1fighter', at: [14, -8], yaw: -0.1 },
          { kind: 'n1fighter', at: [-22, 30], yaw: 0.5 },
          { kind: 'n1fighter', at: [24, 32], yaw: -0.4 },
          { kind: 'crates', at: [-26, 8] },
          { kind: 'crates', at: [27, 10] },
        ],
      },
      {
        id: 'paonga',
        name: 'Lake Paonga',
        at: [70, 120],
        r: 60,
        about: 'Under the lake lies Otoh Gunga, the Gungans’ city of glowing bubbles. Go down in a bongo, and mind the opee sea killers. There’s always a bigger fish.',
        lines: {
          xwing: [['luke', 'There’s a whole city down there, Artoo. Under the water. Lights and everything.'], ['r2', '(A worried warble: Artoo doesn’t do lakes.)']],
          falcon: [['han', 'An underwater city. Nope. I like my air in a can, thanks.'], ['chewie', '(A rumbling laugh.)']],
          cruiser: [['rick', 'Hydrostatic bubble tech, Morty. Gungans. Can’t speak a sentence, but they can hold back a lake.'], ['morty', 'Is it okay to be impressed by Jar Jar, Rick?']],
          rv: [['jesse', 'Yo, there’s glowing bubbles in the lake. Like, actual lava lamps, Mr. White.'], ['walt', 'Bioluminescence. Or a containment field. Either way: don’t touch it.']],
        },
        things: [
          { kind: 'otohgunga', at: [40, 110], abs: true, y: 0, solid: false },
          { kind: 'bongo', at: [-6, 24], yaw: 2.8, abs: true, y: -0.9 },
        ],
      },
      {
        id: 'varykino',
        name: 'Varykino',
        at: [372, 330],
        yaw: -1.75,
        r: 40,
        flat: { r: 26, edge: 14 },
        about: 'A lake retreat in the Lake Country: terracotta roofs, a terrace over the water, an island Padmé used to swim to. Where she and Anakin were married, in secret.',
        lines: {
          xwing: [['luke', 'This is where they were married, Artoo? My mother and… him?'], ['r2', '(A long, quiet, sad whistle. Artoo was there.)']],
          falcon: [['han', 'Nice place for a honeymoon. Not that I’m thinking about that.'], ['chewie', '(A teasing growl.)'], ['han', 'Shut up.']],
          cruiser: [['morty', 'Rick, it’s so romantic.'], ['rick', 'It’s where a guy who hates sand married a senator in secret, Morty. Read the room.']],
        },
        things: [{ kind: 'varykino', at: [0, 0] }],
      },
      {
        id: 'sacred',
        name: 'The Gungan sacred place',
        at: [-320, -230],
        r: 50,
        flat: { r: 30, edge: 16 },
        about: 'Ruins in the swamp forest, great stone heads half sunk in the moss: where the Gungans hid from the droid army, and where the Queen knelt to ask Boss Nass for help.',
        lines: {
          xwing: [['luke', 'Ruins. Older than anything on Naboo, I’d say. Feel that, Artoo? It’s… still here.'], ['r2', '(A hushed, uncertain beep.)']],
          falcon: [['han', 'Big stone heads. Always a good sign.'], ['chewie', '(An uneasy groan.)']],
          cruiser: [['morty', 'Rick, those heads are kind of looking at us.'], ['rick', 'Every civilisation builds giant heads, Morty. It’s the cosmic equivalent of a phase.']],
          rv: [['jesse', 'This is like, Indiana Jones, yo.'], ['walt', 'Don’t take anything.']],
        },
        things: [
          { kind: 'stonehead', at: [8, -6], yaw: -0.4, sink: 2.2, roll: 0.12 },
          { kind: 'stonehead', at: [-14, 10], yaw: 0.7, sink: 3, opts: { s: 1.4 }, roll: -0.18 },
          { kind: 'stonehead', at: [20, 18], yaw: -1.6, sink: 4, opts: { s: 0.8 }, pitch: 0.4 },
          { kind: 'ruins', at: [0, 0], opts: { seed: 4 } },
          { kind: 'grove', at: [-36, -30], opts: { n: 14, r: 26, seed: 11 } },
          { kind: 'grove', at: [36, -26], opts: { n: 12, r: 22, seed: 12 } },
          { kind: 'grove', at: [-40, 34], opts: { n: 12, r: 24, seed: 13 } },
          { kind: 'grove', at: [30, 44], opts: { n: 10, r: 20, seed: 14 } },
          { kind: 'grove', at: [-80, -4], opts: { n: 14, r: 28, seed: 15 } },
          { kind: 'grove', at: [70, 6], opts: { n: 12, r: 24, seed: 16 } },
        ],
      },
      {
        id: 'battle',
        name: 'The Gungan shield',
        at: [260, -250],
        r: 70,
        flat: { r: 60, edge: 30 },
        about: 'The Great Grass Plains, where the Gungan Grand Army raised its shield and stood against the droid army, to buy the Queen time to take back her palace.',
        lines: {
          xwing: [['luke', 'The Gungans held the droids off right here. With slings and energy balls, Artoo.'], ['r2', '(An impressed, stuttering whistle.)']],
          falcon: [['han', 'Shields, catapults and big lizards. My kind of army.'], ['chewie', '(An approving roar.)']],
          cruiser: [['morty', 'Rick, they’re throwing glowing balls at robots!'], ['rick', 'Plasma boomas, Morty. Honestly? Better tech than the Republic’s.']],
          rv: [['jesse', 'Yo, the frog guys have a force field. A force field, Mr. White!'], ['walt', 'And the robots have tanks. Never bring a force field to a tank fight.']],
        },
        things: [
          { kind: 'shield', at: [0, 0], yaw: 2.4 },
          { kind: 'boomas', at: [26, -14] },
          { kind: 'boomas', at: [34, 4] },
          { kind: 'boomas', at: [18, 26] },
          { kind: 'boomas', at: [-6, 36] },
        ],
      },
      {
        id: 'droids',
        name: 'The droid army',
        at: [400, -380],
        r: 55,
        flat: { r: 50, edge: 30 },
        about: 'The Trade Federation’s army, marching on the Gungans in their thousands: tanks, transports and battle droids, all run from the control ship up in orbit. Until a boy blew it up.',
        lines: {
          xwing: [['luke', 'Battle droids. Hundreds of them. And all of them switched off from one ship up there.'], ['r2', '(A rude raspberry at the droids.)']],
          falcon: [['han', 'Ah, droids. They never know when to quit.'], ['chewie', '(A low, mean growl.)']],
          cruiser: [['rick', 'Roger, roger, Morty. Centrally controlled, no redundancy. That’s what you get for outsourcing.'], ['morty', 'It’s kind of sad when they all fall over, Rick.']],
          rv: [['jesse', 'Roger, roger. Ha! Mr. White, they all say roger roger.'], ['walt', 'One ship controls all of them. One point of failure. Amateurs.']],
        },
        things: [
          { kind: 'mtt', at: [20, 0], yaw: -2.3 },
          { kind: 'aat', at: [-14, 16], yaw: -2.4 },
          { kind: 'aat', at: [-24, -6], yaw: -2.2 },
          { kind: 'aat', at: [4, 30], yaw: -2.5 },
          { kind: 'droideka', at: [-30, 18], yaw: -2.3, opts: { shield: true } },
          { kind: 'droideka', at: [-26, 26], yaw: -2.4 },
          { kind: 'droideka', at: [-36, 8], yaw: -2.2 },
        ],
      },
    ],
    things: [
      // where you set down: a farm's cart and its cargo on the road to
      // Theed, a stand of trees by the lake side
      { kind: 'speedertruck', at: [-24, 18], yaw: 2.3 },
      { kind: 'barrel', at: [-20, 22], yaw: 0.3 },
      { kind: 'barrel', at: [-19, 23.2], yaw: 1.1 },
      { kind: 'bevelcrate', at: [-21.5, 24], yaw: 0.6 },
      { kind: 'crates', at: [18, -10] },
      { kind: 'lamp', at: [-28, 14], opts: { h: 4.5, light: '#ffe2a8' } },
      { kind: 'grove', at: [70, 60], opts: { n: 7, r: 20, seed: 27 } },
      // Theed: its houses and halls along the plateau
      { kind: 'theed', at: [-300, 250], yaw: 2.6, opts: { style: 'hall' } },
      { kind: 'theed', at: [-345, 300], yaw: 2.0, opts: { style: 'tower' } },
      { kind: 'theed', at: [-180, 380], yaw: 2.6, opts: { style: 'tower' } },
      { kind: 'theed', at: [-250, 400], yaw: 2.4, opts: { style: 'rotunda' } },
      { kind: 'theed', at: [-350, 220], yaw: 2.2, opts: { style: 'rotunda' } },
      { kind: 'theed', at: [-205, 215], yaw: 2.2, opts: { style: 'hall' } },
      { kind: 'theed', at: [-400, 350], yaw: 2.0, opts: { style: 'hall' } },
      { kind: 'theed', at: [-320, 420], yaw: 2.6, opts: { style: 'hall' } },
      { kind: 'theed', at: [-420, 260], yaw: 1.8, opts: { style: 'tower' } },
      { kind: 'theed', at: [-260, 470], yaw: 2.8, opts: { style: 'rotunda' } },
      { kind: 'theed', at: [-160, 470], yaw: 2.8, opts: { style: 'hall' } },
      { kind: 'theed', at: [-470, 420], yaw: 2.2, opts: { style: 'hall' } },
      // the Royal Starship, on the apron before the hangar
      { kind: 'royalship', at: [-240, 140], yaw: 2.6 },
      // lamps up the road to Theed
      { kind: 'lamp', at: [-118, 46], opts: { h: 4.5, light: '#ffe2a8' } },
      { kind: 'lamp', at: [-138, 76], opts: { h: 4.5, light: '#ffe2a8' } },
      { kind: 'lamp', at: [-158, 100], opts: { h: 4.5, light: '#ffe2a8' } },
      { kind: 'lamp', at: [-176, 124], opts: { h: 4.5, light: '#ffe2a8' } },
      // the forest out past the sacred place, and along the lake
      { kind: 'grove', at: [-470, -120], opts: { n: 16, r: 34, seed: 21 } },
      { kind: 'grove', at: [-200, -400], opts: { n: 14, r: 30, seed: 22 } },
      { kind: 'grove', at: [-460, -360], opts: { n: 16, r: 34, seed: 23 } },
      { kind: 'grove', at: [-110, -300], opts: { n: 10, r: 24, seed: 24 } },
      { kind: 'grove', at: [480, 120], opts: { n: 12, r: 30, seed: 25 } },
      { kind: 'grove', at: [-60, 120], opts: { n: 8, r: 20, seed: 26 } },
    ],
    scatter: [
      { kind: 'nabootree', n: 80, within: [50, 600], scale: [0.7, 1.4], flat: 0.9 },
      { kind: 'grass', n: 700, within: [6, 320], scale: [0.7, 1.5], solid: false },
      { kind: 'grass', n: 260, within: [6, 260], scale: [0.7, 1.2], solid: false, opts: { color: '#7fa646', flower: '#f4e27a' } },
      { kind: 'grass', n: 160, within: [6, 260], scale: [0.7, 1.2], solid: false, opts: { color: '#6a9a40', flower: '#e8eef8' } },
      { kind: 'rock', n: 50, within: [40, 560], scale: [0.6, 2.4], opts: { color: '#8e8a78', sharp: 0.3 } },
    ],
    life: [
      { kind: 'gungan', n: 10, at: [250, -235], spread: 40, roam: 14, speed: 1.1, name: 'Gungan soldier', says: ['Wesa ready to do are-sa part!', 'Da shield up! Da droids no getting in here!', 'Boomas! Get da boomas!', 'Yousa stay behind da shield, okeyday?'] },
      { kind: 'kaadu', n: 5, at: [230, -220], spread: 30, roam: 18, speed: 1.4, r: 0.8 },
      { kind: 'gungan', n: 1, at: [40, 30], roam: 20, speed: 1.2, name: 'Jar Jar Binks', says: ['Meesa Jar Jar Binks!', 'Exsqueeze me, but de mostest safest place would be Gunga City.', 'How wude!', 'Mesa day startin’ pretty okee-day, with a brisky morning munchy. Den BOOM!', 'Mesa called Jar Jar Binks. Mesa your humble servant.'] },
      { kind: 'gungan', n: 1, at: [-320, -238], still: true, scale: 1.35, r: 0.7, name: 'Boss Nass', says: ['Wesa no like da Naboo. Un dey no like uss-en.', 'Yousa tinkin’ yousa people ganna die?', 'Mesa like dis. Maybe wesa bein’ friends.'] },
      { kind: 'gungan', n: 4, at: [-322, -226], spread: 14, roam: 8, speed: 0.9, name: 'Gungan', says: ['Dis a sacred place. Yousa be quiet, okeyday?', 'Da Naboo tink dey so smarty. Dey tink dey brainses so big.', 'Boss Nass say we hide here till da droids go.'] },
      { kind: 'battledroid', n: 9, path: [[360, -330], [420, -360], [450, -420], [390, -440], [340, -400]], speed: 1.3, name: 'Battle droid', says: ['Roger, roger.', 'Halt! Who goes there?', 'Uh-oh.', 'Move along. Move along.'] },
      { kind: 'battledroid', n: 6, at: [380, -400], spread: 20, roam: 6, speed: 1, name: 'Battle droid', says: ['Roger, roger.', 'They’re still coming through! Er… roger, roger.'] },
      { kind: 'shaak', n: 7, at: [150, -60], spread: 40, roam: 30, speed: 0.6, r: 1.1 },
      { kind: 'shaak', n: 3, at: [50, 20], spread: 16, roam: 20, speed: 0.5, r: 1.1 },
      { kind: 'farmer', n: 2, at: [-20, 14], spread: 6, roam: 8, speed: 0.9, name: 'Naboo farmer', says: ['Shaak herd’s restless today. Something in the sky.', 'Theed’s up the road. Mind the Gungans in the long grass.', 'Milk, cheese, and more milk. That’s a shaak farm.'] },
      { kind: 'astromech', n: 1, at: [-16, 24], roam: 6, speed: 0.6, name: 'Astromech', says: ['(A cheerful whistle at the cart. It is in charge of the cart.)'] },
      { kind: 'shaak', n: 4, at: [-120, -140], spread: 30, roam: 25, speed: 0.6, r: 1.1 },
      { kind: 'villager', n: 6, at: [-250, 260], spread: 40, roam: 24, speed: 1.0, name: 'Theed citizen', says: ['The Queen will speak from the palace steps at noon.', 'Have you seen the falls from the plaza? The whole city hums with them.', 'Our Senator Palpatine is from Theed, you know. Such a kind, patient man.', 'They say the Gungans and the Queen are friends now. Imagine that.'] },
      { kind: 'rebel', n: 3, at: [-245, 255], spread: 12, roam: 10, speed: 1.1, name: 'Palace guard', says: ['The palace is open to visitors today. Stay on the paths.', 'Royal Naboo Security Forces. Keep moving, please.'] },
      { kind: 'rebel', n: 1, at: [-292, 200], roam: 8, speed: 1.1, name: 'Captain Panaka', says: ['Your Highness, we have a problem: the Federation has landed its army.', 'We’ll take the hangar first. Then the throne room.', 'Our people are dying. We must act.'] },
      { kind: 'pilot', n: 3, at: [-300, 188], spread: 14, roam: 10, speed: 1.2, name: 'Bravo Squadron pilot', says: ['We’re going after the droid control ship. Who’s with us?', 'Bravo Flight, fly with me!', 'There was a kid in one of the fighters. He blew the control ship from the inside!'] },
      { kind: 'droid', n: 1, at: [-296, 176], roam: 6, speed: 0.7, name: 'R2-D2', says: ['(A proud whistle. It was the only droid to get the Queen’s ship through the blockade.)', '(A cheeky beep, and a look at the N-1’s astromech socket.)'] },
      { kind: 'jedi', n: 1, at: [60, 170], roam: 10, speed: 0.9, name: 'Qui-Gon Jinn', says: ['There’s always a bigger fish.', 'The ability to speak does not make you intelligent.', 'Feel, don’t think. Use your instincts.'] },
      { kind: 'villager', n: 1, at: [366, 336], roam: 5, speed: 0.8, name: 'Padmé', says: ['When I was in the Legislative Youth Program, we came here for school retreat. We’d swim to that island every day.', 'I love the water. We’d lie on the sand and let the sun dry us.', 'It’s so peaceful here.'] },
      { kind: 'jedi', n: 1, at: [376, 324], roam: 5, speed: 0.8, name: 'Anakin', says: ['I don’t like sand. It’s coarse and rough and irritating, and it gets everywhere. Not like here.', 'Here, everything is soft and smooth.'] },
    ],
    rides: [
      { kind: 'kaadu', at: [214, -196], yaw: 2.2 },
      { kind: 'kaadu', at: [24, -10], yaw: 1.4 },
    ],
    flyovers: [
      { kind: 'n1', n: 3, metres: 11, alt: 90, speed: 120, every: 50 },
      { kind: 'nubian', n: 1, metres: 76, alt: 170, speed: 60, every: 90 },
      { kind: 'vulture', n: 2, metres: 7, alt: 70, speed: 140, every: 70 },
    ],
  },

  coruscant: {
    place: 'The Federal District',
    line: 'A city to the edge of the world, and down further than anyone’s been.',
    sky: {
      zenith: '#26335e',
      horizon: '#f2a46a',
      haze: 0.95,
      hazeColor: '#f7b47c',
      below: '#6a4a52',
      suns: [{ az: -1.9, el: 0.07, color: '#ffb072', size: 0.03, glow: 1.7 }],
      clouds: { cover: 0.22, color: '#f6c49c', shade: '#6e5674', scale: 0.45, speed: 0.004, sharp: 1.5 },
      stars: 0.25,
      bodies: [
        { az: 0.9, el: 0.42, size: 0.016, color: '#d8d0c8', color2: '#b8aca0' },
        { az: 1.2, el: 0.3, size: 0.008, color: '#e0d8d0' },
      ],
    },
    fog: { color: '#c88c72', density: 0.0016 },
    light: { sun: 2.4, sky: '#8a92c4', ground: '#6a4a48', ambient: 0.9 },
    ground: {
      seed: 5,
      layers: [{ type: 'level', height: -330 }],
      palette: { low: '#4a3a3e', high: '#4a3a3e', rock: '#3a2e30', hLow: -340, hHigh: -320, grain: 0.2 },
    },
    fall: -40,
    dust: '#b8a8a0',
    edge: 'More city. All the way round the planet, and all the way down. Better turn back before you get lost on level 1313.',
    lines: {
      out: {
        xwing: [['luke', 'Coruscant. The whole planet is one city, Artoo. I didn’t think it’d be this… big.'], ['r2', '(A nervous warble about the long drop.)']],
        falcon: [['han', 'Imperial Center. Or whatever they call it now. Watch your pockets, Chewie.'], ['chewie', '(A low, wary growl.)']],
        cruiser: [['rick', 'An ecumenopolis, Morty. One city, one planet, a trillion people and not one decent parking spot.'], ['morty', 'Rick, I can’t see the ground. Where’s the ground?']],
        rv: [['jesse', 'Yo, Mr. White, it’s like, all city. Where do people even cook?'], ['walt', 'Down there, Jesse. Where nobody looks.']],
      },
    },
    land: { at: [0, 0], yaw: 0.6 },
    places: [
      {
        id: 'temple',
        name: 'The Jedi Temple',
        at: [0, 400],
        r: 125,
        about: 'Home of the Jedi Order for a thousand generations: a ziggurat of pale stone under five spires, the High Council meeting in the tallest. Until the night of Order 66.',
        lines: {
          xwing: [['luke', 'The Jedi Temple. Ben trained here, Artoo. And my father.'], ['r2', '(A long, sad, low whistle.)']],
          falcon: [['han', 'So this is where they kept all the Jedi. Huh. Bigger than I figured, for a bunch of hokey religion.'], ['chewie', '(A respectful rumble.)']],
          cruiser: [['morty', 'Rick, it’s the Jedi Temple! Can we go in?'], ['rick', 'It’s a monastery for space wizards, Morty. Ten thousand years and they never put in an elevator.']],
          rv: [['jesse', 'Yo, that’s where the Jedi live. Like, the actual Jedi.'], ['walt', 'Lived, Jesse. Something happened here.']],
        },
        things: [
          { kind: 'jeditemple', at: [0, 32], yaw: Math.PI, abs: true, y: 0, solid: { box: [100, 100] } },
          { kind: 'plinth', at: [0, 32], abs: true, y: 0, solid: false, opts: { w: 196, d: 196 } },
        ],
      },
      {
        id: 'processional',
        name: 'The Processional Way',
        at: [0, 150],
        r: 36,
        about: 'The avenue of statues to the Temple’s doors, Jedi of old standing over it. On the night of Order 66, Anakin Skywalker marched the 501st up it.',
        lines: {
          xwing: [['luke', 'Jedi, all the way up. I wonder if Ben’s master is one of them.'], ['r2', '(A quiet beep. Artoo saw that night, from Padmé’s window.)']],
          falcon: [['han', 'Nice statues. Bet nobody’s dusted ’em in twenty years.']],
          cruiser: [['rick', 'Statues of dead wizards lining the road to a building full of dead wizards, Morty. Subtle.'], ['morty', 'You’re really a buzzkill today, Rick.']],
        },
        things: [],
      },
      {
        id: 'senate',
        name: 'The Galactic Senate',
        at: [400, 40],
        r: 100,
        about: 'The Senate Rotunda, a dome as big as a city, where a thousand worlds argued, and where liberty died, with thunderous applause.',
        lines: {
          xwing: [['luke', 'The Senate. The Emperor dissolved it. Leia sat in it, though, when she was a senator.'], ['r2', '(An indignant squawk at the Emperor’s name.)']],
          falcon: [['han', 'Politicians. Give me a Hutt any day: at least you know where you stand.']],
          cruiser: [['morty', 'That’s where the Emperor took over, Rick. They all clapped!'], ['rick', 'A thousand senators cheered for a dictator, Morty. That’s the most realistic thing in the franchise.']],
          rv: [['walt', 'A man can say anything in a room like that, if they’re afraid enough.'], ['jesse', 'Yo, that’s dark, Mr. White.']],
        },
        things: [
          { kind: 'deck', at: [-60, 0], abs: true, y: 0, opts: { hw: 50, hd: 40 } },
          { kind: 'senate', at: [70, 0], abs: true, y: 0, solid: { r: 56 } },
          { kind: 'plinth', at: [70, 0], abs: true, y: 0, solid: false, opts: { w: 112, round: true } },
          { kind: 'statue', at: [-96, 34], abs: true, y: 0, yaw: Math.PI },
          { kind: 'statue', at: [-66, 34], abs: true, y: 0, yaw: Math.PI },
          { kind: 'statue', at: [-36, 34], abs: true, y: 0, yaw: Math.PI },
          { kind: 'statue', at: [-96, -34], abs: true, y: 0 },
          { kind: 'statue', at: [-66, -34], abs: true, y: 0 },
          { kind: 'statue', at: [-36, -34], abs: true, y: 0 },
        ],
      },
      {
        id: 'republica',
        name: '500 Republica',
        at: [-308, 65],
        r: 26,
        about: 'The tallest of the Senate’s apartment towers: Senator Amidala lived at the top. Assassins sent kouhuns to her bed here, and Anakin went out the window after the droid.',
        lines: {
          xwing: [['luke', 'This was my mother’s home? Artoo, you’ve been here before, haven’t you?'], ['r2', '(A soft, sad whistle, and a bleep of yes.)']],
          falcon: [['han', 'Senator’s penthouse. Swanky. I’d steal the furniture, but it’d never fit in the Falcon.']],
          cruiser: [['morty', 'Rick, Anakin jumped out of this window. Onto a flying droid.'], ['rick', 'And then he married her, Morty. Real “guy who jumps out of windows” energy.']],
        },
        things: [{ kind: 'republica', at: [-22, 4.6], yaw: 1.78, abs: true, y: 0 }],
      },
      {
        id: 'dex',
        name: 'Dex’s Diner',
        at: [-150, -270],
        r: 26,
        about: 'Dexter Jettster’s diner in CoCo Town, where Obi-Wan came with a strange dart: a Kamino saberdart, said Dex, from a planet the Jedi Archives didn’t have.',
        lines: {
          xwing: [['luke', 'A diner! Artoo, I could really go for something that isn’t a ration bar.'], ['r2', '(A grumpy beep: the sign says no droids.)']],
          falcon: [['han', 'Now this is my kind of place. Grease, caf and nobody asking questions.'], ['chewie', '(A hungry rumble.)']],
          cruiser: [['rick', 'Finally, Morty! A 1950s diner run by a four-armed alien. The one constant in the multiverse.'], ['morty', 'Do you think they do milkshakes?']],
          rv: [['jesse', 'Yo, a diner! Do you think they have, like, space pancakes?'], ['walt', 'Order something cheap. We’re not here to eat.']],
        },
        things: [
          { kind: 'cplatform', at: [0, 0], abs: true, y: 0, opts: { r: 24, light: '#ffb070' } },
          { kind: 'dexdiner', at: [0, 4], yaw: 0.6, abs: true, y: 0.3 },
          { kind: 'airspeeder', at: [-12, -8], yaw: 2.3, abs: true, y: 0.3 },
          { kind: 'lamp', at: [12, -10], abs: true, y: 0.3, opts: { h: 4, light: '#ffb070' } },
        ],
      },
      {
        id: 'club',
        name: 'The Outlander Club',
        at: [200, -290],
        r: 26,
        about: 'A gambling club in the Uscru entertainment district, all neon and noise: where Obi-Wan cornered the changeling Zam Wesell, and turned down some death sticks.',
        lines: {
          xwing: [['luke', 'Ben said never to go into places like this. I think. Stay close, Artoo.'], ['r2', '(A nervous little burble.)']],
          falcon: [['han', 'Uscru. I know a guy in there owes me money. Let’s not go in.'], ['chewie', '(A knowing growl.)']],
          cruiser: [['morty', 'Rick, a guy in there tried to sell me death sticks.'], ['rick', 'You don’t want to buy death sticks, Morty. You want to go home and rethink your life.']],
          rv: [['jesse', 'Death sticks, yo? Are they… is it like, a pyramid thing?'], ['walt', 'Jesse. Go home and rethink your life.']],
        },
        things: [
          { kind: 'cplatform', at: [0, 0], abs: true, y: 0, opts: { r: 24, light: '#ff6ad0' } },
          { kind: 'club', at: [0, 8], yaw: Math.PI + 0.6, abs: true, y: 0.3 },
          { kind: 'airspeeder', at: [10, -10], yaw: -0.5, abs: true, y: 0.3, opts: { color: '#c8c8cc' } },
        ],
      },
      {
        id: 'works',
        name: 'The Works',
        at: [-430, -250],
        r: 38,
        about: 'A dead industrial district of rusting cranes and empty factories. Darth Sidious met his apprentices here, out of sight of the Jedi just across the skyline.',
        lines: {
          xwing: [['luke', 'I don’t like this place, Artoo. Something… cold happened here.'], ['r2', '(A frightened, falling whistle.)']],
          falcon: [['han', 'Abandoned factories. Perfect place for a deal. Or an ambush.'], ['chewie', '(A tense growl.)']],
          cruiser: [['rick', 'Every Sith Lord needs a creepy warehouse, Morty. It’s in the bylaws.'], ['morty', 'Can we not be in the creepy warehouse, Rick?']],
        },
        things: [
          { kind: 'cplatform', at: [0, 0], abs: true, y: 0, opts: { r: 36, light: '#ff8a4a', color: '#7a6a5c' } },
          { kind: 'works', at: [0, 0], yaw: 0.4, abs: true, y: 0.3 },
        ],
      },
    ],
    things: [
      // where you land, and the bridges out
      { kind: 'cplatform', at: [0, 0], abs: true, y: 0, opts: { r: 30 } },
      { kind: 'deck', at: [0, 290], abs: true, y: 0, opts: { hw: 60, hd: 40 } },
      span([0, 0], [0, 290], 30, 40, 16),
      span([0, 0], [340, 40], 30, 50.4, 7),
      span([0, 0], [-308.5, 65.4], 30, 15.6, 6),
      span([0, 0], [-150, -270], 30, 24, 6),
      span([0, 0], [200, -290], 30, 24, 6),
      span([-150, -270], [-430, -250], 24, 36, 6),
      // the statues along the Processional Way
      ...[60, 100, 140, 180, 220].flatMap((z) => [
        { kind: 'statue', at: [-14, z], yaw: Math.PI / 2, abs: true, y: -6, opts: { h: 26, drop: 200 } },
        { kind: 'statue', at: [14, z], yaw: -Math.PI / 2, abs: true, y: -6, opts: { h: 26, drop: 200 } },
      ]),
      // Anakin's airspeeder, by your ship, and the platform's clutter: cargo
      // waiting for a lift, a lamp over it
      { kind: 'airspeeder', at: [16, -14], yaw: 0.9, abs: true, y: 0.3 },
      { kind: 'cratecube', at: [-18, -10], yaw: 0.4, abs: true, y: 0 },
      { kind: 'cratecube', at: [-16.6, -9.4], yaw: 1.2, abs: true, y: 0 },
      { kind: 'empirecrate', at: [-19, -13], yaw: 2.1, abs: true, y: 0 },
      { kind: 'cooler', at: [-15, -12], yaw: 0.8, abs: true, y: 0 },
      { kind: 'lamp', at: [-22, -6], abs: true, y: 0, opts: { h: 5, light: '#ffd9a0' } },
      { kind: 'lamp', at: [22, 10], abs: true, y: 0, opts: { h: 5, light: '#ffd9a0' } },
      // the skylanes
      { kind: 'airlane', at: [0, 60], yaw: Math.PI / 2, abs: true, y: 40, solid: false, opts: { len: 1700, n: 30, seed: 1 } },
      { kind: 'airlane', at: [110, 0], yaw: 0, abs: true, y: -45, solid: false, opts: { len: 1700, n: 30, seed: 2 } },
      { kind: 'airlane', at: [-60, -100], yaw: 0.8, abs: true, y: 85, solid: false, opts: { len: 1700, n: 26, seed: 3, speed: 40 } },
      { kind: 'airlane', at: [0, -170], yaw: Math.PI / 2, abs: true, y: -90, solid: false, opts: { len: 1700, n: 30, seed: 4 } },
      { kind: 'airlane', at: [-200, 150], yaw: -0.6, abs: true, y: 22, solid: false, opts: { len: 1500, n: 24, seed: 5, speed: 28 } },
      { kind: 'airlane', at: [300, 200], yaw: 0.3, abs: true, y: 140, solid: false, opts: { len: 1700, n: 24, seed: 6, speed: 46 } },
      // the towers nearest, rising past you: Galactic City's own first
      { kind: 'corutower', at: [-120, 170], abs: true, y: -140, yaw: 0.4, scale: 1.7, solid: false },
      { kind: 'corutower', at: [130, 170], abs: true, y: -170, yaw: 2.3, scale: 1.9, solid: false },
      { kind: 'corutower', at: [-300, -120], abs: true, y: -120, yaw: 1.1, scale: 1.6, solid: false },
      { kind: 'corutower', at: [330, -160], abs: true, y: -150, yaw: 3.0, scale: 1.5, solid: false },
      { kind: 'corutower', at: [-250, 250], abs: true, y: -200, yaw: 0.9, scale: 2.1, solid: false },
      { kind: 'corutower', at: [560, 250], abs: true, y: -180, yaw: 2.7, scale: 2.0, solid: false },
      tower([-210, -70], 1, 380, 30),
      tower([190, -110], 2, 440),
      tower([60, -210], 1, 300, 28),
      tower([-60, -400], 3, 480),
      tower([260, 220], 0, 500),
      tower([420, -320], 1, 460, 34),
      tower([-470, 60], 3, 440),
      tower([-560, -380], 0, 520),
      tower([150, 520], 2, 560),
      tower([-200, 470], 1, 480, 32),
      tower([540, -120], 2, 470),
      tower([20, -560], 0, 500),
    ],
    scatter: [
      { kind: 'skyscraper', n: 70, within: [640, 2600], scale: [1, 1.6], stretch: [1.3, 2.5], solid: false, opts: { style: 0, seed: 3 } },
      { kind: 'skyscraper', n: 60, within: [640, 2600], scale: [1, 1.6], stretch: [1.3, 2.4], solid: false, opts: { style: 1, seed: 4 } },
      { kind: 'skyscraper', n: 60, within: [640, 2600], scale: [1, 1.6], stretch: [1.3, 2.6], solid: false, opts: { style: 2, seed: 5 } },
      { kind: 'skyscraper', n: 60, within: [640, 2600], scale: [1, 1.6], stretch: [1.3, 2.5], solid: false, opts: { style: 3, seed: 6 } },
      { kind: 'skyscraper', n: 40, within: [60, 620], scale: [0.7, 1.1], stretch: [0.6, 1.25], solid: false, opts: { style: 0, seed: 7 } },
      { kind: 'skyscraper', n: 40, within: [60, 620], scale: [0.7, 1.1], stretch: [0.6, 1.25], solid: false, opts: { style: 1, seed: 8 } },
      { kind: 'skyscraper', n: 40, within: [60, 620], scale: [0.7, 1.1], stretch: [0.6, 1.25], solid: false, opts: { style: 3, seed: 9 } },
    ],
    life: [
      { kind: 'jedi', n: 5, at: [0, 290], spread: 30, roam: 14, speed: 1.0, name: 'Jedi Knight', says: ['May the Force be with you.', 'The Council is in session. Even the Masters are worried.', 'Clouded, the future is. Even here.', 'The Archives are open to all Jedi. If an item does not appear in our records, it does not exist.'] },
      { kind: 'jedi', n: 1, at: [8, 300], roam: 6, speed: 0.6, scale: 0.38, r: 0.3, name: 'Yoda', says: ['Begun, the Clone War has.', 'Clouded, this boy’s future is.', 'Do, or do not. There is no try.', 'Lost a planet, Master Obi-Wan has. How embarrassing.'] },
      { kind: 'clone', n: 4, path: [[-5, 40], [-5, 245], [5, 245], [5, 40]], speed: 1.5, name: 'Clone trooper', says: ['Sir.', 'Yes, sir.', 'Move along. The Temple is closed.', 'Execute Order Sixty-Six.'] },
      { kind: 'senateguard', n: 4, at: [320, 40], spread: 24, roam: 5, speed: 0.6, r: 0.5, name: 'Senate Guard', says: ['(The guard says nothing. The helmet tilts, very slightly, toward the way out.)', 'The Senate is in session. State your business.'] },
      { kind: 'villager', n: 1, at: [330, 30], roam: 8, speed: 0.8, name: 'Padmé Amidala', says: ['So this is how liberty dies. With thunderous applause.', 'I truly believe that the Republic is worth fighting for.', 'Aggressive negotiations? What’s that?'] },
      { kind: 'villager', n: 5, path: [[34, 5], [288, 40]], speed: 1.2, name: 'Senate aide', says: ['The Chancellor has emergency powers now. Just until the crisis is over, they say.', 'The Military Creation Act vote is today. Everyone’s nervous.', 'I’m late, I’m late: the Senator from Alderaan is waiting.'] },
      { kind: 'villager', n: 3, path: [[-20, -22], [-138, -250]], speed: 1.1, name: 'Coruscanti', says: ['Don’t look down. Seriously, don’t.', 'Dex does the best nuna legs this side of the Federal District.', 'Mind the skylanes. Some of those drivers are maniacs.'] },
      { kind: 'villager', n: 1, at: [-150, -262], still: true, scale: 1.45, r: 0.8, name: 'Dexter Jettster', says: ['Hey, old buddy! Take a seat, I’ll be right with you.', 'That baby belongs to them cloners. What you got here is a Kamino saberdart.', 'Those Kaminoans keep to themselves. They’re cloners. Damn good ones, too.', 'I’d expect better from you Jedi. You oughta be able to tell the difference between knowledge and wisdom.'] },
      { kind: 'villager', n: 1, at: [196, -280], roam: 4, speed: 0.8, name: 'Elan Sleazebaggano', says: ['You wanna buy some death sticks?', '(You don’t want to sell me death sticks.) …I don’t want to sell you death sticks.', '(You want to go home and rethink your life.) …I want to go home and rethink my life.'] },
      { kind: 'c3po', n: 1, at: [-306, 70], still: true, r: 0.4, name: 'C-3PO', says: ['Oh, Master Anakin! I’m so glad you’re back. Mistress Padmé has been terribly worried.', 'I do believe the Senator’s apartment is the finest view on Coruscant. Not that I would know what to do with a view.', 'Don’t go too near the edge! It’s a long way down.'] },
      { kind: 'droid', n: 2, at: [6, 10], spread: 8, roam: 8, speed: 0.8, name: 'Astromech', says: ['(A busy, beeping hurry: it has somewhere to be.)'] },
      { kind: 'mousedroid', n: 2, at: [-8, 6], spread: 10, roam: 12, speed: 1.6, r: 0.2, solid: false },
      { kind: 'clone', n: 2, at: [-12, -4], spread: 4, still: true, face: 0.6, name: 'Coruscant Guard', says: ['Platform’s clear, sir.', 'The Temple is that way. Mind the drop.'] },
      { kind: 'villager', n: 3, at: [10, 18], spread: 10, roam: 10, speed: 1.0, name: 'Commuter', says: ['Skylane’s backed up to the 500 block again.', 'Don’t look down. I never look down.', 'Dex’s is that way, if you’re hungry.'] },
    ],
    flyovers: [
      { kind: 'shuttle', n: 1, metres: 20, alt: 380, speed: 70, every: 40 },
      { kind: 'arc170', n: 3, metres: 14.5, alt: 420, speed: 130, every: 60 },
      { kind: 'delta7', n: 2, metres: 8, alt: 360, speed: 140, every: 70 },
      { kind: 'nubian', n: 1, metres: 76, alt: 470, speed: 60, every: 90 },
      { kind: 'transport', n: 1, metres: 40, alt: 300, speed: 50, every: 70 },
    ],
    skyships: [{ kind: 'acclamator', metres: 752, at: [-2200, 520, 2600], yaw: 0.5 }],
  },
  kamino: {
    place: 'Tipoca City',
    line: 'Rain, and the sea, and white domes on stilts in the storm.',
    sky: {
      zenith: '#323c46',
      horizon: '#76828c',
      haze: 0.95,
      hazeColor: '#818d97',
      below: '#3a4650',
      suns: [{ az: 0.8, el: 0.6, color: '#c8d4e0', size: 0.01, glow: 0.3 }],
      clouds: { cover: 0.97, color: '#68747f', shade: '#2e3842', scale: 0.8, speed: 0.03, sharp: 0.8 },
    },
    fog: { color: '#6c7882', density: 0.0034 },
    light: { sun: 1.3, sky: '#9aa8b8', ground: '#3a4650', ambient: 1.15 },
    ground: {
      seed: 9,
      // (the sea floor, and the footing under the landing platform's column)
      layers: [{ type: 'level', height: -40 }, { type: 'island', at: [0, 0], r: 14, height: 45, core: 0.85, ragged: 0 }],
      palette: { low: '#2a343c', high: '#2a343c', rock: '#22282e', hLow: -50, hHigh: -30, grain: 0.2 },
    },
    water: { level: 0, color: '#3e525c', deep: '#16262e', kind: 'sea', foam: 0.7, waves: 1.4 },
    weather: [{ kind: 'rain', count: 4200, speed: 1.3 }, { kind: 'spray', count: 900 }],
    lightning: { every: 9, strength: 3.2 },
    fall: 12,
    dust: '#c8d4dc',
    edge: 'Ocean, and storm, and nothing else for a thousand kilometres. Even the Jedi Archives lost this place.',
    lines: {
      out: {
        xwing: [['luke', 'Kamino. I can’t see a thing for the rain, Artoo.'], ['r2', '(A sputtering, waterlogged complaint.)']],
        falcon: [['han', 'Who parks a city in the middle of an ocean? In a storm?'], ['chewie', '(A miserable, dripping groan.)']],
        cruiser: [['rick', 'Clone farm, Morty. Ocean planet, permanent storm, tall polite aliens. Textbook.'], ['morty', 'Are they going to clone us, Rick?']],
        rv: [['jesse', 'Yo, it’s raining, like, sideways.'], ['walt', 'Stay away from the edge. And don’t sign anything.']],
      },
    },
    land: { at: [0, 0], yaw: -0.5 },
    places: [
      {
        id: 'facility',
        name: 'The cloning facility',
        at: [0, 150],
        r: 40,
        about: 'Where the Kaminoans grow the Republic’s army: a hundred thousand clones in their tubes, ordered ten years ago by a Jedi Master the Jedi say never ordered it.',
        lines: {
          xwing: [['luke', 'They grew an army in there. People, Artoo. Grown like crops.'], ['r2', '(A horrified, wobbling whistle.)']],
          falcon: [['han', 'A whole army out of one guy. Imagine the arguments.'], ['chewie', '(A disgusted huff.)']],
          cruiser: [['rick', 'Accelerated growth, Morty. Half the lifespan, all the obedience. That’s just bad ethics with good branding.'], ['morty', 'That’s horrible, Rick.'], ['rick', 'I said that.']],
          rv: [['walt', 'One product. Perfect consistency. Every unit the same.'], ['jesse', 'Yo, why do you sound jealous right now?']],
        },
        things: [
          { kind: 'kpad', at: [0, -30], abs: true, y: 22, opts: { r: 24 } },
          { kind: 'tipocadome', at: [0, 24], yaw: Math.PI, abs: true, y: 0, scale: 1.5, solid: { r: 29 } },
        ],
      },
      {
        id: 'parade',
        name: 'The parade ground',
        at: [200, 50],
        r: 40,
        about: 'Clone troopers drilling in the rain, rank on rank of Jango Fett’s face behind white helmets. The Republic’s Grand Army, waiting for someone to give the order.',
        lines: {
          xwing: [['luke', 'Clone troopers. They became the stormtroopers, Artoo. The same ones.'], ['r2', '(A low, uneasy beep.)']],
          falcon: [['han', 'Real clones. Huh. I’d have figured they’d be better shots.'], ['chewie', '(A short laugh.)']],
          cruiser: [['morty', 'Rick, they all look the same. They all ARE the same.'], ['rick', 'Welcome to the military-industrial complex, Morty. It just has better hygiene here.']],
          rv: [['jesse', 'Dude, it’s like a whole army of the same guy. That guy’s gotta have a big ego.'], ['walt', 'He got paid, Jesse. And he got one for himself.']],
        },
        things: [{ kind: 'kpad', at: [0, 0], abs: true, y: 22, opts: { r: 40 } }],
      },
      {
        id: 'slave1',
        name: 'Jango Fett’s landing platform',
        at: [-170, -50],
        r: 32,
        about: 'Where Slave I stood in the rain, and where Obi-Wan fought Jango Fett, rocket pack and all, to the very edge of the platform. Then Jango got away, with a tracker on his ship.',
        lines: {
          xwing: [['luke', 'A Firespray. Boba Fett’s ship! Artoo, that’s the ship that took Han away.'], ['r2', '(An angry, buzzing whistle.)']],
          falcon: [['han', 'Slave I. I know that ship. I hate that ship.'], ['chewie', '(A furious roar.)']],
          cruiser: [['rick', 'Firespray-31, Morty. Seismic charges. Very rude ship.'], ['morty', 'It looks like a big iron, Rick.']],
          rv: [['jesse', 'Yo, that ship looks like a flat iron.'], ['walt', 'That ship belongs to a man who kills for money. Keep walking.']],
        },
        things: [
          { kind: 'kpad', at: [0, 0], abs: true, y: 22, opts: { r: 28 } },
          { kind: 'slave1', at: [2, 4], yaw: 0.6, abs: true, y: 22.3 },
        ],
      },
      {
        id: 'quarters',
        name: 'Jango Fett’s quarters',
        at: [-200, 116],
        r: 22,
        about: 'Where Jango Fett lived with his “son”, Boba, the one clone he kept for himself, unaltered: his payment, as well as his money.',
        lines: {
          xwing: [['luke', 'Someone lived here. A father and a son.'], ['r2', '(A careful, quiet beep.)']],
          falcon: [['han', 'Bounty hunter’s apartment. No pictures on the walls. Figures.']],
          cruiser: [['morty', 'He raised his own clone as his son, Rick. That’s kind of sweet?'], ['rick', 'That’s a mid-life crisis with extra steps, Morty.']],
        },
        things: [
          { kind: 'kpad', at: [0, -6], abs: true, y: 22, opts: { r: 16 } },
          { kind: 'tipocadome', at: [0, 22], yaw: Math.PI, abs: true, y: 0, scale: 0.7, solid: { r: 14 } },
        ],
      },
      {
        id: 'mast',
        name: 'The storm platform',
        at: [70, -230],
        r: 26,
        about: 'Out at the edge of Tipoca City, a weather mast in the wind: from here you can watch the aiwhas glide in over the waves, under the lightning.',
        lines: {
          xwing: [['luke', 'Look, Artoo, out over the waves: something’s flying!'], ['r2', '(An excited, rising whistle.)']],
          falcon: [['han', 'Great view. Of rain.'], ['chewie', '(A shake, and a spray of water off his fur.)'], ['han', 'Hey!']],
          cruiser: [['rick', 'Aiwhas, Morty. Whales with wings. Evolution got bored and started doing requests.'], ['morty', 'They’re beautiful, Rick.']],
          rv: [['jesse', 'Mr. White. Mr. White. There’s a flying whale.'], ['walt', 'Of course there is.']],
        },
        things: [
          { kind: 'kpad', at: [0, 0], abs: true, y: 22, opts: { r: 22 } },
          { kind: 'kmast', at: [-6, 6], abs: true, y: 22.3 },
        ],
      },
      {
        id: 'primeminister',
        name: 'The Prime Minister’s tower',
        at: [230, 220],
        r: 24,
        about: 'Lama Su’s tower. He showed Obi-Wan the army, and told him how pleased the Republic would be. Nobody there thought to mention who was paying.',
        lines: {
          xwing: [['luke', 'The Prime Minister of Kamino. I wonder what he’d make of the Empire.'], ['r2', '(A doubtful beep.)']],
          falcon: [['han', 'Let me guess. They want to talk about payment.']],
          cruiser: [['morty', 'Rick, they’re so polite.'], ['rick', 'Polite like a contract, Morty. Every word costs extra.']],
          rv: [['walt', 'A man who sells armies. He’ll want to know who we’re working for.'], ['jesse', 'Tell him we’re independent contractors, yo.']],
        },
        things: [
          { kind: 'kpad', at: [0, 0], abs: true, y: 22, opts: { r: 18 } },
          { kind: 'tipoca', at: [16, 22], abs: true, y: 0, opts: { style: 'tower' } },
        ],
      },
    ],
    things: [
      { kind: 'kpad', at: [0, 0], abs: true, y: 22, opts: { r: 30 } },
      // the pad's stores, under tarps against the rain
      { kind: 'cratecube', at: [-16, 12], yaw: 0.3, abs: true, y: 22 },
      { kind: 'cratecube', at: [-14.7, 12.6], yaw: 1.0, abs: true, y: 22 },
      { kind: 'barrel', at: [-17.5, 10.5], yaw: 0.2, abs: true, y: 22 },
      { kind: 'barrel', at: [-16.3, 9.8], yaw: 1.7, abs: true, y: 22 },
      { kind: 'empirecrate', at: [18, -12], yaw: 2.4, abs: true, y: 22 },
      { kind: 'lamp', at: [-20, 16], abs: true, y: 22, opts: { h: 5, light: '#cfe8ff', color: '#e8ecf0' } },
      { kind: 'lamp', at: [22, -8], abs: true, y: 22, opts: { h: 5, light: '#cfe8ff', color: '#e8ecf0' } },
      span([0, 0], [0, 120], 30, 24, 7, 'kamino', 22),
      span([0, 0], [200, 50], 30, 40, 7, 'kamino', 22),
      span([0, 0], [-170, -50], 30, 28, 6, 'kamino', 22),
      span([-170, -50], [-200, 110], 28, 16, 5, 'kamino', 22),
      span([0, 0], [70, -230], 30, 22, 5, 'kamino', 22),
      span([200, 50], [230, 220], 40, 18, 5, 'kamino', 22),
      // the rest of the city, out in the storm
      { kind: 'tipocadome', at: [-130, 270], yaw: 0.5, abs: true, y: 0, solid: false },
      { kind: 'tipocadome', at: [130, 330], yaw: 2.1, abs: true, y: 0, solid: false, scale: 1.3 },
      { kind: 'tipocadome', at: [-320, 240], yaw: 1.2, abs: true, y: 0, solid: false },
      { kind: 'tipocadome', at: [-330, -210], yaw: 0.1, abs: true, y: 0, solid: false, scale: 1.2 },
      { kind: 'tipocadome', at: [340, -120], yaw: 2.6, abs: true, y: 0, solid: false },
      { kind: 'tipocadome', at: [-80, -330], yaw: 1.9, abs: true, y: 0, solid: false },
      { kind: 'tipocadome', at: [390, 160], yaw: 0.4, abs: true, y: 0, solid: false, scale: 1.4 },
      { kind: 'tipocadome', at: [-430, 40], yaw: 1.4, abs: true, y: 0, solid: false },
      { kind: 'tipocadome', at: [210, -390], yaw: 0.9, abs: true, y: 0, solid: false },
      { kind: 'tipocadome', at: [20, 470], yaw: 2.8, abs: true, y: 0, solid: false, scale: 1.6 },
      { kind: 'tipocadome', at: [520, -320], yaw: 0.2, abs: true, y: 0, solid: false },
      { kind: 'tipocadome', at: [-520, 380], yaw: 1.1, abs: true, y: 0, solid: false, scale: 1.3 },
      { kind: 'tipocadome', at: [640, 60], yaw: 2.2, abs: true, y: 0, solid: false },
      { kind: 'tipocadome', at: [-640, -260], yaw: 0.7, abs: true, y: 0, solid: false, scale: 1.5 },
      { kind: 'tipocadome', at: [300, 520], yaw: 1.6, abs: true, y: 0, solid: false },
      { kind: 'tipocadome', at: [-240, -520], yaw: 2.4, abs: true, y: 0, solid: false },
      { kind: 'tipoca', at: [-180, 420], abs: true, y: 0, solid: false, opts: { style: 'tower' } },
      { kind: 'tipoca', at: [420, -40], abs: true, y: 0, solid: false, opts: { style: 'tower' } },
      { kind: 'tipoca', at: [-420, -120], abs: true, y: 0, solid: false, opts: { style: 'tower' } },
      { kind: 'kpad', at: [-260, 330], abs: true, y: 22, solid: false, opts: { r: 22 } },
      { kind: 'kpad', at: [460, 260], abs: true, y: 22, solid: false, opts: { r: 26 } },
    ],
    // (lifted from the sea floor to the waves: sink below nothing)
    scatter: [
      { kind: 'tipocadome', n: 30, within: [360, 1000], scale: [0.8, 1.5], sink: -40, dry: false, solid: false },
      { kind: 'tipoca', n: 10, within: [360, 1000], scale: [0.8, 1.3], sink: -40, dry: false, solid: false, opts: { style: 'tower' } },
      { kind: 'buoy', n: 40, within: [80, 640], scale: [0.8, 1.2], sink: -40.6, dry: false, solid: false },
    ],
    life: [
      { kind: 'clone', n: 20, path: [[188, 36], [194, 36], [200, 36], [206, 36], [212, 36], [188, 43], [194, 43], [200, 43], [206, 43], [212, 43], [188, 50], [194, 50], [200, 50], [206, 50], [212, 50], [188, 57], [194, 57], [200, 57], [206, 57], [212, 57]], still: true, face: Math.PI, name: 'Clone trooper', says: ['Sir!', 'Yes, sir.', 'We’re ready to ship out, sir. Just waiting on the order.', 'Training’s over when the Kaminoans say it’s over.'] },
      { kind: 'clone', n: 6, path: [[176, 22], [224, 22], [226, 78], [174, 78]], speed: 1.5, name: 'Clone cadet', says: ['Left, right, left. Sir!', 'Excuse us, sir. Drill.'] },
      { kind: 'clone', n: 2, at: [6, -12], spread: 8, roam: 10, speed: 1.1, name: 'Clone trooper', says: ['Welcome to Tipoca City, sir.', 'Mind the edge. It’s a long way down in this weather.'] },
      { kind: 'clonephase1', n: 4, at: [-8, -6], spread: 4, still: true, face: 2.6, name: 'Clone trooper', says: ['Sir.', 'Phase One armour, sir. Heavy, but it keeps the rain out.', 'The cadets drill on the far pad. We stand here.'] },
      { kind: 'r5', n: 1, at: [16, 8], roam: 6, speed: 0.6, name: 'An R5 unit', says: ['(A damp, miserable beep.)'] },
      { kind: 'kaminoan', n: 1, at: [12, 6], roam: 5, speed: 0.7, name: 'Taun We', says: ['Master Jedi. So good to see you. The Prime Minister expects you.', 'I trust you will find everything you need. The clones are most impressive.', 'They are totally obedient, taking any order without question.'] },
      { kind: 'kaminoan', n: 3, at: [0, 112], spread: 10, roam: 7, speed: 0.7, name: 'Kaminoan', says: ['The clones are bred for combat. They show much less independence than the original host.', 'Ten years ago a Jedi Master placed the order. We have been working ever since.', 'Please, this way. The weather is most inclement today.'] },
      { kind: 'kaminoan', n: 1, at: [228, 216], still: true, scale: 1.08, name: 'Lama Su', says: ['I trust you are going to stay for a while?', 'You will be delighted to hear we are on schedule. Two hundred thousand units are ready, with a million more well on the way.', 'Magnificent, aren’t they?'] },
      { kind: 'jango', n: 1, at: [-164, -44], roam: 6, speed: 0.9, name: 'Jango Fett', says: ['I’m just a simple man, trying to make my way in the universe.', 'Ever make your way as far into the interior as Coruscant?', 'Boba, pack your things. We’re leaving.'] },
      { kind: 'villager', n: 1, at: [-198, 108], roam: 4, speed: 1.0, scale: 0.68, name: 'Boba Fett', says: ['My dad’s the best bounty hunter in the galaxy.', 'Dad! There’s a Jedi on the landing platform!', 'Get him, Dad! Get him!'] },
      { kind: 'aiwha', n: 2, path: [[300, -150], [430, -260], [300, -400], [170, -300]], y: 72, speed: 9, solid: false },
      { kind: 'aiwha', n: 2, path: [[-300, -140], [-440, -40], [-380, 180], [-260, 40]], y: 66, speed: 8, solid: false },
    ],
    flyovers: [
      { kind: 'delta7', n: 1, metres: 8, alt: 80, speed: 120, every: 60 },
      { kind: 'arc170', n: 2, metres: 14.5, alt: 110, speed: 130, every: 80 },
      { kind: 'acclamator', n: 1, metres: 752, alt: 420, speed: 40, every: 120 },
    ],
    skyships: [{ kind: 'acclamator', metres: 752, at: [1300, 320, -1500], yaw: 0.8 }],
  },
  geonosis: {
    place: 'The Plains of Geonosis',
    line: 'Red rock, hive spires and a ringed, rust-coloured sky.',
    sky: {
      zenith: '#b77a62',
      horizon: '#f1c39a',
      haze: 0.9,
      hazeColor: '#f5c89c',
      suns: [{ az: 2.3, el: 0.32, color: '#fff0d6', size: 0.02, glow: 1.3 }],
      clouds: { cover: 0.12, color: '#fbe0c4', shade: '#c08a6a', scale: 0.5, speed: 0.003 },
      bodies: [
        { az: -0.7, el: 0.5, size: 0.022, color: '#d8c0a8', color2: '#b89a80', bands: 0 },
        { az: -0.4, el: 0.36, size: 0.01, color: '#e0ccb4' },
      ],
    },
    fog: { color: '#e6b48c', density: 0.0009 },
    light: { sun: 3.0, sky: '#f0c8a8', ground: '#a0583a', ambient: 0.75 },
    ground: { detail: 'redsoil', detailLook: { color: 0.75, normal: 0.8 },
      seed: 33,
      wind: 1.1,
      layers: [
        { type: 'swell', scale: 420, height: 7 },
        { type: 'hills', scale: 160, height: 6 },
        { type: 'mesas', scale: 480, height: 34, cover: 0.3, cliff: 0.05 },
        { type: 'ridges', scale: 120, height: 4 },
        { type: 'mountains', from: 750, to: 3000, height: 380, scale: 1000 },
      ],
      palette: {
        low: '#b46c44',
        high: '#c98b5c',
        rock: '#8a4a2e',
        accent: '#d49c66',
        deep: '#9c5a36',
        hLow: -2,
        hHigh: 18,
        rockAt: 0.34,
        accentCover: 0.24,
        ripple: { strength: 0.06, scale: 2.6, wind: 1.1 },
        grain: 0.7,
        mark: '#8a4a2e',
      },
    },
    weather: [{ kind: 'sand', count: 1300, color: '#e8a878' }],
    dust: '#d89a6a',
    edge: 'Red rock and hive spires, as far as the haze lets you see. The droid army came from out there; best not to follow it.',
    lines: {
      out: {
        xwing: [['luke', 'Geonosis. This is where the Clone Wars started, Artoo.'], ['r2', '(A wary, low beep: Artoo remembers.)']],
        falcon: [['han', 'Bug planet. Great. Keep the blasters handy, Chewie.'], ['chewie', '(A grim growl.)']],
        cruiser: [['rick', 'Geonosis, Morty. A hive of space termites who build robots for whoever pays. My kind of planet.'], ['morty', 'Rick, there’s a ring in the sky!']],
        rv: [['jesse', 'Yo, it’s like New Mexico, but redder. And with bugs.'], ['walt', 'Factories, Jesse. The whole planet is a factory.']],
      },
    },
    land: { at: [0, 0], yaw: -0.6 },
    places: [
      {
        id: 'arena',
        name: 'The Petranaki arena',
        at: [-260, 200],
        r: 100,
        flat: { r: 92, edge: 24 },
        about: 'The execution arena, where Obi-Wan, Anakin and Padmé were chained to the pillars for the reek, the acklay and the nexu; and where two hundred Jedi came to save them.',
        lines: {
          xwing: [['luke', 'The arena. Ben was chained up in there with my father. And my mother.'], ['r2', '(A frantic, remembering whistle: Artoo flew in there.)']],
          falcon: [['han', 'Executions as entertainment. Remind me why we came here?'], ['chewie', '(A disgusted roar.)']],
          cruiser: [['morty', 'Rick, they fed people to monsters here! For fun!'], ['rick', 'It’s a stadium, Morty. Every stadium is that, eventually.']],
          rv: [['jesse', 'Yo, it’s like the Colosseum. With bugs.'], ['walt', 'Bread and circuses, Jesse. Keep them watching the arena, and they never look up.']],
        },
        things: [
          { kind: 'arena', at: [0, 0], yaw: 2.23 },
          { kind: 'pillars', at: [0, 0], yaw: 2.23 },
          { kind: 'droideka', at: [6, -20], yaw: 2.4, opts: { shield: true } },
          { kind: 'droideka', at: [-14, -16], yaw: 2.0 },
        ],
      },
      {
        id: 'battle',
        name: 'The first battle',
        at: [260, 170],
        r: 70,
        flat: { r: 62, edge: 26 },
        about: 'Where the Republic’s gunships came down out of the sky with the clone army, and the Clone Wars began: AT-TEs against spider droids, clones against droids, in the dust.',
        lines: {
          xwing: [['luke', 'This is where the clones fought the droids. The first battle of the whole war.'], ['r2', '(A soft, sad tune.)']],
          falcon: [['han', 'So this is where it all started. Look at the size of those walkers.'], ['chewie', '(A low whistle-growl.)']],
          cruiser: [['rick', 'The opening battle of a war both sides were secretly running, Morty. Twist.'], ['morty', 'That’s so messed up, Rick.']],
          rv: [['jesse', 'Yo, the gunships. The gunships are so sick, Mr. White.'], ['walt', 'One man ordered both armies. And everyone cheered.']],
        },
        things: [
          { kind: 'laat', at: [-20, -6], yaw: 2.6, y: 1.5 },
          { kind: 'laat', at: [14, 20], yaw: 2.9, y: 2.5 },
          { kind: 'laat', at: [24, -26], yaw: 2.3, y: 1.8 },
          { kind: 'atte', at: [-30, 30], yaw: 2.4, model: false },
          { kind: 'crates', at: [0, 4] },
          { kind: 'crates', at: [-8, 14] },
        ],
      },
      {
        id: 'command',
        name: 'The forward command post',
        at: [120, 330],
        r: 26,
        flat: { r: 20, edge: 14 },
        about: 'Yoda’s command post on a ridge over the battle, the fight drawn in blue light on the holotable. Begun, the Clone War has.',
        lines: {
          xwing: [['luke', 'Master Yoda was here? Commanding clones?'], ['r2', '(A confirming beep, and a holo-flicker of a tiny green Jedi.)']],
          falcon: [['han', 'A tactical map. Nice. I never had one of those. Didn’t need one.']],
          cruiser: [['morty', 'That’s Yoda’s table, Rick!'], ['rick', 'Nine hundred years old and he fights a war off a hologram, Morty. Delegation.']],
        },
        things: [{ kind: 'commandpost', at: [0, 0], yaw: 3.6 }],
      },
      {
        id: 'foundry',
        name: 'The droid foundry',
        at: [-330, -230],
        r: 60,
        flat: { r: 50, edge: 24 },
        about: 'Where the Geonosians stamp out battle droids by the million in furnace light: Anakin and Padmé nearly went through the presses, and Threepio’s head ended up on a droid’s body.',
        lines: {
          xwing: [['luke', 'A droid factory. Artoo, stay away from those conveyors.'], ['r2', '(A very, very firm beep.)']],
          falcon: [['han', 'So this is where all those droids come from. Somebody should shut this place down.'], ['chewie', '(An approving growl.)']],
          cruiser: [['rick', 'Mass production, Morty. They’re not even trying to make them good. Just many.'], ['morty', 'That’s every robot army, Rick.']],
          rv: [['walt', 'An assembly line. Efficient. Terrible quality control.'], ['jesse', 'Yo, they put the gold guy’s head on a robot. That’s messed up.']],
        },
        things: [
          { kind: 'foundry', at: [0, -6], yaw: 0.8 },
          { kind: 'droideka', at: [14, 22], yaw: 0.8 },
        ],
      },
      {
        id: 'hangar',
        name: 'Count Dooku’s hangar',
        at: [300, -300],
        r: 40,
        flat: { r: 34, edge: 18 },
        about: 'Dooku’s secret hangar, where Yoda caught up with him, and the old Count dropped a pillar on Obi-Wan and Anakin to get away in his solar sailer.',
        lines: {
          xwing: [['luke', 'Yoda fought here. Ben told me. Yoda, with a lightsaber!'], ['r2', '(An awed warble.)']],
          falcon: [['han', 'A guy with a lightsaber and a solar sail. Sounds like a nice life.']],
          cruiser: [['morty', 'Yoda did flips here, Rick! Backflips!'], ['rick', 'Nine hundred years old, Morty, and he still can’t keep his feet on the ground.']],
          rv: [['jesse', 'Yo, that’s a sail. A space sail. That’s so tight.'], ['walt', 'It’s a getaway car, Jesse. The most important thing a man can own.']],
        },
        things: [
          { kind: 'geohangar', at: [0, -10], yaw: -0.7 },
          { kind: 'solarsailer', at: [-6, 2], yaw: 2.4, y: 0.4 },
        ],
      },
      {
        id: 'hive',
        name: 'The Stalgasin hive',
        at: [-40, -420],
        r: 60,
        about: 'The Geonosians’ hive, their spires of red rock rising out of the plain, honeycombed, buzzing with drones on their wings.',
        lines: {
          xwing: [['luke', 'It’s a hive. Like a sandwasp nest, but the size of a city.'], ['r2', '(A buzzy, nervous whistle.)']],
          falcon: [['han', 'Bugs. I hate bugs.'], ['chewie', '(A rumbling, uneasy growl.)']],
          cruiser: [['rick', 'Eusocial insectoids, Morty. One queen, a billion workers, zero unions.'], ['morty', 'They’re kind of looking at us, Rick.']],
        },
        things: [
          { kind: 'hive', at: [0, 0], opts: { h: 95, seed: 2 } },
          { kind: 'hive', at: [34, 20], opts: { h: 70, seed: 3 } },
          { kind: 'hive', at: [-30, 28], opts: { h: 60, seed: 4 } },
          { kind: 'hive', at: [-24, -36], opts: { h: 80, seed: 5 } },
          { kind: 'hive', at: [30, -30], opts: { h: 55, seed: 6 } },
        ],
      },
      {
        id: 'coreships',
        name: 'The core ships',
        at: [470, -120],
        r: 70,
        flat: { r: 50, edge: 24 },
        about: 'The Separatists’ great spherical starships, set down on the plain to load the droid army; when the battle turned, they lifted off and ran for space.',
        lines: {
          xwing: [['luke', 'Those spheres are the hearts of Trade Federation battleships. Big enough to carry an army.'], ['r2', '(A long, impressed whistle.)']],
          falcon: [['han', 'Now that’s a cargo hold.'], ['chewie', '(A thoughtful rumble.)']],
          cruiser: [['morty', 'Rick, it’s taking off! A whole ball the size of a stadium!'], ['rick', 'Big round target, Morty. The Republic’s about to learn some geometry.']],
          rv: [['jesse', 'Yo, the giant balls are leaving.'], ['walt', 'Jesse.']],
        },
        things: [
          { kind: 'coresphere', at: [240, 40], yaw: 0.2, model: false, solid: false },
          { kind: 'coresphere', at: [160, -240], yaw: 1.1, model: false, solid: false, opts: { rise: 4 } },
          { kind: 'droideka', at: [-10, 6], yaw: -1.6 },
          { kind: 'droideka', at: [-14, -4], yaw: -1.5, opts: { shield: true } },
        ],
      },
    ],
    things: [
      // the ring, across the sky
      { kind: 'skyring', at: [0, 0], abs: true, y: 0, solid: false, opts: { az: 0.3, el: 0.36, width: 0.06 } },
      // where you set down: a clone squad's forward post, a BARC speeder,
      // and a spider droid they brought down
      { kind: 'barc', at: [-24, -18], yaw: 1.4 },
      { kind: 'cratecube', at: [-18, 14], yaw: 0.5 },
      { kind: 'cratecube', at: [-16.7, 14.5], yaw: 1.3 },
      { kind: 'barrel', at: [-19.5, 16], yaw: 0.2 },
      { kind: 'lamp', at: [-14, 18], opts: { h: 4, light: '#ffd9a0' } },
      { kind: 'homingspider', at: [62, -38], yaw: 2.6, roll: 0.4, sink: 0.5, solid: { r: 3 } },
      { kind: 'wrecksmoke', at: [62, -38], solid: false, opts: { h: 16, r: 1.2 } },
      // AT-TEs out on the plain, and a third gunship coming in
      { kind: 'atte', at: [140, 60], yaw: 2.0, model: false },
      { kind: 'laat', at: [80, 140], yaw: 2.2, y: 24, solid: false },
      // the hives along the horizon (and three nearer), too big to scatter:
      // the hive model (a mesa with its spires), scaled to each one's height
      { kind: 'geohive', at: [-620, 120], yaw: 1.74, scale: 1.07, sink: 4.3, solid: false },
      { kind: 'geohive', at: [-560, -420], yaw: 3.04, scale: 0.8, sink: 3.2, solid: false },
      { kind: 'geohive', at: [380, 560], yaw: 4.34, scale: 0.93, sink: 3.7, solid: false },
      { kind: 'geohive', at: [650, 300], yaw: 5.64, scale: 0.73, sink: 2.9, solid: false },
      { kind: 'geohive', at: [-200, 640], yaw: 0.66, scale: 0.87, sink: 3.5, solid: false },
      { kind: 'geohive', at: [180, -640], yaw: 1.96, scale: 1, sink: 4, solid: false },
      { kind: 'geohive', at: [-120, 140], yaw: 3.26, scale: 0.3, sink: 1.2 },
      { kind: 'geohive', at: [140, -120], yaw: 4.56, scale: 0.25, sink: 1 },
      { kind: 'geohive', at: [-160, -60], yaw: 5.86, scale: 0.35, sink: 1.4 },
    ],
    scatter: [
      { kind: 'spire', n: 90, within: [70, 900], scale: [0.35, 1.2], stretch: [0.7, 1.4] },
      { kind: 'spire', n: 40, within: [70, 600], scale: [0.25, 0.6], opts: { seed: 5, color: '#9a5a38' } },
      { kind: 'rock', n: 130, within: [20, 580], scale: [0.6, 3], opts: { color: '#94583a', sharp: 0.55 } },
      { kind: 'stones', n: 240, within: [8, 420], scale: [0.25, 0.7], solid: false, opts: { color: '#a0623e' } },
    ],
    life: [
      { kind: 'geonosian', n: 8, at: [-250, 190], spread: 30, roam: 16, speed: 1.2, name: 'Geonosian', says: ['(A dry, clicking chatter.)', '(It buzzes its wings and points you back toward the gate.)', '(Clicks, a hiss, and something like a laugh.)'] },
      { kind: 'geonosian', n: 1, at: [-262, 220], still: true, scale: 1.1, name: 'Poggle the Lesser', says: ['(The Archduke clicks a command. Somewhere, the crowd roars.)', '(He gestures at the pillars, and then at you, and then at the pillars again.)'] },
      { kind: 'acklay', n: 1, at: [-262, 196], roam: 22, speed: 1.6, r: 2, model: false },
      { kind: 'jedi', n: 2, at: [-256, 202], spread: 6, roam: 8, speed: 1.0, name: 'Jedi', says: ['This party’s over.', 'Hold on. This whole operation’s about to get a lot more interesting.', 'I’ve a bad feeling about this.'] },
      { kind: 'geonosian', n: 6, path: [[-80, -360], [10, -400], [-30, -490], [-110, -440]], y: 18, speed: 5, name: 'Geonosian drone', says: ['(A buzzing dive past your head.)'] },
      { kind: 'geonosian', n: 4, at: [-320, -210], spread: 24, roam: 14, speed: 1.1, name: 'Geonosian worker', says: ['(It clicks irritably and hauls a droid torso past you.)', '(Click. Click-click. Back to work.)'] },
      { kind: 'c3po', n: 1, at: [-312, -206], still: true, name: 'C-3PO', says: ['Oh, this is such a drag.', 'Die, Jedi dogs! …Oh, what did I say?', 'I’m terribly sorry about all this.', 'Machines making machines. How perverse.'] },
      { kind: 'clonephase1', n: 4, at: [-20, 10], spread: 5, still: true, face: -0.6, name: 'Clone trooper', says: ['Forward post, sir. The droids pulled back to the spires.', 'First day of the war, and we’re already winning.', 'Gunships inbound. Keep clear of the pad.'] },
      { kind: 'dwarfspider', n: 2, path: [[40, 50], [70, 40], [84, 60], [60, 76]], speed: 0.9, r: 1.0, name: 'Dwarf spider droid', says: ['(It clicks. Its cannon finds you, then loses interest.)'] },
      { kind: 'battledroid', n: 4, at: [56, -20], spread: 10, roam: 8, speed: 1.2, name: 'Battle droid', says: ['Roger, roger.', 'The spider droid is… down. Uh-oh.', 'Fall back! Fall back!'] },
      { kind: 'clone', n: 10, at: [256, 176], spread: 36, roam: 14, speed: 1.6, name: 'Clone trooper', says: ['Move up! Move up!', 'Gunship coming in, keep your heads down!', 'Sir, the droids are pulling back to the core ships.', 'Watch the spider droids!'] },
      { kind: 'clone', n: 3, at: [120, 326], spread: 6, roam: 5, speed: 1, name: 'Clone commander', says: ['Master Yoda, all forward positions are advancing.', 'Target the core ships, sir?', 'Concentrate all fire on the nearest starship.'] },
      { kind: 'jedi', n: 1, at: [116, 334], still: true, scale: 0.38, r: 0.3, name: 'Yoda', says: ['Concentrate all fire on the nearest starship.', 'Around the survivors a perimeter create.', 'Begun, the Clone War has.', 'Victory? Victory, you say? Not victory.'] },
      { kind: 'battledroid', n: 10, path: [[420, -60], [380, -10], [330, 30], [380, -100], [440, -140]], speed: 1.4, name: 'Battle droid', says: ['Roger, roger.', 'Retreat! Retreat! To the core ships!', 'Uh-oh.'] },
      { kind: 'superdroid', n: 4, at: [430, -110], spread: 20, roam: 12, speed: 1.0, name: 'Super battle droid', says: ['(It raises a wrist blaster and stomps past.)', 'Halt. Identify.'] },
      { kind: 'atte', n: 2, path: [[200, 260], [340, 120], [300, 40], [160, 180]], speed: 2.2, r: 5, model: false, solid: false },
      { kind: 'jedi', n: 1, at: [306, -296], roam: 6, speed: 0.8, name: 'Count Dooku', says: ['Master Kenobi, you disappoint me. Yoda holds you in such high esteem.', 'I have become more powerful than any Jedi.', 'This is just the beginning.'] },
    ],
    rides: [
      { kind: 'speederbike', at: [290, -282], yaw: 2.4 },
      { kind: 'speederbike', at: [18, -14], yaw: 2.0 },
    ],
    flyovers: [
      { kind: 'acclamator', n: 1, metres: 752, alt: 380, speed: 45, every: 90 },
      { kind: 'coreship', n: 1, metres: 600, alt: 500, speed: 30, every: 120 },
      { kind: 'delta7', n: 2, metres: 8, alt: 90, speed: 130, every: 60 },
      { kind: 'vulture', n: 3, metres: 7, alt: 70, speed: 140, every: 60 },
    ],
    skyships: [{ kind: 'acclamator', metres: 752, at: [-1400, 760, 2200], yaw: 2.6 }],
  },
};
