// Coruscant, from the ground: the Federal District's platform, the Jedi
// Temple and its Processional Way, the Senate, 500 Republica, Dex's Diner,
// the Outlander Club and the Works, with the skylanes between. (sites/
// index.js has what a site is; core.js has the rest of the core worlds.)

import { span, tower } from './core';

export const SITE = {
  // the look (look.js): violet shade, the sunset's amber at the horizon and
  // the blue overhead, towers melting into the haze by distance
  look: { shadow: '#5a4a7a', edge: [0.12, 0.8], fogBelow: 0.7, halo: '#ff9a50' },
  place: 'The Federal District',
  line: 'A city to the edge of the world, and down further than anyone’s been.',
  sky: {
    zenith: '#26335e',
    horizon: '#f2a46a',
    haze: 0.95,
    hazeColor: '#f7b47c',
    below: '#6a4a52',
    suns: [{ az: -1.9, el: 0.07, color: '#ffb072', size: 0.03, glow: 1.7 }],
    clouds: { cover: 0.22, color: '#f6c49c', shade: '#6e5674', scale: 0.45, speed: 0.004, sharp: 1.5 },
    stars: 0.25,
    bodies: [
      { az: 0.9, el: 0.42, size: 0.016, color: '#d8d0c8', color2: '#b8aca0' },
      { az: 1.2, el: 0.3, size: 0.008, color: '#e0d8d0' },
    ],
  },
  fog: { color: '#c88c72', density: 0.0016 },
  light: { sun: 2.4, sky: '#8a92c4', ground: '#6a4a48', ambient: 0.9 },
  ground: {
    seed: 5,
    layers: [{ type: 'level', height: -330 }],
    palette: { low: '#4a3a3e', high: '#4a3a3e', rock: '#3a2e30', hLow: -340, hHigh: -320, grain: 0.2 },
  },
  fall: -40,
  dust: '#b8a8a0',
  edge: 'More city. All the way round the planet, and all the way down. Better turn back before you get lost on level 1313.',
  lines: {
    out: {
      xwing: [['luke', 'Coruscant. The whole planet is one city, Artoo. I didn’t think it’d be this… big.'], ['r2', '(A nervous warble about the long drop.)']],
      falcon: [['han', 'Imperial Center. Or whatever they call it now. Watch your pockets, Chewie.'], ['chewie', '(A low, wary growl.)']],
      cruiser: [['rick', 'An ecumenopolis, Morty. One city, one planet, a trillion people and not one decent parking spot.'], ['morty', 'Rick, I can’t see the ground. Where’s the ground?']],
      rv: [['jesse', 'Yo, Mr. White, it’s like, all city. Where do people even cook?'], ['walt', 'Down there, Jesse. Where nobody looks.']],
    },
  },
  land: { at: [0, 0], yaw: 0.6 },
  places: [
    {
      id: 'temple',
      name: 'The Jedi Temple',
      at: [0, 400],
      r: 125,
      about: 'Home of the Jedi Order for a thousand generations: a ziggurat of pale stone under five spires, the High Council meeting in the tallest. Until the night of Order 66.',
      lines: {
        xwing: [['luke', 'The Jedi Temple. Ben trained here, Artoo. And my father.'], ['r2', '(A long, sad, low whistle.)']],
        falcon: [['han', 'So this is where they kept all the Jedi. Huh. Bigger than I figured, for a bunch of hokey religion.'], ['chewie', '(A respectful rumble.)']],
        cruiser: [['morty', 'Rick, it’s the Jedi Temple! Can we go in?'], ['rick', 'It’s a monastery for space wizards, Morty. Ten thousand years and they never put in an elevator.']],
        rv: [['jesse', 'Yo, that’s where the Jedi live. Like, the actual Jedi.'], ['walt', 'Lived, Jesse. Something happened here.']],
      },
      things: [
        { kind: 'jeditemple', at: [0, 32], yaw: Math.PI, abs: true, y: 0, solid: { box: [100, 100] } },
        { kind: 'plinth', at: [0, 32], abs: true, y: 0, solid: false, opts: { w: 196, d: 196 } },
      ],
    },
    {
      id: 'processional',
      name: 'The Processional Way',
      at: [0, 150],
      r: 36,
      about: 'The avenue of statues to the Temple’s doors, Jedi of old standing over it. On the night of Order 66, Anakin Skywalker marched the 501st up it.',
      lines: {
        xwing: [['luke', 'Jedi, all the way up. I wonder if Ben’s master is one of them.'], ['r2', '(A quiet beep. Artoo saw that night, from Padmé’s window.)']],
        falcon: [['han', 'Nice statues. Bet nobody’s dusted ’em in twenty years.']],
        cruiser: [['rick', 'Statues of dead wizards lining the road to a building full of dead wizards, Morty. Subtle.'], ['morty', 'You’re really a buzzkill today, Rick.']],
      },
      things: [],
    },
    {
      id: 'senate',
      name: 'The Galactic Senate',
      at: [400, 40],
      r: 100,
      about: 'The Senate Rotunda, a dome as big as a city, where a thousand worlds argued, and where liberty died, with thunderous applause.',
      lines: {
        xwing: [['luke', 'The Senate. The Emperor dissolved it. Leia sat in it, though, when she was a senator.'], ['r2', '(An indignant squawk at the Emperor’s name.)']],
        falcon: [['han', 'Politicians. Give me a Hutt any day: at least you know where you stand.']],
        cruiser: [['morty', 'That’s where the Emperor took over, Rick. They all clapped!'], ['rick', 'A thousand senators cheered for a dictator, Morty. That’s the most realistic thing in the franchise.']],
        rv: [['walt', 'A man can say anything in a room like that, if they’re afraid enough.'], ['jesse', 'Yo, that’s dark, Mr. White.']],
      },
      things: [
        { kind: 'deck', at: [-60, 0], abs: true, y: 0, opts: { hw: 50, hd: 40 } },
        { kind: 'senate', at: [70, 0], abs: true, y: 0, solid: { r: 56 } },
        { kind: 'plinth', at: [70, 0], abs: true, y: 0, solid: false, opts: { w: 112, round: true } },
        { kind: 'statue', at: [-96, 34], abs: true, y: 0, yaw: Math.PI },
        { kind: 'statue', at: [-66, 34], abs: true, y: 0, yaw: Math.PI },
        { kind: 'statue', at: [-36, 34], abs: true, y: 0, yaw: Math.PI },
        { kind: 'statue', at: [-96, -34], abs: true, y: 0 },
        { kind: 'statue', at: [-66, -34], abs: true, y: 0 },
        { kind: 'statue', at: [-36, -34], abs: true, y: 0 },
      ],
    },
    {
      id: 'republica',
      name: '500 Republica',
      at: [-308, 65],
      r: 26,
      about: 'The tallest of the Senate’s apartment towers: Senator Amidala lived at the top. Assassins sent kouhuns to her bed here, and Anakin went out the window after the droid.',
      lines: {
        xwing: [['luke', 'This was my mother’s home? Artoo, you’ve been here before, haven’t you?'], ['r2', '(A soft, sad whistle, and a bleep of yes.)']],
        falcon: [['han', 'Senator’s penthouse. Swanky. I’d steal the furniture, but it’d never fit in the Falcon.']],
        cruiser: [['morty', 'Rick, Anakin jumped out of this window. Onto a flying droid.'], ['rick', 'And then he married her, Morty. Real “guy who jumps out of windows” energy.']],
      },
      things: [{ kind: 'republica', at: [-22, 4.6], yaw: 1.78, abs: true, y: 0 }],
    },
    {
      id: 'dex',
      name: 'Dex’s Diner',
      at: [-150, -270],
      r: 26,
      about: 'Dexter Jettster’s diner in CoCo Town, where Obi-Wan came with a strange dart: a Kamino saberdart, said Dex, from a planet the Jedi Archives didn’t have.',
      lines: {
        xwing: [['luke', 'A diner! Artoo, I could really go for something that isn’t a ration bar.'], ['r2', '(A grumpy beep: the sign says no droids.)']],
        falcon: [['han', 'Now this is my kind of place. Grease, caf and nobody asking questions.'], ['chewie', '(A hungry rumble.)']],
        cruiser: [['rick', 'Finally, Morty! A 1950s diner run by a four-armed alien. The one constant in the multiverse.'], ['morty', 'Do you think they do milkshakes?']],
        rv: [['jesse', 'Yo, a diner! Do you think they have, like, space pancakes?'], ['walt', 'Order something cheap. We’re not here to eat.']],
      },
      things: [
        { kind: 'cplatform', at: [0, 0], abs: true, y: 0, opts: { r: 24, light: '#ffb070' } },
        { kind: 'dexdiner', at: [0, 4], yaw: 0.6, abs: true, y: 0.3 },
        { kind: 'airspeeder', at: [-12, -8], yaw: 2.3, abs: true, y: 0.3 },
        { kind: 'lamp', at: [12, -10], abs: true, y: 0.3, opts: { h: 4, light: '#ffb070' } },
      ],
    },
    {
      id: 'club',
      name: 'The Outlander Club',
      at: [200, -290],
      r: 26,
      about: 'A gambling club in the Uscru entertainment district, all neon and noise: where Obi-Wan cornered the changeling Zam Wesell, and turned down some death sticks.',
      lines: {
        xwing: [['luke', 'Ben said never to go into places like this. I think. Stay close, Artoo.'], ['r2', '(A nervous little burble.)']],
        falcon: [['han', 'Uscru. I know a guy in there owes me money. Let’s not go in.'], ['chewie', '(A knowing growl.)']],
        cruiser: [['morty', 'Rick, a guy in there tried to sell me death sticks.'], ['rick', 'You don’t want to buy death sticks, Morty. You want to go home and rethink your life.']],
        rv: [['jesse', 'Death sticks, yo? Are they… is it like, a pyramid thing?'], ['walt', 'Jesse. Go home and rethink your life.']],
      },
      things: [
        { kind: 'cplatform', at: [0, 0], abs: true, y: 0, opts: { r: 24, light: '#ff6ad0' } },
        { kind: 'club', at: [0, 8], yaw: Math.PI + 0.6, abs: true, y: 0.3 },
        { kind: 'airspeeder', at: [10, -10], yaw: -0.5, abs: true, y: 0.3, opts: { color: '#c8c8cc' } },
      ],
    },
    {
      id: 'works',
      name: 'The Works',
      at: [-430, -250],
      r: 38,
      about: 'A dead industrial district of rusting cranes and empty factories. Darth Sidious met his apprentices here, out of sight of the Jedi just across the skyline.',
      lines: {
        xwing: [['luke', 'I don’t like this place, Artoo. Something… cold happened here.'], ['r2', '(A frightened, falling whistle.)']],
        falcon: [['han', 'Abandoned factories. Perfect place for a deal. Or an ambush.'], ['chewie', '(A tense growl.)']],
        cruiser: [['rick', 'Every Sith Lord needs a creepy warehouse, Morty. It’s in the bylaws.'], ['morty', 'Can we not be in the creepy warehouse, Rick?']],
      },
      things: [
        { kind: 'cplatform', at: [0, 0], abs: true, y: 0, opts: { r: 36, light: '#ff8a4a', color: '#7a6a5c' } },
        { kind: 'works', at: [0, 0], yaw: 0.4, abs: true, y: 0.3 },
      ],
    },
  ],
  things: [
    // where you land, and the bridges out
    { kind: 'cplatform', at: [0, 0], abs: true, y: 0, opts: { r: 30 } },
    { kind: 'deck', at: [0, 290], abs: true, y: 0, opts: { hw: 60, hd: 40 } },
    span([0, 0], [0, 290], 30, 40, 16),
    span([0, 0], [340, 40], 30, 50.4, 7),
    span([0, 0], [-308.5, 65.4], 30, 15.6, 6),
    span([0, 0], [-150, -270], 30, 24, 6),
    span([0, 0], [200, -290], 30, 24, 6),
    span([-150, -270], [-430, -250], 24, 36, 6),
    // the statues along the Processional Way
    ...[60, 100, 140, 180, 220].flatMap((z) => [
      { kind: 'statue', at: [-14, z], yaw: Math.PI / 2, abs: true, y: -6, opts: { h: 26, drop: 200 } },
      { kind: 'statue', at: [14, z], yaw: -Math.PI / 2, abs: true, y: -6, opts: { h: 26, drop: 200 } },
    ]),
    // Anakin's airspeeder, by your ship, and the platform's clutter: cargo
    // waiting for a lift, a lamp over it
    { kind: 'airspeeder', at: [16, -14], yaw: 0.9, abs: true, y: 0.3 },
    { kind: 'cratecube', at: [-18, -10], yaw: 0.4, abs: true, y: 0 },
    { kind: 'cratecube', at: [-16.6, -9.4], yaw: 1.2, abs: true, y: 0 },
    { kind: 'empirecrate', at: [-19, -13], yaw: 2.1, abs: true, y: 0 },
    { kind: 'cooler', at: [-15, -12], yaw: 0.8, abs: true, y: 0 },
    { kind: 'lamp', at: [-22, -6], abs: true, y: 0, opts: { h: 5, light: '#ffd9a0' } },
    { kind: 'lamp', at: [22, 10], abs: true, y: 0, opts: { h: 5, light: '#ffd9a0' } },
    // the skylanes
    { kind: 'airlane', at: [0, 60], yaw: Math.PI / 2, abs: true, y: 40, solid: false, opts: { len: 1700, n: 30, seed: 1 } },
    { kind: 'airlane', at: [110, 0], yaw: 0, abs: true, y: -45, solid: false, opts: { len: 1700, n: 30, seed: 2 } },
    { kind: 'airlane', at: [-60, -100], yaw: 0.8, abs: true, y: 85, solid: false, opts: { len: 1700, n: 26, seed: 3, speed: 40 } },
    { kind: 'airlane', at: [0, -170], yaw: Math.PI / 2, abs: true, y: -90, solid: false, opts: { len: 1700, n: 30, seed: 4 } },
    { kind: 'airlane', at: [-200, 150], yaw: -0.6, abs: true, y: 22, solid: false, opts: { len: 1500, n: 24, seed: 5, speed: 28 } },
    { kind: 'airlane', at: [300, 200], yaw: 0.3, abs: true, y: 140, solid: false, opts: { len: 1700, n: 24, seed: 6, speed: 46 } },
    // the towers nearest, rising past you: Galactic City's own first
    { kind: 'corutower', at: [-120, 170], abs: true, y: -140, yaw: 0.4, scale: 1.7, solid: false, windows: true },
    { kind: 'corutower', at: [130, 170], abs: true, y: -170, yaw: 2.3, scale: 1.9, solid: false, windows: true },
    { kind: 'corutower', at: [-300, -120], abs: true, y: -120, yaw: 1.1, scale: 1.6, solid: false, windows: true },
    { kind: 'corutower', at: [330, -160], abs: true, y: -150, yaw: 3.0, scale: 1.5, solid: false, windows: true },
    { kind: 'corutower', at: [-250, 250], abs: true, y: -200, yaw: 0.9, scale: 2.1, solid: false, windows: true },
    { kind: 'corutower', at: [560, 250], abs: true, y: -180, yaw: 2.7, scale: 2.0, solid: false, windows: true },
    tower([-210, -70], 1, 380, 30),
    tower([190, -110], 2, 440),
    tower([60, -210], 1, 300, 28),
    tower([-60, -400], 3, 480),
    tower([260, 220], 0, 500),
    tower([420, -320], 1, 460, 34),
    tower([-470, 60], 3, 440),
    tower([-560, -380], 0, 520),
    tower([150, 520], 2, 560),
    tower([-200, 470], 1, 480, 32),
    tower([540, -120], 2, 470),
    tower([20, -560], 0, 500),
  ],
  scatter: [
    { kind: 'skyscraper', n: 70, within: [640, 2600], scale: [1, 1.6], stretch: [1.3, 2.5], solid: false, opts: { style: 0, seed: 3 } },
    { kind: 'skyscraper', n: 60, within: [640, 2600], scale: [1, 1.6], stretch: [1.3, 2.4], solid: false, opts: { style: 1, seed: 4 } },
    { kind: 'skyscraper', n: 60, within: [640, 2600], scale: [1, 1.6], stretch: [1.3, 2.6], solid: false, opts: { style: 2, seed: 5 } },
    { kind: 'skyscraper', n: 60, within: [640, 2600], scale: [1, 1.6], stretch: [1.3, 2.5], solid: false, opts: { style: 3, seed: 6 } },
    { kind: 'skyscraper', n: 40, within: [60, 620], scale: [0.7, 1.1], stretch: [0.6, 1.25], solid: false, opts: { style: 0, seed: 7 } },
    { kind: 'skyscraper', n: 40, within: [60, 620], scale: [0.7, 1.1], stretch: [0.6, 1.25], solid: false, opts: { style: 1, seed: 8 } },
    { kind: 'skyscraper', n: 40, within: [60, 620], scale: [0.7, 1.1], stretch: [0.6, 1.25], solid: false, opts: { style: 3, seed: 9 } },
  ],
  life: [
    { kind: 'jedi', n: 5, at: [0, 290], spread: 30, roam: 14, speed: 1.0, name: 'Jedi Knight', says: ['May the Force be with you.', 'The Council is in session. Even the Masters are worried.', 'Clouded, the future is. Even here.', 'The Archives are open to all Jedi. If an item does not appear in our records, it does not exist.'] },
    { kind: 'jedi', n: 1, at: [8, 300], roam: 6, speed: 0.6, scale: 0.38, r: 0.3, name: 'Yoda', says: ['Begun, the Clone War has.', 'Clouded, this boy’s future is.', 'Do, or do not. There is no try.', 'Lost a planet, Master Obi-Wan has. How embarrassing.'] },
    { kind: 'clone', n: 4, path: [[-5, 40], [-5, 245], [5, 245], [5, 40]], speed: 1.5, name: 'Clone trooper', says: ['Sir.', 'Yes, sir.', 'Move along. The Temple is closed.', 'Execute Order Sixty-Six.'] },
    { kind: 'senateguard', n: 4, at: [320, 40], spread: 24, roam: 5, speed: 0.6, r: 0.5, name: 'Senate Guard', says: ['(The guard says nothing. The helmet tilts, very slightly, toward the way out.)', 'The Senate is in session. State your business.'] },
    { kind: 'villager', n: 1, at: [330, 30], roam: 8, speed: 0.8, name: 'Padmé Amidala', says: ['So this is how liberty dies. With thunderous applause.', 'I truly believe that the Republic is worth fighting for.', 'Aggressive negotiations? What’s that?'] },
    { kind: 'villager', n: 5, path: [[34, 5], [288, 40]], speed: 1.2, name: 'Senate aide', says: ['The Chancellor has emergency powers now. Just until the crisis is over, they say.', 'The Military Creation Act vote is today. Everyone’s nervous.', 'I’m late, I’m late: the Senator from Alderaan is waiting.'] },
    { kind: 'villager', n: 3, path: [[-20, -22], [-138, -250]], speed: 1.1, name: 'Coruscanti', says: ['Don’t look down. Seriously, don’t.', 'Dex does the best nuna legs this side of the Federal District.', 'Mind the skylanes. Some of those drivers are maniacs.'] },
    { kind: 'villager', n: 1, at: [-150, -262], still: true, scale: 1.45, r: 0.8, name: 'Dexter Jettster', says: ['Hey, old buddy! Take a seat, I’ll be right with you.', 'That baby belongs to them cloners. What you got here is a Kamino saberdart.', 'Those Kaminoans keep to themselves. They’re cloners. Damn good ones, too.', 'I’d expect better from you Jedi. You oughta be able to tell the difference between knowledge and wisdom.'] },
    { kind: 'villager', n: 1, at: [196, -280], roam: 4, speed: 0.8, name: 'Elan Sleazebaggano', says: ['You wanna buy some death sticks?', '(You don’t want to sell me death sticks.) …I don’t want to sell you death sticks.', '(You want to go home and rethink your life.) …I want to go home and rethink my life.'] },
    { kind: 'c3po', n: 1, at: [-306, 70], still: true, r: 0.4, name: 'C-3PO', says: ['Oh, Master Anakin! I’m so glad you’re back. Mistress Padmé has been terribly worried.', 'I do believe the Senator’s apartment is the finest view on Coruscant. Not that I would know what to do with a view.', 'Don’t go too near the edge! It’s a long way down.'] },
    { kind: 'droid', n: 2, at: [6, 10], spread: 8, roam: 8, speed: 0.8, name: 'Astromech', says: ['(A busy, beeping hurry: it has somewhere to be.)'] },
    { kind: 'mousedroid', n: 2, at: [-8, 6], spread: 10, roam: 12, speed: 1.6, r: 0.2, solid: false },
    { kind: 'clone', n: 2, at: [-12, -4], spread: 4, still: true, face: 0.6, name: 'Coruscant Guard', says: ['Platform’s clear, sir.', 'The Temple is that way. Mind the drop.'] },
    { kind: 'villager', n: 3, at: [10, 18], spread: 10, roam: 10, speed: 1.0, name: 'Commuter', says: ['Skylane’s backed up to the 500 block again.', 'Don’t look down. I never look down.', 'Dex’s is that way, if you’re hungry.'] },
  ],
  flyovers: [
    { kind: 'shuttle', n: 1, metres: 20, alt: 380, speed: 70, every: 40 },
    { kind: 'arc170', n: 3, metres: 14.5, alt: 420, speed: 130, every: 60 },
    { kind: 'delta7', n: 2, metres: 8, alt: 360, speed: 140, every: 70 },
    { kind: 'nubian', n: 1, metres: 76, alt: 470, speed: 60, every: 90 },
    { kind: 'transport', n: 1, metres: 40, alt: 300, speed: 50, every: 70 },
  ],
  skyships: [{ kind: 'acclamator', metres: 752, at: [-2200, 520, 2600], yaw: 0.5 }],

};
