// Tatooine, from the ground. (sites/index.js has what a site is.)

export const SITES = {
  tatooine: {
    place: 'The Jundland Wastes',
    line: 'Two suns, and sand to the edge of the world.',
    sky: {
      zenith: '#4f86c6',
      horizon: '#e8d3ac',
      haze: 0.8,
      hazeColor: '#f3ddb5',
      suns: [
        { az: 0.5, el: 0.3, color: '#fff3dc', size: 0.017, glow: 1.3 },
        { az: 0.66, el: 0.37, color: '#ffc68c', size: 0.012, glow: 0.9 },
      ],
      clouds: { cover: 0.12, color: '#fffaf0', shade: '#e2d2b4', scale: 0.55, speed: 0.004 },
      bodies: [
        { az: -0.9, el: 0.62, size: 0.024, color: '#e0d8c8', color2: '#bdb4a2', bands: 0 },
        { az: -0.62, el: 0.7, size: 0.011, color: '#cfc6b6' },
      ],
    },
    fog: { color: '#e9d4ab', density: 0.00055 },
    light: { sun: 3.2, second: 1.0, sky: '#b9d2f2', ground: '#c89e6a', ambient: 0.7 },
    ground: {
      seed: 3,
      wind: 0.5,
      layers: [
        { type: 'swell', scale: 420, height: 8 },
        { type: 'dunes', scale: 64, height: 9, wind: 0.5 },
        { type: 'mesas', scale: 560, height: 46, cover: 0.32, cliff: 0.045 },
        { type: 'mountains', from: 700, to: 3000, height: 520, scale: 1300 },
      ],
      palette: {
        low: '#d2b083',
        high: '#ebd4a6',
        rock: '#a46c42',
        accent: '#c3925f',
        deep: '#b4875a',
        hLow: -4,
        hHigh: 12,
        rockAt: 0.36,
        accentCover: 0.22,
        ripple: { strength: 0.09, scale: 3.2, wind: 0.5 },
        grain: 0.6,
        mark: '#b98a5a',
      },
    },
    weather: [{ kind: 'sand', count: 1300 }],
    land: { at: [0, 0], yaw: 0.9 },
    places: [
      {
        id: 'homestead',
        name: 'The Lars homestead',
        at: [-170, 150],
        r: 34,
        flat: { r: 24 },
        about: 'Owen and Beru Lars’ moisture farm, where Luke grew up: a domed hut over a courtyard sunk into the sand, out of the heat.',
        lines: {
          xwing: [['luke', 'Uncle Owen’s. I used to stand up there and watch the suns go down.'], ['r2', '(A soft, sad whistle.)']],
          falcon: [['han', 'So this is where the kid’s from. No wonder he wanted off this rock.']],
          cruiser: [['morty', 'Rick, this is the farm! From the movie!'], ['rick', 'Moisture farm, Morty. Nobody ever asks where the water comes from.']],
        },
        things: [
          { kind: 'homestead', at: [0, 0], yaw: 0.4 },
          { kind: 'vaporator', at: [16, -6] },
          { kind: 'vaporator', at: [-14, -12] },
          { kind: 'vaporator', at: [22, 12] },
          { kind: 'vaporator', at: [-20, 14] },
          { kind: 'vaporator', at: [4, 22] },
        ],
        // (the courtyard: a pit beside the hut)
        pits: [{ at: [-1.5, -4.4], r: 9, depth: 6 }],
      },
      {
        id: 'moseisley',
        name: 'Mos Eisley',
        at: [300, -230],
        r: 70,
        flat: { r: 64 },
        about: 'A wretched hive of scum and villainy: domes, docking bays, a cantina and a garrison of stormtroopers looking for two droids.',
        lines: {
          xwing: [['luke', 'Mos Eisley. Ben said we’d never find a more wretched hive of scum and villainy.']],
          falcon: [['han', 'Home sweet home. Keep your head down, Chewie: Jabba’s got people everywhere.'], ['chewie', '(A wary rumble.)']],
          rv: [['walt', 'A cantina full of smugglers and bounty hunters.'], ['jesse', 'So… basically Albuquerque.']],
        },
        things: [
          { kind: 'cantina', at: [0, 0], yaw: 0.3 },
          { kind: 'dockingbay', at: [-34, 22], yaw: 2.2 },
          { kind: 'adobe', at: [26, 16], opts: { r: 4.5 } },
          { kind: 'adobe', at: [34, -10], opts: { r: 3.6 } },
          { kind: 'adobe', at: [18, -28], opts: { r: 5 } },
          { kind: 'adobe', at: [-12, -30], opts: { r: 4 } },
          { kind: 'adobe', at: [-36, -14], opts: { r: 3.5 } },
          { kind: 'adobe', at: [-24, 48], opts: { r: 4.2 } },
          { kind: 'adobe', at: [8, 44], opts: { r: 3.8 } },
          { kind: 'adobe', at: [44, 34], opts: { r: 4.6 } },
          { kind: 'adobe', at: [52, -30], opts: { r: 3.4 } },
          { kind: 'stall', at: [12, 20], yaw: 2.6 },
          { kind: 'stall', at: [-6, 24], yaw: 3.4 },
          { kind: 'stall', at: [22, -6], yaw: 1.4 },
          { kind: 'crates', at: [-20, 8] },
          { kind: 'crates', at: [30, 2] },
          { kind: 'vaporator', at: [-46, 4] },
          { kind: 'vaporator', at: [40, -46] },
          { kind: 'landspeeder', at: [6, 12], yaw: 1.9, y: 0.7, solid: { r: 1.4 } },
        ],
      },
      {
        id: 'sandcrawler',
        name: 'A Jawa sandcrawler',
        at: [140, 250],
        r: 40,
        flat: { r: 30 },
        about: 'The Jawas’ rolling fortress, trawling the wastes for droids and scrap to sell to moisture farmers.',
        lines: {
          xwing: [['luke', 'Jawas! Careful, Artoo. They’ll have you in the back of that thing before you can beep.'], ['r2', '(An indignant squeal.)']],
          falcon: [['han', 'Jawas. Never buy a droid off ’em. Never sell ’em one either.']],
        },
        things: [{ kind: 'sandcrawler', at: [0, 0], yaw: 2.6 }],
      },
      {
        id: 'krayt',
        name: 'The krayt dragon’s bones',
        at: [-330, -150],
        r: 30,
        about: 'All that’s left of a krayt dragon, bleached in the twin suns. Tuskens say its pearl is still out here somewhere.',
        lines: {
          xwing: [['luke', 'A krayt dragon. Ben scared off a whole band of Tuskens with that howl once.']],
          falcon: [['chewie', '(An impressed whoop.)'], ['han', 'Yeah, I wouldn’t want to meet the live one either.']],
        },
        things: [{ kind: 'krayt', at: [0, 0], yaw: 0.7, sink: 0.6 }],
      },
      {
        id: 'escapepod',
        name: 'The escape pod',
        at: [-70, -330],
        r: 22,
        about: 'Where Artoo and Threepio came down, with the Death Star plans. No life forms aboard, said the Star Destroyer’s gunner, so he held his fire.',
        lines: {
          xwing: [['luke', 'This is the pod you and Threepio came down in, isn’t it, Artoo?'], ['r2', '(A proud trill.)']],
        },
        things: [{ kind: 'escapepod', at: [0, 0], yaw: 1.2, sink: 0.4 }],
      },
      {
        id: 'tuskens',
        name: 'A Tusken camp',
        at: [-420, 250],
        r: 34,
        flat: { r: 22 },
        about: 'Sand People: they ride banthas in single file, to hide their numbers, and don’t take kindly to visitors.',
        lines: {
          xwing: [['luke', 'Sand People. Easy, Artoo. Quiet.']],
          falcon: [['han', 'Tuskens. Let’s not stay for dinner.']],
        },
        things: [
          { kind: 'tent', at: [0, 0], yaw: 0.2 },
          { kind: 'tent', at: [8, -5], yaw: 1.4 },
          { kind: 'tent', at: [-7, -7], yaw: 2.5 },
          { kind: 'tent', at: [4, 9], yaw: 3.6 },
          { kind: 'fire', at: [1, -3] },
        ],
      },
      {
        id: 'benhut',
        name: 'Ben Kenobi’s hut',
        at: [420, 170],
        r: 26,
        flat: { r: 14 },
        about: 'Old Ben’s hermitage on the edge of the Dune Sea, where he gave Luke his father’s lightsaber.',
        lines: {
          xwing: [['luke', 'Ben’s place. He told me about my father here. And gave me his lightsaber.']],
        },
        things: [{ kind: 'benhut', at: [0, 0], yaw: -0.6 }],
      },
      {
        id: 'sarlacc',
        name: 'The Great Pit of Carkoon',
        at: [390, 370],
        r: 40,
        about: 'The nesting place of the all-powerful Sarlacc. In its belly you’ll find a new definition of pain and suffering, as you’re slowly digested over a thousand years.',
        lines: {
          xwing: [['luke', 'The Pit of Carkoon. We nearly went in, all of us.']],
          falcon: [['han', 'I can’t see a thing, but I remember it. I really remember it.'], ['chewie', '(A shuddering groan.)']],
          cruiser: [['morty', 'Th-that thing has teeth, Rick! In the sand!'], ['rick', 'A thousand years of digestion, Morty. Kind of aspirational.']],
        },
        things: [{ kind: 'sarlacc', at: [0, 0], y: 0 }],
        pits: [{ at: [0, 0], r: 26, depth: 11, cone: true }],
      },
    ],
    things: [
      // Jabba's palace, far off on the horizon
      { kind: 'palace', at: [-1400, 1900], yaw: 2.4, model: false, solid: false },
      // the farm's vaporators, out past the homestead
      { kind: 'vaporator', at: [-120, 110] },
      { kind: 'vaporator', at: [-130, 190] },
      { kind: 'vaporator', at: [-210, 110] },
    ],
    scatter: [
      { kind: 'rock', n: 140, within: [30, 560], scale: [0.6, 3.2], opts: { color: '#9e7a56', sharp: 0.5 } },
      { kind: 'stones', n: 260, within: [10, 400], scale: [0.25, 0.7], solid: false, opts: { color: '#a68462' } },
    ],
    life: [
      { kind: 'jawa', n: 7, at: [140, 268], spread: 14, roam: 16, speed: 0.9, name: 'Jawa', says: ['Utinni!', 'Utinni! (It holds up a power converter, and names a price you don’t understand.)', 'M’um m’aloo!', '(It counts your credits, then counts them again.)'] },
      { kind: 'bantha', n: 4, at: [-400, 230], spread: 20, roam: 20, speed: 0.8, r: 1.5 },
      { kind: 'tusken', n: 3, at: [-420, 250], spread: 10, roam: 10, speed: 1.0, name: 'Tusken Raider', says: ['(A long, rising howl, and the gaffi stick held high.)', '(It stares. It doesn’t move. You get the message.)'] },
      { kind: 'stormtrooper', n: 4, path: [[290, -200], [330, -230], [300, -270], [262, -236]], speed: 1.4, name: 'Stormtrooper', says: ['Move along.', 'Let me see your identification.', 'How long have you had these droids?', 'These aren’t the droids we’re looking for.'] },
      { kind: 'sandtrooper', n: 2, at: [-60, -320], spread: 8, roam: 12, speed: 1.1, name: 'Sandtrooper', says: ['Look, sir: droids. Someone was in the pod.', 'The tracks go off in this direction.'] },
      { kind: 'dewback', n: 2, at: [-80, -300], spread: 10, roam: 14, speed: 0.7, r: 1.2 },
      { kind: 'villager', n: 5, at: [300, -230], spread: 40, roam: 25, speed: 1.1, name: 'Mos Eisley local', says: ['Watch yourself. This place can be a little rough.', 'Chalmun’s got a band in tonight. No droids, though.', 'If you’re looking for a pilot, try the cantina.', 'Hutt business. Don’t ask.'] },
      { kind: 'droid', n: 1, at: [-160, 140], roam: 10, speed: 0.6, name: 'An R5 unit', says: ['(A cheerful whistle. Its motivator sounds fine… for now.)'] },
    ],
    rides: [
      { kind: 'landspeeder', at: [14, -10], yaw: 2.4 },
      { kind: 'bantha', at: [-390, 270], yaw: 0.4 },
    ],
    flyovers: [
      { kind: 'tie', n: 2, metres: 7, alt: 90, speed: 110, every: 55 },
      { kind: 'xwing', n: 1, metres: 12.5, alt: 70, speed: 100, every: 90 },
      { kind: 'freighter', n: 1, metres: 40, alt: 160, speed: 45, every: 80 },
    ],
    skyships: [{ kind: 'destroyer', metres: 1600, at: [900, 2600, 3800], yaw: -2.2 }],
  },
};
