// The edge worlds, from the ground: Mustafar, Scarif, Exegol, Ahch-To and
// Bespin's Cloud City. (sites/index.js has what a site is.)

export const SITES = {
  mustafar: {
    place: 'The lava fields of Mustafar',
    line: 'Black rock, rivers of fire, and ash falling like snow.',
    sky: {
      zenith: '#160c0b',
      horizon: '#b4441c',
      below: '#3a1408',
      haze: 0.95,
      hazeColor: '#ff6a2a',
      suns: [{ az: 2.4, el: 0.22, color: '#ffb27a', size: 0.022, glow: 1.6 }],
      clouds: { cover: 0.62, color: '#5a2a1e', shade: '#1e100c', scale: 0.7, speed: 0.006, sharp: 0.8 },
      stars: 0,
    },
    fog: { color: '#5e2414', density: 0.0012 },
    light: { sun: 1.8, sky: '#8a4a36', ground: '#6a240c', ambient: 0.75 },
    dust: '#2a2220',
    edge: 'Nothing out there but more lava. Better turn back before your boots melt.',
    ground: {
      seed: 4,
      wind: 0.8,
      layers: [
        { type: 'swell', scale: 320, height: 7 },
        { type: 'ridges', scale: 150, height: 10 },
        { type: 'channels', scale: 360, depth: 18, width: 0.08 },
        { type: 'mountains', from: 650, to: 2600, height: 420, scale: 1100 },
        // the bank Obi-Wan stood on
        { type: 'island', at: [300, 380], r: 60, height: 7 },
      ],
      palette: {
        low: '#2b2421',
        high: '#3e3430',
        rock: '#161313',
        accent: '#4e3022',
        deep: '#1e1918',
        hLow: -6,
        hHigh: 14,
        rockAt: 0.34,
        accentCover: 0.18,
        grain: 0.8,
        roughness: 0.9,
        wet: { level: -3, band: 3.5, color: '#9a2a08' },
        mark: '#120e0d',
      },
    },
    water: { level: -3, color: '#ff4a0c', deep: '#260804', kind: 'lava', glow: 3.4 },
    weather: [
      { kind: 'ash', count: 2600, color: '#3a3030' },
      { kind: 'embers', count: 900 },
    ],
    land: { at: [0, 0], yaw: 0.6 },
    lines: {
      out: {
        xwing: [['luke', 'Mustafar. This is where it happened, Artoo. Where my father…'], ['r2', '(A low, mournful whistle.)']],
        falcon: [['han', 'Whoa. Don’t touch anything, Chewie. Don’t breathe anything either.'], ['chewie', '(A worried growl, fur smoking.)']],
        cruiser: [['morty', 'Rick, the ground’s on fire! The whole planet’s on fire!'], ['rick', 'It’s a volcano planet, Morty. The Sith love a theme.']],
        rv: [['jesse', 'Yo, it’s like a thousand degrees out here, Mr. White.'], ['walt', 'One thousand two hundred, at the lava’s surface. Keep your feet on the rock.']],
      },
    },
    places: [
      {
        id: 'platform',
        name: 'The landing platform',
        at: [-70, 150],
        r: 30,
        flat: { r: 28 },
        about: 'Where Padmé’s skiff set down at the edge of the facility, and where Anakin, sure she had betrayed him, choked her in front of Obi-Wan.',
        lines: {
          xwing: [['luke', 'My mother came here, didn’t she, Artoo? To bring him back.'], ['r2', '(A very quiet beep.)']],
          falcon: [['han', 'Nice ship. Royal yacht, chrome all over. Somebody important came here.']],
          cruiser: [['morty', 'Th-that’s the shiny ship from the prequels, Rick!'], ['rick', 'Chrome, Morty. On a lava planet. Real smart.']],
        },
        things: [
          { kind: 'mpad', at: [0, 0], yaw: 0.3 },
          { kind: 'crates', at: [14, -10] },
          { kind: 'crates', at: [-15, 8] },
          { kind: 'lamp', at: [17, 6], opts: { h: 5, light: '#ffb070', color: '#2a2828' } },
          { kind: 'lamp', at: [-16, -7], opts: { h: 5, light: '#ffb070', color: '#2a2828' } },
        ],
      },
      {
        id: 'facility',
        name: 'The mining facility',
        at: [-200, 300],
        r: 60,
        flat: { r: 42 },
        about: 'Klegger Corp’s lava-collection plant, where the Separatist council hid at the end of the war, and where Anakin, now Vader, came to end them.',
        lines: {
          xwing: [['luke', 'The Separatists hid here. He came alone, and none of them left.']],
          falcon: [['han', 'Mining outfit. Big one. Bet the pay’s lousy and the heat’s worse.'], ['chewie', '(A grunt of agreement.)']],
          rv: [['walt', 'They’re harvesting minerals out of the lava itself. That’s… actually rather elegant.'], ['jesse', 'Elegant? It’s a murder castle, yo.']],
        },
        things: [
          { kind: 'mining', at: [0, 0], yaw: 0 },
          { kind: 'lamp', at: [-26, 24], opts: { h: 6, light: '#ffb070', color: '#2a2828' } },
          { kind: 'lamp', at: [26, 24], opts: { h: 6, light: '#ffb070', color: '#2a2828' } },
          { kind: 'crates', at: [30, 10] },
          { kind: 'crates', at: [-30, 12] },
        ],
        // (the lava it reaches back over)
        pits: [{ at: [0, -62], r: 34, depth: 16 }],
      },
      {
        id: 'river',
        name: 'The lava river',
        at: [210, 170],
        r: 50,
        about: 'Where the duel went down the river: Obi-Wan and Anakin on a collector arm adrift on the lava, then leaping to the droid platforms, still fighting.',
        lines: {
          xwing: [['luke', 'They fought all the way down this river. Master and apprentice.'], ['r2', '(A nervous trill.)']],
          falcon: [['han', 'Who sword-fights on a lava river? Who does that?']],
          cruiser: [['rick', 'Laser swords on a raft on a lava river, Morty. Peak space-wizard decision making.'], ['morty', 'It’s actually kind of awesome, Rick.']],
        },
        pits: [{ at: [0, 0], r: 46, depth: 16 }],
      },
      {
        id: 'highground',
        name: 'The high ground',
        at: [300, 360],
        r: 32,
        about: 'A bank of black sand above the river. “It’s over, Anakin. I have the high ground.” He jumped anyway.',
        lines: {
          xwing: [['luke', 'Ben stood here. He left my father on that bank, burning.'], ['r2', '(A long, sad whistle.)']],
          falcon: [['han', 'High ground, huh. Kid, always take the high ground.'], ['chewie', '(A sage rumble.)']],
          cruiser: [['morty', 'Rick! Rick, it’s the high ground!'], ['rick', 'Don’t, Morty. Don’t try it.']],
          rv: [['jesse', 'He literally just had to not jump, yo.'], ['walt', 'Pride, Jesse. It gets everyone in the end.']],
        },
        pits: [{ at: [0, -74], r: 74, depth: 18, cone: true }],
      },
      {
        id: 'fortress',
        name: 'Fortress Vader',
        at: [-300, -380],
        r: 80,
        about: 'Vader’s castle, built over the lava where he was burned: two black towers, a bacta tank in their foot, and a long bridge out to the landing pad.',
        lines: {
          xwing: [['luke', 'He came back here. To the place where he lost everything.'], ['r2', '(A frightened squeal.)']],
          falcon: [['han', 'Charming. Real homey.'], ['chewie', '(A low, uneasy growl.)']],
          cruiser: [['morty', 'Rick, w-why would you build your house where you got your legs cut off?'], ['rick', 'Feng shui, Morty. Dark side feng shui.']],
          rv: [['walt', 'He built his home on the site of his greatest humiliation.'], ['jesse', 'That’s messed up, Mr. White. Even for you.']],
        },
        things: [
          { kind: 'fortress', at: [0, -18], yaw: 0.67, solid: { box: [36, 28] } },
          { kind: 'vadermeditation', at: [8, 34], yaw: 2.6 },
          { kind: 'lamp', at: [-6, 42], opts: { h: 6, light: '#ff6a4a', color: '#1a1a1c' } },
          { kind: 'lamp', at: [18, 44], opts: { h: 6, light: '#ff6a4a', color: '#1a1a1c' } },
        ],
        flat: { r: 50, edge: 20 },
        pits: [
          { at: [-50, 0], r: 26, depth: 14 },
          { at: [52, -6], r: 24, depth: 14 },
        ],
      },
      {
        id: 'camp',
        name: 'The Mustafarian camp',
        at: [380, -150],
        r: 40,
        flat: { r: 30 },
        about: 'Mustafarians in their heat-proof suits, and their lava fleas: they ride them out over the crust to harvest what the lava brings up.',
        lines: {
          xwing: [['luke', 'Lava fleas. Big ones. Don’t get under their back legs, Artoo.']],
          falcon: [['han', 'I’ve seen bigger. Not many.'], ['chewie', '(A doubtful whine.)']],
          cruiser: [['morty', 'Th-those are fleas, Rick? Fleas?!'], ['rick', 'Space fleas, Morty. Everything’s bigger in space.']],
        },
        things: [
          { kind: 'lavaspout', at: [-34, -28], opts: { h: 18 } },
          { kind: 'crates', at: [8, -6], opts: { color: '#5a4636' } },
          { kind: 'crates', at: [-10, 8], opts: { color: '#5a4636' } },
          { kind: 'fire', at: [0, 2] },
        ],
      },
    ],
    things: [
      // the volcanoes, out past the edge
      { kind: 'volcano', at: [1500, 900], model: false, solid: false, opts: { h: 520, r: 760 } },
      { kind: 'volcano', at: [-1300, 1300], model: false, solid: false, opts: { h: 380, r: 600 } },
      { kind: 'volcano', at: [-200, -1700], model: false, solid: false, opts: { h: 600, r: 820 } },
      // geysers along the rivers, platforms adrift
      { kind: 'lavaspout', at: [90, -60], opts: { h: 14 } },
      { kind: 'lavaspout', at: [-120, -200], opts: { h: 20 } },
      { kind: 'collector', at: [212, 176], abs: true, y: -3.2, yaw: 0.7 },
      { kind: 'droidplatform', at: [190, 150], abs: true, y: -3.3 },
      { kind: 'droidplatform', at: [236, 196], abs: true, y: -3.3 },
      { kind: 'droidplatform', at: [292, 336], abs: true, y: -3.3 },
    ],
    scatter: [
      { kind: 'spire', n: 70, within: [60, 580], scale: [1.5, 5], opts: { color: '#1c1818' } },
      { kind: 'basalt', n: 90, within: [30, 560], scale: [0.8, 2.2] },
      { kind: 'rock', n: 120, within: [20, 560], scale: [0.6, 2.8], opts: { color: '#2a2422', sharp: 0.7 } },
      { kind: 'stones', n: 240, within: [8, 420], scale: [0.25, 0.8], solid: false, opts: { color: '#2e2624' } },
    ],
    life: [
      { kind: 'obiwan', at: [300, 364], face: 3.14, still: true, name: 'Obi-Wan Kenobi', says: ['It’s over, Anakin. I have the high ground.', 'Don’t try it.', 'You were the Chosen One! It was said that you would destroy the Sith, not join them!', 'You were my brother, Anakin. I loved you.'] },
      { kind: 'anakin', at: [301, 349], face: 0, still: true, name: 'Anakin Skywalker', says: ['You underestimate my power!', 'If you’re not with me, then you’re my enemy.', 'From my point of view, the Jedi are evil!', 'I hate you!'] },
      { kind: 'vader', at: [-292, -340], face: 0.4, still: true, name: 'Darth Vader', says: ['Be careful not to choke on your aspirations, Director.', 'You were not summoned here to grovel.', '(The breathing. Just the breathing.)', 'I find your lack of faith disturbing.'] },
      { kind: 'mustafarian', n: 5, at: [380, -150], spread: 18, roam: 16, speed: 0.9, name: 'Mustafarian', says: ['(It clicks and hisses through its mask, and points at the lava.)', '(It offers you a lump of something still glowing. Cooling, it says. Mostly.)', '(It eyes your boots. They are not rated for this.)'] },
      { kind: 'lavaflea', n: 4, at: [360, -180], spread: 30, roam: 40, speed: 1.6, r: 2.2, name: 'Lava flea', says: ['(It chitters, and a shower of hot grit falls off its shell.)', '(It hops a little closer. Its back legs twitch.)'] },
      { kind: 'battledroid', n: 4, path: [[-232, 330], [-168, 330], [-162, 266], [-238, 266]], speed: 1.2, name: 'Battle droid', says: ['Roger, roger.', 'Halt! This is a restricted facility.', 'The Viceroy is not to be disturbed.', 'Uh oh.'] },
      { kind: 'battledroid', n: 2, at: [-60, 140], spread: 8, roam: 10, speed: 1, name: 'Battle droid', says: ['Landing clearance confirmed. Roger, roger.', 'Is that… a Jedi? Uh oh.'] },
      { kind: 'c3po', at: [-80, 160], roam: 6, speed: 0.6, name: 'C-3PO', says: ['Oh dear. Oh my. I don’t like the look of this at all.', 'Master Anakin? Oh, I do hope he’s all right.', 'This place is far too hot for my circuits.'] },
      { kind: 'droid', at: [-66, 162], roam: 8, speed: 0.6, name: 'R2-D2', says: ['(An urgent string of beeps. Something is very wrong.)', '(A worried whistle, and a look back at the ship.)'] },
    ],
    rides: [{ kind: 'speederbike', at: [-48, 130], yaw: 1.2 }],
    flyovers: [
      { kind: 'shuttle', n: 1, metres: 20, alt: 120, speed: 70, every: 60 },
      { kind: 'vulture', n: 3, metres: 7, alt: 90, speed: 120, every: 70 },
      { kind: 'nubian', n: 1, metres: 29, alt: 70, speed: 80, every: 110 },
    ],
    skyships: [
      { kind: 'destroyer', metres: 1600, at: [-1600, 2200, -3600], yaw: 0.6 },
      // Padmé's skiff, down on the platform
      { kind: 'nubian', metres: 29, at: [-70, 0, 150], yaw: 0.3 },
    ],
  },
};
