// Naboo, from the ground: the Great Grass Plains, Theed's palace and
// hangar over the falls, Lake Paonga, Varykino, the Gungans' sacred place
// and their shield, and the droid army on the plains. In a file of its own,
// as Coruscant's and Yavin's are. (sites/index.js has what a site is;
// core.js has the other core worlds, and the ramp Theed's road climbs by.)
//
//   SITE                the site
//   SITES               { naboo: SITE }, for index.js to spread

import { ramp } from './core';

export const SITE = {
  place: 'The Great Grass Plains',
  line: 'Green hills, still lakes, and Theed’s domes over the falls.',
  sky: {
    zenith: '#3f82cf',
    horizon: '#cfe4ef',
    haze: 0.7,
    hazeColor: '#e2eef0',
    suns: [{ az: -2.4, el: 0.62, color: '#fff4dc', size: 0.016, glow: 1.1 }],
    clouds: { cover: 0.34, color: '#ffffff', shade: '#c6d2dc', scale: 0.7, speed: 0.005 },
    bodies: [
      { az: 0.5, el: 0.34, size: 0.03, color: '#dfe6ea', color2: '#c4ccd2', bands: 0 },
      { az: 0.78, el: 0.46, size: 0.012, color: '#e4dccc' },
    ],
  },
  fog: { color: '#d3e3e6', density: 0.00075 },
  light: { sun: 3.0, sky: '#b8d4f0', ground: '#6e8a4a', ambient: 0.75 },
  ground: { detail: 'grass', detailLook: { color: 0.7, normal: 0.6 },
    seed: 21,
    wind: 0.3,
    layers: [
      { type: 'swell', scale: 520, height: 6 },
      { type: 'hills', scale: 240, height: 14 },
      // Theed's plateau, its east edge a cliff over the lake
      { type: 'island', at: [-330, 300], r: 250, height: 30, core: 0.9, ragged: 0.1 },
      // the lake, and Padmé's island in it
      { type: 'island', at: [100, 330], r: 290, height: -38, core: 0.5, ragged: 0.25 },
      { type: 'island', at: [300, 420], r: 56, height: 43, core: 0.55, ragged: 0.3 },
      // the swamp round the Gungans' sacred place
      { type: 'island', at: [-360, -280], r: 70, height: -16, core: 0.4, ragged: 0.4 },
      { type: 'mountains', from: 800, to: 3200, height: 460, scale: 1200 },
    ],
    // the road up to Theed
    flats: ramp([-104, 38], [-196, 148], 15, 39.5, 16, 7),
    // (the Great Grass Plains as filmed: a warm, yellow-leaning green)
    palette: {
      low: '#5f7034',
      high: '#7f9440',
      rock: '#8a8270',
      accent: '#8f9a48',
      deep: '#4a5a2e',
      hLow: 0,
      hHigh: 30,
      rockAt: 0.3,
      accentCover: 0.3,
      ripple: { strength: 0.03, scale: 1.6, wind: 0.3 },
      grain: 0.7,
      wet: { level: 0.5, band: 2.5, color: '#6a6248' },
    },
  },
  water: { level: 0, color: '#3c7f88', deep: '#1f4a58', kind: 'sea', foam: 0.12 },
  // the meadow round you, yellow flowers in it here and there
  grass: { h: [0.22, 0.5], w: 0.05, root: '#55693a', mid: '#7a903e', tip: '#a9b656', dry: '#aaa45c', cover: 0.8, scale: 120, wind: 0.5, flower: { color: '#f4e27a', share: 0.03 } },
  weather: [{ kind: 'motes', count: 260, color: '#fffbe0' }],
  dust: '#a8b878',
  edge: 'Grass and gentle hills, all the way to the mountains. The Gungans’ swamps are that way; Theed’s behind you.',
  lines: {
    out: {
      xwing: [['luke', 'Naboo. I never thought anywhere could be this green.'], ['r2', '(A happy, rising whistle: Artoo’s been here before.)']],
      falcon: [['han', 'Nice place. Too nice. Somebody’s got a blockade parked up there, mark my words.'], ['chewie', '(A contented rumble.)']],
      cruiser: [['morty', 'Wow, Rick. It’s like a screensaver.'], ['rick', 'It’s a monarchy with an elected teenage queen, Morty. Don’t get attached.']],
      rv: [['jesse', 'Yo, this is like the nicest place we’ve ever parked the RV.'], ['walt', 'Don’t get comfortable. Nice places have the worst neighbours.']],
    },
  },
  land: { at: [0, 0], yaw: 2.3 },
  places: [
    {
      id: 'palace',
      name: 'The Royal Palace of Theed',
      at: [-235, 300],
      yaw: 2.2,
      r: 75,
      flat: { r: 66, h: 39.5 },
      about: 'Queen Amidala’s palace, high over the falls: green domes, colonnades and the throne room the Trade Federation took, and the Queen took back.',
      lines: {
        xwing: [['luke', 'The palace. Leia said our mother was a queen here, once.'], ['r2', '(A soft, knowing beep.)']],
        falcon: [['han', 'Fancy. I’ve been thrown out of less fancy places than this.']],
        cruiser: [['rick', 'Classical revival, Morty. A whole planet LARPing the Renaissance.'], ['morty', 'I think it’s pretty, Rick.']],
        rv: [['walt', 'An elected queen. Fourteen years old.'], ['jesse', 'Dude, at fourteen I couldn’t elect what to have for lunch.']],
      },
      things: [
        { kind: 'theedpalace', at: [0, 0] },
        { kind: 'plaza', at: [0, 60], opts: { w: 72, d: 48, fountain: false } },
        // (robed statues along the plaza, in front of the palace's façade)
        { kind: 'statue', at: [-30, 52], scale: 0.32 },
        { kind: 'statue', at: [-18, 52], scale: 0.32 },
        { kind: 'statue', at: [18, 52], scale: 0.32 },
        { kind: 'statue', at: [30, 52], scale: 0.32 },
        { kind: 'lamp', at: [-14, 50], opts: { h: 5, light: '#ffe2a8' } },
        { kind: 'lamp', at: [14, 50], opts: { h: 5, light: '#ffe2a8' } },
        { kind: 'lamp', at: [-14, 56], opts: { h: 5, light: '#ffe2a8' } },
        { kind: 'lamp', at: [14, 56], opts: { h: 5, light: '#ffe2a8' } },
      ],
    },
    {
      id: 'falls',
      name: 'The falls of Theed',
      at: [-130, 300],
      r: 44,
      flat: { r: 28, h: 38, edge: 5 },
      about: 'Theed is built on the edge of a cliff, and the river falls out from under the city in sheets of white, a hundred metres down into the gorge.',
      lines: {
        xwing: [['luke', 'Look at that, Artoo. Water, just… falling off the edge. On Tatooine they’d have a war over this.'], ['r2', '(An awed whistle.)']],
        falcon: [['chewie', '(A long, happy howl at the falls.)'], ['han', 'Yeah, yeah. It’s not Kashyyyk, pal.']],
        cruiser: [['morty', 'It’s beautiful, Rick.'], ['rick', 'It’s erosion, Morty. With a tourism board.']],
      },
      things: [
        { kind: 'waterfall', at: [23.4, -12.4], yaw: 2.06, opts: { h: 46, w: 10, out: 13 } },
        { kind: 'waterfall', at: [26.5, 0], yaw: Math.PI / 2, opts: { h: 46, w: 14, out: 13 } },
        { kind: 'waterfall', at: [23.4, 12.4], yaw: 1.08, opts: { h: 46, w: 10, out: 13 } },
        { kind: 'theed', at: [-44, 2], yaw: Math.PI / 2, opts: { style: 'rotunda' } },
        { kind: 'lamp', at: [4, -18], opts: { h: 4.5, light: '#ffe2a8' } },
        { kind: 'lamp', at: [4, 20], opts: { h: 4.5, light: '#ffe2a8' } },
      ],
    },
    {
      id: 'hangar',
      name: 'The Theed Royal Hangar',
      at: [-300, 180],
      yaw: 2.4,
      r: 55,
      flat: { r: 48, h: 39.5 },
      about: 'Where the N-1 starfighters of Bravo Squadron wait, yellow and chrome. A boy hid in one of their cockpits, and flew it to the droid control ship.',
      lines: {
        xwing: [['luke', 'N-1s. Look at the lines on those, Artoo. Somebody built these to be beautiful.'], ['r2', '(A smug little trill. Artoo knows these.)']],
        falcon: [['han', 'Pretty. Chrome. Not much armour. I’d still take one for a spin.']],
        cruiser: [['morty', 'A kid flew one of these and blew up a whole space station, Rick.'], ['rick', 'Ugh, don’t tell me that, Morty. I hate it when the kid wins.']],
        rv: [['jesse', 'Yo, these are like the Lamborghinis of spaceships.'], ['walt', 'Hand-built. No two the same. Craftsmanship, Jesse.']],
      },
      things: [
        { kind: 'hangar', at: [0, -6] },
        { kind: 'n1fighter', at: [-14, -8], yaw: 0.1 },
        { kind: 'n1fighter', at: [0, -12], yaw: 0 },
        { kind: 'n1fighter', at: [14, -8], yaw: -0.1 },
        { kind: 'n1fighter', at: [-22, 30], yaw: 0.5 },
        { kind: 'n1fighter', at: [24, 32], yaw: -0.4 },
        // (Bravo Squadron's rows, further in: the hangar held at least twenty-seven)
        { kind: 'n1fighter', at: [-21, -18], yaw: 0 },
        { kind: 'n1fighter', at: [-7, -19], yaw: 0 },
        { kind: 'n1fighter', at: [7, -19], yaw: 0 },
        { kind: 'n1fighter', at: [21, -18], yaw: 0 },
        { kind: 'crates', at: [-26, 8] },
        { kind: 'crates', at: [27, 10] },
      ],
    },
    {
      id: 'paonga',
      name: 'Lake Paonga',
      at: [70, 120],
      r: 60,
      about: 'Under the lake lies Otoh Gunga, the Gungans’ city of glowing bubbles. Go down in a bongo, and mind the opee sea killers. There’s always a bigger fish.',
      lines: {
        xwing: [['luke', 'There’s a whole city down there, Artoo. Under the water. Lights and everything.'], ['r2', '(A worried warble: Artoo doesn’t do lakes.)']],
        falcon: [['han', 'An underwater city. Nope. I like my air in a can, thanks.'], ['chewie', '(A rumbling laugh.)']],
        cruiser: [['rick', 'Hydrostatic bubble tech, Morty. Gungans. Can’t speak a sentence, but they can hold back a lake.'], ['morty', 'Is it okay to be impressed by Jar Jar, Rick?']],
        rv: [['jesse', 'Yo, there’s glowing bubbles in the lake. Like, actual lava lamps, Mr. White.'], ['walt', 'Bioluminescence. Or a containment field. Either way: don’t touch it.']],
      },
      things: [
        { kind: 'otohgunga', at: [40, 110], abs: true, y: 0, solid: false },
        { kind: 'bongo', at: [-6, 24], yaw: 2.8, abs: true, y: -0.9, float: { len: 13, beam: 6, draft: 0.9 } },
      ],
    },
    {
      id: 'varykino',
      name: 'Varykino',
      at: [372, 330],
      yaw: -1.75,
      r: 40,
      flat: { r: 26, edge: 14 },
      about: 'A lake retreat in the Lake Country: terracotta roofs, a terrace over the water, an island Padmé used to swim to. Where she and Anakin were married, in secret.',
      lines: {
        xwing: [['luke', 'This is where they were married, Artoo? My mother and… him?'], ['r2', '(A long, quiet, sad whistle. Artoo was there.)']],
        falcon: [['han', 'Nice place for a honeymoon. Not that I’m thinking about that.'], ['chewie', '(A teasing growl.)'], ['han', 'Shut up.']],
        cruiser: [['morty', 'Rick, it’s so romantic.'], ['rick', 'It’s where a guy who hates sand married a senator in secret, Morty. Read the room.']],
      },
      things: [{ kind: 'varykino', at: [0, 0] }],
    },
    {
      id: 'sacred',
      name: 'The Gungan sacred place',
      at: [-320, -230],
      r: 50,
      flat: { r: 30, edge: 16 },
      about: 'Ruins in the swamp forest, great stone heads half sunk in the moss: where the Gungans hid from the droid army, and where the Queen knelt to ask Boss Nass for help.',
      lines: {
        xwing: [['luke', 'Ruins. Older than anything on Naboo, I’d say. Feel that, Artoo? It’s… still here.'], ['r2', '(A hushed, uncertain beep.)']],
        falcon: [['han', 'Big stone heads. Always a good sign.'], ['chewie', '(An uneasy groan.)']],
        cruiser: [['morty', 'Rick, those heads are kind of looking at us.'], ['rick', 'Every civilisation builds giant heads, Morty. It’s the cosmic equivalent of a phase.']],
        rv: [['jesse', 'This is like, Indiana Jones, yo.'], ['walt', 'Don’t take anything.']],
      },
      things: [
        { kind: 'stonehead', at: [8, -6], yaw: -0.4, sink: 1.0, roll: 0.12 },
        { kind: 'stonehead', at: [-14, 10], yaw: 0.7, sink: 1.4, scale: 1.4, roll: -0.18 },
        { kind: 'stonehead', at: [20, 18], yaw: -1.6, sink: 4, scale: 0.8, pitch: 0.4 },
        { kind: 'ruins', at: [0, 0], opts: { seed: 4 } },
        { kind: 'grove', at: [-36, -30], opts: { n: 14, r: 26, seed: 11 } },
        { kind: 'grove', at: [36, -26], opts: { n: 12, r: 22, seed: 12 } },
        { kind: 'grove', at: [-40, 34], opts: { n: 12, r: 24, seed: 13 } },
        { kind: 'grove', at: [30, 44], opts: { n: 10, r: 20, seed: 14 } },
        { kind: 'grove', at: [-80, -4], opts: { n: 14, r: 28, seed: 15 } },
        { kind: 'grove', at: [70, 6], opts: { n: 12, r: 24, seed: 16 } },
      ],
    },
    {
      id: 'battle',
      name: 'The Gungan shield',
      at: [260, -250],
      r: 70,
      flat: { r: 60, edge: 30 },
      about: 'The Great Grass Plains, where the Gungan Grand Army raised its shield and stood against the droid army, to buy the Queen time to take back her palace.',
      lines: {
        xwing: [['luke', 'The Gungans held the droids off right here. With slings and energy balls, Artoo.'], ['r2', '(An impressed, stuttering whistle.)']],
        falcon: [['han', 'Shields, catapults and big lizards. My kind of army.'], ['chewie', '(An approving roar.)']],
        cruiser: [['morty', 'Rick, they’re throwing glowing balls at robots!'], ['rick', 'Plasma boomas, Morty. Honestly? Better tech than the Republic’s.']],
        rv: [['jesse', 'Yo, the frog guys have a force field. A force field, Mr. White!'], ['walt', 'And the robots have tanks. Never bring a force field to a tank fight.']],
      },
      things: [
        { kind: 'shield', at: [0, 0], yaw: 2.4 },
        { kind: 'boomas', at: [26, -14] },
        { kind: 'boomas', at: [34, 4] },
        { kind: 'boomas', at: [18, 26] },
        { kind: 'boomas', at: [-6, 36] },
      ],
    },
    {
      id: 'droids',
      name: 'The droid army',
      at: [400, -380],
      r: 55,
      flat: { r: 50, edge: 30 },
      about: 'The Trade Federation’s army, marching on the Gungans in their thousands: tanks, transports and battle droids, all run from the control ship up in orbit. Until a boy blew it up.',
      lines: {
        xwing: [['luke', 'Battle droids. Hundreds of them. And all of them switched off from one ship up there.'], ['r2', '(A rude raspberry at the droids.)']],
        falcon: [['han', 'Ah, droids. They never know when to quit.'], ['chewie', '(A low, mean growl.)']],
        cruiser: [['rick', 'Roger, roger, Morty. Centrally controlled, no redundancy. That’s what you get for outsourcing.'], ['morty', 'It’s kind of sad when they all fall over, Rick.']],
        rv: [['jesse', 'Roger, roger. Ha! Mr. White, they all say roger roger.'], ['walt', 'One ship controls all of them. One point of failure. Amateurs.']],
      },
      things: [
        { kind: 'mtt', at: [20, 0], yaw: -2.3 },
        { kind: 'aat', at: [-14, 16], yaw: -2.4 },
        { kind: 'aat', at: [-24, -6], yaw: -2.2 },
        { kind: 'aat', at: [4, 30], yaw: -2.5 },
        { kind: 'droideka', at: [-30, 18], yaw: -2.3, opts: { shield: true } },
        { kind: 'droideka', at: [-26, 26], yaw: -2.4 },
        { kind: 'droideka', at: [-36, 8], yaw: -2.2 },
      ],
    },
  ],
  things: [
    // where you set down: a farm's cart and its cargo on the road to
    // Theed, a stand of trees by the lake side
    { kind: 'speedertruck', at: [-24, 18], yaw: 2.3 },
    { kind: 'barrel', at: [-20, 22], yaw: 0.3 },
    { kind: 'barrel', at: [-19, 23.2], yaw: 1.1 },
    { kind: 'bevelcrate', at: [-21.5, 24], yaw: 0.6 },
    { kind: 'crates', at: [18, -10] },
    { kind: 'lamp', at: [-28, 14], opts: { h: 4.5, light: '#ffe2a8' } },
    { kind: 'grove', at: [70, 60], opts: { n: 7, r: 20, seed: 27 } },
    // Theed: its houses and halls along the plateau
    { kind: 'theed', at: [-300, 250], yaw: 2.6, opts: { style: 'hall' } },
    { kind: 'theed', at: [-345, 300], yaw: 2.0, opts: { style: 'tower' } },
    { kind: 'theed', at: [-180, 380], yaw: 2.6, opts: { style: 'tower' } },
    { kind: 'theed', at: [-250, 400], yaw: 2.4, opts: { style: 'rotunda' } },
    { kind: 'theed', at: [-350, 220], yaw: 2.2, opts: { style: 'rotunda' } },
    { kind: 'theed', at: [-205, 215], yaw: 2.2, opts: { style: 'hall' } },
    { kind: 'theed', at: [-400, 350], yaw: 2.0, opts: { style: 'hall' } },
    { kind: 'theed', at: [-320, 420], yaw: 2.6, opts: { style: 'hall' } },
    { kind: 'theed', at: [-420, 260], yaw: 1.8, opts: { style: 'tower' } },
    { kind: 'theed', at: [-260, 470], yaw: 2.8, opts: { style: 'rotunda' } },
    { kind: 'theed', at: [-160, 470], yaw: 2.8, opts: { style: 'hall' } },
    { kind: 'theed', at: [-470, 420], yaw: 2.2, opts: { style: 'hall' } },
    // the Royal Starship, on the apron before the hangar
    { kind: 'royalship', at: [-240, 140], yaw: 2.6 },
    // lamps up the road to Theed
    { kind: 'lamp', at: [-118, 46], opts: { h: 4.5, light: '#ffe2a8' } },
    { kind: 'lamp', at: [-138, 76], opts: { h: 4.5, light: '#ffe2a8' } },
    { kind: 'lamp', at: [-158, 100], opts: { h: 4.5, light: '#ffe2a8' } },
    { kind: 'lamp', at: [-176, 124], opts: { h: 4.5, light: '#ffe2a8' } },
    // the forest out past the sacred place, and along the lake
    { kind: 'grove', at: [-470, -120], opts: { n: 16, r: 34, seed: 21 } },
    { kind: 'grove', at: [-200, -400], opts: { n: 14, r: 30, seed: 22 } },
    { kind: 'grove', at: [-460, -360], opts: { n: 16, r: 34, seed: 23 } },
    { kind: 'grove', at: [-110, -300], opts: { n: 10, r: 24, seed: 24 } },
    { kind: 'grove', at: [480, 120], opts: { n: 12, r: 30, seed: 25 } },
    { kind: 'grove', at: [-60, 120], opts: { n: 8, r: 20, seed: 26 } },
  ],
  scatter: [
    // (Quaternius's ground cover, under the built plants: catalog/quaternius.js)
    { kind: 'qclover', n: 150, within: [4, 100], scale: [0.8, 1.6], solid: false },
    { kind: 'qgrass', n: 200, within: [4, 120], scale: [0.8, 1.5], solid: false },
    { kind: 'nabootree', n: 80, within: [50, 600], scale: [0.7, 1.4], flat: 0.9 },
    { kind: 'rock', n: 50, within: [40, 560], scale: [0.6, 2.4], opts: { color: '#8e8a78', sharp: 0.3 } },
  ],
  life: [
    { kind: 'gungan', n: 10, at: [250, -235], spread: 40, roam: 14, speed: 1.1, name: 'Gungan soldier', says: ['Wesa ready to do are-sa part!', 'Da shield up! Da droids no getting in here!', 'Boomas! Get da boomas!', 'Yousa stay behind da shield, okeyday?'] },
    { kind: 'kaadu', n: 5, at: [230, -220], spread: 30, roam: 18, speed: 1.4, r: 0.8 },
    // (the army's fambaas, which carried the shield generators)
    { kind: 'fambaa', n: 2, at: [262, -262], spread: 30, roam: 10, speed: 0.5, r: 3.5 },
    { kind: 'gungan', n: 1, at: [40, 30], roam: 20, speed: 1.2, name: 'Jar Jar Binks', says: ['Meesa Jar Jar Binks!', 'Exsqueeze me, but de mostest safest place would be Gunga City.', 'How wude!', 'Mesa day startin’ pretty okee-day, with a brisky morning munchy. Den BOOM!', 'Mesa called Jar Jar Binks. Mesa your humble servant.'] },
    { kind: 'gungan', n: 1, at: [-320, -238], still: true, scale: 1.35, r: 0.7, name: 'Boss Nass', says: ['Wesa no like da Naboo. Un dey no like uss-en.', 'Yousa tinkin’ yousa people ganna die?', 'Mesa like dis. Maybe wesa bein’ friends.'] },
    { kind: 'gungan', n: 4, at: [-322, -226], spread: 14, roam: 8, speed: 0.9, name: 'Gungan', says: ['Dis a sacred place. Yousa be quiet, okeyday?', 'Da Naboo tink dey so smarty. Dey tink dey brainses so big.', 'Boss Nass say we hide here till da droids go.'] },
    { kind: 'battledroid', n: 9, path: [[360, -330], [420, -360], [450, -420], [390, -440], [340, -400]], speed: 1.3, name: 'Battle droid', says: ['Roger, roger.', 'Halt! Who goes there?', 'Uh-oh.', 'Move along. Move along.'] },
    { kind: 'battledroid', n: 6, at: [380, -400], spread: 20, roam: 6, speed: 1, name: 'Battle droid', says: ['Roger, roger.', 'They’re still coming through! Er… roger, roger.'] },
    { kind: 'shaak', n: 7, at: [150, -60], spread: 40, roam: 30, speed: 0.6, r: 1.1 },
    { kind: 'shaak', n: 3, at: [50, 20], spread: 16, roam: 20, speed: 0.5, r: 1.1 },
    { kind: 'farmer', n: 2, at: [-20, 14], spread: 6, roam: 8, speed: 0.9, name: 'Naboo farmer', says: ['Shaak herd’s restless today. Something in the sky.', 'Theed’s up the road. Mind the Gungans in the long grass.', 'Milk, cheese, and more milk. That’s a shaak farm.'] },
    { kind: 'astromech', n: 1, at: [-16, 24], roam: 6, speed: 0.6, name: 'Astromech', says: ['(A cheerful whistle at the cart. It is in charge of the cart.)'] },
    { kind: 'shaak', n: 4, at: [-120, -140], spread: 30, roam: 25, speed: 0.6, r: 1.1 },
    { kind: 'villager', n: 6, at: [-250, 260], spread: 40, roam: 24, speed: 1.0, name: 'Theed citizen', says: ['The Queen will speak from the palace steps at noon.', 'Have you seen the falls from the plaza? The whole city hums with them.', 'Our Senator Palpatine is from Theed, you know. Such a kind, patient man.', 'They say the Gungans and the Queen are friends now. Imagine that.'] },
    { kind: 'rebel', n: 3, at: [-245, 255], spread: 12, roam: 10, speed: 1.1, name: 'Palace guard', says: ['The palace is open to visitors today. Stay on the paths.', 'Royal Naboo Security Forces. Keep moving, please.'] },
    { kind: 'rebel', n: 1, at: [-292, 200], roam: 8, speed: 1.1, name: 'Captain Panaka', says: ['Your Highness, we have a problem: the Federation has landed its army.', 'We’ll take the hangar first. Then the throne room.', 'Our people are dying. We must act.'] },
    { kind: 'rebelpilot', n: 3, at: [-300, 188], spread: 14, roam: 10, speed: 1.2, name: 'Bravo Squadron pilot', says: ['We’re going after the droid control ship. Who’s with us?', 'Bravo Flight, fly with me!', 'There was a kid in one of the fighters. He blew the control ship from the inside!'] },
    { kind: 'droid', n: 1, at: [-296, 176], roam: 6, speed: 0.7, name: 'R2-D2', says: ['(A proud whistle. It was the only droid to get the Queen’s ship through the blockade.)', '(A cheeky beep, and a look at the N-1’s astromech socket.)'] },
    { kind: 'quigon', n: 1, at: [60, 170], roam: 10, speed: 0.9, name: 'Qui-Gon Jinn', says: ['There’s always a bigger fish.', 'The ability to speak does not make you intelligent.', 'Feel, don’t think. Use your instincts.'] },
    { kind: 'villager', n: 1, at: [366, 336], roam: 5, speed: 0.8, name: 'Padmé', says: ['When I was in the Legislative Youth Program, we came here for school retreat. We’d swim to that island every day.', 'I love the water. We’d lie on the sand and let the sun dry us.', 'It’s so peaceful here.'] },
    { kind: 'anakin', n: 1, at: [376, 324], still: true, name: 'Anakin', says: ['I don’t like sand. It’s coarse and rough and irritating, and it gets everywhere. Not like here.', 'Here, everything is soft and smooth.'] },
  ],
  rides: [
    { kind: 'kaadu', at: [214, -196], yaw: 2.2 },
    { kind: 'kaadu', at: [24, -10], yaw: 1.4 },
  ],
  flyovers: [
    { kind: 'n1', n: 3, metres: 11, alt: 90, speed: 120, every: 50 },
    { kind: 'nubian', n: 1, metres: 76, alt: 170, speed: 60, every: 90 },
    { kind: 'vulture', n: 2, metres: 7, alt: 70, speed: 140, every: 70 },
  ],
};

export const SITES = { naboo: SITE };
