// The multiverse's destinations as data, and the portal gun's dial. Each
// place stands in its own column west of the rooms, one per 100 m of z from
// z = 900 (the plan's Global Constraints); its builder (./<id>.js) loads the
// first time the portal opens on it. Rick's garage portal goes wherever the
// dial is set (kept as tp-rm-dial); every destination's portal goes home to
// the garage.
//
// Pure: rules.js spreads these into AREAS, LINKS, PEOPLE, HOTSPOTS and
// TASKS; RmWorld.jsx takes the names, what people say and what talking to
// them does.

export const DEST_COL = { x0: -470, x1: -330 };
export const DEST_X = (DEST_COL.x0 + DEST_COL.x1) / 2;
export const destZ = (i) => 900 + 100 * i;
// a place's box: `deep` along z round its row, `wide` across the column's middle
export const destArea = (i, deep = 50, wide = DEST_COL.x1 - DEST_COL.x0) => ({ x0: DEST_X - wide / 2, x1: DEST_X + wide / 2, z0: destZ(i) - deep / 2, z1: destZ(i) + deep / 2 });

// headings, as rules.js has them: a figure facing `face` looks along (cos, −sin)
const N = Math.PI / 2;
const S = -Math.PI / 2;
const E = 0;
const W = Math.PI;

// where every portal home arrives: beside the garage's portal, facing into the room
export const GARAGE_BACK = { x: -301.2, z: 101.4, face: 0 };

// A place: its row `i`, its box, and everything in it in metres from its
// middle (dx east, dz south), turned into the world's coordinates here.
// `acts`: a hotspot that, used, tells the place's builder (its `actions`, by
// name). `escape`: a place left in a hurry: once its `spot` is used (with its
// `after` spot used first on this visit, else that spot says `before`),
// getting home through the portal inside `s` seconds is `task` done.
// `goal`: the hotspot the map points to for the place's thing to do, where
// no talk or escape says (the Vindicators' door to Rick's rooms).
// `collect`: a task done once every one of its `spots` has been used on a
// visit (the simulation's slips); with `escape: { s }`, the clock starts
// then instead, and getting home inside it is the task done; with `start`,
// nothing is done yet: the place is only told ('collected': Evil Rick comes).
// `caught`: what's said when one of the place's hunters catches Morty
// (stage.js's NPC behaviour); he's put back at the way in.
// A person or one of the crowd may carry `ai` (stage.js): `wander` points in
// metres from the middle (turned into the world's here), `watch`, `bark`,
// `hunt`. Anyone who roams is marked so, and isn't in the way.
const roams = (ai) => Boolean(ai?.wander || ai?.hunt);
function place(i, { id, name, note, kind, deep, wide, sky, ceiling, people = [], extras = [], spots = [], solids = [], tasks = [], say = {}, done = {}, unlock = {}, acts = {}, escape = null, goal = null, collect = null, caught = null, kinds = [] }) {
  const area = destArea(i, deep, wide);
  const cx = DEST_X;
  const cz = destZ(i);
  const w = (o) => ({ ...o, x: cx + o.dx, z: cz + o.dz, ...(o.ai && { ai: { ...o.ai, ...(o.ai.wander && { wander: o.ai.wander.map(([dx, dz]) => [cx + dx, cz + dz]) }) }, ...(roams(o.ai) && { roams: true }) }) });
  return {
    id,
    i,
    name,
    note,
    kind,
    area,
    sky,
    ceiling,
    centre: { x: cx, z: cz },
    // in at the south edge facing north; the way home 3 m behind
    arrive: { x: cx, z: area.z1 - (kind === 'room' ? 4.6 : 7), face: N },
    back: { x: cx, z: area.z1 - (kind === 'room' ? 1.6 : 4) },
    people: people.map((p) => ({ ...w(p), area: id })),
    // the crowd: copies of the Meshy figures made for it, standing about ({ kind, dx, dz, face })
    extras: extras.map((e) => w(e)),
    hotspots: spots.map((s) => ({ r: 1.4, ...w(s), area: id })),
    // what can't be walked through: { id, dx, dz, w, d } boxes and { id, dx, dz, r } posts
    solids: solids.map((s) => w(s)),
    tasks,
    say,
    done,
    unlock,
    acts,
    escape,
    goal,
    collect,
    caught,
    kinds,
  };
}

export const DESTINATIONS = [
  place(0, {
    id: 'customs',
    name: 'Interdimensional Customs',
    note: 'The customs hall between the dimensions. Rick’s Mega Seeds shouldn’t go through the scanner.',
    kind: 'room',
    deep: 30,
    wide: 34,
    ceiling: 8,
    people: [
      { id: 'customs-agent1', who: 'gromflomite', dx: -4, dz: -4.6, face: S, ai: { watch: 9, hunt: { speed: 3.1, catchR: 1.1 } } },
      { id: 'customs-agent2', who: 'gromflomite', dx: 4, dz: -4.6, face: S, ai: { watch: 9, hunt: { speed: 2.9, catchR: 1.1 } } },
      { id: 'krombopulos', dx: 10, dz: -8, face: W, ai: { watch: 7, bark: { r: 5, every: 18, lines: ['Oh boy, here I go killing again!', 'I just love killin’. Not you though, Morty. You seem nice.'] } } },
    ],
    extras: [
      { kind: 'zigerion', dx: -6, dz: 2, face: N, ai: { wander: [[-6, 2], [-6, 2.6]], speed: 0.4, pause: 6 } },
      { kind: 'gearperson-a', dx: -6, dz: 4, face: N, ai: { wander: [[-6, 4], [-6, 4.6]], speed: 0.4, pause: 7 } },
      { kind: 'zigerion', dx: -6, dz: 6, face: N + 0.3, ai: { wander: [[-6, 6], [-6, 6.6]], speed: 0.4, pause: 5 } },
      { kind: 'plutonian-a', dx: -6, dz: 7.8, face: N, ai: { wander: [[-6, 7.8], [-6, 8.4]], speed: 0.4, pause: 8 } },
      { kind: 'zigerion', dx: -11, dz: -9, face: 0.4, ai: { wander: [[-11, -9], [-13, -5], [-9, -3], [-11, -9]], speed: 0.9, pause: 3 } },
    ],
    spots: [
      { id: 'seeds', dx: 6, dz: 5.4, label: 'Rick’s Mega Seeds', verb: 'Take' },
      { id: 'scanner', dx: 0, dz: 0, label: 'The scanner', verb: 'Walk through', r: 1.1 },
      { id: 'customs-agent1', dx: -4, dz: -2.8, label: 'A customs agent', verb: 'Talk' },
      { id: 'customs-agent2', dx: 4, dz: -2.8, label: 'A customs agent', verb: 'Talk' },
      { id: 'krombopulos', dx: 10, dz: -8, label: 'Krombopulos Michael', verb: 'Talk' },
      { id: 'queue', dx: -4.2, dz: 5, label: 'The queue', verb: 'Look' },
    ],
    solids: [
      { id: 'arch-west', dx: -1.45, dz: 0, r: 0.35 },
      { id: 'arch-east', dx: 1.45, dz: 0, r: 0.35 },
      { id: 'arch-b-west', dx: -7.45, dz: 0, r: 0.35 },
      { id: 'arch-b-east', dx: -4.55, dz: 0, r: 0.35 },
      { id: 'desk-west', dx: -4, dz: -3.6, w: 3, d: 0.9 },
      { id: 'desk-east', dx: 4, dz: -3.6, w: 3, d: 0.9 },
      { id: 'seeds', dx: 6, dz: 6.6, w: 1.6, d: 0.8 },
      { id: 'pad-west', dx: -10, dz: -10.5, r: 1.7 },
      { id: 'pad-east', dx: 3, dz: -10.5, r: 1.7 },
    ],
    tasks: [{ id: 'customs', name: 'Get the seeds through customs', hint: 'Dial Interdimensional Customs on the portal gun, take Rick’s Mega Seeds, walk through the scanner, and get back through the portal before they catch you.' }],
    say: {
      seeds: { who: null, text: 'Rick’s Mega Seeds. He says to keep them somewhere the scanner won’t look. He didn’t say where.' },
      scanner: { who: null, text: 'The arch goes red and the sirens start. They’ve found the seeds. Run for the portal.' },
      'customs-agent1': { who: 'A customs agent', text: 'Next. Anything to declare? Seeds, fruit, Ricks?' },
      'customs-agent2': { who: 'A customs agent', text: 'Bags on the belt, stand in the arch, and don’t make it weird.' },
      krombopulos: { who: 'Krombopulos Michael', text: 'Krombopulos Michael. Oh boy, here I go killing again! Not you, kid. You seem nice.' },
      queue: { who: null, text: 'The queue for the other arch. Everyone in it is from somewhere else, and they’ve all been waiting a while.' },
    },
    acts: { seeds: 'took', scanner: 'alarm' },
    escape: { spot: 'scanner', after: 'seeds', before: { who: 'A customs agent', text: 'The arch stays green. “Clean. Next.”' }, s: 60, task: 'customs' },
    caught: 'A Gromflomite gets a hand on your collar. “Seeds. Confiscated.” You’re marched back to the door, and the alarm stops.',
    kinds: ['gromflomite', 'krombopulos', 'zigerion', 'gearperson-a', 'plutonian-a'],
  }),
  place(1, {
    id: 'squanch',
    name: 'Planet Squanch',
    note: 'Squanchy’s planet, red grass and cat-tree houses. Birdperson’s getting married today.',
    kind: 'outdoor',
    deep: 50,
    wide: 70,
    sky: { top: 0x2a8a9a, mid: 0x7ad2c8, low: 0xf2d8b8, sun: 0xfff0d8, clouds: 1, moons: 0 },
    people: [
      { id: 'squanchy', dx: -10, dz: -6, face: S, ai: { watch: 8, bark: { r: 5, every: 20, lines: ['I squanch my family!', 'This is my squanch, Morty. Welcome to it.'] } } },
      { id: 'sbirdperson', who: 'birdperson', dx: 5.2, dz: -11, face: S, until: 'squanch' },
      { id: 'stammy', who: 'tammy', dx: 6.8, dz: -11, face: S, until: 'squanch' },
    ],
    extras: [
      { kind: 'magdalian-a', dx: 1, dz: -3, face: N, ai: { wander: [[1, -3], [6, -1], [9, 2], [3, 3]], speed: 0.8, pause: 4 } },
      { kind: 'magdalian-c', dx: 11, dz: -3, face: N, ai: { wander: [[11, -3], [13, 1], [8, 3]], speed: 0.7, pause: 5 } },
      { kind: 'magdalian-b', dx: 2.5, dz: 1, face: N + 0.2, ai: { wander: [[2.5, 1], [-3, 2], [-6, -1], [0, -2]], speed: 0.9, pause: 3 } },
    ],
    spots: [
      { id: 'squanchy', dx: -10, dz: -6, label: 'Squanchy', verb: 'Talk' },
      { id: 'sbirdperson', dx: 5.2, dz: -9.4, label: 'Birdperson', verb: 'Talk', until: 'squanch' },
      { id: 'stammy', dx: 6.8, dz: -9.4, label: 'Tammy', verb: 'Talk', until: 'squanch' },
      { id: 'toast', dx: 16, dz: -1.6, label: 'The wedding toast', verb: 'Raise a glass' },
      { id: 'suckulents', dx: -19, dz: 9, label: 'Suckulents', verb: 'Look', r: 2 },
      { id: 'cattree', dx: -14, dz: -9, label: 'Squanchy’s house', verb: 'Look', r: 2 },
    ],
    solids: [
      { id: 'house', dx: -14, dz: -14, r: 3.6 },
      { id: 'tree-b', dx: 22, dz: -14, r: 2.6 },
      { id: 'tree-c', dx: -25, dz: 4, r: 2.6 },
      { id: 'arch-west', dx: 4, dz: -12.6, r: 0.3 },
      { id: 'arch-east', dx: 8, dz: -12.6, r: 0.3 },
      { id: 'table', dx: 16, dz: -3.4, w: 5, d: 1.2 },
      { id: 'suckulents', dx: -19, dz: 11, r: 1.4 },
    ],
    tasks: [{ id: 'squanch', name: 'Survive Birdperson’s wedding', hint: 'Dial Planet Squanch on the portal gun, raise a glass at the wedding, and get back through the portal when the Federation arrives.' }],
    say: {
      squanchy: { who: 'Squanchy', text: 'You squanch what you squanch, Morty. Birdperson’s getting squanched today. Married. Same thing.' },
      sbirdperson: { who: 'Birdperson', text: 'Morty. I am glad you came. Tammy and I are to be joined. It will be a day to remember.' },
      stammy: { who: 'Tammy', text: 'Birdperson and I are getting married! Isn’t that squanchy?' },
      toast: { who: null, text: 'You raise a glass. The band stops. Tammy smiles: she’s been Federation all along. Portals open round the arch. Run.' },
      suckulents: { who: null, text: 'Suckulents. They suck the blood out of you in seconds. Don’t sit on one.' },
      cattree: { who: null, text: 'Squanchy’s house: a cat tree three storeys tall, with a toy on a string on every floor.' },
    },
    acts: { toast: 'raid' },
    escape: { spot: 'toast', s: 60, task: 'squanch' },
    caught: 'A Gromflomite agent tackles you into the red grass. “Got the kid.” You come round by the portal, and the wedding’s over.',
    kinds: ['squanchy', 'birdperson', 'tammy', 'gromflomite', 'squanchy-house', 'magdalian-a', 'magdalian-b', 'magdalian-c'],
  }),
  place(2, {
    id: 'gazorpazorp',
    name: 'Gazorpazorp',
    note: 'A red desert where the men fight rocks and the women live in a city of their own.',
    kind: 'outdoor',
    deep: 50,
    wide: 70,
    sky: { top: 0x3a1a3a, mid: 0xc85a3a, low: 0xf2b070, sun: 0xffd8a0, clouds: 0, moons: 0 },
    people: [
      { id: 'marsha', dx: 0, dz: -14.6, face: S, ai: { watch: 10 } },
      { id: 'mortyjr', dx: -9, dz: 9, face: E, ai: { wander: [[-9, 9], [-5, 12], [-12, 13], [-14, 8]], speed: 0.8, pause: 3, bark: { r: 4, every: 16, lines: ['Dad? Is that you? You look smaller.', 'I want to be a writer when I grow up. Or a conqueror.'] } } },
      { id: 'gazorpian-a', who: 'gazorpian', dx: 13, dz: -1, face: E, ai: { wander: [[13, -1], [15, -9], [20, -4], [12, 4]], speed: 1.4, pause: 1.5, hunt: { speed: 3.4, catchR: 1.3, near: 6.5, lose: 11 } } },
      { id: 'gazorpian-b', who: 'gazorpian', dx: 17, dz: -1, face: W, ai: { wander: [[17, -1], [22, 8], [16, 10], [10, -6]], speed: 1.3, pause: 2, hunt: { speed: 3.2, catchR: 1.3, near: 6.5, lose: 11 } } },
    ],
    spots: [
      { id: 'marsha', dx: 0, dz: -13, label: 'Mar-Sha', verb: 'Talk' },
      { id: 'gate', dx: 4.5, dz: -16, label: 'The gate of the women’s city', verb: 'Knock' },
      { id: 'mortyjr', dx: -9, dz: 9, label: 'Morty Jr.', verb: 'Talk' },
      { id: 'gazorpian-a', dx: 15, dz: 1.4, label: 'Two Gazorpians', verb: 'Look', r: 2 },
    ],
    solids: [
      { id: 'wall-west', dx: -19, dz: -21, w: 30, d: 6 },
      { id: 'wall-east', dx: 19, dz: -21, w: 30, d: 6 },
      { id: 'gate-doors', dx: 0, dz: -21, w: 8, d: 5 },
      { id: 'dais', dx: 0, dz: -16.6, w: 4, d: 2.4 },
      { id: 'rock-a', dx: 15, dz: -12, r: 2.4 },
      { id: 'rock-b', dx: -18, dz: 2, r: 3 },
      { id: 'rock-c', dx: 24, dz: 10, r: 2.2 },
    ],
    tasks: [{ id: 'gazorp', name: 'Visit the women of Gazorpazorp', hint: 'Dial Gazorpazorp on the portal gun, and knock at the gate of the women’s city. Keep clear of the men.' }],
    caught: 'A Gazorpian picks you up by the shirt, roars, and throws you back to where you came in.',
    say: {
      marsha: { who: 'Mar-Sha', text: 'Welcome, Morty. The men stay outside. You may come in. You seem harmless.' },
      gate: { who: null, text: 'Men are not allowed in. Mar-Sha makes an exception for a Morty.' },
      mortyjr: { who: 'Morty Jr.', text: 'Dad. I wrote a book. It’s called My Horrible Father. It’s doing very well.' },
      'gazorpian-a': { who: null, text: 'Two Gazorpians, fighting over a rock. The rock is winning.' },
    },
    done: { gate: 'gazorp' },
    unlock: { gate: 'gazorp' },
    kinds: ['marsha', 'mortyjr', 'gazorpian'],
  }),
  place(3, {
    id: 'birdworld',
    name: 'Bird World',
    note: 'Birdperson’s home planet: clay towers under umbrella trees, and crystals in the grass.',
    kind: 'outdoor',
    deep: 50,
    wide: 70,
    sky: { top: 0x8ac8a8, mid: 0xd2ecc8, low: 0xf6f2d0, sun: 0xfff8d8, clouds: 1, moons: 2 },
    people: [
      { id: 'bbirdperson', who: 'birdperson', dx: -2.6, dz: -9.6, face: S, until: 'squanch' },
      { id: 'phoenixperson', dx: -2.6, dz: -9.6, face: S, after: 'squanch' },
      { id: 'unity', dx: 10, dz: -3, face: W, ai: { wander: [[10, -3], [6, 2], [12, 5], [15, 0]], speed: 0.9, pause: 4, bark: { r: 4, every: 18, lines: ['We are Unity. All of us. It’s nice to meet you, Morty.', 'Rick isn’t good for us. We know. We’re here anyway.'] } } },
    ],
    spots: [
      { id: 'bbirdperson', dx: -2.6, dz: -9.6, label: 'Birdperson', verb: 'Talk', until: 'squanch' },
      { id: 'phoenixperson', dx: -2.6, dz: -9.6, label: 'Phoenixperson', verb: 'Talk', after: 'squanch' },
      { id: 'unity', dx: 10, dz: -3, label: 'Unity', verb: 'Talk' },
      { id: 'door', dx: 1.4, dz: -11.4, label: 'Birdperson’s door', verb: 'Knock' },
      { id: 'crystals', dx: -12, dz: 4, label: 'The crystals', verb: 'Look', r: 2 },
    ],
    solids: [
      { id: 'house', dx: 0, dz: -16, r: 4 },
      { id: 'tower-a', dx: -22, dz: -15, r: 4 },
      { id: 'tower-b', dx: 20, dz: -17, r: 4.5 },
      { id: 'tree-a', dx: -16, dz: 10, r: 1.2 },
      { id: 'tree-b', dx: 18, dz: 6, r: 1.2 },
      { id: 'crystals', dx: -12, dz: 6, r: 1.2 },
    ],
    tasks: [{ id: 'birdworld', name: 'Visit Birdperson at home', hint: 'Dial Bird World on the portal gun, and knock at Birdperson’s door.' }],
    say: {
      bbirdperson: { who: 'Birdperson', text: 'Morty. In my culture, this is the time of greeting. Welcome to my home.' },
      phoenixperson: { who: 'Phoenixperson', text: 'Birdperson is gone. There is only Phoenixperson now.' },
      unity: { who: 'Unity', text: 'Rick isn’t here? Good. I came to see Birdperson. We all get a little lonely, Morty.' },
      door: { who: null, text: 'Birdperson’s house. He doesn’t lock it. Nobody on Bird World does.' },
      crystals: { who: null, text: 'The crystals hum when you walk past them. It’s nice.' },
    },
    done: { door: 'birdworld' },
    unlock: { door: 'birdworld' },
    kinds: ['birdperson', 'phoenixperson', 'unity', 'birdperson-house'],
  }),
  place(4, {
    id: 'fantasy',
    name: 'Fantasy World',
    note: 'A village of stairs that bite, a tavern and a beanstalk. The giants are up the beanstalk.',
    kind: 'outdoor',
    deep: 50,
    wide: 70,
    sky: { top: 0x3f8fe0, mid: 0x9ad2f5, low: 0xf6efd2, sun: 0xfff2c8, clouds: 1, moons: 0 },
    people: [
      { id: 'fmeeseeks', who: 'meeseeks', dx: 5, dz: 1, face: S, ai: { watch: 8, bark: { r: 5, every: 12, lines: ['I’m Mr. Meeseeks! Look at me!', 'Existence is pain to a Meeseeks, Morty. Give me something to do.', 'Caaan do!'] } } },
      { id: 'kingjellybean', dx: -13, dz: -6, face: E, until: 'fantasy', ai: { wander: [[-13, -6], [-10, -3], [-15, -1]], speed: 0.7, pause: 5, watch: 6 } },
    ],
    spots: [
      { id: 'fmeeseeks', dx: 5, dz: 1, label: 'The Meeseeks at the well', verb: 'Talk' },
      { id: 'kingjellybean', dx: -13, dz: -6, label: 'King Jellybean', verb: 'Talk', until: 'fantasy' },
      { id: 'tavern', dx: -6, dz: -13, label: 'The Thirsty Step', verb: 'Look' },
      { id: 'giant', dx: 14, dz: -14, label: 'A giant', verb: 'Look' },
      { id: 'goblins', dx: 9, dz: 8, label: 'Stair Goblins', verb: 'Look' },
    ],
    solids: [
      { id: 'tavern', dx: -6, dz: -19, w: 11, d: 9 },
      { id: 'well', dx: 5, dz: -1.4, r: 1.1 },
      { id: 'privy', dx: -15.6, dz: -6, w: 1.7, d: 1.7 },
      { id: 'beanstalk', dx: -22, dz: -19, r: 1.6 },
      { id: 'giant', dx: 16, dz: -20, r: 2.6 },
      { id: 'cottage-a', dx: -25, dz: -6, w: 7, d: 6 },
      { id: 'cottage-b', dx: -25, dz: 8, w: 7, d: 6 },
      { id: 'cottage-c', dx: 24, dz: 4, w: 7, d: 6 },
    ],
    tasks: [{ id: 'fantasy', name: 'Get the village’s help', hint: 'Dial Fantasy World on the portal gun in Rick’s garage, and ask the Meeseeks at the well.' }],
    say: {
      fmeeseeks: { who: 'A Meeseeks', text: 'I’m Mr. Meeseeks! Look at me! The village needs a hand, and I’m the hand. Ooh, there. Done!' },
      kingjellybean: { who: 'King Jellybean', text: 'A visitor. Welcome to my kingdom, boy. Mind the stairs. Some of them bite.' },
      tavern: { who: null, text: 'The Thirsty Step. A note on the door: no stairs inside, by order of the stairs.' },
      giant: { who: null, text: 'Dale. He fell on his sword. It’s complicated.' },
      goblins: { who: null, text: 'Stair Goblins. They want you to go up them. Don’t go up them.' },
    },
    done: { fmeeseeks: 'fantasy' },
    unlock: { fmeeseeks: 'fantasy' },
    kinds: ['meeseeks', 'kingjellybean', 'thirstystep', 'giant', 'stairgoblin'],
  }),
  place(5, {
    id: 'microverse',
    name: 'The Microverse',
    note: 'Inside the car’s battery: Zeep’s lab, and a world stomping on gooble boxes.',
    kind: 'room',
    deep: 16,
    wide: 22,
    ceiling: 5,
    people: [
      { id: 'zeep', dx: -1.5, dz: -5.2, face: S, ai: { watch: 8, bark: { r: 4, every: 16, lines: ['Welcome to my universe. It powers itself, thank you.', 'You’re from the battery, aren’t you. Don’t say it.'] } } },
      { id: 'kyle', dx: 6, dz: -1, face: W, until: 'microverse', ai: { wander: [[6, -1], [8, 2], [4, 3]], speed: 0.8, pause: 4 } },
    ],
    spots: [
      { id: 'zeep', dx: -1.5, dz: -5.2, label: 'Zeep Xanflorp', verb: 'Talk' },
      { id: 'kyle', dx: 6, dz: -1, label: 'Kyle', verb: 'Talk', until: 'microverse' },
      { id: 'gooble', dx: -7, dz: 1, label: 'The gooble boxes', verb: 'Look' },
      { id: 'battery', dx: 2, dz: -1, label: 'The Miniverse battery', verb: 'Look' },
    ],
    solids: [
      { id: 'battery', dx: 2, dz: -2.7, r: 1.2 },
      { id: 'console', dx: -1.5, dz: -6.6, w: 3.4, d: 0.9 },
      { id: 'gooble', dx: -8.8, dz: 1, w: 1.4, d: 4.4 },
    ],
    tasks: [{ id: 'microverse', name: 'Meet the man inside the battery', hint: 'Dial the Microverse on the portal gun in Rick’s garage, and talk to Zeep at his console.' }],
    say: {
      zeep: { who: 'Zeep Xanflorp', text: 'You’re in the battery of your grandfather’s car, Morty. His car runs on my world, and my world runs on Kyle’s. It’s batteries all the way down.' },
      kyle: { who: 'Kyle', text: 'I made a universe to power ours. Now I find out ours is somebody’s power too. I’m going to go and live in a hut.' },
      gooble: { who: null, text: 'They stomp on them. The stomping makes the power. Slavery with extra steps.' },
      battery: { who: null, text: 'The Miniverse battery, glowing green. There’s a whole world in there making the power for this one.' },
    },
    done: { zeep: 'microverse' },
    unlock: { zeep: 'microverse' },
    kinds: ['zeep', 'kyle'],
  }),
  place(6, {
    id: 'anatomy',
    name: 'Anatomy Park',
    note: 'A theme park inside a man called Ruben. The diseases have got out.',
    kind: 'room',
    deep: 26,
    wide: 38,
    ceiling: 9,
    people: [
      { id: 'xenonbloom', dx: 2, dz: 7, face: N, ai: { watch: 9, bark: { r: 5, every: 18, lines: ['Welcome to Anatomy Park. Mind the pens, the hepatitis is moody today.', 'Pirates of the Pancreas is this way. It’s my favourite.'] } } },
      { id: 'poncho', dx: -9, dz: 1, face: E, ai: { wander: [[-9, 1], [-12, 4], [-6, 5], [-4, 0]], speed: 1.0, pause: 3, bark: { r: 4, every: 20, lines: ['Nothing in the bag. Don’t look in the bag.'] } } },
      { id: 'annie', dx: 7, dz: 2, face: W, ai: { watch: 8 } },
    ],
    spots: [
      { id: 'xenonbloom', dx: 2, dz: 7, label: 'Dr. Xenon Bloom', verb: 'Talk' },
      { id: 'poncho', dx: -9, dz: 1, label: 'Poncho', verb: 'Talk' },
      { id: 'annie', dx: 7, dz: 2, label: 'Annie', verb: 'Talk' },
      { id: 'hepatitis', dx: -14, dz: -6.6, label: 'Hepatitis A', verb: 'Look', r: 2.2 },
      { id: 'gonorrhoea', dx: -7, dz: -6.6, label: 'Gonorrhoea', verb: 'Look', r: 2.2 },
      { id: 'tuberculosis', dx: 0, dz: -6.6, label: 'Tuberculosis', verb: 'Look', r: 2.2 },
      { id: 'plague', dx: 7, dz: -6.6, label: 'The bubonic plague', verb: 'Look', r: 2.2 },
      { id: 'ecoli', dx: 14, dz: -6.6, label: 'E. coli', verb: 'Look', r: 2.2 },
      { id: 'pancreas', dx: 16, dz: 3, label: 'Pirates of the Pancreas', verb: 'Ride' },
    ],
    solids: [
      ...[-14, -7, 0, 7, 14].map((dx, n) => ({ id: `pen-${n}`, dx, dz: -10, w: 5.6, d: 3.6 })),
      { id: 'kiosk', dx: -14, dz: 6, w: 2.2, d: 2.2 },
      { id: 'gate-west', dx: 16, dz: 0.6, r: 0.35 },
      { id: 'gate-east', dx: 16, dz: 5.4, r: 0.35 },
    ],
    tasks: [{ id: 'anatomy', name: 'Ride Anatomy Park', hint: 'Dial Anatomy Park on the portal gun, and get round the park to Pirates of the Pancreas.' }],
    say: {
      xenonbloom: { who: 'Dr. Xenon Bloom', text: 'Welcome to Anatomy Park! The only theme park inside a human body. Keep your helmet on and your arms inside the bloodstream.' },
      poncho: { who: 'Poncho', text: 'Stay close, kid. The diseases are out, and I’ve seen this before. Different body, same mess.' },
      annie: { who: 'Annie', text: 'Hi! Welcome to Anatomy Park! Spleen Mountain’s closed. Everything’s closed. We might all die.' },
      hepatitis: { who: null, text: 'Hepatitis A. Out of its pen, and hungry.' },
      gonorrhoea: { who: null, text: 'Gonorrhoea. The glass was meant to hold it. The glass was wrong.' },
      tuberculosis: { who: null, text: 'Tuberculosis. It coughs when it sees you. That’s not a good sign.' },
      plague: { who: null, text: 'The bubonic plague, the park’s oldest attraction. It doesn’t like the new ones.' },
      ecoli: { who: null, text: 'E. coli. It came in with lunch.' },
      pancreas: { who: null, text: 'Pirates of the Pancreas, the last ride. You sit in a little boat and float down the pancreatic duct. Everyone else ran.' },
    },
    done: { pancreas: 'anatomy' },
    unlock: { pancreas: 'anatomy' },
    kinds: ['xenonbloom', 'poncho', 'annie', 'hepatitis', 'gonorrhoea', 'tuberculosis', 'plague', 'ecoli'],
  }),
  place(7, {
    id: 'needful',
    name: 'Needful Things',
    note: 'A curiosity shop where everything’s free. Its owner has very red hair.',
    kind: 'room',
    deep: 11,
    wide: 13,
    ceiling: 3.4,
    people: [{ id: 'needful', dx: 0, dz: -3.6, face: S }],
    spots: [
      { id: 'needful', dx: 0, dz: -1.9, label: 'Mr. Needful', verb: 'Talk' },
      { id: 'typewriter', dx: -4.6, dz: -2, label: 'A typewriter', verb: 'Look' },
      { id: 'aftershave', dx: 4.6, dz: -2, label: 'Aftershave', verb: 'Look' },
      { id: 'cream', dx: 4.6, dz: 1.5, label: 'Beauty cream', verb: 'Look' },
    ],
    solids: [
      { id: 'counter', dx: 0, dz: -2.8, w: 4, d: 0.7 },
      { id: 'shelf-west', dx: -5.9, dz: -0.5, w: 0.7, d: 7 },
      { id: 'shelf-east', dx: 5.9, dz: -0.5, w: 0.7, d: 7 },
    ],
    tasks: [{ id: 'needful', name: 'Take something free from Mr. Needful', hint: 'Dial Needful Things on the portal gun, and ask Mr. Needful at the counter what anything costs.' }],
    say: {
      needful: { who: 'Mr. Needful', text: 'Free. Everything here is free. Take the typewriter. It only costs you something you weren’t using.' },
      typewriter: { who: null, text: 'A typewriter that writes the truth about whoever owns it. Nobody keeps it long.' },
      aftershave: { who: null, text: 'Aftershave. Smells of success, and a little of everyone you let down to get it.' },
      cream: { who: null, text: 'Beauty cream. Works overnight. Only for the one night.' },
    },
    done: { needful: 'needful' },
    unlock: { needful: 'needful' },
    kinds: ['needful'],
  }),
  place(8, {
    id: 'jerryboree',
    name: 'The Jerryboree',
    note: 'A daycare for Jerrys, so the Ricks can go on adventures without them.',
    kind: 'room',
    deep: 16,
    wide: 22,
    ceiling: 4,
    people: [
      { id: 'jerryreal', who: 'jerry', dx: -6.5, dz: 4.5, face: N, ai: { watch: 7, bark: { r: 4, every: 14, lines: ['Morty! Oh thank god. Tell them I’m your Jerry.', 'They have a TV here. It only shows one channel. It’s fine.'] } } },
      { id: 'receptionist', who: 'rick', dx: 6.5, dz: 2.2, face: S, ai: { watch: 9 } },
      { id: 'jerrytv', who: 'jerry-cardigan', dx: -2, dz: -5, face: N },
    ],
    extras: [
      { kind: 'jerry-robe', dx: -8.5, dz: -3.5, face: 0, ai: { wander: [[-8.5, -3.5], [-7, -1], [-9, 1]], speed: 0.6, pause: 4 } },
      { kind: 'jerry-golf', dx: 2, dz: -1.6, face: W, ai: { wander: [[2, -1.6], [4, 0.5], [1, 1]], speed: 0.6, pause: 5 } },
      { kind: 'jerry-tux', dx: -5, dz: 1.5, face: 0.6, ai: { wander: [[-5, 1.5], [-3, 3.5], [-6, 3]], speed: 0.6, pause: 6 } },
      { kind: 'jerry-track', dx: 8.5, dz: -1.5, face: W, ai: { wander: [[8.5, -1.5], [8, 1], [6, -3]], speed: 0.6, pause: 7 } },
      { kind: 'jerry-gown', dx: -8.4, dz: -0.6, face: -0.4 },
      { kind: 'jerry-golf', dx: 0.5, dz: 2.5, face: -2.2 },
      { kind: 'jerry-robe', dx: 8.6, dz: -6.4, face: 2.6 },
      { kind: 'jerry-tux', dx: -4.4, dz: -6.2, face: -1.2 },
      { kind: 'jerry-track', dx: 1.6, dz: -6.4, face: 1.2 },
    ],
    spots: [
      { id: 'jerryreal', dx: -6.5, dz: 4.5, label: 'A Jerry by the door', verb: 'Talk' },
      { id: 'receptionist', dx: 6.5, dz: 4.1, label: 'The Rick on the desk', verb: 'Talk' },
      { id: 'ticket', dx: 3.5, dz: 4.8, label: 'The ticket machine', verb: 'Look' },
      { id: 'jerrytv', dx: -2, dz: -5, label: 'A Jerry at the TV', verb: 'Talk' },
      { id: 'ballpit', dx: 5, dz: -1.2, label: 'The ball pit', verb: 'Look', r: 2 },
    ],
    solids: [
      { id: 'desk', dx: 6.5, dz: 3.1, w: 3.2, d: 0.8 },
      { id: 'ticket', dx: 3.5, dz: 5.9, w: 0.6, d: 0.6 },
      { id: 'ballpit', dx: 5, dz: -4, w: 4.4, d: 4.4 },
      { id: 'tv', dx: -2, dz: -7.4, w: 2.4, d: 0.6 },
      { id: 'cot-a', dx: -8.5, dz: -5, w: 2, d: 1.1 },
      { id: 'cot-b', dx: -8.5, dz: -2, w: 2, d: 1.1 },
    ],
    tasks: [{ id: 'jerryboree', name: 'Pick up the right Jerry', hint: 'Dial the Jerryboree on the portal gun, and find our Jerry: he’ll ask about Beth.' }],
    say: {
      jerryreal: { who: 'Jerry', text: 'Morty! Is Beth here? Tell her I’ve been good. I made a friend. He’s also me.' },
      receptionist: { who: 'The Jerryboree’s Rick', text: 'Drop-off or pick-up? Ticket, please. No ticket, no Jerry. Rules are rules.' },
      ticket: { who: null, text: 'Take a ticket. Rick forgot his.' },
      jerrytv: { who: 'A Jerry', text: 'Shh. It’s the one where the guy fixes the house. I’ve seen it four hundred times. It’s really good.' },
      ballpit: { who: null, text: 'The ball pit. A Jerry went in an hour ago. He’s fine. He says he’s fine.' },
    },
    done: { jerryreal: 'jerryboree' },
    unlock: { jerryreal: 'jerryboree' },
    kinds: ['jerry', 'rick', 'jerry-robe', 'jerry-golf', 'jerry-tux', 'jerry-track', 'jerry-gown', 'jerry-cardigan'],
  }),
  place(9, {
    id: 'purge',
    name: 'The Purge Planet',
    note: 'A quiet farming village of cat people, one night a year.',
    kind: 'outdoor',
    deep: 50,
    wide: 70,
    sky: { top: 0x1c2350, mid: 0x7a4a7a, low: 0xf2a070, sun: 0xffd2a0, clouds: 1, moons: 1 },
    people: [{ id: 'arthricia', dx: 3, dz: -1, face: S }],
    extras: [
      { kind: 'magdalian-a', dx: -6, dz: 2, face: 0.4, ai: { wander: [[-6, 2], [-4, 4.5], [-8.5, 3]], speed: 0.7, pause: 4, hunt: { speed: 2.7, catchR: 1.2 } } },
      { kind: 'magdalian-b', dx: 9, dz: -5, face: 2.6, ai: { wander: [[9, -5], [11, -2.5], [6.5, -4]], speed: 0.7, pause: 4, hunt: { speed: 2.7, catchR: 1.2 } } },
      { kind: 'magdalian-c', dx: -14, dz: -2, face: -0.3, ai: { wander: [[-14, -2], [-12, 0.5], [-16.5, -1]], speed: 0.7, pause: 4, hunt: { speed: 2.7, catchR: 1.2 } } },
      { kind: 'magdalian-a', dx: 13, dz: 3, face: 3.4, ai: { wander: [[13, 3], [15, 5.5], [10.5, 4]], speed: 0.7, pause: 4, hunt: { speed: 2.7, catchR: 1.2 } } },
      { kind: 'magdalian-b', dx: -3, dz: -9, face: -1.6, ai: { wander: [[-3, -9], [-1, -6.5], [-5.5, -8]], speed: 0.7, pause: 4, hunt: { speed: 2.7, catchR: 1.2 } } },
      { kind: 'magdalian-c', dx: 7, dz: 7, face: 1.9, ai: { wander: [[7, 7], [9, 9.5], [4.5, 8]], speed: 0.7, pause: 4, hunt: { speed: 2.7, catchR: 1.2 } } },
    ],
    spots: [
      { id: 'arthricia', dx: 3, dz: -1, label: 'Arthricia', verb: 'Talk' },
      { id: 'siren', dx: -11, dz: -12, label: 'The purge siren', verb: 'Pull' },
    ],
    solids: [
      { id: 'well', dx: 3, dz: -3.4, r: 1.1 },
      { id: 'siren', dx: -11, dz: -13.4, r: 0.4 },
      { id: 'cottage-a', dx: -22, dz: -10, w: 7, d: 6 },
      { id: 'cottage-b', dx: -22, dz: 6, w: 7, d: 6 },
      { id: 'cottage-c', dx: 18, dz: -13, w: 7, d: 6 },
      { id: 'cottage-d', dx: 22, dz: 6, w: 7, d: 6 },
      { id: 'barn', dx: 0, dz: -19, w: 10, d: 7 },
    ],
    tasks: [{ id: 'purge', name: 'Get out before the purge', hint: 'Dial the Purge Planet on the portal gun, pull the siren, and get back through the portal within a minute.' }],
    say: {
      arthricia: { who: 'Arthricia', text: 'You’re not from here. Tonight’s the purge, and anything goes. If the siren goes off, run for your portal.' },
      siren: { who: null, text: 'The siren howls over the village. The purge has begun. Run for the portal.' },
    },
    acts: { siren: 'siren' },
    caught: 'The villagers catch you by the lanterns. It’s the purge. You wake up by the portal with your pockets turned out, and the sky is calm again.',
    escape: { spot: 'siren', s: 60, task: 'purge' },
    kinds: ['arthricia', 'magdalian-a', 'magdalian-b', 'magdalian-c'],
  }),
  place(10, {
    id: 'pluto',
    name: 'Pluto',
    note: 'A planet. Say it. The king insists.',
    kind: 'outdoor',
    deep: 50,
    wide: 70,
    sky: { top: 0x070b1e, mid: 0x1d2a55, low: 0x4f6fa8, sun: 0xe8eeff, clouds: 0, moons: 2 },
    people: [
      { id: 'flippynips', dx: 0, dz: -12, face: S, ai: { watch: 10, bark: { r: 6, every: 18, lines: ['Pluto is a planet! Say it with me, boy.', 'Scroopy Noopers is a liar and a plutonium hoarder.'] } } },
      { id: 'scroopy', dx: 11, dz: -2, face: W, ai: { wander: [[11, -2], [13, 2], [9, 4]], speed: 0.8, pause: 5, bark: { r: 4, every: 20, lines: ['Pluto is shrinking. The plutonium mines. Nobody listens.'] } } },
    ],
    extras: [
      { kind: 'plutonian-a', dx: -4, dz: -5, face: N, ai: { wander: [[-4, -5], [-2.5, -3], [-5.5, -4]], speed: 0.5, pause: 6 } },
      { kind: 'plutonian-b', dx: 3.5, dz: -4.5, face: N, ai: { wander: [[3.5, -4.5], [5.0, -2.5], [2.0, -3.5]], speed: 0.5, pause: 6 } },
      { kind: 'plutonian-a', dx: 1, dz: -3.2, face: N },
      { kind: 'plutonian-b', dx: -7.5, dz: -3, face: 1.2, ai: { wander: [[-7.5, -3], [-6.0, -1], [-9.0, -2]], speed: 0.5, pause: 6 } },
      { kind: 'plutonian-a', dx: 7, dz: -6, face: 2.2, ai: { wander: [[7, -6], [8.5, -4], [5.5, -5]], speed: 0.5, pause: 6 } },
    ],
    spots: [
      { id: 'flippynips', dx: 0, dz: -12, label: 'King Flippy Nips', verb: 'Talk' },
      { id: 'podium', dx: 0, dz: -7.6, label: 'The podium', verb: 'Speak' },
      { id: 'scroopy', dx: 11, dz: -2, label: 'Scroopy Noopers', verb: 'Talk' },
    ],
    solids: [
      { id: 'palace', dx: 0, dz: -19, w: 14, d: 8 },
      { id: 'podium', dx: 0, dz: -9.2, w: 1.2, d: 0.8 },
      { id: 'sign', dx: 12.6, dz: -2, w: 0.3, d: 1.6 },
      { id: 'house-a', dx: -20, dz: -8, r: 3 },
      { id: 'house-b', dx: -22, dz: 7, r: 3 },
      { id: 'house-c', dx: 21, dz: 8, r: 3 },
    ],
    tasks: [{ id: 'pluto', name: 'Tell Pluto it’s a planet', hint: 'Dial Pluto on the portal gun, and step up to the king’s podium.' }],
    say: {
      flippynips: { who: 'King Flippy Nips', text: 'Pluto is a planet! The scientists say so. The scientists who work for me say so.' },
      podium: { who: null, text: 'You step up to the podium. “Pluto is a planet.” They cheer for a long, long time.' },
      scroopy: { who: 'Scroopy Noopers', text: 'Pluto’s shrinking, kid. They’re mining the core. Nobody wants to hear it.' },
    },
    done: { podium: 'pluto' },
    unlock: { podium: 'pluto' },
    kinds: ['flippynips', 'scroopy', 'plutonian-a', 'plutonian-b'],
  }),
  place(11, {
    id: 'gearworld',
    name: 'Gear World',
    note: 'A city of brass gears, and Rick’s oldest friend.',
    kind: 'outdoor',
    deep: 50,
    wide: 70,
    sky: { top: 0x6a4a2a, mid: 0xc98a4a, low: 0xf2d39a, sun: 0xfff0c8, clouds: 1, moons: 0 },
    people: [{ id: 'gearhead', dx: -7, dz: -7.2, face: S }],
    extras: [
      { kind: 'gearperson-a', dx: 3, dz: -2, face: 2.4, ai: { wander: [[3, -2], [6, 3], [0, 5]], speed: 0.9, pause: 3 } },
      { kind: 'gearperson-b', dx: 12, dz: 2, face: W, ai: { wander: [[12, 2], [15, -3], [9, -4]], speed: 0.9, pause: 3 } },
      { kind: 'gearperson-a', dx: -14, dz: 2, face: 0.3, ai: { wander: [[-14, 2], [-10, 5], [-16, 6]], speed: 0.9, pause: 3 } },
      { kind: 'gearperson-b', dx: 5, dz: 6, face: -2, ai: { wander: [[5, 6], [8, 9], [2, 9]], speed: 0.9, pause: 3 } },
    ],
    spots: [
      { id: 'gearhead', dx: -7, dz: -7.2, label: 'Gearhead', verb: 'Talk' },
      { id: 'cogs', dx: 9, dz: -8, label: 'The city’s gears', verb: 'Look', r: 2.5 },
    ],
    solids: [
      { id: 'shop', dx: -7, dz: -11.5, w: 8, d: 5 },
      { id: 'cog', dx: 9, dz: -12, r: 3.2 },
      { id: 'tower-a', dx: -22, dz: -12, r: 5 },
      { id: 'tower-b', dx: 22, dz: -14, r: 6 },
      { id: 'tower-c', dx: 23, dz: 7, r: 4 },
      { id: 'tower-d', dx: -23, dz: 8, r: 4 },
    ],
    tasks: [{ id: 'gearworld', name: 'Visit Gearhead', hint: 'Dial Gear World on the portal gun, and say hello to Gearhead at his shop.' }],
    say: {
      gearhead: { who: 'Gearhead', text: 'Morty! Rick’s my best friend. Rick’s everyone’s best friend. That’s the problem with Rick.' },
      cogs: { who: null, text: 'The whole city turns. If one gear stops, everyone hears about it.' },
    },
    done: { gearhead: 'gearworld' },
    unlock: { gearhead: 'gearworld' },
    kinds: ['gearhead', 'gearperson-a', 'gearperson-b'],
  }),
  place(12, {
    id: 'vindicators',
    name: 'The Vindicators’ ship',
    note: 'The morning after Rick got drunk on the Vindicators’ ship. He left them a gauntlet of rooms.',
    kind: 'room',
    deep: 20,
    wide: 24,
    ceiling: 6,
    people: [
      { id: 'vance', dx: -2.6, dz: -5.4, face: S, ai: { watch: 8 } },
      { id: 'supernova', dx: 2.8, dz: -5.6, face: S, ai: { watch: 8 } },
      { id: 'alanrails', dx: -7.8, dz: 0.6, face: E, ai: { watch: 7 } },
      { id: 'millionants', dx: 7.8, dz: -0.6, face: W, ai: { watch: 7 } },
      { id: 'crocubot', dx: 6.6, dz: -6.8, face: S + 0.4 },
      { id: 'noobnoob', dx: -5.8, dz: 4.2, face: E, ai: { wander: [[-5.8, 4.2], [-2, 2.2], [1.6, 3.4], [-3.5, 5.6]], speed: 0.7, pause: 3, bark: { r: 4, every: 16, lines: ['Ha! Classic Rick.', 'Noob-Noob’s got it. Noob-Noob’s always got it.'] } } },
    ],
    spots: [
      { id: 'vance', dx: -2.6, dz: -4.2, label: 'Vance Maximus', verb: 'Talk' },
      { id: 'supernova', dx: 2.8, dz: -4.4, label: 'Supernova', verb: 'Talk' },
      { id: 'alanrails', dx: -7.8, dz: 0.6, label: 'Alan Rails', verb: 'Talk' },
      { id: 'millionants', dx: 7.8, dz: -0.6, label: 'Million Ants', verb: 'Talk' },
      { id: 'crocubot', dx: 6.6, dz: -6.8, label: 'Crocubot', verb: 'Talk' },
      { id: 'noobnoob', dx: -5.8, dz: 4.2, label: 'Noob-Noob', verb: 'Talk' },
      { id: 'saw', dx: -10.6, dz: -6, label: 'Rick’s rooms', verb: 'Go in', kind: 'trial' },
      { id: 'holotable', dx: 0, dz: 0.6, label: 'The holo-table', verb: 'Look', r: 1.6 },
      { id: 'beacon', dx: 9, dz: -8, label: 'The beacon', verb: 'Look' },
    ],
    solids: [
      { id: 'holotable', dx: 0, dz: -1.4, r: 1.9 },
      { id: 'beacon', dx: 9.6, dz: -9, r: 0.6 },
    ],
    tasks: [{ id: 'vindicators', name: 'Get through Rick’s rooms', hint: 'Dial the Vindicators’ ship on the portal gun, and go through the door to the rooms Rick left them.' }],
    say: {
      vance: { who: 'Vance Maximus', text: 'Rick’s passed out and he’s rigged the ship with traps. Typical. We’re the Vindicators, kid. We’ll handle this.' },
      supernova: { who: 'Supernova', text: 'Your grandfather is a disgusting drunk. He was right about Vance, though.' },
      alanrails: { who: 'Alan Rails', text: 'My ghost trains can tunnel through solid rock. They can’t tunnel through whatever Rick did to those doors.' },
      millionants: { who: 'Million Ants', text: 'We are Million Ants. All million of us are very tired of Rick.' },
      crocubot: { who: 'Crocubot', text: 'Half crocodile, half robot. All of me is done with this.' },
      noobnoob: { who: 'Noob-Noob', text: 'Ha! Rick’s the best. Did you see what he did to the holo-table? Classic. I’ve been mopping it all morning.' },
      holotable: { who: null, text: 'The holo-table. Rick did something on it last night that nobody will describe. It smells of lemon now. Noob-Noob’s work.' },
      beacon: { who: null, text: 'The Vindicators’ beacon. When it lights, they assemble. It lit for this.' },
    },
    goal: 'saw',
    kinds: ['vance', 'supernova', 'alanrails', 'millionants', 'crocubot', 'noobnoob', 'vindicators-ship'],
  }),
  place(13, {
    id: 'simulation',
    name: 'The Zigerions’ simulation',
    note: 'A copy of the Smiths’ street, run by the Zigerions to get Rick’s recipe. They’ve cut corners.',
    kind: 'room',
    deep: 40,
    wide: 56,
    ceiling: 9,
    people: [
      { id: 'nebulon', dx: 0, dz: -17.4, y: 3.2, face: S, ai: { watch: 30, bark: { r: 9, every: 20, lines: ['Act natural down there. Nothing is wrong with the street.', 'The recipe, Morty. Concentrated dark matter. Just say it out loud, to no one.'] } } },
      { id: 'zig-console-a', who: 'zigerion-b', dx: -7, dz: -17.6, y: 3.2, face: S, ai: { hunt: { speed: 2.7, catchR: 1.2 } } },
      { id: 'zig-console-b', who: 'zigerion-c', dx: 7, dz: -17.6, y: 3.2, face: S, ai: { hunt: { speed: 2.5, catchR: 1.2 } } },
    ],
    extras: [
      // the two men, the same man, out for the same walk, a step apart
      { kind: 'simman', dx: -0.8, dz: 5.6, face: W, ai: { wander: [[-0.8, 5.6], [-9, 5.6], [-9, 12], [6, 12], [6, 5.6]], speed: 1.0, pause: 0.5 } },
      { kind: 'simman', dx: 0.8, dz: 5.6, face: W, ai: { wander: [[0.8, 5.6], [-7.4, 5.6], [-7.4, 12], [7.6, 12], [7.6, 5.6]], speed: 1.0, pause: 0.5 } },
      // the pop-tart at his toaster's door, waving
      { kind: 'poptart', dx: 17, dz: 8.2, face: N, ai: { watch: 9, bark: { r: 5, every: 15, lines: ['Hi! I live in a toaster!', 'Nice day. It’s always a nice day.'] } } },
      { kind: 'toasterhouse', dx: 17, dz: 10.6, face: N },
    ],
    spots: [
      { id: 'twins', dx: 0, dz: 4, label: 'Two men, the same man', verb: 'Look', r: 1.8 },
      { id: 'poptart', dx: 17, dz: 7, label: 'A pop-tart in a toaster', verb: 'Look', r: 1.8 },
      { id: 'sun', dx: 24.6, dz: -4, label: 'The sun', verb: 'Look', r: 2 },
      { id: 'simhouse', dx: -12, dz: -3.4, label: 'The Smiths’ house', verb: 'Look', r: 1.8 },
      { id: 'nebulon', dx: 0, dz: -13.6, label: 'Prince Nebulon', verb: 'Call up', r: 1.8 },
      { id: 'consoles', dx: 7, dz: -13.6, label: 'The consoles', verb: 'Look', r: 1.8 },
    ],
    solids: [
      { id: 'walkway', dx: 0, dz: -17.6, w: 56, d: 4.8 },
      { id: 'simhouse', dx: -12, dz: -8.6, w: 10, d: 8 },
      { id: 'simhouse-b', dx: 12, dz: -8.6, w: 9, d: 7 },
      { id: 'toaster', dx: 17, dz: 10.6, w: 4.4, d: 3.4 },
    ],
    tasks: [{ id: 'simulation', name: 'Spot the simulation', hint: 'Dial the Zigerions’ simulation on the portal gun, find three things they got wrong, and get back through the portal before the Zigerions get to you.' }],
    say: {
      twins: { who: null, text: 'Two men walking the same way, the same face, the same step. One of them says “Hello” and the other one says it too. Slip one.' },
      poptart: { who: null, text: 'A pop-tart, living in a toaster. He waves. Nobody in the real street does that. Slip two.' },
      sun: { who: null, text: 'The sun is a yellow disc painted on the wall. It hasn’t moved all day. Slip three. Somewhere above you, somebody says “Shut it down.”' },
      simhouse: { who: null, text: 'The Smiths’ house, in two colours, with the windows painted on. The door doesn’t open.' },
      nebulon: { who: 'Prince Nebulon', text: 'Is it the kid? Of course it’s the kid. We don’t have the processing power for a Rick. Just act natural down there and tell us the recipe for concentrated dark matter.' },
      consoles: { who: null, text: 'Two Zigerions at the consoles, running the street. One of them is scrolling. The other is asleep.' },
    },
    collect: { task: 'simulation', spots: ['twins', 'poptart', 'sun'], escape: { s: 45 } },
    caught: 'Four hands close on your shoulders. “Got him, your highness.” The simulation reloads round you, and you’re back at the start of the street.',
    goal: 'twins',
    kinds: ['nebulon', 'zigerion-b', 'zigerion-c', 'simman', 'poptart', 'toasterhouse'],
  }),
  place(14, {
    id: 'storytrain',
    name: 'The Story Train',
    note: 'A carriage on the Story Train, the anthology going past the windows. Someone wants to see your ticket.',
    kind: 'room',
    deep: 30,
    wide: 10,
    ceiling: 3.4,
    people: [
      { id: 'storylord', dx: 0, dz: -13, face: S, ai: { wander: [[0, -13], [1.2, -12.2], [-1.2, -12.2]], speed: 0.5, pause: 4, watch: 8, bark: { r: 5, every: 18, lines: ['Give me a beat, Morty. Any beat. A character wants something.', 'This carriage is Act Two. Nothing ever happens in Act Two.'] } } },
      { id: 'ticketsguy', dx: 0, dz: -3, face: S, ai: { watch: 6, hunt: { speed: 0.85, catchR: 1.3, always: true, until: 'storytrain', line: '“Tickets, please.” You haven’t got one. He takes you by the ear and walks you to the back of the carriage.' } } },
    ],
    spots: [
      { id: 'storylord', dx: 0, dz: -11.4, label: 'Story Lord', verb: 'Talk' },
      { id: 'ticketsguy', dx: 0, dz: -1.6, label: 'The conductor', verb: 'Talk' },
      { id: 'trainticket', dx: 2.2, dz: 6.6, label: 'Something under the seat', verb: 'Reach for', r: 1.2 },
      { id: 'trainwindow', dx: -3.4, dz: 1, label: 'The window', verb: 'Look', r: 1.4 },
      { id: 'routemap', dx: 1.6, dz: -7.5, label: 'The route map', verb: 'Look', r: 1.2 },
    ],
    solids: [
      ...[-10, -7.5, -5, -2.5, 0, 2.5, 5, 7.5, 10].flatMap((dz) => [
        { id: `seat-w${dz}`, dx: -3.1, dz, w: 2.9, d: 1.1 },
        { id: `seat-e${dz}`, dx: 3.1, dz, w: 2.9, d: 1.1 },
      ]),
    ],
    tasks: [{ id: 'storytrain', name: 'Find your ticket', hint: 'Dial the Story Train on the portal gun, and find a ticket under a seat before the conductor reaches you. He walks the aisle; the seats are the way round him.' }],
    say: {
      storylord: { who: 'Story Lord', text: 'I am Story Lord. This train runs on stories, and yours has been meandering for a while, Morty. Give me a beat. Any beat.' },
      ticketsguy: { who: 'The conductor', text: 'Tickets, please. No ticket, no ride. Rules of the anthology.' },
      trainticket: { who: null, text: 'A ticket, folded under the seat. Someone got off in a hurry. It’s yours now. Tickets, please.' },
      trainwindow: { who: null, text: 'The windows show the stories as they pass: a wedding, a heist, a man who is also a train. None of them stop long enough to make sense.' },
      routemap: { who: null, text: 'The route: Cold Open, Act One, Act Two, Act Three, Tag. The train is running late past Act Two.' },
    },
    done: { trainticket: 'storytrain' },
    kinds: ['storylord', 'ticketsguy'],
  }),
  place(15, {
    id: 'fortress',
    name: 'Rick Prime’s fortress',
    note: 'A cold hangar of Rick Prime’s, somewhere out past the Central Finite Curve. The Omega Device is here.',
    kind: 'room',
    deep: 36,
    wide: 40,
    ceiling: 12,
    people: [{ id: 'rickprime', dx: 0, dz: -12.4, face: S, until: 'fortress', ai: { watch: 14 } }],
    extras: [
      // his security drones, round their loops; one that gets a look at Morty goes for him
      { kind: 'primedrone', dx: -10, dz: 6, y: 1.5, face: E, ai: { wander: [[-10, 6], [-4, 6], [-4, -2], [-10, -2]], speed: 1.8, pause: 0.2, hunt: { speed: 2.9, catchR: 1.5, near: 3.6, lose: 7 } } },
      { kind: 'primedrone', dx: 10, dz: -6, y: 1.5, face: W, ai: { wander: [[10, -6], [4, -6], [4, 4], [10, 4]], speed: 1.9, pause: 0.2, hunt: { speed: 2.9, catchR: 1.5, near: 3.6, lose: 7 } } },
      { kind: 'primedrone', dx: 0, dz: -8, y: 1.5, face: E, ai: { wander: [[0, -8], [8, -9], [-8, -9]], speed: 1.6, pause: 0.5, hunt: { speed: 2.9, catchR: 1.5, near: 3.6, lose: 7 } } },
    ],
    spots: [
      { id: 'omegadevice', dx: 5, dz: -1.8, label: 'The Omega Device', verb: 'Look', r: 1.9 },
      { id: 'primeconsole', dx: 0, dz: -10.6, label: 'Rick Prime’s console', verb: 'Reach', r: 1.6 },
      { id: 'primetanks', dx: -16, dz: 0, label: 'The tanks', verb: 'Look', r: 2.2 },
      { id: 'primepicture', dx: 17.6, dz: -8, label: 'A picture on the wall', verb: 'Look', r: 1.6 },
    ],
    solids: [
      { id: 'plinth', dx: 5, dz: -4, r: 1.7 },
      { id: 'primeconsole', dx: 0, dz: -14, w: 7, d: 1.6 },
      ...[-10, -6, -2, 2, 6, 10].map((dz) => ({ id: `tank${dz}`, dx: -18.2, dz, r: 1.1 })),
      { id: 'crate-a', dx: 14, dz: 10, w: 2.4, d: 2.4 },
      { id: 'crate-b', dx: 16.6, dz: 8, w: 1.8, d: 1.8 },
    ],
    tasks: [{ id: 'fortress', name: 'Reach Rick Prime', hint: 'Dial Rick Prime’s fortress on the portal gun, and get to his console past the drones. One red eye on you and you’re back at the door.' }],
    caught: 'A drone’s red eye finds you and shrieks. Rick Prime looks up, says “Nope,” and is gone. You come round at the way in, and he’s back at his console as if nothing happened.',
    say: {
      omegadevice: { who: null, text: 'The Omega Device. Rick built one to erase Diane from every dimension. Rick Prime built this one, and used it.' },
      primeconsole: { who: 'Rick Prime', text: '“Oh, it’s the backup. Tell him I said hi, kid. Tell him he’s still boring.” A portal opens behind him and he steps through it without looking back.' },
      primetanks: { who: null, text: 'Tanks along the wall, each with a Rick in it, half-made. He keeps spares.' },
      primepicture: { who: null, text: 'A framed picture of a garage. There’s a family in it. Somebody has drawn over two of their faces.' },
    },
    done: { primeconsole: 'fortress' },
    acts: { primeconsole: 'gone' },
    kinds: ['rickprime', 'primedrone', 'omegadevice', 'rick'],
  }),
  place(16, {
    id: 'froopyland',
    name: 'Froopyland',
    note: 'The world Rick built for Beth when she was small. Soft ground, candy hills, and the creatures aren’t friendly.',
    kind: 'outdoor',
    deep: 50,
    wide: 70,
    sky: { top: 0xff9ad8, mid: 0xffd0ec, low: 0xfff2c8, sun: 0xfff8e0, clouds: 1, moons: 0 },
    people: [{ id: 'tommy', dx: 16, dz: -14, face: S, ai: { wander: [[16, -14], [20, -10], [14, -8], [11, -13]], speed: 0.9, pause: 3, watch: 8, bark: { r: 5, every: 16, lines: ['Beth? Is Beth with you? She said she’d come back.', 'I’ve been here a long time. The Froopylanders and I have an arrangement.'] } } }],
    extras: [
      { kind: 'froopy-a', dx: -8, dz: 4, face: E, ai: { wander: [[-8, 4], [-3, 8], [-12, 10], [-14, 2]], speed: 1.2, pause: 1, hunt: { speed: 3.0, catchR: 1.2, near: 5, lose: 9 } } },
      { kind: 'froopy-a', dx: 6, dz: 10, face: W, ai: { wander: [[6, 10], [12, 14], [2, 16], [-2, 9]], speed: 1.1, pause: 1.5, hunt: { speed: 3.0, catchR: 1.2, near: 5, lose: 9 } } },
      { kind: 'froopy-b', dx: -20, dz: -8, face: E, ai: { wander: [[-20, -8], [-14, -14], [-24, -16], [-27, -4]], speed: 1.4, pause: 2, hunt: { speed: 3.3, catchR: 1.3, near: 6, lose: 10 } } },
      { kind: 'froopy-b', dx: 2, dz: -4, face: S, ai: { wander: [[2, -4], [8, -2], [4, 3], [-4, -2]], speed: 1.3, pause: 2, hunt: { speed: 3.3, catchR: 1.3, near: 6, lose: 10 } } },
    ],
    spots: [
      { id: 'tommy', dx: 16, dz: -12.4, label: 'Tommy', verb: 'Talk' },
      { id: 'froopyriver', dx: -12, dz: -18, label: 'The honey river', verb: 'Look', r: 2.4 },
      { id: 'froopysign', dx: -6, dz: 14, label: 'A sign', verb: 'Read', r: 1.6 },
      { id: 'froopyhill', dx: 24, dz: -2, label: 'A candy hill', verb: 'Look', r: 2.4 },
    ],
    solids: [
      { id: 'hill-a', dx: 24, dz: 6, r: 5 },
      { id: 'hill-b', dx: -26, dz: 14, r: 4.5 },
      { id: 'hill-c', dx: 10, dz: -20, r: 4 },
      { id: 'tree-a', dx: -10, dz: -10, r: 1.2 },
      { id: 'tree-b', dx: 14, dz: 6, r: 1.2 },
      { id: 'sign', dx: -6, dz: 15.6, w: 1.8, d: 0.4 },
    ],
    tasks: [{ id: 'froopyland', name: 'Find Tommy in Froopyland', hint: 'Dial Froopyland on the portal gun, and get to Tommy past the Froopylanders. They bite.' }],
    say: {
      tommy: { who: 'Tommy', text: 'Beth left me here. I made a life. The Froopylanders are my friends, and also, when it comes to it, my dinner. Tell her I said hi.' },
      froopyriver: { who: null, text: 'A river of honey, slow and gold. Rick made it breathable and the ground bouncy so nothing could ever hurt her here. The creatures came later.' },
      froopysign: { who: null, text: '“FROOPYLAND. Pop. 1 (+ Froopylanders). No Ricks.” In a child’s handwriting, gone over later by a grown man.' },
      froopyhill: { who: null, text: 'A hill of candy pink, soft as a mattress. Beth used to roll down it. Something is watching from the top.' },
    },
    done: { tommy: 'froopyland' },
    caught: 'A Froopylander gets its teeth into your sleeve and the others come running. You bounce, twice, and come down back where the portal is.',
    kinds: ['tommy', 'froopy-a', 'froopy-b'],
  }),
  place(17, {
    id: 'nimbus',
    name: 'Mr. Nimbus’s beach',
    note: 'The shore where the land meets the sea. Mr. Nimbus controls the police, and he’s expecting Rick.',
    kind: 'outdoor',
    deep: 50,
    wide: 70,
    sky: { top: 0x2a7ad8, mid: 0x8ad0f0, low: 0xfff0d0, sun: 0xfff8e8, clouds: 1, moons: 0 },
    people: [
      { id: 'nimbus', dx: 0, dz: -15, face: S, ai: { watch: 14, bark: { r: 7, every: 15, lines: ['Richard. I was told you’d come. I was told wrong, it seems.', 'I am Mr. Nimbus. I control the police. Behave on my beach.', 'Tell your grandfather the treaty stands. For now.'] } } },
      { id: 'atlantean-a', who: 'atlantean', dx: -12, dz: -6, face: E, ai: { wander: [[-12, -6], [-6, -2], [-14, 4], [-20, -4]], speed: 1.1, pause: 2, hunt: { speed: 3.0, catchR: 1.3, near: 4.5, lose: 9 } } },
      { id: 'atlantean-b', who: 'atlantean', dx: 12, dz: -6, face: W, ai: { wander: [[12, -6], [6, -2], [14, 4], [20, -4]], speed: 1.0, pause: 2.5, hunt: { speed: 3.0, catchR: 1.3, near: 4.5, lose: 9 } } },
      { id: 'atlantean-c', who: 'atlantean', dx: 0, dz: -7, face: S, ai: { wander: [[0, -7], [-7, -10], [7, -10]], speed: 0.9, pause: 3, hunt: { speed: 3.0, catchR: 1.3, near: 4.5, lose: 9 } } },
    ],
    spots: [
      { id: 'nimbus', dx: 0, dz: -13.4, label: 'Mr. Nimbus', verb: 'Approach' },
      { id: 'treaty', dx: -4, dz: -14.6, label: 'The treaty', verb: 'Read', r: 1.4 },
      { id: 'shell', dx: 16, dz: 10, label: 'A shell', verb: 'Pick up', r: 1.4 },
      { id: 'sea', dx: 0, dz: -22, label: 'The sea', verb: 'Look', r: 3 },
    ],
    solids: [
      { id: 'throne', dx: 0, dz: -16.6, w: 3.6, d: 2.4 },
      { id: 'rock-a', dx: -22, dz: -12, r: 3 },
      { id: 'rock-b', dx: 24, dz: -14, r: 3.4 },
      { id: 'rock-c', dx: 26, dz: 12, r: 2 },
      { id: 'palm-a', dx: -18, dz: 12, r: 0.5 },
      { id: 'palm-b', dx: 20, dz: 14, r: 0.5 },
    ],
    tasks: [{ id: 'nimbus', name: 'Approach Mr. Nimbus', hint: 'Dial Mr. Nimbus’s beach on the portal gun, and reach his throne past the Atlantean guard. They don’t like anyone near their king.' }],
    say: {
      nimbus: { who: 'Mr. Nimbus', text: '“Richard sends a boy. Of course he does.” He looks you up and down. “Tell him Nimbus remembers. Tell him the ocean remembers. And tell him to call.”' },
      treaty: { who: null, text: 'The treaty, carved on a slab: the land keeps out of the sea, the sea keeps out of the land, and Rick keeps out of the whole thing. Signed with a trident and a flask.' },
      shell: { who: null, text: 'A conch. You hold it to your ear and hear the police being controlled.' },
      sea: { who: null, text: 'The sea, all the way out. Something in it is moving the way a kingdom moves.' },
    },
    done: { nimbus: 'nimbus' },
    caught: 'A spear-butt catches you behind the knee and two Atlanteans march you back up the beach. “Not near the king.”',
    kinds: ['nimbus', 'atlantean'],
  }),
  place(18, {
    id: 'gromflomites',
    name: 'The Gromflomite base',
    note: 'Where the Federation keeps Fart, the being Krombopulos Michael was paid to kill. Guards on every walkway.',
    kind: 'room',
    deep: 36,
    wide: 40,
    ceiling: 9,
    people: [
      { id: 'kmichael', who: 'krombopulos', dx: -16, dz: 12, face: E, ai: { watch: 8, bark: { r: 5, every: 16, lines: ['Shh. Big day. Nobody look at me.', 'The cell’s at the far end. I just need a clear run. Or a boy to make one.'] } } },
      { id: 'guard-a', who: 'gromflomite', dx: -8, dz: 4, face: E, ai: { wander: [[-8, 4], [8, 4], [8, -4], [-8, -4]], speed: 1.5, pause: 0.5, hunt: { speed: 3.2, catchR: 1.3, near: 4.2, lose: 8 } } },
      { id: 'guard-b', who: 'gromflomite', dx: 10, dz: -8, face: W, ai: { wander: [[10, -8], [-10, -8], [-10, -2], [10, -2]], speed: 1.4, pause: 0.5, hunt: { speed: 3.2, catchR: 1.3, near: 4.2, lose: 8 } } },
      { id: 'guard-c', who: 'gromflomite', dx: 14, dz: 8, face: N, ai: { wander: [[14, 8], [14, -12], [4, -12]], speed: 1.3, pause: 1, hunt: { speed: 3.2, catchR: 1.3, near: 4.2, lose: 8 } } },
      { id: 'guard-d', who: 'gromflomite', dx: -14, dz: -10, face: S, ai: { wander: [[-14, -10], [-14, 6], [-4, 10]], speed: 1.3, pause: 1, hunt: { speed: 3.2, catchR: 1.3, near: 4.2, lose: 8 } } },
    ],
    extras: [{ kind: 'fart', dx: 0, dz: -14.6, y: 0.6, face: S, ai: { watch: 12, bark: { r: 5, every: 14, lines: ['Morty. I know your name because I know your mind. Open the cell.', 'Your species is the cancer, Morty. But you, personally, are fine.'] } } }],
    spots: [
      { id: 'kmichael', dx: -16, dz: 12, label: 'Krombopulos Michael', verb: 'Talk' },
      { id: 'fartcell', dx: 0, dz: -12.4, label: 'The cell', verb: 'Open', r: 1.6 },
      { id: 'basescreen', dx: 16.6, dz: -2, label: 'A screen', verb: 'Look', r: 1.6 },
      { id: 'lockers', dx: -17, dz: -2, label: 'The lockers', verb: 'Look', r: 1.8 },
    ],
    solids: [
      { id: 'cell', dx: 0, dz: -15, w: 6, d: 4 },
      { id: 'crate-a', dx: -6, dz: 0, w: 2.6, d: 2.6 },
      { id: 'crate-b', dx: 6, dz: 0, w: 2.6, d: 2.6 },
      { id: 'crate-c', dx: 0, dz: -6, w: 3.2, d: 2 },
      { id: 'crate-d', dx: -12, dz: -6, w: 2, d: 2 },
      { id: 'crate-e', dx: 12, dz: 6, w: 2, d: 2 },
      { id: 'lockers', dx: -18.6, dz: -2, w: 1.2, d: 8 },
    ],
    tasks: [{ id: 'gromflomites', name: 'Open Fart’s cell', hint: 'Dial the Gromflomite base on the portal gun, and reach the cell at the far end without a guard seeing you. Use the crates.' }],
    say: {
      kmichael: { who: 'Krombopulos Michael', text: 'Oh boy. Hi, Morty. Don’t mind me, I’m just here to kill a guy. A gas, technically. Look, if you got the cell open for me I’d be real grateful. I’d owe you a killing.' },
      fartcell: { who: 'Fart', text: 'The lock sings a note and the door slides. “Thank you, Morty.” Across the room, Krombopulos Michael says “Oh boy” and is already running.' },
      basescreen: { who: null, text: 'A screen in the Federation’s script. A face with four eyes, a number counting down, and a crude drawing of Rick with a line through it.' },
      lockers: { who: null, text: 'The guards’ lockers. One holds a blaster, one a lunch, one a photograph of a Gromflomite family on a beach.' },
    },
    done: { fartcell: 'gromflomites' },
    acts: { fartcell: 'opened' },
    caught: 'A Gromflomite’s four eyes meet yours. “Intruder!” The blaster’s set to stun, and you come round by the door with a headache.',
    kinds: ['krombopulos', 'gromflomite', 'fart'],
  }),
  place(19, {
    id: 'heistcon',
    name: 'Heist-Con',
    note: 'The convention for heist crews. Miles Knightly is assembling one, and Heistotron is at the keynote.',
    kind: 'room',
    deep: 34,
    wide: 44,
    ceiling: 8,
    people: [
      { id: 'miles', dx: -8, dz: -8, face: S, ai: { watch: 9, bark: { r: 6, every: 16, lines: ['You look like a kid who could be a crew member. Everybody’s somebody’s crew member.', 'The heist of the century, and it’s this: the heist is the con. The con is the heist.'] } } },
      { id: 'heister-a1', who: 'heister-a', dx: 6, dz: 2, face: W, ai: { wander: [[6, 2], [12, 6], [4, 8]], speed: 0.8, pause: 4 } },
      { id: 'heister-b1', who: 'heister-b', dx: -12, dz: 4, face: E, ai: { wander: [[-12, 4], [-6, 8], [-15, 9]], speed: 0.9, pause: 3 } },
    ],
    extras: [
      { kind: 'heister-a', dx: 14, dz: -6, face: W, ai: { wander: [[14, -6], [10, -2], [16, 0]], speed: 0.7, pause: 5 } },
      { kind: 'heister-b', dx: -16, dz: -4, face: E, ai: { wander: [[-16, -4], [-12, 0], [-18, 2]], speed: 0.7, pause: 5 } },
      { kind: 'heister-a', dx: 2, dz: 10, face: N },
      { kind: 'heister-b', dx: -4, dz: 10, face: N },
      { kind: 'heistotron', dx: 0, dz: -12.6, face: S },
    ],
    spots: [
      { id: 'miles', dx: -8, dz: -6.4, label: 'Miles Knightly', verb: 'Talk' },
      { id: 'heister-a1', dx: 6, dz: 2, label: 'A heister', verb: 'Recruit', r: 1.6 },
      { id: 'heister-b1', dx: -12, dz: 4, label: 'A cat burglar', verb: 'Recruit', r: 1.6 },
      { id: 'heistotron', dx: 0, dz: -9, label: 'Heistotron', verb: 'Look', r: 2 },
      { id: 'heistbooth', dx: 14, dz: 10, label: 'A booth', verb: 'Look', r: 1.8 },
      { id: 'heistbadge', dx: -8, dz: 11.4, label: 'The badge table', verb: 'Take a badge', r: 1.6 },
    ],
    solids: [
      { id: 'stage', dx: 0, dz: -14, w: 14, d: 4 },
      { id: 'booth-a', dx: 15, dz: 12, w: 4, d: 2 },
      { id: 'booth-b', dx: -15, dz: 12, w: 4, d: 2 },
      { id: 'booth-c', dx: 17, dz: -10, w: 2, d: 4 },
      { id: 'booth-d', dx: -17, dz: -10, w: 2, d: 4 },
      { id: 'badges', dx: -8, dz: 13, w: 3, d: 1 },
    ],
    tasks: [{ id: 'heistcon', name: 'Assemble a crew', hint: 'Dial Heist-Con on the portal gun, take a badge, and recruit two heisters for Miles Knightly.' }],
    say: {
      miles: { who: 'Miles Knightly', text: '“Kid. You in?” He doesn’t wait. “Get me a muscle and a cat burglar and we’ve got the start of something. Then we double-cross everyone. That’s the job.”' },
      'heister-a1': { who: 'A heister', text: '“Muscle? Sure. I lift things. Sometimes they’re safes.” He hands you a card. It just says MUSCLE.' },
      'heister-b1': { who: 'A cat burglar', text: '“Lasers, vents, roofs. I’m in if Knightly’s in. Tell him I want a bigger cut than last time.”' },
      heistotron: { who: null, text: 'Heistotron. A robot built to plan heists. Rick built it to beat Miles, then it heisted Rick’s plan to heist it. It’s giving the keynote.' },
      heistbooth: { who: null, text: 'A booth selling grappling hooks, glass cutters and a book called “Your Crew And You”. Everything is stolen as you watch.' },
      heistbadge: { who: null, text: 'A badge: HELLO MY NAME IS and a blank. You write MORTY, and somebody steals the pen.' },
    },
    collect: { task: 'heistcon', spots: ['heistbadge', 'heister-a1', 'heister-b1'] },
    goal: 'heistbadge',
    kinds: ['miles', 'heister-a', 'heister-b', 'heistotron'],
  }),
  place(20, {
    id: 'snakeplanet',
    name: 'Snake Planet',
    note: 'A planet of snakes, with a space programme. Everything here is a snake, and most of them bite.',
    kind: 'outdoor',
    deep: 50,
    wide: 70,
    sky: { top: 0x5a3a8a, mid: 0xc87a6a, low: 0xf2c890, sun: 0xffe0b0, clouds: 0, moons: 1 },
    extras: [
      { kind: 'snakeastronaut', dx: 14, dz: -14, face: S, ai: { watch: 8, bark: { r: 5, every: 15, lines: ['Hsss. (It salutes with its tail, which is also the rest of it.)', 'Hssssss. Hss. (The launch is in an hour. Nobody is allowed near the rocket.)'] } } },
      { kind: 'snake-a', dx: -8, dz: 2, face: E, ai: { wander: [[-8, 2], [-2, 6], [-12, 8], [-14, 0]], speed: 1.4, pause: 1, hunt: { speed: 3.4, catchR: 1.1, near: 5, lose: 9 } } },
      { kind: 'snake-b', dx: 6, dz: 8, face: W, ai: { wander: [[6, 8], [12, 12], [2, 14], [-2, 8]], speed: 1.3, pause: 1, hunt: { speed: 3.4, catchR: 1.1, near: 5, lose: 9 } } },
      { kind: 'snake-a', dx: 4, dz: -4, face: S, ai: { wander: [[4, -4], [10, -2], [8, 4], [-2, -2]], speed: 1.5, pause: 0.8, hunt: { speed: 3.6, catchR: 1.1, near: 5.5, lose: 9 } } },
      { kind: 'snake-b', dx: -18, dz: -8, face: E, ai: { wander: [[-18, -8], [-12, -12], [-22, -14], [-25, -4]], speed: 1.2, pause: 1.5, hunt: { speed: 3.3, catchR: 1.1, near: 5, lose: 9 } } },
      { kind: 'snake-a', dx: 20, dz: 4, face: W, ai: { wander: [[20, 4], [24, 10], [16, 12], [14, 4]], speed: 1.3, pause: 1.2, hunt: { speed: 3.4, catchR: 1.1, near: 5, lose: 9 } } },
      { kind: 'snakerocket', dx: 12, dz: -17, face: S },
    ],
    spots: [
      { id: 'snakerocket', dx: 12, dz: -14.4, label: 'The snake rocket', verb: 'Touch', r: 1.8 },
      { id: 'snakeastronaut', dx: 14, dz: -12.4, label: 'A snake astronaut', verb: 'Salute', r: 1.6 },
      { id: 'snakesign', dx: -6, dz: 14, label: 'A sign', verb: 'Read', r: 1.6 },
      { id: 'snakehole', dx: -20, dz: 12, label: 'A hole', verb: 'Look', r: 1.8 },
    ],
    solids: [
      { id: 'rocket', dx: 12, dz: -17, r: 2.4 },
      { id: 'pad', dx: 18, dz: -18, w: 6, d: 4 },
      { id: 'rock-a', dx: -24, dz: -12, r: 3 },
      { id: 'rock-b', dx: 26, dz: 10, r: 2.6 },
      { id: 'rock-c', dx: -6, dz: -16, r: 2.2 },
      { id: 'sign', dx: -6, dz: 15.6, w: 1.8, d: 0.4 },
    ],
    tasks: [{ id: 'snakeplanet', name: 'Reach the snake rocket', hint: 'Dial Snake Planet on the portal gun, and get to the rocket on the far side without being bitten. The snakes strike when you come close.' }],
    say: {
      snakerocket: { who: null, text: 'The snakes’ rocket, cold to the touch, no bigger than a van. A snake is going to the moon in it, and Morty is the reason there will be a snake war. Not yet.' },
      snakeastronaut: { who: 'A snake astronaut', text: 'Hssss. (It bows its helmet. You have been accepted, provisionally, into the snake space programme.)' },
      snakesign: { who: null, text: 'A sign in snake: a long wavy line and a dot. It probably says “Welcome” or “Keep off the grass”. It’s hard to tell with snakes.' },
      snakehole: { who: null, text: 'A hole in the ground, and in the hole, eyes. Many eyes. Something hisses the snake word for “later”.' },
    },
    done: { snakerocket: 'snakeplanet' },
    caught: 'Fangs, in the ankle. The world goes green at the edges, and you come round back where you started with two small holes in your sock.',
    kinds: ['snake-a', 'snake-b', 'snakeastronaut', 'snakerocket'],
  }),
  place(21, {
    id: 'nuptia',
    name: 'Nuptia 4',
    note: 'The couples’ retreat on a cliff over the clouds. The machine reads what you think of each other, and makes it.',
    kind: 'outdoor',
    deep: 50,
    wide: 70,
    sky: { top: 0x6a4ab8, mid: 0xd8a0d8, low: 0xffe0c0, sun: 0xfff0e0, clouds: 1, moons: 2 },
    people: [
      { id: 'glexo', dx: 0, dz: -12, face: S, ai: { watch: 10, bark: { r: 6, every: 16, lines: ['Welcome to Nuptia 4. Love is a scan, and a scan is a thing that can be made.', 'We ask every couple one question: what do you see when you look at each other? Then we show them.'] } } },
      { id: 'nbeth', who: 'beth', dx: -10, dz: 2, face: E, ai: { wander: [[-10, 2], [-6, 5], [-12, 7]], speed: 0.7, pause: 5, bark: { r: 4, every: 18, lines: ['Morty? What are you doing here? Don’t tell your father I said anything about him.'] } } },
      { id: 'njerry', who: 'jerry', dx: -8, dz: 2, face: W, ai: { wander: [[-8, 2], [-4, 5], [-10, 7]], speed: 0.7, pause: 5, bark: { r: 4, every: 18, lines: ['Morty! Your mother and I are doing great. The machine said so. Mostly.'] } } },
    ],
    extras: [
      { kind: 'mytholog', dx: 16, dz: -4, face: W, ai: { wander: [[16, -4], [22, 2], [14, 8], [10, 0]], speed: 1.1, pause: 1.5, hunt: { speed: 3.0, catchR: 1.4, near: 5.5, lose: 10 } } },
      { kind: 'mytholog', dx: -20, dz: -8, face: E, ai: { wander: [[-20, -8], [-26, -2], [-18, 4], [-14, -6]], speed: 1.0, pause: 2, hunt: { speed: 3.0, catchR: 1.4, near: 5.5, lose: 10 } } },
      { kind: 'nuptiamachine', dx: 6, dz: -14, face: S },
    ],
    spots: [
      { id: 'glexo', dx: 0, dz: -10.4, label: 'Glexo Slim Slom', verb: 'Talk' },
      { id: 'nuptiamachine', dx: 6, dz: -11.4, label: 'The machine', verb: 'Sit in', r: 1.8 },
      { id: 'nuptiaedge', dx: 0, dz: -20, label: 'The edge', verb: 'Look', r: 2.4 },
      { id: 'nbeth', dx: -10, dz: 2, label: 'Beth', verb: 'Talk', r: 1.6 },
      { id: 'njerry', dx: -8, dz: 2, label: 'Jerry', verb: 'Talk', r: 1.6 },
    ],
    solids: [
      { id: 'machine', dx: 6, dz: -14, w: 4, d: 3 },
      { id: 'dais', dx: 0, dz: -13.4, r: 1.6 },
      { id: 'pillar-a', dx: -12, dz: -16, r: 0.8 },
      { id: 'pillar-b', dx: 12, dz: -16, r: 0.8 },
      { id: 'pillar-c', dx: -24, dz: 10, r: 0.8 },
      { id: 'pillar-d', dx: 24, dz: 10, r: 0.8 },
    ],
    tasks: [{ id: 'nuptia', name: 'Take the test on Nuptia 4', hint: 'Dial Nuptia 4 on the portal gun, talk to Glexo Slim Slom, and sit in the machine. Keep away from the mythologs: they’re other couples’ problems.' }],
    say: {
      glexo: { who: 'Glexo Slim Slom', text: '“A child. The machine will scan you alone, then. Sit, and think of whoever you think of.” He gestures at the pod. The mythologs on the lawn turn their heads.' },
      nuptiamachine: { who: null, text: 'You sit, and the helmet comes down. You think of Rick. The readout says: TALL. UNRELIABLE. YOURS. Glexo nods like that’s normal.' },
      nuptiaedge: { who: null, text: 'The cliff drops into cloud. Down there is where the machine’s monsters go when a couple leaves. Some couples leave fast.' },
      nbeth: { who: 'Beth', text: 'We’re trying, Morty. The machine made a thing of what I think of your father. It had a lot of teeth. We’re working through it.' },
      njerry: { who: 'Jerry', text: 'Mine was a… it was a kind of worm with a crown? Your mother says that’s on me.' },
    },
    collect: { task: 'nuptia', spots: ['glexo', 'nuptiamachine'] },
    goal: 'glexo',
    caught: 'A mytholog folds you into its cold wet arms and sets you down, gently, back where the portal is. It wasn’t about you.',
    kinds: ['glexo', 'beth', 'jerry', 'mytholog', 'nuptiamachine'],
  }),
  place(22, {
    id: 'gloopynoops',
    name: 'St. Gloopy Noops',
    note: 'The hospital in space. Shrimply Pibbles is dying, and the galaxy’s doctors want something of Jerry’s.',
    kind: 'room',
    deep: 34,
    wide: 44,
    ceiling: 6,
    people: [
      { id: 'glipglop', dx: 4, dz: -6, face: S, ai: { wander: [[4, -6], [10, -4], [8, 2], [0, -2]], speed: 0.9, pause: 4, watch: 7, bark: { r: 5, every: 16, lines: ['The Jerry’s with you? Good. We just need a small part of him. Trust me, I’m Dr. Glip-Glop.', 'Shrimply Pibbles freed a billion people. Jerry Smith watched a lot of television. Weigh it.'] } } },
      { id: 'gjerry', who: 'jerry', dx: -12, dz: 4, face: E, ai: { watch: 6, bark: { r: 4, every: 16, lines: ['Morty, they want my… they want a thing. I said I’d think about it. Tell them I’m still thinking.'] } } },
    ],
    extras: [
      { kind: 'gloopnurse', dx: -4, dz: 6, face: N, ai: { wander: [[-4, 6], [-10, 10], [6, 10], [2, 4]], speed: 0.8, pause: 3 } },
      { kind: 'gloopnurse', dx: 14, dz: -10, face: W, ai: { wander: [[14, -10], [14, 6], [8, 8]], speed: 0.7, pause: 4 } },
      { kind: 'shrimply', dx: 0, dz: -13, face: S },
    ],
    spots: [
      { id: 'glipglop', dx: 4, dz: -6, label: 'Dr. Glip-Glop', verb: 'Talk', r: 1.6 },
      { id: 'shrimply', dx: 0, dz: -10.6, label: 'Shrimply Pibbles', verb: 'Visit', r: 1.8 },
      { id: 'gjerry', dx: -12, dz: 4, label: 'Jerry', verb: 'Talk', r: 1.6 },
      { id: 'reception', dx: 12, dz: 12, label: 'Reception', verb: 'Ask', r: 1.8 },
      { id: 'vending', dx: -18, dz: 12, label: 'A vending machine', verb: 'Look', r: 1.6 },
    ],
    solids: [
      { id: 'bed', dx: 0, dz: -13.6, w: 3, d: 4 },
      { id: 'reception', dx: 12, dz: 14, w: 5, d: 1.4 },
      { id: 'vending', dx: -19.5, dz: 12, w: 1.2, d: 1.6 },
      { id: 'bench-a', dx: -12, dz: 6, w: 3, d: 1 },
      { id: 'bench-b', dx: -6, dz: 14, w: 3, d: 1 },
      { id: 'cart', dx: 8, dz: -2, w: 1.2, d: 1.6 },
    ],
    tasks: [{ id: 'gloopynoops', name: 'Visit Shrimply Pibbles', hint: 'Dial St. Gloopy Noops on the portal gun, ask at reception, and visit Shrimply Pibbles in his bed.' }],
    say: {
      glipglop: { who: 'Dr. Glip-Glop', text: '“The boy. Good. Your father is being very brave, by which I mean he hasn’t run yet.” He checks a clipboard that is also a screen. “Visiting hours are now.”' },
      shrimply: { who: 'Shrimply Pibbles', text: 'A soft voice from the bed. “Child. Whatever your father decides, tell him I understand. I have been many things to many people. I can be one more.”' },
      gjerry: { who: 'Jerry', text: '“I keep saying I’m thinking about it and they keep nodding. I don’t know how to say no to a hero, Morty. I don’t know how to say no to anyone.”' },
      reception: { who: 'The receptionist', text: '“Pibbles? Room one. Everyone’s here for Pibbles.” She points down the ward without looking up.' },
      vending: { who: null, text: 'A vending machine. Row C is Jerry Smith branded, already. Somebody was confident.' },
    },
    collect: { task: 'gloopynoops', spots: ['reception', 'shrimply'] },
    goal: 'reception',
    kinds: ['glipglop', 'jerry', 'gloopnurse', 'shrimply'],
  }),
  place(23, {
    id: 'resort',
    name: 'The Immortality Field Resort',
    note: 'A resort where nobody can die, inside the field. Risotto Groupon runs it, and he has plans for Rick.',
    kind: 'outdoor',
    deep: 50,
    wide: 70,
    sky: { top: 0x2a8ad8, mid: 0x9ad8f8, low: 0xffe8c0, sun: 0xfff8e8, clouds: 1, moons: 0 },
    people: [{ id: 'risotto', dx: 0, dz: -8, face: S, ai: { wander: [[0, -8], [6, -6], [-6, -6]], speed: 0.6, pause: 6, watch: 9, bark: { r: 6, every: 16, lines: ['Welcome to the Immortality Field Resort. Inside the field, nothing can hurt you. Outside it, everything can.', 'Your grandfather took my kingdom. I don’t hold it against you. I hold it against him, quite hard.'] } } }],
    extras: [
      { kind: 'resortguest-a', dx: -6, dz: 10, face: E, ai: { wander: [[-6, 10], [-2, 6], [-8, 14]], speed: 0.6, pause: 5 } },
      { kind: 'resortguest-b', dx: 10, dz: 6, face: W, ai: { wander: [[10, 6], [16, 10], [6, 12]], speed: 0.7, pause: 4 } },
      { kind: 'resortguest-a', dx: 18, dz: -2, face: W },
      { kind: 'resortguest-b', dx: -20, dz: -4, face: E },
      { kind: 'dirlycar', dx: 14, dz: -16, face: W },
    ],
    spots: [
      { id: 'risotto', dx: 0, dz: -6.4, label: 'Risotto Groupon', verb: 'Talk' },
      { id: 'dirly', dx: 14, dz: -13.4, label: 'The Whirly Dirly', verb: 'Ride', r: 1.8 },
      { id: 'fieldpost', dx: -16, dz: -16, label: 'The field generator', verb: 'Look', r: 2 },
      { id: 'poolbar', dx: -14, dz: -1.6, label: 'The pool bar', verb: 'Order', r: 2 },
    ],
    solids: [
      { id: 'dirlycar', dx: 14, dz: -16, w: 3, d: 2 },
      { id: 'dirly-pylon-a', dx: 20, dz: -20, r: 0.6 },
      { id: 'dirly-pylon-b', dx: 8, dz: -22, r: 0.6 },
      { id: 'generator', dx: -16, dz: -18.4, r: 1.6 },
      { id: 'pool', dx: -14, dz: 4, w: 12, d: 6 },
      { id: 'bar', dx: -14, dz: -1.6, w: 5, d: 1.2 },
      { id: 'palm-a', dx: 22, dz: 8, r: 0.5 },
      { id: 'palm-b', dx: -26, dz: 2, r: 0.5 },
    ],
    tasks: [{ id: 'resort', name: 'Ride the Whirly Dirly', hint: 'Dial the Immortality Field Resort on the portal gun, talk to Risotto Groupon, and ride the Whirly Dirly. Part of it leaves the field.' }],
    say: {
      risotto: { who: 'Risotto Groupon', text: '“The grandson. Welcome. Enjoy the resort. The Whirly Dirly is our pride, and for a few seconds at the top it leaves the field. Do tell your grandfather to ride it.”' },
      dirly: { who: null, text: 'The car climbs, the field’s shimmer falls behind, and for three seconds at the top anything could kill you. Nothing does. You come down screaming anyway.' },
      fieldpost: { who: null, text: 'The field generator, a column of humming blue rings. Inside the field’s edge nothing dies, and the guests know exactly where the edge is.' },
      poolbar: { who: 'The bartender', text: '“A drink for a kid? It’s an immortality resort. Have whatever you want.” You have a lemonade. It’s the best lemonade you’ve ever had, forever.' },
    },
    collect: { task: 'resort', spots: ['risotto', 'dirly'] },
    goal: 'risotto',
    kinds: ['risotto', 'resortguest-a', 'resortguest-b', 'dirlycar'],
  }),
  place(24, {
    id: 'schwifty',
    name: 'The Get Schwifty show',
    note: 'The Cromulons want a hit, or Earth’s gone. Water-T is on the bill, and Ice-T is on the ice.',
    kind: 'outdoor',
    deep: 50,
    wide: 70,
    sky: { top: 0x1a1a4a, mid: 0x4a3a8a, low: 0xd86a4a, sun: 0xffb060, clouds: 0, moons: 0 },
    people: [{ id: 'watert', dx: -4, dz: -12, face: S, ai: { watch: 10, bark: { r: 6, every: 15, lines: ['You here to play, little man? The heads want a song. Give the heads a song.', 'My father was a block of ice. I became water. We all become something.'] } } }],
    extras: [
      { kind: 'cromulon', dx: 0, dz: -60, face: S, y: 10, h: 24, ai: { watch: 80, bark: { r: 70, every: 20, lines: ['SHOW ME WHAT YOU GOT.', 'I LIKE WHAT YOU GOT. GOOD JOB.', 'DISQUALIFIED.'] } } },
      { kind: 'cromulon', dx: -40, dz: -56, face: S + 0.3, y: 10, h: 24 },
      { kind: 'cromulon', dx: 40, dz: -58, face: S - 0.3, y: 10, h: 24 },
      { kind: 'icet', dx: 8, dz: -13, face: S },
    ],
    spots: [
      { id: 'watert', dx: -4, dz: -10.4, label: 'Water-T', verb: 'Talk' },
      { id: 'mic', dx: 0, dz: -9.4, label: 'The mic', verb: 'Get schwifty', r: 1.6 },
      { id: 'icet', dx: 8, dz: -10.6, label: 'Ice-T', verb: 'Look', r: 1.8 },
      { id: 'heads', dx: 0, dz: -20, label: 'The Cromulons', verb: 'Look', r: 3 },
      { id: 'amps', dx: -12, dz: -11, label: 'The amps', verb: 'Look', r: 1.8 },
    ],
    solids: [
      { id: 'stage', dx: 0, dz: -14, w: 30, d: 6 },
      { id: 'amp-a', dx: -12, dz: -13, w: 2, d: 1.6 },
      { id: 'amp-b', dx: 12, dz: -13, w: 2, d: 1.6 },
      { id: 'tower-a', dx: -20, dz: -16, r: 0.8 },
      { id: 'tower-b', dx: 20, dz: -16, r: 0.8 },
    ],
    tasks: [{ id: 'schwifty', name: 'Get schwifty', hint: 'Dial the Get Schwifty show on the portal gun, talk to Water-T, and take the mic. The heads are watching.' }],
    say: {
      watert: { who: 'Water-T', text: '“The mic’s yours, kid. Don’t think. Nobody who ever thought about it got schwifty.” He nods at the heads filling the sky.' },
      mic: { who: null, text: 'You take the mic. You don’t think. “Oh yeah, you gotta get schwifty…” The heads lean in. One of them says, slowly, “I LIKE WHAT YOU GOT.”' },
      icet: { who: null, text: 'Ice-T, in his true form: a block of ice shaped like a T. He’s not cold. He says he just doesn’t care, and the ice says it for him.' },
      heads: { who: null, text: 'Three heads the size of towns hang in the sky, their mouths open. One is humming. If they don’t like the song, the planet goes.' },
      amps: { who: null, text: 'The amps go to eleven, then to a number that isn’t one. Rick wired them. Somebody has written “schwifty” on one in marker.' },
    },
    collect: { task: 'schwifty', spots: ['watert', 'mic'] },
    goal: 'watert',
    kinds: ['watert', 'cromulon', 'icet'],
  }),
  place(25, {
    id: 'evilrick',
    name: 'Evil Rick’s lair',
    note: 'The dimension where a Rick with a scar wired up a dome of Mortys to hide his brainwaves. Somebody’s behind him.',
    kind: 'room',
    deep: 40,
    wide: 44,
    ceiling: 10,
    people: [
      // Evil Rick at his console till the Mortys are freed; then he comes for Morty, and the fight is the thing
      { id: 'evilrick', dx: 0, dz: -12, face: S, ai: { watch: 12, bark: { r: 9, every: 14, lines: ['Another Morty. I’ve got hundreds. What’s one more?', 'Your Rick thinks he’s the smartest man in the universe. He isn’t even the smartest in this room.'] }, hunt: { speed: 2.4, catchR: 1.6, duel: { hp: 6, mortyHp: 3, task: 'evilrick', won: { who: 'Evil Rick', text: 'He goes down by his own console, and his eye flickers. A receiver, behind the ear. He was never the one in charge.' } }, line: 'Evil Rick’s fist finds your jaw. “Sit down, Morty. There’s a slot in the dome with your name on it.” You come round by the door.' } } },
      // Evil Morty, sitting in his chair at the back with his arms crossed, till he's spoken to
      { id: 'evilmorty', dx: 14, dz: -14, face: W, until: 'evilmorty', ai: { clip: 'sitcross', bark: { r: 6, every: 18, lines: ['(He watches you fight. He doesn’t get up.)', '(He says nothing. He’s counting something.)'] } } },
    ],
    // (the dome's Mortys in their pods are placed by the builder, which frees them one by one)
    spots: [
      { id: 'pod1', dx: -15.4, dz: -8, label: 'A Morty in a pod', verb: 'Free', r: 1.4 },
      { id: 'pod2', dx: -15.4, dz: -2, label: 'A Morty in a pod', verb: 'Free', r: 1.4 },
      { id: 'pod3', dx: -15.4, dz: 4, label: 'A Morty in a pod', verb: 'Free', r: 1.4 },
      { id: 'evilrick', dx: 0, dz: -10.4, label: 'Evil Rick', verb: 'Face him', r: 1.6 },
      { id: 'evilmorty', dx: 12.4, dz: -14, label: 'A Morty with an eyepatch', verb: 'Talk', r: 1.6, until: 'evilmorty' },
      { id: 'domewall', dx: 0, dz: -16, label: 'The dome', verb: 'Look', r: 2.4 },
      { id: 'scarconsole', dx: 4, dz: -12.4, label: 'His console', verb: 'Look', r: 1.6 },
    ],
    solids: [
      { id: 'console', dx: 0, dz: -14, w: 7, d: 1.6 },
      { id: 'chair', dx: 14.6, dz: -14, w: 1.2, d: 1.2 },
      ...[-8, -2, 4].map((dz) => ({ id: `podw${dz}`, dx: -17.6, dz, w: 1.6, d: 2.4 })),
      ...[2, 8].map((dz) => ({ id: `pode${dz}`, dx: 17.6, dz, w: 1.6, d: 2.4 })),
      { id: 'crate-a', dx: -6, dz: 6, w: 2.4, d: 2.4 },
      { id: 'crate-b', dx: 7, dz: 4, w: 2, d: 2 },
    ],
    tasks: [
      { id: 'evilrick', name: 'Beat Evil Rick', hint: 'Dial Evil Rick’s lair on the portal gun, free three Mortys from the dome, and when he comes for you, fight: F fires, and he hits hard. Keep moving.' },
      { id: 'evilmorty', name: 'Find out who was behind him', hint: 'Once Evil Rick is down, talk to the Morty with the eyepatch before he leaves.' },
    ],
    say: {
      pod1: { who: null, text: 'You pull the plug and the Morty slumps out, blinking. “Th-thanks. Which one are you?” Behind you, Evil Rick looks up from the console.' },
      pod2: { who: null, text: 'Another plug, another Morty. He hugs you and runs for the door. Evil Rick is standing now.' },
      pod3: { who: null, text: 'The third plug. The dome goes dark, and a thousand Mortys sigh at once. Evil Rick says, quietly, “That was mine,” and starts towards you.' },
      evilrick: { who: 'Evil Rick', text: '“Hundreds of Mortys. Every one of them a little bit of camouflage. You think you’re different, kid? You’re a slot in the wall.”' },
      evilmorty: { who: 'The Morty with the eyepatch', text: 'He takes the eyepatch off. Behind it, a perfectly good eye. “He was a puppet. They all are.” A yellow portal opens behind him. “Tell your Rick I’m not done.” He steps through, and the chair is empty.' },
      domewall: { who: null, text: 'The dome: hundreds of Mortys in pods, wired by the head, their brainwaves cancelling a Rick’s. Three pods have plugs you can reach.' },
      scarconsole: { who: null, text: 'His console, keyed to his hand. A screen tracks every Rick in the Citadel. One Rick, C-137, is circled in red. Twice.' },
    },
    collect: { task: 'evilrick', spots: ['pod1', 'pod2', 'pod3'], start: true },
    done: { evilmorty: 'evilmorty' },
    unlock: {},
    acts: { pod1: 'freed1', pod2: 'freed2', pod3: 'freed3', evilmorty: 'leave' },
    goal: 'pod1',
    caught: 'Evil Rick’s fist finds your jaw. You come round by the door, and he’s back at his console as if you’d never got up.',
    kinds: ['evilrick', 'evilmorty', 'mortyclone'],
  }),
];

export const destinationById = (id) => DESTINATIONS.find((d) => d.id === id) ?? null;

// ── the dial ──

export const DIAL = [{ id: 'annex', name: 'Blips and Chitz', note: 'An arcade on an alien street. Roy: A Life Well Lived is in the back.' }, ...DESTINATIONS.map(({ id, name, note }) => ({ id, name, note }))];
export const DIAL_KEY = 'tp-rm-dial';
export const portalTarget = (dial) => (DIAL.some((d) => d.id === dial) ? dial : 'annex');
export function readDial() {
  try {
    return portalTarget(localStorage.getItem(DIAL_KEY));
  } catch {
    return 'annex';
  }
}
export function writeDial(id) {
  try {
    localStorage.setItem(DIAL_KEY, portalTarget(id));
  } catch {
    /* (private mode: the dial lasts the visit) */
  }
}

// the garage portal, sent where the dial is set; any other link as it is
export function linkTarget(link, dial) {
  if (link.id !== 'garage-portal') return link;
  const d = destinationById(portalTarget(dial));
  return d ? { ...link, to: d.id, label: `Through the portal to ${d.name}`, arrive: d.arrive } : link;
}

// a saved spot, if it's still somewhere Morty can be: in a built-in area, or
// in a destination (whatever the dial says now: the way home's there), else
// the garage, where the portal is
export function validArrive(saved, areas) {
  const a = saved && areas[saved.area];
  if (a && saved.x >= a.x0 && saved.x <= a.x1 && saved.z >= a.z0 && saved.z <= a.z1) return { area: saved.area, x: saved.x, z: saved.z, face: saved.face ?? 0 };
  return { area: 'garage', ...GARAGE_BACK };
}
