// The portal gun's dial, rows 13 to 24: the simulation to the Get Schwifty show (./destinations.js joins the three files; ./place.js says what each field is).

import { E, N, S, W, place } from './place';

export const ROWS = [
  place(13, {
    id: 'simulation',
    name: 'The Zigerions’ simulation',
    note: 'A copy of the Smiths’ street, run by the Zigerions to get Rick’s recipe. They’ve cut corners.',
    kind: 'room',
    deep: 40,
    wide: 56,
    ceiling: 9,
    people: [
      { id: 'nebulon', dx: 0, dz: -17.4, y: 3.2, face: S, ai: { watch: 30, bark: { r: 9, every: 20, lines: ['Act natural down there. Nothing is wrong with the street.', 'The recipe, Morty. Concentrated dark matter. Just say it out loud, to no one.'] } } },
      { id: 'zig-console-a', who: 'zigerion-b', dx: -7, dz: -17.6, y: 3.2, face: S, ai: { hunt: { speed: 2.7, catchR: 1.2 } } },
      { id: 'zig-console-b', who: 'zigerion-c', dx: 7, dz: -17.6, y: 3.2, face: S, ai: { hunt: { speed: 2.5, catchR: 1.2 } } },
    ],
    extras: [
      // the two men, the same man, out for the same walk, a step apart
      { kind: 'simman', dx: -0.8, dz: 5.6, face: W, ai: { wander: [[-0.8, 5.6], [-9, 5.6], [-9, 12], [6, 12], [6, 5.6]], speed: 1.0, pause: 0.5 } },
      { kind: 'simman', dx: 0.8, dz: 5.6, face: W, ai: { wander: [[0.8, 5.6], [-7.4, 5.6], [-7.4, 12], [7.6, 12], [7.6, 5.6]], speed: 1.0, pause: 0.5 } },
      // the pop-tart at his toaster's door, waving
      { kind: 'poptart', dx: 17, dz: 8.2, face: N, ai: { watch: 9, bark: { r: 5, every: 15, lines: ['Hi! I live in a toaster!', 'Nice day. It’s always a nice day.'] } } },
      { kind: 'toasterhouse', dx: 17, dz: 10.6, face: N },
    ],
    spots: [
      { id: 'twins', dx: 0, dz: 4, label: 'Two men, the same man', verb: 'Look', r: 1.8 },
      { id: 'poptart', dx: 17, dz: 7, label: 'A pop-tart in a toaster', verb: 'Look', r: 1.8 },
      { id: 'sun', dx: 24.6, dz: -4, label: 'The sun', verb: 'Look', r: 2 },
      { id: 'simhouse', dx: -12, dz: -3.4, label: 'The Smiths’ house', verb: 'Look', r: 1.8 },
      { id: 'nebulon', dx: 0, dz: -13.6, label: 'Prince Nebulon', verb: 'Call up', r: 1.8 },
      { id: 'consoles', dx: 7, dz: -13.6, label: 'The consoles', verb: 'Look', r: 1.8 },
    ],
    solids: [
      { id: 'walkway', dx: 0, dz: -17.6, w: 56, d: 4.8 },
      { id: 'simhouse', dx: -12, dz: -8.6, w: 10, d: 8 },
      { id: 'simhouse-b', dx: 12, dz: -8.6, w: 9, d: 7 },
      { id: 'toaster', dx: 17, dz: 10.6, w: 4.4, d: 3.4 },
    ],
    tasks: [{ id: 'simulation', name: 'Spot the simulation', hint: 'Dial the Zigerions’ simulation on the portal gun, find three things they got wrong, and get back through the portal before the Zigerions get to you.' }],
    say: {
      twins: { who: null, text: 'Two men walking the same way, the same face, the same step. One of them says “Hello” and the other one says it too. Slip one.' },
      poptart: { who: null, text: 'A pop-tart, living in a toaster. He waves. Nobody in the real street does that. Slip two.' },
      sun: { who: null, text: 'The sun is a yellow disc painted on the wall. It hasn’t moved all day. Slip three. Somewhere above you, somebody says “Shut it down.”' },
      simhouse: { who: null, text: 'The Smiths’ house, in two colours, with the windows painted on. The door doesn’t open.' },
      nebulon: { who: 'Prince Nebulon', text: 'Is it the kid? Of course it’s the kid. We don’t have the processing power for a Rick. Just act natural down there and tell us the recipe for concentrated dark matter.' },
      consoles: { who: null, text: 'Two Zigerions at the consoles, running the street. One of them is scrolling. The other is asleep.' },
    },
    collect: { task: 'simulation', spots: ['twins', 'poptart', 'sun'], escape: { s: 45 } },
    caught: 'Four hands close on your shoulders. “Got him, your highness.” The simulation reloads round you, and you’re back at the start of the street.',
    goal: 'twins',
    kinds: ['nebulon', 'zigerion-b', 'zigerion-c', 'simman', 'poptart', 'toasterhouse'],
  }),
  place(14, {
    id: 'storytrain',
    name: 'The Story Train',
    note: 'A carriage on the Story Train, the anthology going past the windows. Someone wants to see your ticket.',
    kind: 'room',
    deep: 30,
    wide: 10,
    ceiling: 3.4,
    people: [
      { id: 'storylord', dx: 0, dz: -13, face: S, ai: { wander: [[0, -13], [1.2, -12.2], [-1.2, -12.2]], speed: 0.5, pause: 4, watch: 8, bark: { r: 5, every: 18, lines: ['Give me a beat, Morty. Any beat. A character wants something.', 'This carriage is Act Two. Nothing ever happens in Act Two.'] } } },
      { id: 'ticketsguy', dx: 0, dz: -3, face: S, ai: { watch: 6, hunt: { speed: 0.85, catchR: 1.3, always: true, until: 'storytrain', line: '“Tickets, please.” You haven’t got one. He takes you by the ear and walks you to the back of the carriage.' } } },
    ],
    spots: [
      { id: 'storylord', dx: 0, dz: -11.4, label: 'Story Lord', verb: 'Talk' },
      { id: 'ticketsguy', dx: 0, dz: -1.6, label: 'The conductor', verb: 'Talk' },
      { id: 'trainticket', dx: 2.2, dz: 6.6, label: 'Something under the seat', verb: 'Reach for', r: 1.2 },
      { id: 'trainwindow', dx: -3.4, dz: 1, label: 'The window', verb: 'Look', r: 1.4 },
      { id: 'routemap', dx: 1.6, dz: -7.5, label: 'The route map', verb: 'Look', r: 1.2 },
    ],
    solids: [
      ...[-10, -7.5, -5, -2.5, 0, 2.5, 5, 7.5, 10].flatMap((dz) => [
        { id: `seat-w${dz}`, dx: -3.1, dz, w: 2.9, d: 1.1 },
        { id: `seat-e${dz}`, dx: 3.1, dz, w: 2.9, d: 1.1 },
      ]),
    ],
    tasks: [{ id: 'storytrain', name: 'Find your ticket', hint: 'Dial the Story Train on the portal gun, and find a ticket under a seat before the conductor reaches you. He walks the aisle; the seats are the way round him.' }],
    say: {
      storylord: { who: 'Story Lord', text: 'I am Story Lord. This train runs on stories, and yours has been meandering for a while, Morty. Give me a beat. Any beat.' },
      ticketsguy: { who: 'The conductor', text: 'Tickets, please. No ticket, no ride. Rules of the anthology.' },
      trainticket: { who: null, text: 'A ticket, folded under the seat. Someone got off in a hurry. It’s yours now. Tickets, please.' },
      trainwindow: { who: null, text: 'The windows show the stories as they pass: a wedding, a heist, a man who is also a train. None of them stop long enough to make sense.' },
      routemap: { who: null, text: 'The route: Cold Open, Act One, Act Two, Act Three, Tag. The train is running late past Act Two.' },
    },
    done: { trainticket: 'storytrain' },
    kinds: ['storylord', 'ticketsguy'],
  }),
  place(15, {
    id: 'fortress',
    name: 'Rick Prime’s fortress',
    note: 'A cold hangar of Rick Prime’s, somewhere out past the Central Finite Curve. The Omega Device is here.',
    kind: 'room',
    deep: 36,
    wide: 40,
    ceiling: 12,
    people: [{ id: 'rickprime', dx: 0, dz: -12.4, face: S, until: 'fortress', ai: { watch: 14 } }],
    extras: [
      // his security drones, round their loops; one that gets a look at Morty goes for him
      { kind: 'primedrone', dx: -10, dz: 6, y: 1.5, face: E, ai: { wander: [[-10, 6], [-4, 6], [-4, -2], [-10, -2]], speed: 1.8, pause: 0.2, hunt: { speed: 2.9, catchR: 1.5, near: 3.6, lose: 7 } } },
      { kind: 'primedrone', dx: 10, dz: -6, y: 1.5, face: W, ai: { wander: [[10, -6], [4, -6], [4, 4], [10, 4]], speed: 1.9, pause: 0.2, hunt: { speed: 2.9, catchR: 1.5, near: 3.6, lose: 7 } } },
      { kind: 'primedrone', dx: 0, dz: -8, y: 1.5, face: E, ai: { wander: [[0, -8], [8, -9], [-8, -9]], speed: 1.6, pause: 0.5, hunt: { speed: 2.9, catchR: 1.5, near: 3.6, lose: 7 } } },
    ],
    spots: [
      { id: 'omegadevice', dx: 5, dz: -1.8, label: 'The Omega Device', verb: 'Look', r: 1.9 },
      { id: 'primeconsole', dx: 0, dz: -10.6, label: 'Rick Prime’s console', verb: 'Reach', r: 1.6 },
      { id: 'primetanks', dx: -16, dz: 0, label: 'The tanks', verb: 'Look', r: 2.2 },
      { id: 'primepicture', dx: 17.6, dz: -8, label: 'A picture on the wall', verb: 'Look', r: 1.6 },
    ],
    solids: [
      { id: 'plinth', dx: 5, dz: -4, r: 1.7 },
      { id: 'primeconsole', dx: 0, dz: -14, w: 7, d: 1.6 },
      ...[-10, -6, -2, 2, 6, 10].map((dz) => ({ id: `tank${dz}`, dx: -18.2, dz, r: 1.1 })),
      { id: 'crate-a', dx: 14, dz: 10, w: 2.4, d: 2.4 },
      { id: 'crate-b', dx: 16.6, dz: 8, w: 1.8, d: 1.8 },
    ],
    tasks: [{ id: 'fortress', name: 'Reach Rick Prime', hint: 'Dial Rick Prime’s fortress on the portal gun, and get to his console past the drones. One red eye on you and you’re back at the door.' }],
    spotted: 'A drone’s eye goes from dull to bright red, and it turns.',
    caught: 'A drone’s red eye finds you and shrieks. Rick Prime looks up, says “Nope,” and is gone. You come round at the way in, and he’s back at his console as if nothing happened.',
    say: {
      omegadevice: { who: null, text: 'The Omega Device. Rick built one to erase Diane from every dimension. Rick Prime built this one, and used it.' },
      primeconsole: { who: 'Rick Prime', text: '“Oh, it’s the backup. Tell him I said hi, kid. Tell him he’s still boring.” A portal opens behind him and he steps through it without looking back.' },
      primetanks: { who: null, text: 'Tanks along the wall, each with a Rick in it, half-made. He keeps spares.' },
      primepicture: { who: null, text: 'A framed picture of a garage. There’s a family in it. Somebody has drawn over two of their faces.' },
    },
    done: { primeconsole: 'fortress' },
    acts: { primeconsole: 'gone' },
    kinds: ['rickprime', 'primedrone', 'omegadevice', 'rick'],
  }),
  place(16, {
    id: 'froopyland',
    name: 'Froopyland',
    note: 'The world Rick built for Beth when she was small. Soft ground, candy hills, and the creatures aren’t friendly.',
    kind: 'outdoor',
    deep: 50,
    wide: 70,
    sky: { top: 0xff9ad8, mid: 0xffd0ec, low: 0xfff2c8, sun: 0xfff8e0, clouds: 1, moons: 0 },
    people: [{ id: 'tommy', dx: 16, dz: -14, face: S, ai: { wander: [[16, -14], [20, -10], [14, -8], [11, -13]], speed: 0.9, pause: 3, watch: 8, bark: { r: 5, every: 16, lines: ['Beth? Is Beth with you? She said she’d come back.', 'I’ve been here a long time. The Froopylanders and I have an arrangement.'] } } }],
    extras: [
      { kind: 'froopy-a', dx: -8, dz: 4, face: E, ai: { wander: [[-8, 4], [-3, 8], [-12, 10], [-14, 2]], speed: 1.2, pause: 1, hunt: { speed: 3.0, catchR: 1.2, near: 5, lose: 9 } } },
      { kind: 'froopy-a', dx: 6, dz: 10, face: W, ai: { wander: [[6, 10], [12, 14], [2, 16], [-2, 9]], speed: 1.1, pause: 1.5, hunt: { speed: 3.0, catchR: 1.2, near: 5, lose: 9 } } },
      { kind: 'froopy-b', dx: -20, dz: -8, face: E, ai: { wander: [[-20, -8], [-14, -14], [-24, -16], [-27, -4]], speed: 1.4, pause: 2, hunt: { speed: 3.3, catchR: 1.3, near: 6, lose: 10 } } },
      { kind: 'froopy-b', dx: 2, dz: -4, face: S, ai: { wander: [[2, -4], [8, -2], [4, 3], [-4, -2]], speed: 1.3, pause: 2, hunt: { speed: 3.3, catchR: 1.3, near: 6, lose: 10 } } },
    ],
    spots: [
      { id: 'tommy', dx: 16, dz: -12.4, label: 'Tommy', verb: 'Talk' },
      { id: 'froopyriver', dx: -12, dz: -18, label: 'The honey river', verb: 'Look', r: 2.4 },
      { id: 'froopysign', dx: -6, dz: 14, label: 'A sign', verb: 'Read', r: 1.6 },
      { id: 'froopyhill', dx: 24, dz: -2, label: 'A candy hill', verb: 'Look', r: 2.4 },
    ],
    solids: [
      { id: 'hill-a', dx: 24, dz: 6, r: 5 },
      { id: 'hill-b', dx: -26, dz: 14, r: 4.5 },
      { id: 'hill-c', dx: 10, dz: -20, r: 4 },
      { id: 'tree-a', dx: -10, dz: -10, r: 1.2 },
      { id: 'tree-b', dx: 14, dz: 6, r: 1.2 },
      { id: 'sign', dx: -6, dz: 15.6, w: 1.8, d: 0.4 },
    ],
    tasks: [{ id: 'froopyland', name: 'Find Tommy in Froopyland', hint: 'Dial Froopyland on the portal gun, and get to Tommy past the Froopylanders. They bite.' }],
    say: {
      tommy: { who: 'Tommy', text: 'Beth left me here. I made a life. The Froopylanders are my friends, and also, when it comes to it, my dinner. Tell her I said hi.' },
      froopyriver: { who: null, text: 'A river of honey, slow and gold. Rick made it breathable and the ground bouncy so nothing could ever hurt her here. The creatures came later.' },
      froopysign: { who: null, text: '“FROOPYLAND. Pop. 1 (+ Froopylanders). No Ricks.” In a child’s handwriting, gone over later by a grown man.' },
      froopyhill: { who: null, text: 'A hill of candy pink, soft as a mattress. Beth used to roll down it. Something is watching from the top.' },
    },
    done: { tommy: 'froopyland' },
    caught: 'A Froopylander gets its teeth into your sleeve and the others come running. You bounce, twice, and come down back where the portal is.',
    kinds: ['tommy', 'froopy-a', 'froopy-b'],
  }),
  place(17, {
    id: 'nimbus',
    name: 'Mr. Nimbus’s beach',
    note: 'The shore where the land meets the sea. Mr. Nimbus controls the police, and he’s expecting Rick.',
    kind: 'outdoor',
    deep: 50,
    wide: 70,
    sky: { top: 0x2a7ad8, mid: 0x8ad0f0, low: 0xfff0d0, sun: 0xfff8e8, clouds: 1, moons: 0 },
    people: [
      { id: 'nimbus', dx: 0, dz: -15, face: S, ai: { watch: 14, bark: { r: 7, every: 15, lines: ['Richard. I was told you’d come. I was told wrong, it seems.', 'I am Mr. Nimbus. I control the police. Behave on my beach.', 'Tell your grandfather the treaty stands. For now.'] } } },
      { id: 'atlantean-a', who: 'atlantean', dx: -12, dz: -6, face: E, ai: { wander: [[-12, -6], [-6, -2], [-14, 4], [-20, -4]], speed: 1.1, pause: 2, hunt: { speed: 3.0, catchR: 1.3, near: 4.5, lose: 9 } } },
      { id: 'atlantean-b', who: 'atlantean', dx: 12, dz: -6, face: W, ai: { wander: [[12, -6], [6, -2], [14, 4], [20, -4]], speed: 1.0, pause: 2.5, hunt: { speed: 3.0, catchR: 1.3, near: 4.5, lose: 9 } } },
      { id: 'atlantean-c', who: 'atlantean', dx: 0, dz: -7, face: S, ai: { wander: [[0, -7], [-7, -10], [7, -10]], speed: 0.9, pause: 3, hunt: { speed: 3.0, catchR: 1.3, near: 4.5, lose: 9 } } },
    ],
    spots: [
      { id: 'nimbus', dx: 0, dz: -13.4, label: 'Mr. Nimbus', verb: 'Approach' },
      { id: 'treaty', dx: -4, dz: -14.6, label: 'The treaty', verb: 'Read', r: 1.4 },
      { id: 'shell', dx: 16, dz: 10, label: 'A shell', verb: 'Pick up', r: 1.4 },
      { id: 'sea', dx: 0, dz: -22, label: 'The sea', verb: 'Look', r: 3 },
    ],
    solids: [
      { id: 'throne', dx: 0, dz: -16.6, w: 3.6, d: 2.4 },
      { id: 'rock-a', dx: -22, dz: -12, r: 3 },
      { id: 'rock-b', dx: 24, dz: -14, r: 3.4 },
      { id: 'rock-c', dx: 26, dz: 12, r: 2 },
      { id: 'palm-a', dx: -18, dz: 12, r: 0.5 },
      { id: 'palm-b', dx: 20, dz: 14, r: 0.5 },
    ],
    tasks: [{ id: 'nimbus', name: 'Approach Mr. Nimbus', hint: 'Dial Mr. Nimbus’s beach on the portal gun, and reach his throne past the Atlantean guard. They don’t like anyone near their king.' }],
    say: {
      nimbus: { who: 'Mr. Nimbus', text: '“Richard sends a boy. Of course he does.” He looks you up and down. “Tell him Nimbus remembers. Tell him the ocean remembers. And tell him to call.”' },
      treaty: { who: null, text: 'The treaty, carved on a slab: the land keeps out of the sea, the sea keeps out of the land, and Rick keeps out of the whole thing. Signed with a trident and a flask.' },
      shell: { who: null, text: 'A conch. You hold it to your ear and hear the police being controlled.' },
      sea: { who: null, text: 'The sea, all the way out. Something in it is moving the way a kingdom moves.' },
    },
    done: { nimbus: 'nimbus' },
    caught: 'A spear-butt catches you behind the knee and two Atlanteans march you back up the beach. “Not near the king.”',
    kinds: ['nimbus', 'atlantean'],
  }),
  place(18, {
    id: 'gromflomites',
    name: 'The Gromflomite base',
    note: 'Where the Federation keeps Fart, the being Krombopulos Michael was paid to kill. Guards on every walkway.',
    kind: 'room',
    deep: 36,
    wide: 40,
    ceiling: 9,
    people: [
      { id: 'kmichael', who: 'krombopulos', dx: -16, dz: 12, face: E, ai: { watch: 8, bark: { r: 5, every: 16, lines: ['Shh. Big day. Nobody look at me.', 'The cell’s at the far end. I just need a clear run. Or a boy to make one.'] } } },
      { id: 'guard-a', who: 'gromflomite', dx: -8, dz: 4, face: E, ai: { wander: [[-8, 4], [8, 4], [8, -4], [-8, -4]], speed: 1.5, pause: 0.5, hunt: { speed: 3.2, catchR: 1.3, near: 4.2, lose: 8 } } },
      { id: 'guard-b', who: 'gromflomite', dx: 10, dz: -8, face: W, ai: { wander: [[10, -8], [-10, -8], [-10, -2], [10, -2]], speed: 1.4, pause: 0.5, hunt: { speed: 3.2, catchR: 1.3, near: 4.2, lose: 8 } } },
      { id: 'guard-c', who: 'gromflomite', dx: 14, dz: 8, face: N, ai: { wander: [[14, 8], [14, -12], [4, -12]], speed: 1.3, pause: 1, hunt: { speed: 3.2, catchR: 1.3, near: 4.2, lose: 8 } } },
      { id: 'guard-d', who: 'gromflomite', dx: -14, dz: -10, face: S, ai: { wander: [[-14, -10], [-14, 6], [-4, 10]], speed: 1.3, pause: 1, hunt: { speed: 3.2, catchR: 1.3, near: 4.2, lose: 8 } } },
    ],
    extras: [{ kind: 'fart', dx: 0, dz: -14.6, y: 0.6, face: S, ai: { watch: 12, bark: { r: 5, every: 14, lines: ['Morty. I know your name because I know your mind. Open the cell.', 'Your species is the cancer, Morty. But you, personally, are fine.'] } } }],
    spots: [
      { id: 'kmichael', dx: -16, dz: 12, label: 'Krombopulos Michael', verb: 'Talk' },
      { id: 'fartcell', dx: 0, dz: -12.4, label: 'The cell', verb: 'Open', r: 1.6 },
      { id: 'basescreen', dx: 16.6, dz: -2, label: 'A screen', verb: 'Look', r: 1.6 },
      { id: 'lockers', dx: -17, dz: -2, label: 'The lockers', verb: 'Look', r: 1.8 },
    ],
    solids: [
      { id: 'cell', dx: 0, dz: -15, w: 6, d: 4 },
      { id: 'crate-a', dx: -6, dz: 0, w: 2.6, d: 2.6 },
      { id: 'crate-b', dx: 6, dz: 0, w: 2.6, d: 2.6 },
      { id: 'crate-c', dx: 0, dz: -6, w: 3.2, d: 2 },
      { id: 'crate-d', dx: -12, dz: -6, w: 2, d: 2 },
      { id: 'crate-e', dx: 12, dz: 6, w: 2, d: 2 },
      { id: 'lockers', dx: -18.6, dz: -2, w: 1.2, d: 8 },
    ],
    tasks: [{ id: 'gromflomites', name: 'Open Fart’s cell', hint: 'Dial the Gromflomite base on the portal gun, and reach the cell at the far end without a guard seeing you. Use the crates.' }],
    say: {
      kmichael: { who: 'Krombopulos Michael', text: 'Oh boy. Hi, Morty. Don’t mind me, I’m just here to kill a guy. A gas, technically. Look, if you got the cell open for me I’d be real grateful. I’d owe you a killing.' },
      fartcell: { who: 'Fart', text: 'The lock sings a note and the door slides. “Thank you, Morty.” Across the room, Krombopulos Michael says “Oh boy” and is already running.' },
      basescreen: { who: null, text: 'A screen in the Federation’s script. A face with four eyes, a number counting down, and a crude drawing of Rick with a line through it.' },
      lockers: { who: null, text: 'The guards’ lockers. One holds a blaster, one a lunch, one a photograph of a Gromflomite family on a beach.' },
    },
    done: { fartcell: 'gromflomites' },
    acts: { fartcell: 'opened' },
    spotted: 'A guard’s head snaps round. Behind the crates, now.',
    caught: 'A Gromflomite’s four eyes meet yours. “Intruder!” The blaster’s set to stun, and you come round by the door with a headache.',
    kinds: ['krombopulos', 'gromflomite', 'fart'],
  }),
  place(19, {
    id: 'heistcon',
    name: 'Heist-Con',
    note: 'The convention for heist crews. Miles Knightly is assembling one, and Heistotron is at the keynote.',
    kind: 'room',
    deep: 34,
    wide: 44,
    ceiling: 8,
    people: [
      { id: 'miles', dx: -8, dz: -8, face: S, ai: { watch: 9, bark: { r: 6, every: 16, lines: ['You look like a kid who could be a crew member. Everybody’s somebody’s crew member.', 'The heist of the century, and it’s this: the heist is the con. The con is the heist.'] } } },
      { id: 'heister-a1', who: 'heister-a', dx: 6, dz: 2, face: W, ai: { wander: [[6, 2], [12, 6], [4, 8]], speed: 0.8, pause: 4 } },
      { id: 'heister-b1', who: 'heister-b', dx: -12, dz: 4, face: E, ai: { wander: [[-12, 4], [-6, 8], [-15, 9]], speed: 0.9, pause: 3 } },
    ],
    extras: [
      { kind: 'heister-a', dx: 14, dz: -6, face: W, ai: { wander: [[14, -6], [10, -2], [16, 0]], speed: 0.7, pause: 5 } },
      { kind: 'heister-b', dx: -16, dz: -4, face: E, ai: { wander: [[-16, -4], [-12, 0], [-18, 2]], speed: 0.7, pause: 5 } },
      { kind: 'heister-a', dx: 2, dz: 10, face: N },
      { kind: 'heister-b', dx: -4, dz: 10, face: N },
      { kind: 'heistotron', dx: 0, dz: -12.6, face: S },
    ],
    spots: [
      { id: 'miles', dx: -8, dz: -6.4, label: 'Miles Knightly', verb: 'Talk' },
      { id: 'heister-a1', dx: 6, dz: 2, label: 'A heister', verb: 'Recruit', r: 1.6 },
      { id: 'heister-b1', dx: -12, dz: 4, label: 'A cat burglar', verb: 'Recruit', r: 1.6 },
      { id: 'heistotron', dx: 0, dz: -9, label: 'Heistotron', verb: 'Look', r: 2 },
      { id: 'heistbooth', dx: 14, dz: 10, label: 'A booth', verb: 'Look', r: 1.8 },
      { id: 'heistbadge', dx: -8, dz: 11.4, label: 'The badge table', verb: 'Take a badge', r: 1.6 },
    ],
    solids: [
      { id: 'stage', dx: 0, dz: -14, w: 14, d: 4 },
      { id: 'booth-a', dx: 15, dz: 12, w: 4, d: 2 },
      { id: 'booth-b', dx: -15, dz: 12, w: 4, d: 2 },
      { id: 'booth-c', dx: 17, dz: -10, w: 2, d: 4 },
      { id: 'booth-d', dx: -17, dz: -10, w: 2, d: 4 },
      { id: 'badges', dx: -8, dz: 13, w: 3, d: 1 },
    ],
    tasks: [{ id: 'heistcon', name: 'Assemble a crew', hint: 'Dial Heist-Con on the portal gun, take a badge, and recruit two heisters for Miles Knightly.' }],
    say: {
      miles: { who: 'Miles Knightly', text: '“Kid. You in?” He doesn’t wait. “Get me a muscle and a cat burglar and we’ve got the start of something. Then we double-cross everyone. That’s the job.”' },
      'heister-a1': { who: 'A heister', text: '“Muscle? Sure. I lift things. Sometimes they’re safes.” He hands you a card. It just says MUSCLE.' },
      'heister-b1': { who: 'A cat burglar', text: '“Lasers, vents, roofs. I’m in if Knightly’s in. Tell him I want a bigger cut than last time.”' },
      heistotron: { who: null, text: 'Heistotron. A robot built to plan heists. Rick built it to beat Miles, then it heisted Rick’s plan to heist it. It’s giving the keynote.' },
      heistbooth: { who: null, text: 'A booth selling grappling hooks, glass cutters and a book called “Your Crew And You”. Everything is stolen as you watch.' },
      heistbadge: { who: null, text: 'A badge: HELLO MY NAME IS and a blank. You write MORTY, and somebody steals the pen.' },
    },
    collect: { task: 'heistcon', spots: ['heistbadge', 'heister-a1', 'heister-b1'] },
    goal: 'heistbadge',
    kinds: ['miles', 'heister-a', 'heister-b', 'heistotron'],
  }),
  place(20, {
    id: 'snakeplanet',
    name: 'Snake Planet',
    note: 'A planet of snakes, with a space programme. Everything here is a snake, and most of them bite.',
    kind: 'outdoor',
    deep: 50,
    wide: 70,
    sky: { top: 0x5a3a8a, mid: 0xc87a6a, low: 0xf2c890, sun: 0xffe0b0, clouds: 0, moons: 1 },
    extras: [
      { kind: 'snakeastronaut', dx: 14, dz: -14, face: S, ai: { watch: 8, bark: { r: 5, every: 15, lines: ['Hsss. (It salutes with its tail, which is also the rest of it.)', 'Hssssss. Hss. (The launch is in an hour. Nobody is allowed near the rocket.)'] } } },
      { kind: 'snake-a', dx: -8, dz: 2, face: E, ai: { wander: [[-8, 2], [-2, 6], [-12, 8], [-14, 0]], speed: 1.4, pause: 1, hunt: { speed: 3.4, catchR: 1.1, near: 5, lose: 9 } } },
      { kind: 'snake-b', dx: 6, dz: 8, face: W, ai: { wander: [[6, 8], [12, 12], [2, 14], [-2, 8]], speed: 1.3, pause: 1, hunt: { speed: 3.4, catchR: 1.1, near: 5, lose: 9 } } },
      { kind: 'snake-a', dx: 4, dz: -4, face: S, ai: { wander: [[4, -4], [10, -2], [8, 4], [-2, -2]], speed: 1.5, pause: 0.8, hunt: { speed: 3.6, catchR: 1.1, near: 5.5, lose: 9 } } },
      { kind: 'snake-b', dx: -18, dz: -8, face: E, ai: { wander: [[-18, -8], [-12, -12], [-22, -14], [-25, -4]], speed: 1.2, pause: 1.5, hunt: { speed: 3.3, catchR: 1.1, near: 5, lose: 9 } } },
      { kind: 'snake-a', dx: 20, dz: 4, face: W, ai: { wander: [[20, 4], [24, 10], [16, 12], [14, 4]], speed: 1.3, pause: 1.2, hunt: { speed: 3.4, catchR: 1.1, near: 5, lose: 9 } } },
      { kind: 'snakerocket', dx: 12, dz: -17, face: S },
    ],
    spots: [
      { id: 'snakerocket', dx: 12, dz: -14.4, label: 'The snake rocket', verb: 'Touch', r: 1.8 },
      { id: 'snakeastronaut', dx: 14, dz: -12.4, label: 'A snake astronaut', verb: 'Salute', r: 1.6 },
      { id: 'snakesign', dx: -6, dz: 14, label: 'A sign', verb: 'Read', r: 1.6 },
      { id: 'snakehole', dx: -20, dz: 12, label: 'A hole', verb: 'Look', r: 1.8 },
    ],
    solids: [
      { id: 'rocket', dx: 12, dz: -17, r: 2.4 },
      { id: 'pad', dx: 18, dz: -18, w: 6, d: 4 },
      { id: 'rock-a', dx: -24, dz: -12, r: 3 },
      { id: 'rock-b', dx: 26, dz: 10, r: 2.6 },
      { id: 'rock-c', dx: -6, dz: -16, r: 2.2 },
      { id: 'sign', dx: -6, dz: 15.6, w: 1.8, d: 0.4 },
    ],
    tasks: [{ id: 'snakeplanet', name: 'Reach the snake rocket', hint: 'Dial Snake Planet on the portal gun, and get to the rocket on the far side without being bitten. The snakes strike when you come close.' }],
    say: {
      snakerocket: { who: null, text: 'The snakes’ rocket, cold to the touch, no bigger than a van. A snake is going to the moon in it, and Morty is the reason there will be a snake war. Not yet.' },
      snakeastronaut: { who: 'A snake astronaut', text: 'Hssss. (It bows its helmet. You have been accepted, provisionally, into the snake space programme.)' },
      snakesign: { who: null, text: 'A sign in snake: a long wavy line and a dot. It probably says “Welcome” or “Keep off the grass”. It’s hard to tell with snakes.' },
      snakehole: { who: null, text: 'A hole in the ground, and in the hole, eyes. Many eyes. Something hisses the snake word for “later”.' },
    },
    done: { snakerocket: 'snakeplanet' },
    caught: 'Fangs, in the ankle. The world goes green at the edges, and you come round back where you started with two small holes in your sock.',
    kinds: ['snake-a', 'snake-b', 'snakeastronaut', 'snakerocket'],
  }),
  place(21, {
    id: 'nuptia',
    name: 'Nuptia 4',
    note: 'The couples’ retreat on a cliff over the clouds. The machine reads what you think of each other, and makes it.',
    kind: 'outdoor',
    deep: 50,
    wide: 70,
    sky: { top: 0x6a4ab8, mid: 0xd8a0d8, low: 0xffe0c0, sun: 0xfff0e0, clouds: 1, moons: 2 },
    people: [
      { id: 'glexo', dx: 0, dz: -12, face: S, ai: { watch: 10, bark: { r: 6, every: 16, lines: ['Welcome to Nuptia 4. Love is a scan, and a scan is a thing that can be made.', 'We ask every couple one question: what do you see when you look at each other? Then we show them.'] } } },
      { id: 'nbeth', who: 'beth', dx: -10, dz: 2, face: E, ai: { wander: [[-10, 2], [-6, 5], [-12, 7]], speed: 0.7, pause: 5, bark: { r: 4, every: 18, lines: ['Morty? What are you doing here? Don’t tell your father I said anything about him.'] } } },
      { id: 'njerry', who: 'jerry', dx: -8, dz: 2, face: W, ai: { wander: [[-8, 2], [-4, 5], [-10, 7]], speed: 0.7, pause: 5, bark: { r: 4, every: 18, lines: ['Morty! Your mother and I are doing great. The machine said so. Mostly.'] } } },
    ],
    extras: [
      { kind: 'mytholog', dx: 16, dz: -4, face: W, ai: { wander: [[16, -4], [22, 2], [14, 8], [10, 0]], speed: 1.1, pause: 1.5, hunt: { speed: 3.0, catchR: 1.4, near: 5.5, lose: 10 } } },
      { kind: 'mytholog', dx: -20, dz: -8, face: E, ai: { wander: [[-20, -8], [-26, -2], [-18, 4], [-14, -6]], speed: 1.0, pause: 2, hunt: { speed: 3.0, catchR: 1.4, near: 5.5, lose: 10 } } },
      { kind: 'nuptiamachine', dx: 6, dz: -14, face: S },
    ],
    spots: [
      { id: 'glexo', dx: 0, dz: -10.4, label: 'Glexo Slim Slom', verb: 'Talk' },
      { id: 'nuptiamachine', dx: 6, dz: -11.4, label: 'The machine', verb: 'Sit in', r: 1.8 },
      { id: 'nuptiaedge', dx: 0, dz: -20, label: 'The edge', verb: 'Look', r: 2.4 },
      { id: 'nbeth', dx: -10, dz: 2, label: 'Beth', verb: 'Talk', r: 1.6 },
      { id: 'njerry', dx: -8, dz: 2, label: 'Jerry', verb: 'Talk', r: 1.6 },
    ],
    solids: [
      { id: 'machine', dx: 6, dz: -14, w: 4, d: 3 },
      { id: 'dais', dx: 0, dz: -13.4, r: 1.6 },
      { id: 'pillar-a', dx: -12, dz: -16, r: 0.8 },
      { id: 'pillar-b', dx: 12, dz: -16, r: 0.8 },
      { id: 'pillar-c', dx: -24, dz: 10, r: 0.8 },
      { id: 'pillar-d', dx: 24, dz: 10, r: 0.8 },
    ],
    tasks: [{ id: 'nuptia', name: 'Take the test on Nuptia 4', hint: 'Dial Nuptia 4 on the portal gun, talk to Glexo Slim Slom, and sit in the machine. Keep away from the mythologs: they’re other couples’ problems.' }],
    say: {
      glexo: { who: 'Glexo Slim Slom', text: '“A child. The machine will scan you alone, then. Sit, and think of whoever you think of.” He gestures at the pod. The mythologs on the lawn turn their heads.' },
      nuptiamachine: { who: null, text: 'You sit, and the helmet comes down. You think of Rick. The readout says: TALL. UNRELIABLE. YOURS. Glexo nods like that’s normal.' },
      nuptiaedge: { who: null, text: 'The cliff drops into cloud. Down there is where the machine’s monsters go when a couple leaves. Some couples leave fast.' },
      nbeth: { who: 'Beth', text: 'We’re trying, Morty. The machine made a thing of what I think of your father. It had a lot of teeth. We’re working through it.' },
      njerry: { who: 'Jerry', text: 'Mine was a… it was a kind of worm with a crown? Your mother says that’s on me.' },
    },
    collect: { task: 'nuptia', spots: ['glexo', 'nuptiamachine'] },
    goal: 'glexo',
    caught: 'A mytholog folds you into its cold wet arms and sets you down, gently, back where the portal is. It wasn’t about you.',
    kinds: ['glexo', 'beth', 'jerry', 'mytholog', 'nuptiamachine'],
  }),
  place(22, {
    id: 'gloopynoops',
    name: 'St. Gloopy Noops',
    note: 'The hospital in space. Shrimply Pibbles is dying, and the galaxy’s doctors want something of Jerry’s.',
    kind: 'room',
    deep: 34,
    wide: 44,
    ceiling: 6,
    people: [
      { id: 'glipglop', dx: 4, dz: -6, face: S, ai: { wander: [[4, -6], [10, -4], [8, 2], [0, -2]], speed: 0.9, pause: 4, watch: 7, bark: { r: 5, every: 16, lines: ['The Jerry’s with you? Good. We just need a small part of him. Trust me, I’m Dr. Glip-Glop.', 'Shrimply Pibbles freed a billion people. Jerry Smith watched a lot of television. Weigh it.'] } } },
      { id: 'gjerry', who: 'jerry', dx: -12, dz: 4, face: E, ai: { watch: 6, bark: { r: 4, every: 16, lines: ['Morty, they want my… they want a thing. I said I’d think about it. Tell them I’m still thinking.'] } } },
    ],
    extras: [
      { kind: 'gloopnurse', dx: -4, dz: 6, face: N, ai: { wander: [[-4, 6], [-10, 10], [6, 10], [2, 4]], speed: 0.8, pause: 3 } },
      { kind: 'gloopnurse', dx: 14, dz: -10, face: W, ai: { wander: [[14, -10], [14, 6], [8, 8]], speed: 0.7, pause: 4 } },
      { kind: 'shrimply', dx: 0, dz: -13, face: S },
    ],
    spots: [
      { id: 'glipglop', dx: 4, dz: -6, label: 'Dr. Glip-Glop', verb: 'Talk', r: 1.6 },
      { id: 'shrimply', dx: 0, dz: -10.6, label: 'Shrimply Pibbles', verb: 'Visit', r: 1.8 },
      { id: 'gjerry', dx: -12, dz: 4, label: 'Jerry', verb: 'Talk', r: 1.6 },
      { id: 'reception', dx: 12, dz: 12, label: 'Reception', verb: 'Ask', r: 1.8 },
      { id: 'vending', dx: -18, dz: 12, label: 'A vending machine', verb: 'Look', r: 1.6 },
    ],
    solids: [
      { id: 'bed', dx: 0, dz: -13.6, w: 3, d: 4 },
      { id: 'reception', dx: 12, dz: 14, w: 5, d: 1.4 },
      { id: 'vending', dx: -19.5, dz: 12, w: 1.2, d: 1.6 },
      { id: 'bench-a', dx: -12, dz: 6, w: 3, d: 1 },
      { id: 'bench-b', dx: -6, dz: 14, w: 3, d: 1 },
      { id: 'cart', dx: 8, dz: -2, w: 1.2, d: 1.6 },
    ],
    tasks: [{ id: 'gloopynoops', name: 'Visit Shrimply Pibbles', hint: 'Dial St. Gloopy Noops on the portal gun, ask at reception, and visit Shrimply Pibbles in his bed.' }],
    say: {
      glipglop: { who: 'Dr. Glip-Glop', text: '“The boy. Good. Your father is being very brave, by which I mean he hasn’t run yet.” He checks a clipboard that is also a screen. “Visiting hours are now.”' },
      shrimply: { who: 'Shrimply Pibbles', text: 'A soft voice from the bed. “Child. Whatever your father decides, tell him I understand. I have been many things to many people. I can be one more.”' },
      gjerry: { who: 'Jerry', text: '“I keep saying I’m thinking about it and they keep nodding. I don’t know how to say no to a hero, Morty. I don’t know how to say no to anyone.”' },
      reception: { who: 'The receptionist', text: '“Pibbles? Room one. Everyone’s here for Pibbles.” She points down the ward without looking up.' },
      vending: { who: null, text: 'A vending machine. Row C is Jerry Smith branded, already. Somebody was confident.' },
    },
    collect: { task: 'gloopynoops', spots: ['reception', 'shrimply'] },
    goal: 'reception',
    kinds: ['glipglop', 'jerry', 'gloopnurse', 'shrimply'],
  }),
  place(23, {
    id: 'resort',
    name: 'The Immortality Field Resort',
    note: 'A resort where nobody can die, inside the field. Risotto Groupon runs it, and he has plans for Rick.',
    kind: 'outdoor',
    deep: 50,
    wide: 70,
    sky: { top: 0x2a8ad8, mid: 0x9ad8f8, low: 0xffe8c0, sun: 0xfff8e8, clouds: 1, moons: 0 },
    people: [{ id: 'risotto', dx: 0, dz: -8, face: S, ai: { wander: [[0, -8], [6, -6], [-6, -6]], speed: 0.6, pause: 6, watch: 9, bark: { r: 6, every: 16, lines: ['Welcome to the Immortality Field Resort. Inside the field, nothing can hurt you. Outside it, everything can.', 'Your grandfather took my kingdom. I don’t hold it against you. I hold it against him, quite hard.'] } } }],
    extras: [
      { kind: 'resortguest-a', dx: -6, dz: 10, face: E, ai: { wander: [[-6, 10], [-2, 6], [-8, 14]], speed: 0.6, pause: 5 } },
      { kind: 'resortguest-b', dx: 10, dz: 6, face: W, ai: { wander: [[10, 6], [16, 10], [6, 12]], speed: 0.7, pause: 4 } },
      { kind: 'resortguest-a', dx: 18, dz: -2, face: W },
      { kind: 'resortguest-b', dx: -20, dz: -4, face: E },
      { kind: 'dirlycar', dx: 14, dz: -16, face: W },
    ],
    spots: [
      { id: 'risotto', dx: 0, dz: -6.4, label: 'Risotto Groupon', verb: 'Talk' },
      { id: 'dirly', dx: 14, dz: -13.4, label: 'The Whirly Dirly', verb: 'Ride', r: 1.8 },
      { id: 'fieldpost', dx: -16, dz: -16, label: 'The field generator', verb: 'Look', r: 2 },
      { id: 'poolbar', dx: -14, dz: -1.6, label: 'The pool bar', verb: 'Order', r: 2 },
    ],
    solids: [
      { id: 'dirlycar', dx: 14, dz: -16, w: 3, d: 2 },
      { id: 'dirly-pylon-a', dx: 20, dz: -20, r: 0.6 },
      { id: 'dirly-pylon-b', dx: 8, dz: -22, r: 0.6 },
      { id: 'generator', dx: -16, dz: -18.4, r: 1.6 },
      { id: 'pool', dx: -14, dz: 4, w: 12, d: 6 },
      { id: 'bar', dx: -14, dz: -1.6, w: 5, d: 1.2 },
      { id: 'palm-a', dx: 22, dz: 8, r: 0.5 },
      { id: 'palm-b', dx: -26, dz: 2, r: 0.5 },
    ],
    tasks: [{ id: 'resort', name: 'Ride the Whirly Dirly', hint: 'Dial the Immortality Field Resort on the portal gun, talk to Risotto Groupon, and ride the Whirly Dirly. Part of it leaves the field.' }],
    say: {
      risotto: { who: 'Risotto Groupon', text: '“The grandson. Welcome. Enjoy the resort. The Whirly Dirly is our pride, and for a few seconds at the top it leaves the field. Do tell your grandfather to ride it.”' },
      dirly: { who: null, text: 'The car climbs, the field’s shimmer falls behind, and for three seconds at the top anything could kill you. Nothing does. You come down screaming anyway.' },
      fieldpost: { who: null, text: 'The field generator, a column of humming blue rings. Inside the field’s edge nothing dies, and the guests know exactly where the edge is.' },
      poolbar: { who: 'The bartender', text: '“A drink for a kid? It’s an immortality resort. Have whatever you want.” You have a lemonade. It’s the best lemonade you’ve ever had, forever.' },
    },
    collect: { task: 'resort', spots: ['risotto', 'dirly'] },
    goal: 'risotto',
    kinds: ['risotto', 'resortguest-a', 'resortguest-b', 'dirlycar'],
  }),
  place(24, {
    id: 'schwifty',
    name: 'The Get Schwifty show',
    note: 'The Cromulons want a hit, or Earth’s gone. Water-T is on the bill, and Ice-T is on the ice.',
    kind: 'outdoor',
    deep: 50,
    wide: 70,
    sky: { top: 0x1a1a4a, mid: 0x4a3a8a, low: 0xd86a4a, sun: 0xffb060, clouds: 0, moons: 0 },
    people: [{ id: 'watert', dx: -4, dz: -12, face: S, ai: { watch: 10, bark: { r: 6, every: 15, lines: ['You here to play, little man? The heads want a song. Give the heads a song.', 'My father was a block of ice. I became water. We all become something.'] } } }],
    extras: [
      { kind: 'cromulon', dx: 0, dz: -60, face: S, y: 10, h: 24, ai: { watch: 80, bark: { r: 70, every: 20, lines: ['SHOW ME WHAT YOU GOT.', 'I LIKE WHAT YOU GOT. GOOD JOB.', 'DISQUALIFIED.'] } } },
      { kind: 'cromulon', dx: -40, dz: -56, face: S + 0.3, y: 10, h: 24 },
      { kind: 'cromulon', dx: 40, dz: -58, face: S - 0.3, y: 10, h: 24 },
      { kind: 'icet', dx: 8, dz: -13, face: S },
    ],
    spots: [
      { id: 'watert', dx: -4, dz: -10.4, label: 'Water-T', verb: 'Talk' },
      { id: 'mic', dx: 0, dz: -9.4, label: 'The mic', verb: 'Get schwifty', r: 1.6 },
      { id: 'icet', dx: 8, dz: -10.6, label: 'Ice-T', verb: 'Look', r: 1.8 },
      { id: 'heads', dx: 0, dz: -20, label: 'The Cromulons', verb: 'Look', r: 3 },
      { id: 'amps', dx: -12, dz: -11, label: 'The amps', verb: 'Look', r: 1.8 },
    ],
    solids: [
      { id: 'stage', dx: 0, dz: -14, w: 30, d: 6 },
      { id: 'amp-a', dx: -12, dz: -13, w: 2, d: 1.6 },
      { id: 'amp-b', dx: 12, dz: -13, w: 2, d: 1.6 },
      { id: 'tower-a', dx: -20, dz: -16, r: 0.8 },
      { id: 'tower-b', dx: 20, dz: -16, r: 0.8 },
    ],
    tasks: [{ id: 'schwifty', name: 'Get schwifty', hint: 'Dial the Get Schwifty show on the portal gun, talk to Water-T, and take the mic. The heads are watching.' }],
    say: {
      watert: { who: 'Water-T', text: '“The mic’s yours, kid. Don’t think. Nobody who ever thought about it got schwifty.” He nods at the heads filling the sky.' },
      mic: { who: null, text: 'You take the mic. You don’t think. “Oh yeah, you gotta get schwifty…” The heads lean in. One of them says, slowly, “I LIKE WHAT YOU GOT.”' },
      icet: { who: null, text: 'Ice-T, in his true form: a block of ice shaped like a T. He’s not cold. He says he just doesn’t care, and the ice says it for him.' },
      heads: { who: null, text: 'Three heads the size of towns hang in the sky, their mouths open. One is humming. If they don’t like the song, the planet goes.' },
      amps: { who: null, text: 'The amps go to eleven, then to a number that isn’t one. Rick wired them. Somebody has written “schwifty” on one in marker.' },
    },
    collect: { task: 'schwifty', spots: ['watert', 'mic'] },
    goal: 'watert',
    kinds: ['watert', 'cromulon', 'icet'],
  }),
];
