// The portal gun's dial, rows 25 to 34: Evil Rick's lair to Dimension 35-C (./destinations.js joins the three files; ./place.js says what each field is).

import { E, N, S, W, place } from './place';

export const ROWS = [
  place(25, {
    id: 'evilrick',
    name: 'Evil Rick’s lair',
    note: 'The dimension where a Rick with a scar wired up a dome of Mortys to hide his brainwaves. Somebody’s behind him.',
    kind: 'room',
    deep: 40,
    wide: 44,
    ceiling: 10,
    people: [
      // Evil Rick at his console till the Mortys are freed; then he comes for Morty, and the fight is the thing
      { id: 'evilrick', dx: 0, dz: -12, face: S, ai: { watch: 12, bark: { r: 9, every: 14, lines: ['Another Morty. I’ve got hundreds. What’s one more?', 'Your Rick thinks he’s the smartest man in the universe. He isn’t even the smartest in this room.'] }, hunt: { speed: 2.4, catchR: 1.6, duel: { hp: 6, mortyHp: 3, task: 'evilrick', won: { who: 'Evil Rick', text: 'He goes down by his own console, and his eye flickers. A receiver, behind the ear. He was never the one in charge.' } }, line: 'Evil Rick’s fist finds your jaw. “Sit down, Morty. There’s a slot in the dome with your name on it.” You come round by the door.' } } },
      // Evil Morty, sitting in his chair at the back with his arms crossed, till he's spoken to
      { id: 'evilmorty', dx: 14, dz: -14, face: W, until: 'evilmorty', ai: { clip: 'sitcross', bark: { r: 6, every: 18, lines: ['(He watches you fight. He doesn’t get up.)', '(He says nothing. He’s counting something.)'] } } },
    ],
    // (the dome's Mortys in their pods are placed by the builder, which frees them one by one)
    spots: [
      { id: 'pod1', dx: -15.4, dz: -8, label: 'A Morty in a pod', verb: 'Free', r: 1.4 },
      { id: 'pod2', dx: -15.4, dz: -2, label: 'A Morty in a pod', verb: 'Free', r: 1.4 },
      { id: 'pod3', dx: -15.4, dz: 4, label: 'A Morty in a pod', verb: 'Free', r: 1.4 },
      { id: 'evilrick', dx: 0, dz: -10.4, label: 'Evil Rick', verb: 'Face him', r: 1.6 },
      { id: 'evilmorty', dx: 12.4, dz: -14, label: 'A Morty with an eyepatch', verb: 'Talk', r: 1.6, until: 'evilmorty' },
      { id: 'domewall', dx: 0, dz: -16, label: 'The dome', verb: 'Look', r: 2.4 },
      { id: 'scarconsole', dx: 4, dz: -12.4, label: 'His console', verb: 'Look', r: 1.6 },
    ],
    solids: [
      { id: 'console', dx: 0, dz: -14, w: 7, d: 1.6 },
      { id: 'chair', dx: 14.6, dz: -14, w: 1.2, d: 1.2 },
      ...[-8, -2, 4].map((dz) => ({ id: `podw${dz}`, dx: -17.6, dz, w: 1.6, d: 2.4 })),
      ...[2, 8].map((dz) => ({ id: `pode${dz}`, dx: 17.6, dz, w: 1.6, d: 2.4 })),
      { id: 'crate-a', dx: -6, dz: 6, w: 2.4, d: 2.4 },
      { id: 'crate-b', dx: 7, dz: 4, w: 2, d: 2 },
    ],
    tasks: [
      { id: 'evilrick', name: 'Beat Evil Rick', hint: 'Dial Evil Rick’s lair on the portal gun, free three Mortys from the dome, and when he comes for you, fight: F fires, and he hits hard. Keep moving.' },
      { id: 'evilmorty', name: 'Find out who was behind him', hint: 'Once Evil Rick is down, talk to the Morty with the eyepatch before he leaves.' },
    ],
    say: {
      pod1: { who: null, text: 'You pull the plug and the Morty slumps out, blinking. “Th-thanks. Which one are you?” Behind you, Evil Rick looks up from the console.' },
      pod2: { who: null, text: 'Another plug, another Morty. He hugs you and runs for the door. Evil Rick is standing now.' },
      pod3: { who: null, text: 'The third plug. The dome goes dark, and a thousand Mortys sigh at once. Evil Rick says, quietly, “That was mine,” and starts towards you.' },
      evilrick: { who: 'Evil Rick', text: '“Hundreds of Mortys. Every one of them a little bit of camouflage. You think you’re different, kid? You’re a slot in the wall.”' },
      evilmorty: { who: 'The Morty with the eyepatch', text: 'He takes the eyepatch off. Behind it, a perfectly good eye. “He was a puppet. They all are.” A yellow portal opens behind him. “Tell your Rick I’m not done.” He steps through, and the chair is empty.' },
      domewall: { who: null, text: 'The dome: hundreds of Mortys in pods, wired by the head, their brainwaves cancelling a Rick’s. Three pods have plugs you can reach.' },
      scarconsole: { who: null, text: 'His console, keyed to his hand. A screen tracks every Rick in the Citadel. One Rick, C-137, is circled in red. Twice.' },
    },
    collect: { task: 'evilrick', spots: ['pod1', 'pod2', 'pod3'], start: true },
    done: { evilmorty: 'evilmorty' },
    unlock: {},
    acts: { pod1: 'freed1', pod2: 'freed2', pod3: 'freed3', evilmorty: 'leave' },
    goal: 'pod1',
    caught: 'Evil Rick’s fist finds your jaw. You come round by the door, and he’s back at his console as if you’d never got up.',
    kinds: ['evilrick', 'evilmorty', 'mortyclone'],
  }),
  place(26, {
    id: 'cronenberg',
    name: 'Cronenberg World',
    note: 'The dimension Rick and Morty left behind, after the love potion. Everyone’s a Cronenberg now, except the Smiths who stayed.',
    kind: 'outdoor',
    deep: 50,
    wide: 70,
    sky: { top: 0x3a2a3a, mid: 0x8a6a6a, low: 0xc8a08a, sun: 0xffc8a0, clouds: 1, moons: 0 },
    people: [
      { id: 'cjerry', who: 'jerry', dx: -14, dz: -10, face: E, ai: { wander: [[-14, -10], [-10, -8], [-16, -6]], speed: 0.6, pause: 6, bark: { r: 5, every: 16, lines: ['We’re doing fine, actually. Better than fine. We hunt now.', 'Your grandfather did this. The other one. Ours. Then he left.'] } } },
      { id: 'cbeth', who: 'beth', dx: -11, dz: -12, face: S, ai: { watch: 8, bark: { r: 5, every: 18, lines: ['Morty? You look… the same. How are you the same?', 'There are two graves in our yard. Don’t dig.'] } } },
      { id: 'csummer', who: 'summer', dx: -17, dz: -8, face: E, ai: { wander: [[-17, -8], [-20, -2], [-13, -4]], speed: 0.9, pause: 3, bark: { r: 4, every: 16, lines: ['I have a spear now. It’s fine. Everything’s fine.'] } } },
    ],
    extras: [
      { kind: 'cronenberg', dx: 8, dz: 2, face: W, ai: { wander: [[8, 2], [14, 6], [4, 10], [0, 4]], speed: 1.1, pause: 1, hunt: { speed: 2.9, catchR: 1.3, near: 5, lose: 9 } } },
      { kind: 'cronenberg', dx: 18, dz: -6, face: W, ai: { wander: [[18, -6], [24, 0], [16, 4]], speed: 1.0, pause: 1.5, hunt: { speed: 2.9, catchR: 1.3, near: 5, lose: 9 } } },
      { kind: 'cronenberg', dx: 2, dz: -14, face: S, ai: { wander: [[2, -14], [8, -18], [-4, -18]], speed: 1.2, pause: 1, hunt: { speed: 3.1, catchR: 1.3, near: 5.5, lose: 9 } } },
      { kind: 'bigcronenberg', dx: 24, dz: 12, face: W, ai: { wander: [[24, 12], [18, 16], [28, 18]], speed: 0.8, pause: 2, hunt: { speed: 2.4, catchR: 1.8, near: 6, lose: 10 } } },
      { kind: 'blob', dx: -4, dz: 12, face: N, ai: { wander: [[-4, 12], [0, 15], [-8, 15]], speed: 0.7, pause: 2 } },
    ],
    spots: [
      { id: 'cbeth', dx: -11, dz: -10.4, label: 'Beth', verb: 'Talk' },
      { id: 'cjerry', dx: -14, dz: -10, label: 'Jerry', verb: 'Talk', r: 1.6 },
      { id: 'csummer', dx: -17, dz: -8, label: 'Summer', verb: 'Talk', r: 1.6 },
      { id: 'graves', dx: -20, dz: -16, label: 'Two graves', verb: 'Look', r: 2 },
      { id: 'shovel', dx: 12, dz: -12, label: 'A shovel', verb: 'Take', r: 1.4 },
      { id: 'wreckedcar', dx: 16, dz: 10, label: 'A wrecked car', verb: 'Look', r: 2.2 },
    ],
    solids: [
      { id: 'house', dx: -16, dz: -20, w: 14, d: 8 },
      { id: 'graves', dx: -20, dz: -17.6, w: 3.6, d: 1.2 },
      { id: 'car', dx: 16, dz: 12, w: 4.4, d: 2.2 },
      { id: 'wall-a', dx: 6, dz: -20, w: 10, d: 1 },
      { id: 'post-a', dx: 4, dz: 6, r: 0.3 },
      { id: 'post-b', dx: -8, dz: 4, r: 0.3 },
      { id: 'rubble', dx: 22, dz: -16, r: 2.4 },
    ],
    tasks: [{ id: 'cronenberg', name: 'Visit the Smiths who stayed', hint: 'Land on Cronenberg World in the Rick and Morty sector, take the shovel, and talk to Beth at the house. The Cronenbergs come for anything that moves.' }],
    say: {
      cbeth: { who: 'Beth', text: '“You have the shovel. Good. There’s always something to bury.” She looks at you for a long time. “Our Morty would be your age. Go home, Morty. Whichever one it is.”' },
      cjerry: { who: 'Jerry', text: '“We lived, Morty. No Rick, no portal gun, just us and a lot of spears. I’ve never been happier. Don’t tell your mother I said that.”' },
      csummer: { who: 'Summer', text: '“Did you come through a portal? Did you see a Rick? Of course you did. Tell him Summer says… tell him nothing. Tell him we’re fine.”' },
      graves: { who: null, text: 'Two graves in the yard, side by side, with no names. Somebody dug them in a hurry and filled them in slowly. Beth said don’t dig.' },
      shovel: { who: null, text: 'A shovel, leaning on a wall. The handle is worn where two hands have held it for a long time. You take it.' },
      wreckedcar: { who: null, text: 'A car on its side, the windows gone, something with too many mouths asleep in the back seat. You leave it asleep.' },
    },
    collect: { task: 'cronenberg', spots: ['shovel', 'cbeth'] },
    goal: 'shovel',
    caught: 'A Cronenberg gets its mouths on you. Summer’s spear gets it off. You come round by the portal, with a new scar and no shovel.',
    kinds: ['jerry', 'beth', 'summer', 'cronenberg', 'bigcronenberg', 'blob'],
  }),
  place(27, {
    id: 'blooddome',
    name: 'The Blood Dome',
    note: 'The Death Stalkers’ arena in the wasteland. Hemorrhage fights whoever walks into the ring. Summer’s here, and she likes it.',
    kind: 'outdoor',
    deep: 50,
    wide: 70,
    sky: { top: 0x6a3a1a, mid: 0xd88a4a, low: 0xffd8a0, sun: 0xffe8c0, clouds: 0, moons: 0 },
    people: [
      { id: 'hemorrhage', dx: 0, dz: -8, face: S, ai: { watch: 12, bark: { r: 10, every: 14, lines: ['Who wants to go in the Blood Dome? Who wants to be a man?', 'The ring is the law. The law is the ring.'] }, hunt: { speed: 2.3, catchR: 1.7, duel: { hp: 5, mortyHp: 3, task: 'blooddome', won: { who: 'Hemorrhage', text: 'He drops to one knee and pulls the helmet off. Underneath, a tired bald man. “Fine,” he says. “You’re a man. Go and tell your sister.”' } }, line: 'Hemorrhage’s gauntlet puts you on the sand. “Not a man yet,” he says, not unkindly, and the Death Stalkers carry you back to the gate.' } } },
      { id: 'bsummer', who: 'summer', dx: -10, dz: -4, face: E, ai: { watch: 8, bark: { r: 5, every: 15, lines: ['Morty! Oh my god, this place is amazing. I killed a guy. It was fine.', 'If you fight him, don’t stand still. That’s the whole trick.'] } } },
    ],
    extras: [
      { kind: 'deathstalker-a', dx: 10, dz: 4, face: W, ai: { wander: [[10, 4], [14, 8], [8, 10]], speed: 0.9, pause: 3 } },
      { kind: 'deathstalker-b', dx: -12, dz: 6, face: E, ai: { wander: [[-12, 6], [-16, 10], [-8, 12]], speed: 0.8, pause: 4 } },
      { kind: 'deathstalker-a', dx: 16, dz: -10, face: W },
      { kind: 'deathstalker-b', dx: -16, dz: -12, face: E },
      { kind: 'armothy', dx: 14, dz: -14, face: S, ai: { watch: 8, bark: { r: 5, every: 16, lines: ['(It flexes. It has no mouth. It is very clear what it means.)'] } } },
    ],
    spots: [
      { id: 'ring', dx: 0, dz: -2, label: 'The ring', verb: 'Step in', r: 2 },
      { id: 'bsummer', dx: -10, dz: -4, label: 'Summer', verb: 'Talk', r: 1.6 },
      { id: 'armothy', dx: 14, dz: -11.4, label: 'Armothy', verb: 'Look', r: 1.8 },
      { id: 'bloodsign', dx: 0, dz: 14, label: 'A sign', verb: 'Read', r: 1.8 },
    ],
    solids: [
      { id: 'post-a', dx: -8, dz: -16, r: 0.5 },
      { id: 'post-b', dx: 8, dz: -16, r: 0.5 },
      { id: 'post-c', dx: -8, dz: 6, r: 0.5 },
      { id: 'post-d', dx: 8, dz: 6, r: 0.5 },
      { id: 'wreck-a', dx: 24, dz: 10, w: 5, d: 2.4 },
      { id: 'wreck-b', dx: -24, dz: -10, w: 4, d: 2.4 },
      { id: 'sign', dx: 0, dz: 15.6, w: 2.4, d: 0.4 },
    ],
    tasks: [{ id: 'blooddome', name: 'Win in the Blood Dome', hint: 'Dial the Blood Dome on the portal gun, step into the ring, and beat Hemorrhage: F fires, and he hits hard. Don’t stand still.' }],
    say: {
      ring: { who: 'Hemorrhage', text: '“A boy walks into my ring.” The Death Stalkers start to chant. “Then a boy fights.” He comes down off the gate.' },
      bsummer: { who: 'Summer', text: '“I live here now, kind of. It’s a whole thing. Rick’s doing a whole thing too, with an arm. Don’t ask.”' },
      armothy: { who: null, text: 'Armothy. An arm. Rick’s been training it, and it’s been training Rick. It is the strongest thing here, and it knows it.' },
      bloodsign: { who: null, text: '“BLOOD DOME. No weapons. No mercy. No refunds.” Somebody has crossed out “weapons” and written “guns are fine”.' },
    },
    acts: { ring: 'fight' },
    goal: 'ring',
    caught: 'A Death Stalker drags you out of the ring by the collar and dumps you at the gate. “Not a man yet.”',
    kinds: ['hemorrhage', 'summer', 'deathstalker-a', 'deathstalker-b', 'armothy'],
  }),
  place(28, {
    id: 'prison',
    name: 'The Federation prison',
    note: 'Where the Galactic Federation keeps Rick, in the Brainalyzer, telling Cornvelious Daniel about the Szechuan sauce.',
    kind: 'room',
    deep: 40,
    wide: 40,
    ceiling: 8,
    people: [
      { id: 'cornvelious', dx: 4, dz: -14, face: S, ai: { watch: 10, bark: { r: 7, every: 15, lines: ['The portal gun, Rick. Just the formula. Then you can go back to your little… sauce.', 'Another Morty. The old man’s stories always have a Morty in them.'] } } },
      { id: 'prick', who: 'rick', dx: -3, dz: -14, face: S, ai: { bark: { r: 6, every: 12, lines: ['M-Morty! Took you long enough. Hit the switches. The green ones. Not the red. I mean it about the red.', 'Nine more seasons, Morty. Nine more seasons until I get that dipping Szechuan sauce.'] } } },
      { id: 'pguard-a', who: 'gromflomite', dx: -10, dz: 4, face: E, ai: { wander: [[-10, 4], [10, 4], [10, -4], [-10, -4]], speed: 1.6, pause: 0.4, hunt: { speed: 3.3, catchR: 1.3, near: 4.4, lose: 8 } } },
      { id: 'pguard-b', who: 'gromflomite', dx: 12, dz: 10, face: W, ai: { wander: [[12, 10], [-12, 10], [-12, 14], [12, 14]], speed: 1.5, pause: 0.4, hunt: { speed: 3.3, catchR: 1.3, near: 4.4, lose: 8 } } },
      { id: 'pguard-c', who: 'gromflomite', dx: 14, dz: -8, face: W, ai: { wander: [[14, -8], [14, 2], [6, 2], [6, -8]], speed: 1.4, pause: 0.6, hunt: { speed: 3.3, catchR: 1.3, near: 4.4, lose: 8 } } },
    ],
    extras: [{ kind: 'brainalyzer', dx: -3, dz: -15.4, face: S }],
    spots: [
      { id: 'switch1', dx: -16, dz: -2, label: 'A switch', verb: 'Throw', r: 1.4 },
      { id: 'switch2', dx: 16, dz: -2, label: 'A switch', verb: 'Throw', r: 1.4 },
      { id: 'prick', dx: -3, dz: -12.4, label: 'Rick, in the Brainalyzer', verb: 'Unstrap', r: 1.6 },
      { id: 'cornvelious', dx: 4, dz: -12.4, label: 'Cornvelious Daniel', verb: 'Talk', r: 1.6 },
      { id: 'cells', dx: -17, dz: 12, label: 'The cells', verb: 'Look', r: 2 },
    ],
    solids: [
      { id: 'chair', dx: -3, dz: -15.6, w: 2.4, d: 2.6 },
      { id: 'console', dx: 4, dz: -15.6, w: 4, d: 1.4 },
      { id: 'switch1', dx: -17.4, dz: -2, w: 0.8, d: 1.2 },
      { id: 'switch2', dx: 17.4, dz: -2, w: 0.8, d: 1.2 },
      { id: 'pillar-a', dx: -6, dz: 0, r: 1 },
      { id: 'pillar-b', dx: 6, dz: 0, r: 1 },
      { id: 'pillar-c', dx: 0, dz: 8, r: 1 },
      { id: 'crate-a', dx: -12, dz: -8, w: 2.4, d: 2.4 },
      { id: 'crate-b', dx: 10, dz: -12, w: 2, d: 2 },
      { id: 'cells', dx: -18.6, dz: 12, w: 1.2, d: 10 },
    ],
    tasks: [{ id: 'prison', name: 'Spring Rick from the Brainalyzer', hint: 'Dial the Federation prison on the portal gun, throw both green switches, and unstrap Rick without a guard seeing you. The pillars and crates are cover.' }],
    say: {
      switch1: { who: null, text: 'A green switch. You throw it. Half the lights go out, and on the far wall a lock sings.' },
      switch2: { who: null, text: 'The other green switch. The rest of the lights go out and the Brainalyzer’s clamps click open. Rick says “Finally.”' },
      prick: { who: 'Rick', text: '“Took you long enough.” He steps out of the chair, cracks his neck, and takes Cornvelious Daniel’s blaster off his belt without looking. “Nine more seasons, Morty.”' },
      cornvelious: { who: 'Cornvelious Daniel', text: '“A Morty. In my prison.” He doesn’t reach for his blaster. He’s not sure he still has it. “Well. Go on, then. Everyone does.”' },
      cells: { who: null, text: 'Cells down the west wall. One has a Rick in it who isn’t ours. One has a very quiet Jerry. One has a sauce packet, and nothing else.' },
    },
    collect: { task: 'prison', spots: ['switch1', 'switch2', 'prick'] },
    acts: { switch1: 'switch1', switch2: 'switch2', prick: 'freed' },
    goal: 'switch1',
    spotted: 'Four eyes lock on you across the floor. “Intruder!” Behind a pillar, now.',
    caught: 'A Gromflomite’s stun blast catches you behind the knees. You come round at the door with the lights back on and Rick back in the chair, mid-sentence.',
    kinds: ['cornvelious', 'rick', 'gromflomite', 'brainalyzer'],
  }),
  place(29, {
    id: 'cablestudio',
    name: 'The cable studio',
    note: 'Where interdimensional cable comes from: every channel’s set on one floor, and the people on them between takes.',
    kind: 'room',
    deep: 36,
    wide: 50,
    ceiling: 8,
    extras: [
      { kind: 'antsjohnson', dx: -18, dz: -10, face: E, ai: { watch: 8, bark: { r: 5, every: 14, lines: ['I’m Ants in my Eyes Johnson! Everything’s black! I can’t see a thing!', 'Is this a TV? I don’t know. I can’t see. There are ants in my eyes.'] } } },
      { kind: 'babylegs', dx: -6, dz: -12, face: S, ai: { wander: [[-6, -12], [-3, -9], [-8, -8]], speed: 0.4, pause: 4, bark: { r: 5, every: 14, lines: ['I’m Baby Legs. I’ve got the legs of a baby. I’m a detective.', 'Chief, I’m a detective. My partner here is Regular Legs.'] } } },
      { kind: 'regularlegs', dx: -3, dz: -12, face: S, ai: { wander: [[-3, -12], [0, -9], [-5, -8]], speed: 0.9, pause: 4, bark: { r: 5, every: 16, lines: ['I’m Regular Legs. I don’t know why I’m on this show.'] } } },
      { kind: 'mrsneezy', dx: 8, dz: -12, face: S, ai: { watch: 7, bark: { r: 5, every: 12, lines: ['Ah… ah… AH-CHOO. I can’t stop. It’s my whole thing.'] } } },
      { kind: 'gazorpazorpfield', dx: 18, dz: -10, face: W, ai: { watch: 8, bark: { r: 5, every: 15, lines: ['I hate Mondays. I hate Jon. Give me the lasagne, Jon.', 'Gimme my damn enchiladas, Jon.'] } } },
      { kind: 'shmlo', dx: -16, dz: 4, face: E, ai: { wander: [[-16, 4], [-12, 8], [-19, 9]], speed: 0.7, pause: 5, bark: { r: 5, every: 16, lines: ['Shmlonathan. From the shmlo show. Shmlangela says hi.'] } } },
      { kind: 'trunkperson', dx: -4, dz: 6, face: N, ai: { wander: [[-4, 6], [0, 9], [-7, 10]], speed: 0.6, pause: 5, bark: { r: 5, every: 16, lines: ['(It makes a sound like a trumpet. It is a happy sound.)'] } } },
      { kind: 'lilbits', dx: 8, dz: 6, face: W, ai: { watch: 7, bark: { r: 5, every: 14, lines: ['Welcome to Lil’ Bits! Tiny food. Tiny pizza. Tiny tiny lasagne.'] } } },
      { kind: 'tophatjones', dx: 16, dz: 6, face: W, ai: { wander: [[16, 6], [19, 10], [13, 10]], speed: 0.8, pause: 4, bark: { r: 5, every: 16, lines: ['(It tips its hat. The monocle stays put.)'] } } },
      { kind: 'realfakedoors', dx: 0, dz: -2, face: S, ai: { watch: 9, bark: { r: 6, every: 12, lines: ['Real fake doors! Come on down to Real Fake Doors! You can’t open them. That’s the point.', 'Need a fake door? We got real fake doors. Buy one, get a fake one free.'] } } },
    ],
    spots: [
      { id: 'set-ants', dx: -18, dz: -7.4, label: 'Ants in my Eyes Johnson’s Electronics', verb: 'Watch', r: 1.8 },
      { id: 'set-legs', dx: -4.5, dz: -9.4, label: 'Baby Legs and Regular Legs', verb: 'Watch', r: 1.8 },
      { id: 'set-sneezy', dx: 8, dz: -9.4, label: 'Mr. Sneezy', verb: 'Watch', r: 1.8 },
      { id: 'set-field', dx: 18, dz: -7.4, label: 'Gazorpazorpfield', verb: 'Watch', r: 1.8 },
      { id: 'set-doors', dx: 0, dz: 0.6, label: 'Real Fake Doors', verb: 'Try a door', r: 1.8 },
      { id: 'set-bits', dx: 8, dz: 8.6, label: 'Lil’ Bits', verb: 'Taste', r: 1.8 },
      { id: 'set-shmlo', dx: -16, dz: 6.6, label: 'The shmlo show', verb: 'Watch', r: 1.8 },
      { id: 'cablebooth', dx: -14, dz: 12.6, label: 'The control booth', verb: 'Look', r: 2 },
    ],
    solids: [
      { id: 'set-a', dx: -18, dz: -13, w: 8, d: 3 },
      { id: 'set-b', dx: -4.5, dz: -15, w: 9, d: 3 },
      { id: 'set-c', dx: 8, dz: -15, w: 7, d: 3 },
      { id: 'set-d', dx: 18, dz: -13, w: 8, d: 3 },
      { id: 'doors', dx: 0, dz: -4.5, w: 7, d: 1 },
      { id: 'bits', dx: 8, dz: 11, w: 4, d: 1.6 },
      { id: 'booth', dx: -14, dz: 15, w: 8, d: 2 },
      { id: 'camera-a', dx: -10, dz: -4, r: 0.6 },
      { id: 'camera-b', dx: 10, dz: -4, r: 0.6 },
    ],
    tasks: [{ id: 'cablestudio', name: 'Watch three channels', hint: 'Dial the cable studio on the portal gun, and watch three of the shows being made.' }],
    say: {
      'set-ants': { who: null, text: 'Ants in my Eyes Johnson’s Electronics. He can’t see the prices, so everything is a dollar. A fridge is a dollar. He has no idea.' },
      'set-legs': { who: null, text: 'Baby Legs and Regular Legs, on the trail of the Killer Regular Legs. The chief says Baby Legs isn’t ready. Baby Legs says he was born ready, and also with these legs.' },
      'set-sneezy': { who: null, text: 'Mr. Sneezy sneezes. The laugh track plays. He sneezes again. The laugh track plays again. This is the whole show, and it is the best show.' },
      'set-field': { who: null, text: 'Gazorpazorpfield tells Jon he hates Mondays, in words you can’t use on television. Jon takes it. Jon always takes it.' },
      'set-doors': { who: null, text: 'You try a real fake door. It doesn’t open. The salesman is delighted. “See? Real fake!” You buy one. It doesn’t open at home either.' },
      'set-bits': { who: null, text: 'Lil’ Bits: a tiny pizza, a tiny burger, a tiny lasagne. You eat the lot in one go. You are still hungry. That is the point of Lil’ Bits.' },
      'set-shmlo': { who: null, text: 'Shmlonathan and Shmlangela have a shmlargument about the shmlo. You don’t follow it, but the audience does.' },
      cablebooth: { who: null, text: 'The control booth: a wall of screens, one for every channel in every dimension, and a Rick asleep in front of them with a bottle. Not ours.' },
    },
    collect: { task: 'cablestudio', spots: ['set-ants', 'set-legs', 'set-sneezy'] },
    goal: 'set-ants',
    kinds: ['antsjohnson', 'babylegs', 'regularlegs', 'mrsneezy', 'gazorpazorpfield', 'shmlo', 'trunkperson', 'lilbits', 'tophatjones', 'realfakedoors'],
  }),
  place(30, {
    id: 'dream',
    name: 'Mr. Goldenfold’s dream',
    note: 'Inside Mr. Goldenfold’s head, three dreams down. Mrs. Pancakes is here, and so is Scary Terry.',
    kind: 'room',
    deep: 40,
    wide: 44,
    ceiling: 9,
    people: [{ id: 'scaryterry', dx: 0, dz: -14, face: S, ai: { watch: 14, bark: { r: 10, every: 11, lines: ['You can run, but you can’t hide, Morty!', 'Welcome to your nightmare, Morty! I’m Scary Terry!', 'Aw, geez, the blades are heavy today.'] }, hunt: { speed: 2.2, catchR: 1.5, always: true, until: 'dream', lose: 14, line: 'Scary Terry’s blades close on your collar. “Got you, Morty!” You wake up two dreams down, back at the door, and he’s back at his end of the room.' } } }],
    extras: [
      { kind: 'mrspancakes', dx: 14, dz: 6, face: W, ai: { watch: 8, bark: { r: 5, every: 15, lines: ['Oh, Mr. Goldenfold. You dream so loud.', 'Is that a child? In this dream? Honey, the rating.'] } } },
      { kind: 'goldenfold', dx: -14, dz: 8, face: E, ai: { wander: [[-14, 8], [-10, 12], [-16, 13]], speed: 0.5, pause: 5, bark: { r: 5, every: 14, lines: ['Morty? What are you doing in my… oh no. Oh, this is a dream, isn’t it.', 'Don’t look at Mrs. Pancakes. Don’t look at anything.'] } } },
    ],
    spots: [
      { id: 'dreamclock', dx: -12, dz: -8, label: 'A melting clock', verb: 'Look', r: 1.6 },
      { id: 'dreamdesk', dx: 12, dz: -8, label: 'Mr. Goldenfold’s desk', verb: 'Look', r: 1.8 },
      { id: 'dreambed', dx: 0, dz: 4, label: 'A bed', verb: 'Hide under', r: 1.8 },
      { id: 'mrspancakes', dx: 14, dz: 6, label: 'Mrs. Pancakes', verb: 'Talk', r: 1.6 },
      { id: 'dgoldenfold', dx: -14, dz: 8, label: 'Mr. Goldenfold', verb: 'Talk', r: 1.6 },
    ],
    solids: [
      { id: 'clock', dx: -12, dz: -10, r: 1 },
      { id: 'desk', dx: 12, dz: -10, w: 3, d: 1.4 },
      { id: 'bed', dx: 0, dz: 2, w: 2.4, d: 3.6 },
      { id: 'wardrobe', dx: -16, dz: -2, w: 1.4, d: 2.6 },
      { id: 'piano', dx: 16, dz: -2, w: 2.6, d: 1.6 },
    ],
    tasks: [{ id: 'dream', name: 'Survive Mr. Goldenfold’s dream', hint: 'Dial Mr. Goldenfold’s dream on the portal gun, and find three things in it before Scary Terry finds you. He never stops. Hide under the bed when he’s close.' }],
    say: {
      dreamclock: { who: null, text: 'A clock, melting off a shelf. It says the time is Wednesday. Behind you, somebody says “Morty” in a voice like a saw.' },
      dreamdesk: { who: null, text: 'Mr. Goldenfold’s desk, with a pop quiz on it. Every question is “Why?” You don’t have a pencil. You never have a pencil in these.' },
      dreambed: { who: null, text: 'You get under the bed. Scary Terry’s boots stop by it. He sighs. “I know you’re under there, Morty.” He doesn’t look. He’s tired too.' },
      mrspancakes: { who: 'Mrs. Pancakes', text: '“A child. In this dream.” She lights a cigarette that becomes a bird. “Mr. Goldenfold is a complicated man. Don’t tell the school.”' },
      dgoldenfold: { who: 'Mr. Goldenfold', text: '“Morty, if you’re here, I’m asleep, and if I’m asleep, that means… oh no. Is Scary Terry here? Please tell me it’s not a Scary Terry night.”' },
    },
    collect: { task: 'dream', spots: ['dreamclock', 'dreamdesk', 'dreambed'] },
    goal: 'dreamclock',
    kinds: ['scaryterry', 'mrspancakes', 'goldenfold'],
  }),
  place(31, {
    id: 'agency',
    name: 'The agency',
    note: 'The embassy where Pickle Rick fought his way out and met Jaguar. The guards are still jumpy.',
    kind: 'room',
    deep: 40,
    wide: 44,
    ceiling: 7,
    people: [
      { id: 'jaguar', dx: 16, dz: -12, face: W, until: 'agency', ai: { watch: 10, bark: { r: 6, every: 14, lines: ['You. Boy. Get me out of this cell and I kill nobody you like.', 'The pickle. Where is the pickle? He owes me a word.'] } } },
      { id: 'pickle', dx: -2, dz: -14, face: S, ai: { watch: 12, bark: { r: 7, every: 10, lines: ['I’M PICKLE RIIICK! Morty, get down here, I’ve got a rat suit and a plan.', 'Don’t touch the rats, Morty. The rats are mine. Everything in here is mine.'] } } },
    ],
    extras: [
      { kind: 'agencyguard', dx: -8, dz: 2, face: E, ai: { wander: [[-8, 2], [8, 2], [8, -6], [-8, -6]], speed: 1.5, pause: 0.4, hunt: { speed: 3.2, catchR: 1.3, near: 4.2, lose: 8 } } },
      { kind: 'agencyguard', dx: 12, dz: 8, face: W, ai: { wander: [[12, 8], [-12, 8], [-12, 13], [12, 13]], speed: 1.4, pause: 0.5, hunt: { speed: 3.2, catchR: 1.3, near: 4.2, lose: 8 } } },
      { kind: 'agencyguard', dx: 10, dz: -4, face: N, ai: { wander: [[10, -4], [10, 4], [2, 4]], speed: 1.3, pause: 0.8, hunt: { speed: 3.2, catchR: 1.3, near: 4.2, lose: 8 } } },
      { kind: 'sewerrat', dx: -14, dz: 10, face: E, ai: { wander: [[-14, 10], [-10, 14], [-17, 14], [-18, 6]], speed: 1.6, pause: 0.5 } },
      { kind: 'sewerrat', dx: -16, dz: -8, face: S, ai: { wander: [[-16, -8], [-12, -12], [-18, -13]], speed: 1.8, pause: 0.3 } },
      { kind: 'sewerrat', dx: -6, dz: 12, face: W, ai: { wander: [[-6, 12], [-2, 15], [-9, 15]], speed: 1.5, pause: 0.6 } },
    ],
    spots: [
      { id: 'cellkey', dx: -14, dz: -2, label: 'A key on a hook', verb: 'Take', r: 1.4 },
      { id: 'jaguar', dx: 13.4, dz: -12, label: 'Jaguar, in his cell', verb: 'Unlock', r: 1.6, until: 'agency' },
      { id: 'picklerick', dx: -2, dz: -11.4, label: 'Pickle Rick', verb: 'Talk', r: 1.6 },
      { id: 'agencyscreen', dx: 0, dz: -17, label: 'The screens', verb: 'Look', r: 2 },
      { id: 'sewer', dx: -16, dz: 12, label: 'The hole in the floor', verb: 'Go down', r: 1.8 },
    ],
    solids: [
      { id: 'cell', dx: 17, dz: -12, w: 5, d: 5 },
      { id: 'desk', dx: -2, dz: -16, w: 6, d: 1.6 },
      { id: 'keyboard', dx: -16, dz: -2, w: 1, d: 0.6 },
      { id: 'pillar-a', dx: -4, dz: -2, r: 0.8 },
      { id: 'pillar-b', dx: 4, dz: -2, r: 0.8 },
      { id: 'crate-a', dx: -10, dz: -10, w: 2.2, d: 2.2 },
      { id: 'crate-b', dx: 6, dz: 10, w: 2, d: 2 },
      { id: 'hole', dx: -16, dz: 14, r: 1.2 },
    ],
    tasks: [
      { id: 'agency', name: 'Spring Jaguar', hint: 'Dial the agency on the portal gun, take the key off its hook, and unlock Jaguar’s cell without a guard seeing you. Pickle Rick is on the desk, being no help at all.' },
      { id: 'sewer', name: 'Run the sewer as Pickle Rick', hint: 'At the agency, go down the hole in the floor by the rats. Dodge the grates, squash the rats, pick up screws, and make the far drain.' },
    ],
    say: {
      cellkey: { who: null, text: 'A key on a hook, under a sign that says DO NOT. You take it. The sign was right, probably.' },
      jaguar: { who: 'Jaguar', text: '“Good.” The door swings. He rolls his shoulders, looks at the guards, looks at you. “I am Jaguar. I kill… later. First, the pickle and I have words.”' },
      picklerick: { who: 'Pickle Rick', text: '“MORTY. Look at me. I’m a pickle. I’ve killed eleven rats and a man named Konstantin and I am having the time of my life. Don’t tell your mother. Tell her it’s therapy.”' },
      agencyscreen: { who: null, text: 'Screens: corridors, a sewer, a laser grid, and one camera pointed at a jar of brine with a face in it.' },
      sewer: { who: null, text: 'A hole in the floor into the sewer, ringed with rat parts, screws and a tiny welded exoskeleton. He built that. Down there. As a pickle.' },
    },
    collect: { task: 'agency', spots: ['cellkey', 'jaguar'] },
    acts: { jaguar: 'unlocked' },
    goal: 'cellkey',
    caught: 'A guard’s rifle butt catches you across the shoulders. You come round by the door, the key back on its hook, Jaguar back in his cell, Pickle Rick laughing.',
    kinds: ['jaguar', 'pickle', 'agencyguard', 'sewerrat'],
  }),
  place(32, {
    id: 'meeseeksgolf',
    name: 'The Meeseeks’ golf course',
    note: 'Where Jerry asked a Meeseeks to take two strokes off his game. They’ve been at it a while. Existence is pain.',
    kind: 'outdoor',
    deep: 50,
    wide: 70,
    sky: { top: 0x3a8ad8, mid: 0x9ad8f8, low: 0xf2f2e0, sun: 0xfff8e8, clouds: 1, moons: 0 },
    people: [{ id: 'gjerry2', who: 'jerry', dx: 0, dz: -6, face: S, ai: { watch: 8, bark: { r: 5, every: 12, lines: ['Keep your shoulders square? I AM keeping them square! Look at them!', 'Morty, make them stop. Tell them I’m fine. Tell them I don’t even like golf.'] } } }],
    extras: [
      { kind: 'meeseeks', dx: -4, dz: -8, face: E, ai: { watch: 9, bark: { r: 6, every: 9, lines: ['I’m Mr. Meeseeks! Look at me! Keep your shoulders square, Jerry!', 'Existence is pain to a Meeseeks, Morty!'] }, hunt: { speed: 3.2, catchR: 1.2 } } },
      { kind: 'meeseeks', dx: 4, dz: -8, face: W, ai: { watch: 9, bark: { r: 6, every: 10, lines: ['Ooh, he’s trying! Can do, Jerry! Caaan do!'] }, hunt: { speed: 3.0, catchR: 1.2 } } },
      { kind: 'meeseeks', dx: -10, dz: 2, face: E, ai: { wander: [[-10, 2], [-6, 6], [-14, 6]], speed: 1.2, pause: 2, hunt: { speed: 3.1, catchR: 1.2 } } },
      { kind: 'meeseeks', dx: 10, dz: 2, face: W, ai: { wander: [[10, 2], [6, 6], [14, 6]], speed: 1.2, pause: 2, hunt: { speed: 3.1, catchR: 1.2 } } },
      { kind: 'meeseeks', dx: 0, dz: 10, face: N, ai: { wander: [[0, 10], [4, 13], [-4, 13]], speed: 1.3, pause: 1.5, hunt: { speed: 3.3, catchR: 1.2 } } },
      { kind: 'meeseeks', dx: -18, dz: -10, face: E, ai: { wander: [[-18, -10], [-22, -4], [-14, -4]], speed: 1.1, pause: 2, hunt: { speed: 3.0, catchR: 1.2 } } },
    ],
    spots: [
      { id: 'gjerry2', dx: 0, dz: -4.4, label: 'Jerry, at the tee', verb: 'Talk' },
      { id: 'meeseeksbox2', dx: 14, dz: -12, label: 'The Meeseeks box', verb: 'Press', r: 1.6 },
      { id: 'hole9', dx: -20, dz: -16, label: 'The ninth hole', verb: 'Look', r: 2 },
      { id: 'golfcart', dx: 18, dz: 8, label: 'A golf cart', verb: 'Look', r: 2.2 },
    ],
    solids: [
      { id: 'box', dx: 14, dz: -13.6, w: 1.2, d: 1.2 },
      { id: 'cart', dx: 18, dz: 10, w: 3, d: 1.8 },
      { id: 'tree-a', dx: -24, dz: 6, r: 1.2 },
      { id: 'tree-b', dx: 26, dz: -8, r: 1.2 },
      { id: 'bunker', dx: 10, dz: -16, r: 3 },
    ],
    tasks: [{ id: 'meeseeksgolf', name: 'Get the Meeseeks off Jerry', hint: 'Dial the Meeseeks’ golf course on the portal gun, and press the box to end it. Once you do, every Meeseeks on the course wants the next job to be you. Get home.' }],
    say: {
      gjerry2: { who: 'Jerry', text: '“Two strokes, Morty. I asked for two strokes. There are six of them now. One of them is inside my swing. I can feel him in there.”' },
      meeseeksbox2: { who: null, text: 'You press the box. Another Meeseeks pops into being, looks at the six already here, and says “Oh, no.” Then every one of them turns to look at you. Run.' },
      hole9: { who: null, text: 'The ninth hole. The flag is a Meeseeks, holding very still, because somebody told it to.' },
      golfcart: { who: null, text: 'A golf cart with four Meeseeks in it, all driving. It goes nowhere. It has been going nowhere for an hour.' },
    },
    acts: { meeseeksbox2: 'swarm' },
    escape: { spot: 'meeseeksbox2', s: 45, task: 'meeseeksgolf' },
    caught: 'Six blue hands take hold of you at once. “Caaan do!” They walk you very helpfully back to the portal, and let go, and stand there, waiting for a job.',
    kinds: ['jerry', 'meeseeks'],
  }),
  place(33, {
    id: 'vat',
    name: 'The vat of acid',
    note: 'Rick’s fake vat of acid, for getting out of a deal. It only works if everyone believes it. Morty didn’t.',
    kind: 'room',
    deep: 24,
    wide: 26,
    ceiling: 7,
    people: [
      { id: 'vrick', who: 'rick', dx: -6, dz: -8, face: E, ai: { watch: 10, bark: { r: 6, every: 12, lines: ['It’s a vat of fake acid, Morty. You jump in, you lie on the bottom, they leave. It’s elegant.', 'Don’t breathe through the straw where they can see you. That’s the one rule.'] } } },
      { id: 'vgromflomite-a', who: 'gromflomite', dx: 6, dz: -8, face: W, ai: { watch: 8, bark: { r: 5, every: 15, lines: ['Where is the crystal, Sanchez? Nobody leaves till we have the crystal.'] } } },
      { id: 'vgromflomite-b', who: 'gromflomite', dx: 8, dz: -4, face: W, ai: { watch: 8 } },
    ],
    spots: [
      { id: 'vatrim', dx: 0, dz: -2, label: 'The vat', verb: 'Jump in', r: 2.2 },
      { id: 'vrick', dx: -6, dz: -6.4, label: 'Rick', verb: 'Talk' },
      { id: 'vatcrystal', dx: -9, dz: 4, label: 'A crystal in a case', verb: 'Look', r: 1.6 },
      { id: 'vatbones', dx: 0, dz: -8.6, label: 'Fake bones', verb: 'Look', r: 1.4 },
    ],
    solids: [
      { id: 'vat', dx: 0, dz: -4, r: 2.6 },
      { id: 'shelf', dx: 0, dz: -10.2, w: 2.4, d: 0.5 },
      { id: 'case', dx: -10, dz: 4, w: 1.2, d: 1.2 },
      { id: 'barrel-a', dx: 9, dz: 6, r: 0.6 },
      { id: 'barrel-b', dx: 10, dz: 4.4, r: 0.6 },
    ],
    tasks: [{ id: 'vat', name: 'Fake your death in the vat', hint: 'Dial the vat of acid on the portal gun, talk to Rick, and jump in. Lie still.' }],
    say: {
      vrick: { who: 'Rick', text: '“Here’s the plan, Morty. We jump in, we lie at the bottom, we breathe through the straws, they think we dissolved, they leave. Don’t make the face. I know you’re going to make the face.”' },
      vatrim: { who: null, text: 'You jump. It’s warm and green and tastes of lime. You lie on the bottom with a straw in your mouth while fake bones float past. The Gromflomites peer in, say “gross”, and go. Rick says, muffled, “Told you.”' },
      vatcrystal: { who: null, text: 'The crystal everyone’s here about, in a glass case marked PROPERTY OF R. SANCHEZ, which is how Rick says “stolen”.' },
      vatbones: { who: null, text: 'Bones on a shelf by the vat, foam ones, painted. A little sign says BONES (FAKE) in Rick’s handwriting. He’s very proud of the bones.' },
    },
    collect: { task: 'vat', spots: ['vrick', 'vatrim'] },
    acts: { vatrim: 'splash' },
    goal: 'vrick',
    kinds: ['rick', 'gromflomite'],
  }),
  place(34, {
    id: 'dim35c',
    name: 'Dimension 35-C',
    note: 'The pilot’s forest of Mega Trees, where the seeds grow. Rick wanted them bad enough to send Morty up a tree.',
    kind: 'outdoor',
    deep: 50,
    wide: 70,
    sky: { top: 0x1a3a6a, mid: 0x5a9ad8, low: 0xc8e8f0, sun: 0xfff0d8, clouds: 1, moons: 2 },
    people: [{ id: 'drick', who: 'rick', dx: 0, dz: -12, face: S, ai: { watch: 10, bark: { r: 6, every: 12, lines: ['Mega Trees, Morty. Mega Seeds. Up you go. I’d do it but I have a bad back from being right all the time.', 'Don’t eat them. Whatever you do, don’t eat them, and don’t ask why I know that.'] } } }],
    extras: [
      { kind: 'gromflomite', dx: 16, dz: 4, face: W, ai: { wander: [[16, 4], [22, 10], [12, 12]], speed: 1.2, pause: 2, hunt: { speed: 3.0, catchR: 1.3, near: 5, lose: 9 } } },
      { kind: 'gromflomite', dx: -18, dz: 8, face: E, ai: { wander: [[-18, 8], [-24, 2], [-14, -2]], speed: 1.1, pause: 2.5, hunt: { speed: 3.0, catchR: 1.3, near: 5, lose: 9 } } },
    ],
    spots: [
      { id: 'drick', dx: 0, dz: -10.4, label: 'Rick', verb: 'Talk' },
      { id: 'seed1', dx: -12, dz: -14, label: 'A Mega Seed, low on a trunk', verb: 'Pick', r: 1.6 },
      { id: 'seed2', dx: 14, dz: -16, label: 'A Mega Seed, among the roots', verb: 'Pick', r: 1.6 },
      { id: 'seed3', dx: -20, dz: 10, label: 'A Mega Seed, fallen', verb: 'Pick', r: 1.6 },
      { id: 'megatree', dx: 0, dz: -22, label: 'A Mega Tree', verb: 'Look', r: 3 },
    ],
    solids: [
      { id: 'tree-a', dx: 0, dz: -24, r: 3.2 },
      { id: 'tree-b', dx: -14, dz: -16, r: 2.6 },
      { id: 'tree-c', dx: 16, dz: -18, r: 2.8 },
      { id: 'tree-d', dx: -22, dz: 12, r: 2.4 },
      { id: 'tree-e', dx: 24, dz: 14, r: 2.6 },
      { id: 'tree-f', dx: 26, dz: -6, r: 2.2 },
      { id: 'root-a', dx: 8, dz: -8, r: 1 },
      { id: 'root-b', dx: -8, dz: 2, r: 1 },
    ],
    tasks: [{ id: 'dim35c', name: 'Pick three Mega Seeds', hint: 'Dial Dimension 35-C on the portal gun, and pick three Mega Seeds from the trees. The Federation patrols the forest; don’t let them get close.' }],
    say: {
      drick: { who: 'Rick', text: '“Three seeds, Morty. Three. Then we get through customs, and I don’t want to hear about where they go.” He belches, and a bird falls out of a tree.' },
      seed1: { who: null, text: 'A Mega Seed, the size of a melon, warm. You pull it off the trunk and it comes with a sound like a kiss.' },
      seed2: { who: null, text: 'A Mega Seed among the roots. Something with twelve legs was sitting on it. It lets you have it.' },
      seed3: { who: null, text: 'A fallen Mega Seed, a little soft. Rick says the soft ones are the good ones. Rick says a lot of things.' },
      megatree: { who: null, text: 'A Mega Tree, as wide as a house and higher than the clouds, its bark glowing faintly where the seeds grow. Morty climbed one of these once and broke both legs. Rick had a serum.' },
    },
    collect: { task: 'dim35c', spots: ['seed1', 'seed2', 'seed3'] },
    goal: 'seed1',
    caught: 'A Gromflomite’s net drops over you. “Seeds. Of course.” They tip you out by the portal and keep the seeds.',
    kinds: ['rick', 'gromflomite'],
  }),
  place(35, {
    id: 'frundles',
    name: 'Mr. Frundles’ Earth',
    note: 'The Earth Rick brought Mr. Frundles home to. He bit the dog, the dog bit Jerry, and by Tuesday the houses had his face. Time to move.',
    kind: 'outdoor',
    deep: 50,
    wide: 70,
    sky: { top: 0x3a6aa8, mid: 0x8ab8e8, low: 0xf0e0d0, sun: 0xfff0d8, clouds: 1, moons: 0 },
    people: [
      { id: 'frick', who: 'rick', dx: 0, dz: 16, face: N, ai: { watch: 10, bark: { r: 6, every: 10, lines: ['Morty, get the family and get back here. Anything with his face, you don’t let it near you.', 'The portal’s open behind me. Fifty seconds, then I leave with whoever’s standing here.'] } } },
      { id: 'fsummer', who: 'summer', dx: -20, dz: -6, face: E, ai: { watch: 8, bark: { r: 5, every: 12, lines: ['Morty! The neighbours are… fuzzy. Get me out of here.'] } } },
      { id: 'fbeth', who: 'beth', dx: 22, dz: -10, face: W, ai: { watch: 8, bark: { r: 5, every: 12, lines: ['I am not leaving the horses. Fine. I am leaving the horses. Where’s your grandfather?'] } } },
      { id: 'fjerry', who: 'jerry', dx: 4, dz: -20, face: S, ai: { watch: 8, bark: { r: 5, every: 12, lines: ['It bit me a little, Morty. A little. Is a little bad? Morty, is a little bad?'] } } },
    ],
    extras: [
      { kind: 'frundleshouse', dx: -16, dz: -18, face: S },
      { kind: 'frundleshouse', dx: 18, dz: -20, face: S },
      { kind: 'frundleshouse', dx: 28, dz: 4, face: W },
      { kind: 'frundlesman', dx: -8, dz: -8, face: E, ai: { wander: [[-8, -8], [-2, -12], [-12, -14], [-14, -2]], speed: 1.1, pause: 1.2, hunt: { speed: 3.0, catchR: 1.2, near: 5, lose: 9 } } },
      { kind: 'frundlesman', dx: 12, dz: -2, face: W, ai: { wander: [[12, -2], [16, -10], [8, -14], [4, -4]], speed: 1.0, pause: 1.5, hunt: { speed: 3.0, catchR: 1.2, near: 5, lose: 9 } } },
      { kind: 'frundlesman', dx: -22, dz: 8, face: E, ai: { wander: [[-22, 8], [-12, 10], [-14, 2], [-26, 0]], speed: 1.2, pause: 1, hunt: { speed: 3.1, catchR: 1.2, near: 5, lose: 9 } } },
      { kind: 'frundlesdog', dx: 20, dz: 10, face: W, ai: { wander: [[20, 10], [10, 14], [6, 6], [16, 2]], speed: 1.8, pause: 0.6, hunt: { speed: 3.6, catchR: 1.0, near: 4, lose: 7 } } },
      { kind: 'frundles', dx: -4, dz: 4, face: S, ai: { wander: [[-4, 4], [2, 8], [-8, 10], [-2, 0]], speed: 1.3, pause: 0.8, hunt: { speed: 2.8, catchR: 0.8, near: 3, lose: 6 } } },
      { kind: 'frundles', dx: 24, dz: -4, face: W, ai: { wander: [[24, -4], [28, -12], [20, -14], [16, -6]], speed: 1.3, pause: 0.8, hunt: { speed: 2.8, catchR: 0.8, near: 3, lose: 6 } } },
      { kind: 'frundles', dx: -26, dz: -12, face: E, ai: { wander: [[-26, -12], [-30, -4], [-24, 2]], speed: 1.2, pause: 1, hunt: { speed: 2.8, catchR: 0.8, near: 3, lose: 6 } } },
      { kind: 'frundles', dx: 8, dz: 18, face: N, ai: { wander: [[8, 18], [14, 20], [12, 12]], speed: 1.4, pause: 0.7 } },
    ],
    spots: [
      { id: 'frick', dx: 0, dz: 14.4, label: 'Rick, at the portal', verb: 'Talk' },
      { id: 'fsummer', dx: -18.4, dz: -6, label: 'Summer', verb: 'Get', r: 1.6 },
      { id: 'fbeth', dx: 20.4, dz: -10, label: 'Beth', verb: 'Get', r: 1.6 },
      { id: 'fjerry', dx: 4, dz: -18.4, label: 'Jerry', verb: 'Get', r: 1.6 },
      { id: 'frundleshouse', dx: -16, dz: -13.6, label: 'The house next door', verb: 'Look', r: 2.2 },
    ],
    solids: [
      { id: 'house-a', dx: -16, dz: -19, w: 9, d: 7 },
      { id: 'house-b', dx: 18, dz: -21, w: 9, d: 7 },
      { id: 'house-c', dx: 29, dz: 4, w: 7, d: 9 },
      { id: 'hedge-a', dx: -8, dz: -22, w: 10, d: 1 },
      { id: 'hedge-b', dx: 10, dz: 6, w: 1, d: 8 },
      { id: 'mailbox', dx: -12, dz: -10, r: 0.4 },
      { id: 'tree-a', dx: -30, dz: 14, r: 1.6 },
      { id: 'tree-b', dx: 30, dz: 16, r: 1.6 },
    ],
    tasks: [{ id: 'frundles', name: 'Move the family off Mr. Frundles’ Earth', hint: 'Dial Mr. Frundles’ Earth on the portal gun. Get Summer, Beth and Jerry, then make the portal before the clock runs out, clear of anything with his face.' }],
    say: {
      frick: { who: 'Rick', text: '“I said don’t let him bite anything. One bite. One. Now the planet’s a Frundles.” He checks the portal gun. “New Earth, same house. The Jerry there’ll be fine. Get the others.”' },
      fsummer: { who: 'Summer', text: '“Finally.” She hitches her bag and runs for Rick. “If my room on the new one is smaller I’m going back.”' },
      fbeth: { who: 'Beth', text: '“Okay. Okay.” A look at the house. A look at the house’s face. “Go. I’m right behind you.”' },
      fjerry: { who: 'Jerry', text: '“Oh thank God.” He holds up a hand with a tiny bandage on it. “It’s nothing. It’s a scratch. Why are you looking at it like that?”' },
      frundleshouse: { who: null, text: 'The Hendersons’ house. It has his eyes now, big and black and wet, and the porch is a mouth, and it looks very happy to see you.' },
    },
    collect: { task: 'frundles', spots: ['fsummer', 'fbeth', 'fjerry'], escape: { s: 50 } },
    goal: 'fsummer',
    caught: 'A soft fuzzy thing gets its mouth round your ankle. Everything goes warm and brown and friendly. You come round by the portal, Rick slapping you: “Not yet. NOT yet.”',
    spotted: 'Something with his face has seen you, and it’s so pleased.',
    kinds: ['rick', 'summer', 'beth', 'jerry', 'frundles', 'frundlesman', 'frundlesdog', 'frundleshouse'],
  }),
];
