"""Builds public/audio/tabla.mp3 and src/components/music/tablaSprite.js: the
music room's tabla, as one audio sprite of real strokes.

The strokes are dio_333's tabla recordings, from Freesound by way of Sonic
Pi's sample library, which publishes them under CC0 (public domain):
https://github.com/sonic-pi-net/sonic-pi/tree/<SONIC_PI>/etc/samples

Each stroke is trimmed to its onset, its tail cut where it falls below
-54 dB and faded, and its level matched on the first 120 ms (the part the
ear judges loudness by), so the engine can mix them by bol alone. They sit
in one file, an eighth of a second apart, so the drum loads in one request and
one decode.

Run: python3 scripts/build-tabla.py   (needs ffmpeg with libmp3lame, and numpy)
"""

import json
import pathlib
import subprocess
import urllib.request

import numpy as np

ROOT = pathlib.Path(__file__).resolve().parent.parent
SONIC_PI = 'b1702c06bf80354b9135b2427e985777251641e0'
URL = f'https://raw.githubusercontent.com/sonic-pi-net/sonic-pi/{SONIC_PI}/etc/samples/{{}}.flac'
CACHE = ROOT / 'node_modules/.cache/tabla'
OUT_AUDIO = ROOT / 'public/audio/tabla.mp3'
OUT_JS = ROOT / 'src/components/music/tablaSprite.js'
SR = 44100
GAP = 0.12  # seconds of silence between strokes
TARGET_RMS_DB = -17.0

# name: longest it may ring (seconds). Everything dio_333 recorded but tabla_dhec,
# whose crack is a compound stroke the engine builds from its parts instead.
STROKES = {
    'tabla_na': 0.7,
    'tabla_na_s': 0.3,
    'tabla_na_o': 1.4,
    'tabla_tas1': 1.0,
    'tabla_tas2': 1.1,
    'tabla_tas3': 1.0,
    'tabla_tun1': 1.7,
    'tabla_tun2': 1.7,
    'tabla_tun3': 1.7,
    'tabla_te1': 0.2,
    'tabla_te2': 0.3,
    'tabla_te_m': 0.3,
    'tabla_te_ne': 0.16,
    'tabla_re': 0.3,
    'tabla_ke1': 0.06,
    'tabla_ke2': 0.06,
    'tabla_ke3': 0.09,
    'tabla_ghe1': 0.6,
    'tabla_ghe2': 2.0,
    'tabla_ghe3': 2.0,
    'tabla_ghe4': 0.8,
    'tabla_ghe5': 2.1,
    'tabla_ghe6': 2.1,
    'tabla_ghe7': 1.9,
    'tabla_ghe8': 0.6,
}


def fetch(name):
    CACHE.mkdir(parents=True, exist_ok=True)
    path = CACHE / f'{name}.flac'
    if not path.exists():
        with urllib.request.urlopen(URL.format(name)) as r:
            path.write_bytes(r.read())
    return path


def decode(path):
    raw = subprocess.run(
        ['ffmpeg', '-v', 'error', '-i', str(path), '-ac', '1', '-ar', str(SR), '-f', 'f32le', '-'],
        check=True,
        capture_output=True,
    ).stdout
    return np.frombuffer(raw, dtype=np.float32).astype(np.float64)


def db(x):
    return 20 * np.log10(max(x, 1e-12))


def prepare(x, longest):
    peak = np.abs(x).max()
    onset = int(np.argmax(np.abs(x) > 0.02 * peak))
    x = x[max(0, onset - int(0.002 * SR)) :]
    # the tail: where a 50 ms window last stays within 54 dB of the peak
    hop = int(0.01 * SR)
    win = int(0.05 * SR)
    env = np.array([np.sqrt(np.mean(x[i : i + win] ** 2)) for i in range(0, max(1, len(x) - win), hop)])
    alive = np.where(env > env.max() * 10 ** (-54 / 20))[0]
    end = min(len(x), (alive[-1] * hop + win) if len(alive) else len(x), int(longest * SR))
    x = x[:end].copy()
    fade = min(int(0.06 * SR), end // 3)
    x[end - fade :] *= np.cos(np.linspace(0, np.pi / 2, fade)) ** 2
    # match loudness on the first 120 ms, without letting any stroke clip
    head = x[: min(len(x), int(0.12 * SR))]
    gain = 10 ** ((TARGET_RMS_DB - db(np.sqrt(np.mean(head**2)))) / 20)
    gain = min(gain, 0.89 / np.abs(x).max())
    return x * gain


def main():
    parts = [np.zeros(int(GAP * SR))]
    slots = {}
    at = GAP
    for name, longest in STROKES.items():
        x = prepare(decode(fetch(name)), longest)
        slots[name.removeprefix('tabla_')] = [round(at, 4), round(len(x) / SR, 4)]
        parts += [x, np.zeros(int(GAP * SR))]
        at += len(x) / SR + GAP
    sprite = np.concatenate(parts).astype(np.float32)
    OUT_AUDIO.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        ['ffmpeg', '-v', 'error', '-y', '-f', 'f32le', '-ar', str(SR), '-ac', '1', '-i', '-', '-c:a', 'libmp3lame', '-b:a', '96k', str(OUT_AUDIO)],
        input=sprite.tobytes(),
        check=True,
    )
    OUT_JS.write_text(
        '// Generated by scripts/build-tabla.py: where each stroke starts in\n'
        '// public/audio/tabla.mp3 and how long it rings, in seconds.\n'
        '// dio_333\'s tabla, from Freesound via Sonic Pi\'s sample library (CC0).\n'
        f'export const TABLA_URL = \'/audio/tabla.mp3\';\n'
        'export const TABLA_SLOTS = {\n' + ''.join(f'  {k}: {json.dumps(v)},\n' for k, v in slots.items()) + '};\n'
    )
    print(f'{OUT_AUDIO.relative_to(ROOT)}: {len(sprite) / SR:.1f} s, {OUT_AUDIO.stat().st_size // 1024} KB, {len(slots)} strokes')


if __name__ == '__main__':
    main()
