// Builds src/data/globe.js: the dotted globe in "Places I've been".
//
// Points are spread evenly over the sphere on a Fibonacci lattice. Each one is
// tested against Natural Earth's 1:50m country outlines (public domain, via the
// world-atlas package); the land points remember which country they fall in.
// The browser rebuilds the same lattice from its size alone, so the file only
// needs one bit per point and a short code per land point. No map library ships
// to the browser.
//
// Run with: node scripts/build-globe.mjs  (re-run after editing PLACES)
import { readFile, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { geoBounds, geoContains, geoDistance } from 'd3-geo';
import { feature } from 'topojson-client';
import { fibonacciPoint, CODE_ALPHABET } from '../src/data/globe-lattice.js';
import { PLACES } from '../src/data/places.js';

const require = createRequire(import.meta.url);
const topo = JSON.parse(await readFile(require.resolve('world-atlas/countries-50m.json'), 'utf8'));

const N = 24000; // lattice size: about 1.3° between neighbouring points

const countries = feature(topo, topo.objects.countries).features.filter((f) => f.id !== '010'); // no Antarctica
const names = countries.map((f) => f.properties.name);
const boxes = countries.map((f) => geoBounds(f));

const inBox = ([lon, lat], [[w, s], [e, n]]) => lat >= s - 0.5 && lat <= n + 0.5 && (w <= e ? lon >= w - 0.5 && lon <= e + 0.5 : lon >= w - 0.5 || lon <= e + 0.5);

const land = new Uint8Array(Math.ceil(N / 8));
const owner = new Int16Array(N).fill(-1);
for (let i = 0; i < N; i++) {
  const ll = fibonacciPoint(i, N);
  for (let c = 0; c < countries.length; c++) {
    if (!inBox(ll, boxes[c])) continue;
    if (geoContains(countries[c], ll)) {
      owner[i] = c;
      land[i >> 3] |= 1 << (i & 7);
      break;
    }
  }
}

// Small countries can slip between lattice points: give each visited country at
// least the lattice point nearest its marker.
const placeCountry = {};
for (const p of PLACES) {
  if (!p.iso) continue;
  const c = countries.findIndex((f) => f.id === p.iso);
  if (c < 0) throw new Error(`No country with id ${p.iso} (${p.name})`);
  placeCountry[p.id] = c;
  if (owner.some((o) => o === c)) continue;
  let best = 0;
  let bestD = Infinity;
  for (let i = 0; i < N; i++) {
    const d = geoDistance(fibonacciPoint(i, N), p.at);
    if (d < bestD) {
      bestD = d;
      best = i;
    }
  }
  owner[best] = c;
  land[best >> 3] |= 1 << (best & 7);
}

let codes = '';
let count = 0;
for (let i = 0; i < N; i++) {
  if (owner[i] < 0) continue;
  codes += CODE_ALPHABET[owner[i] >> 6] + CODE_ALPHABET[owner[i] & 63];
  count++;
}

const data = {
  n: N,
  land: Buffer.from(land).toString('base64'),
  owner: codes,
  names,
  placeCountry,
};
const out = `// Generated by scripts/build-globe.mjs from Natural Earth (public domain, via world-atlas).
// Do not edit by hand: change PLACES there and run \`node scripts/build-globe.mjs\`.
export const GLOBE = ${JSON.stringify(data)};
`;
await writeFile(new URL('../src/data/globe.js', import.meta.url), out);
console.log(`globe.js: ${count} land points of ${N}, ${names.length} countries, ${out.length} bytes`);
for (const p of PLACES) if (p.iso) console.log(`  ${p.name}: ${owner.filter((o) => o === placeCountry[p.id]).length} points`);
