"""Builds public/audio/sitar/*.mp3 and src/components/music/sitarSamples.js:
the sitar's notes across its whole neck, from mandra Pa to taar Ga.

The source is two strokes of one note (D4) on a real sitar by chinpen
(Freesound, CC BY 3.0): scripts/data/sitar/sitar-d4-1.mp3 (a Da, the inward
stroke) and sitar-d4-2.mp3 (a Ra, the outward one). Each is pitch-shifted
with Rubber Band to every fourth semitone from an octave below to sixteen
semitones above, keeping its length and its body's resonances (formants), as
a higher fret on the same instrument would. The engine then retunes the
nearest of these by two semitones at most, so no note is a sped-up or
slowed-down recording.

Run: python3 scripts/build-sitar.py   (needs ffmpeg with librubberband and libmp3lame, and numpy)
"""

import pathlib
import subprocess

import numpy as np

ROOT = pathlib.Path(__file__).resolve().parent.parent
SR = 44100
SOURCES = [('scripts/data/sitar/sitar-d4-1.mp3', 292.4), ('scripts/data/sitar/sitar-d4-2.mp3', 291.9)]
SHIFTS = [-12, -8, -4, 0, 4, 8, 12, 16]
LONGEST = 2.9  # seconds; the tail below -40 dB is faded
GAP = 0.12
OUT_DIR = ROOT / 'public/audio/sitar'
OUT_JS = ROOT / 'src/components/music/sitarSamples.js'
RB = 'rubberband=pitch={}:formant=preserved:pitchq=quality:transients=crisp:detector=percussive:window=standard:phase=laminar'


def decode(path, shift):
    af = ['-af', RB.format(2 ** (shift / 12))] if shift else []
    raw = subprocess.run(
        ['ffmpeg', '-v', 'error', '-i', str(ROOT / path), *af, '-ac', '1', '-ar', str(SR), '-f', 'f32le', '-'],
        check=True,
        capture_output=True,
    ).stdout
    return np.frombuffer(raw, dtype=np.float32).astype(np.float64)


def prepare(x):
    peak = np.abs(x).max()
    onset = int(np.argmax(np.abs(x) > 0.03 * peak))
    x = x[max(0, onset - int(0.002 * SR)) :][: int(LONGEST * SR)].copy()
    fade = int(0.5 * SR)
    x[-fade:] *= np.cos(np.linspace(0, np.pi / 2, fade)) ** 2
    return x / np.abs(x).max() * 0.89


def name(shift):
    return f'{"m" if shift < 0 else "p"}{abs(shift)}'


def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    rows = []
    for shift in SHIFTS:
        parts = [np.zeros(int(GAP * SR))]
        takes = []
        at = GAP
        for path, hz in SOURCES:
            x = prepare(decode(path, shift))
            takes.append(f'[{round(at, 4)}, {round(len(x) / SR, 4)}, {round(hz * 2 ** (shift / 12), 2)}]')
            parts += [x, np.zeros(int(GAP * SR))]
            at += len(x) / SR + GAP
        out = OUT_DIR / f'{name(shift)}.mp3'
        subprocess.run(
            ['ffmpeg', '-v', 'error', '-y', '-f', 'f32le', '-ar', str(SR), '-ac', '1', '-i', '-', '-c:a', 'libmp3lame', '-b:a', '96k', str(out)],
            input=np.concatenate(parts).astype(np.float32).tobytes(),
            check=True,
        )
        rows.append(f"  {{ shift: {shift}, url: '/audio/sitar/{out.name}', takes: [{', '.join(takes)}] }},")
        print(f'{out.relative_to(ROOT)}: {out.stat().st_size // 1024} KB')
    OUT_JS.write_text(
        '// Generated by scripts/build-sitar.py: the sitar\'s notes, a file for every\n'
        '// fourth semitone, each with a Da and a Ra stroke as [start, length, pitch].\n'
        '// From two strokes on a real sitar by chinpen (Freesound, CC BY 3.0).\n'
        'export const SITAR_VARIANTS = [\n' + '\n'.join(rows) + '\n];\n'
    )


if __name__ == '__main__':
    main()
