// Makes the travel photos: every entry in scripts/photo-sources.json becomes a
// few small WebP files in public/photos/, and src/data/photos.js records each
// photo's size, alt text and credit.
//
// A source is `commons` (a freely licensed Wikimedia Commons file, whose author
// and licence are read from Commons and credited on the page), `url` (a photo
// used with its owner's permission, credited as the entry says) or `file`
// (a photo of your own, relative to the project root, credited to you). An
// optional `author` replaces a long or awkward author line from Commons.
//
// Run:   node scripts/photos.mjs          (everything)
//        node scripts/photos.mjs is no    (only these ids)
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import sharp from 'sharp';

const ROOT = new URL('..', import.meta.url);
const OUT_DIR = new URL('public/photos/', ROOT);
const DATA = new URL('src/data/photos.js', ROOT);
const UA = 'tilakpatell.com photo script (https://tilakpatell.com)';
const OWNER = 'Tilak Patel';

const sources = JSON.parse(await readFile(new URL('scripts/photo-sources.json', ROOT), 'utf8'));
delete sources._readme;
const only = process.argv.slice(2);

const existing = await import(`${DATA.href}?t=${Date.now()}`).then((m) => m.PHOTOS).catch(() => ({}));
const photos = { ...existing };

const strip = (html = '') =>
  html
    .replace(/<[^>]+>/g, '')
    .replace(/&amp;/g, '&')
    .replace(/&quot;/g, '"')
    .replace(/&#039;/g, "'")
    .replace(/\s+/g, ' ')
    .trim();

async function commons(title, width, authorOverride) {
  const api = `https://commons.wikimedia.org/w/api.php?action=query&format=json&prop=imageinfo&iiprop=url|extmetadata|size&iiurlwidth=${width}&titles=${encodeURIComponent(title)}`;
  const res = await fetch(api, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`Commons API ${res.status} for ${title}`);
  const page = Object.values((await res.json()).query.pages)[0];
  const info = page?.imageinfo?.[0];
  if (!info) throw new Error(`No such Commons file: ${title}`);
  const meta = info.extmetadata || {};
  const img = await fetch(info.thumburl || info.url, { headers: { 'User-Agent': UA } });
  if (!img.ok) throw new Error(`Download ${img.status} for ${title}`);
  return {
    buffer: Buffer.from(await img.arrayBuffer()),
    credit: {
      author: authorOverride || strip(meta.Artist?.value) || 'Unknown',
      license: strip(meta.LicenseShortName?.value) || 'See source',
      licenseUrl: meta.LicenseUrl?.value || null,
      source: info.descriptionurl,
      title: title.replace(/^File:/, '').replace(/\.[a-z]+$/i, ''),
    },
  };
}

// A photo used with permission from its owner's site: the entry supplies the
// credit (`author`, `license`, and the `source` page it came from).
async function direct(src) {
  const img = await fetch(src.url, { headers: { 'User-Agent': UA } });
  if (!img.ok) throw new Error(`Download ${img.status} for ${src.url}`);
  return {
    buffer: Buffer.from(await img.arrayBuffer()),
    credit: { author: src.author, license: src.license ?? null, licenseUrl: null, source: src.source ?? src.url, title: src.title ?? null },
  };
}

await mkdir(OUT_DIR, { recursive: true });
for (const [id, src] of Object.entries(sources)) {
  if (only.length && !only.includes(id)) continue;
  const max = Math.max(...src.widths);
  const { buffer, credit } = src.commons
    ? await commons(src.commons, max, src.author)
    : src.url
      ? await direct(src)
      : { buffer: await readFile(new URL(src.file, ROOT)), credit: { author: OWNER, license: null, licenseUrl: null, source: null, title: null } };
  const base = sharp(buffer).rotate(); // honour EXIF orientation from phones
  const meta = await base.metadata();
  const ratio = meta.height / meta.width;
  let bytes = 0;
  for (const w of src.widths) {
    const out = await base
      .clone()
      .resize({ width: Math.min(w, meta.width), withoutEnlargement: true })
      .webp({ quality: w >= 1600 ? 68 : 72, effort: 6 })
      .toBuffer();
    bytes += out.length;
    await writeFile(new URL(`${id}-${w}.webp`, OUT_DIR), out);
  }
  photos[id] = { widths: src.widths, ratio: Math.round(ratio * 1000) / 1000, alt: src.alt, credit };
  console.log(`${id.padEnd(10)} ${src.widths.join('/')}px  ${Math.round(bytes / 1024)} KB  ${credit.author} (${credit.license ?? 'own photo'})`);
  if (!src.file) await new Promise((r) => setTimeout(r, 400)); // be gentle with the source
}

const ordered = Object.fromEntries(Object.keys(sources).filter((id) => photos[id]).map((id) => [id, photos[id]]));
await writeFile(
  DATA,
  `// Generated by scripts/photos.mjs from scripts/photo-sources.json. Do not edit by hand.\nexport const PHOTOS = ${JSON.stringify(ordered, null, 2)};\n`,
);
console.log(`\nWrote ${Object.keys(ordered).length} photos to public/photos/ and src/data/photos.js`);
