// The parts of the station you can click on, placed on the 680×400 scene.
// Each has what happens there in A New Hope, and the line it's known for.
export const PARTS = [
  {
    id: 'superlaser',
    x: 462,
    y: 160,
    name: 'Superlaser',
    text: 'Eight tributary beams meet at the focus lens above the dish. One shot is enough for a planet.',
    quote: ['You may fire when ready.', 'Grand Moff Tarkin'],
    gif: 'alderaan',
    action: 'fire',
  },
  {
    id: 'port',
    x: 560,
    y: 96,
    name: 'Thermal exhaust port',
    text: 'Two metres wide, right below the main port. A direct hit starts a chain reaction in the main reactor.',
    quote: ['Use the Force, Luke.', 'Obi-Wan Kenobi'],
    gif: 'yavin',
    action: 'trench',
  },
  {
    id: 'trench',
    x: 620,
    y: 232,
    name: 'Equatorial trench',
    text: 'A canyon of turbolaser towers that runs around the station: the only way in to the exhaust port.',
    quote: ['Stay on target.', 'Gold Five'],
    gif: 'trenchRun',
    action: 'trench',
  },
  {
    id: 'tractor',
    x: 612,
    y: 150,
    name: 'Tractor beam',
    text: 'It caught the Millennium Falcon. Obi-Wan slipped past the guards and switched off a power coupling so it could leave.',
    quote: ['The Force will be with you. Always.', 'Obi-Wan Kenobi'],
  },
  {
    id: 'hangar',
    x: 596,
    y: 300,
    name: 'Docking bay 327',
    text: 'Where the tractor beam pulled the Falcon in, and where it escaped from with the princess aboard.',
    quote: ['That’s no moon. It’s a space station.', 'Obi-Wan Kenobi'],
  },
  {
    id: 'detention',
    x: 414,
    y: 268,
    name: 'Detention block AA-23',
    text: 'Princess Leia was held in cell 2187 until Luke and Han came for her in borrowed armour.',
    quote: ['Aren’t you a little short for a stormtrooper?', 'Princess Leia'],
  },
  {
    id: 'compactor',
    x: 500,
    y: 330,
    name: 'Trash compactor 3263827',
    text: 'The rescue party’s way out of the detention block. The walls close in, and something lives in the water.',
    quote: ['I’ve got a bad feeling about this.', 'Han Solo'],
  },
  {
    id: 'conference',
    x: 512,
    y: 210,
    name: 'Conference room',
    text: 'Where the Imperial commanders meet, and where Admiral Motti doubts the Force out loud.',
    quote: ['I find your lack of faith disturbing.', 'Darth Vader'],
  },
];
