// The parts of the station you can open on the technical readout. `bx`/`by`
// place each one on the 400×400 cutaway blueprint. Each has what happens there
// in A New Hope, and the line it's known for.
export const PARTS = [
  {
    id: 'superlaser',
    bx: 138,
    by: 136,
    name: 'Superlaser',
    text: 'Eight tributary beams meet at the focus lens above the dish. One shot is enough for a planet.',
    quote: ['You may fire when ready.', 'Grand Moff Tarkin'],
    gif: 'alderaan',
    action: 'fire',
  },
  {
    id: 'port',
    bx: 286,
    by: 58,
    name: 'Thermal exhaust port',
    text: 'Two metres wide, right below the main port. The shaft leads straight down to the reactor.',
    quote: ['Use the Force, Luke.', 'Obi-Wan Kenobi'],
    gif: 'yavin',
    action: 'trench',
  },
  {
    id: 'trench',
    bx: 366,
    by: 200,
    name: 'Equatorial trench',
    text: 'A canyon of turbolaser towers that runs around the station: the only way in to the exhaust port.',
    quote: ['Stay on target.', 'Gold Five'],
    gif: 'trenchRun',
    action: 'trench',
  },
  {
    id: 'reactor',
    bx: 200,
    by: 200,
    name: 'Main reactor',
    text: 'The hypermatter core that powers the superlaser. One torpedo down the exhaust shaft starts a chain reaction here.',
    quote: ['Look at the size of that thing!', 'Wedge Antilles'],
    action: 'trench',
  },
  {
    id: 'tractor',
    bx: 120,
    by: 262,
    name: 'Tractor beam',
    text: 'It caught the Millennium Falcon. Obi-Wan slipped past the guards and switched off a power coupling so it could leave.',
    quote: ['The Force will be with you. Always.', 'Obi-Wan Kenobi'],
  },
  {
    id: 'hangar',
    bx: 306,
    by: 238,
    name: 'Docking bay 327',
    text: 'Where the tractor beam pulled the Falcon in, and where it escaped from with the princess aboard.',
    quote: ['That’s no moon. It’s a space station.', 'Obi-Wan Kenobi'],
  },
  {
    id: 'detention',
    bx: 86,
    by: 176,
    name: 'Detention block AA-23',
    text: 'Princess Leia was held in cell 2187 until Luke and Han came for her in borrowed armour.',
    quote: ['Aren’t you a little short for a stormtrooper?', 'Princess Leia'],
  },
  {
    id: 'compactor',
    bx: 170,
    by: 318,
    name: 'Trash compactor 3263827',
    text: 'The rescue party’s way out of the detention block. The walls close in, and something lives in the water.',
    quote: ['I’ve got a bad feeling about this.', 'Han Solo'],
  },
  {
    id: 'conference',
    bx: 252,
    by: 124,
    name: 'Conference room',
    text: 'Where the Imperial commanders meet, and where Admiral Motti doubts the Force out loud.',
    quote: ['I find your lack of faith disturbing.', 'Darth Vader'],
  },
];
