// What the galaxy fetches (models, textures, skies, sound): the install's list (scripts/packs.mjs, src/runtime/install.js); scripts/pack-check.mjs fails when its source names an asset this misses.
export const PACK = {
  id: '/galaxy',
  pages: ['src/pages/Galaxy.jsx', 'src/pages/GalaxyMission.jsx', 'src/pages/GalaxySurface.jsx'], // page modules: the build adds their JS/CSS chunks
  src: [
    'src/components/galaxy',
    'src/pages/Galaxy.jsx',
    'src/pages/GalaxyMission.jsx',
    'src/pages/GalaxySurface.jsx',
    'src/components/universe/glbFleet.js',
    'src/components/universe/shipModels.js',
    'src/components/universe/sounds.js',
    'src/components/universe/trench.js',
  ], // where its source is (files or folders, repo-relative): pack-check scans these
  urls: [
    '/models/albuquerque/walt.glb',
    '/models/albuquerque/jesse.glb',
    '/models/cockpit/chewie.glb',
    '/audio/engines/xwing.mp3',
    '/audio/engines/falcon.mp3',
    '/audio/engines/cruiser.mp3',
    '/audio/engines/rv.mp3',
    '/models/sketchfab/falcon-hd.glb',
    '/models/sketchfab/xwing-hd.glb',
    '/models/universe/cr90.glb',
    '/models/universe/death-star.glb',
    '/models/universe/death-star.hq.glb',
    '/models/universe/falcon.glb',
    '/models/universe/rv-wings.glb',
    '/models/universe/slave1.glb',
    '/models/universe/star-destroyer.glb',
    '/models/universe/trench.glb',
    '/models/universe/venator.glb',
    '/audio/clips/its-a-trap.mp3',
    '/audio/clips/thats-no-moon.mp3',
    '/audio/clips/do-or-do-not.mp3',
    '/audio/clips/im-mr-meeseeks.mp3',
    '/audio/clips/can-do.mp3',
    '/audio/clips/im-in.mp3',
    '/audio/clips/disqualified.mp3',
    '/audio/clips/what-is-my-purpose.mp3',
    '/audio/clips/riggity-wrecked-son.mp3',
    '/audio/clips/not-the-droids.mp3',
    '/audio/clips/bad-feeling-luke.mp3',
    '/audio/clips/fire-when-ready.mp3',
    '/audio/clips/r2-whistle.mp3',
    '/audio/clips/never-tell-me-the-odds.mp3',
    '/audio/clips/chewie-roar.mp3',
    '/audio/clips/hi-im-saul.mp3',
    '/audio/clips/yeah-science.mp3',
    '/audio/clips/private-domicile.mp3',
    '/audio/clips/cool.mp3',
    '/audio/clips/pirates-theme.mp3',
    '/audio/clips/hyperspace-exit.mp3',
    '/audio/clips/i-am-your-father.mp3',
    '/audio/clips/stay-on-target.mp3',
    '/audio/clips/chewie-laugh.mp3',
    '/audio/tanpura-pluck.mp3',
    '/audio/clips/lotr-theme.mp3',
    '/audio/clips/say-my-name.mp3',
    '/audio/clips/thats-what-she-said.mp3',
    '/audio/clips/pickle-rick.mp3',
    '/audio/engines/xwing-pass.mp3',
    '/audio/engines/falcon-pass.mp3',
    '/audio/engines/thruster.mp3',
    '/audio/clips/hyperspace-enter.mp3',
    '/audio/clips/dl-44.mp3',
    '/audio/clips/portal-gun.mp3',
    '/audio/clips/tie-fighter.mp3',
    '/games/meshy/rick.glb',
    '/games/meshy/rick-idle.glb',
    '/games/meshy/rick-walk.glb',
    '/games/meshy/rick-run.glb',
    '/games/meshy/rick-sit.glb',
    '/games/meshy/morty.glb',
    '/games/meshy/morty-idle.glb',
    '/games/meshy/morty-walk.glb',
    '/games/meshy/morty-run.glb',
    '/games/meshy/morty-sit.glb',
  ], // single files
  globs: [
    '/models/galaxy/**',
    '/cc0/galaxy/**',
    // (the Star Wars worlds' surfaces on the game's own maps: lib/three/scans.js)
    '/textures/galaxy/bf2017/**',
    '/models/universe/war/*',
    '/models/gen3d/x-wing*.glb',
    '/models/gen3d/tie-interceptor*.glb',
    '/games/meshy/act-*.glb',
    '/games/meshy/ual-*.glb',
    '/games/meshy/clips-*.glb',
  ], // folders: `*` within a folder, `**` any depth
};
